### ISSUE TITLE
Kafka and Strimzi examples

### ISSUE THREAD

**Issue by mabulgu** [apache/camel-quarkus#1028]
I know there is an issue #310 already open as more examples should be added to the repository, but I thought it is better to open an issue separately for this topic. If it is ok for all I want to create these examples.

**Comment by ppalaga** [comment]
Thanks @mabulgu, please go ahead!

**Comment by zbendhiba** [comment]
the example here mentions Strimzi : https://github.com/apache/camel-quarkus-examples/tree/camel-quarkus-main/kafka

**Comment by mabulgu** [comment]
Thanks @zbendhiba I could not find proper time to work on this. The example you mentioned fits this case so I assume I can close this issue. Thanks for the contribution, and sorry for my laziness at this point:|
