### ISSUE TITLE
Support Quarkus command mode

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1037]
https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/command-mode-reference.adoc

camel-main supports giving some arguments from the command line. i.e. hoe many messages to wait before to shut down so it would be nice if we can optionally support Quarkus' command mode

**Comment by zhfeng** [comment]
I can take a look at this issue, please assign it to me.

**Comment by zhfeng** [comment]
I just think if we support the command lines, it could be too late to pass the args to the camel context which could be started when the Quarkus bootstrap up. Or we have to defer the [CamelMain.start()](https://github.com/apache/camel-quarkus/blob/master/extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/BuildProcessor.java#L605) to the QuarkusApplication main method ?

**Comment by lburgazzoli** [comment]
I think yes, when camel-main is enabled, then it should be started by the QuarkusApplication main method (like any other cmael-main based runtime)

**Comment by lburgazzoli** [comment]
I also think we can revisit the way we do bootstrap camel-quarkus (naming is purely indicative):

- embedded 
  - routes are added to the camel context directly
  - context need to be programmatically configured 
- main  
  - routes are managed by camel-main
  - support for command line
  - support for configuration through properties
- static (aka lightweight)
  - routes are added to the camel context directly
  - some limitation may happen
  - context need to be programmatically configured 

We can then provide `main` and `static` behavior through extensions so depending of the end user need we may achieve different optimization or behaviours without cluttering the code too much.

/cc @gnodet @davsclaus WDYT ?

**Comment by davsclaus** [comment]
Oh @lburgazzoli thats a great idea to have different extensions for the different bootstrap modes. And we can also have camel-quarkus to log at INFO level which mode it runs in so the end user can better see this too - and we can also better document explain this and have different examples etc. Instead of some magic option in the application.properties file to switch mode.

**Comment by lburgazzoli** [comment]
We can probably have a default and overrideable `assembler` in the core extension that does the bare minimum to set-up and run routes on a context so as example running a simple timer -> log example would require only the `camel-quarkus-timer` extension dependency, but then the `assembler` is swiped by adding either the `main` or `static` bootsrtapper

**Comment by zhfeng** [comment]
So the CamelBootstrapBuildItem might be introduced here to be added in the ```assembler``` ? Also I'm not very clear how to control the bootstrap mode by the options in the application,properties. currently the ```quarkus.camel.main.enabled``` is used.

**Comment by lburgazzoli** [comment]
We don't need to control the bootstrap by an option but instead each "boostrap extension" shoul override the default `assembler` so `quarkus.camel.main.enabled` should can go away

**Comment by zhfeng** [comment]
Thanks @lburgazzoli - it looks like a big change to introduce the "bootstrap extension" and I think it could be better to raise a new issue.

**Comment by lburgazzoli** [comment]
yeah I will
