### ISSUE TITLE
Remove enforcing camel keyword in metadata

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#1058]
There is an enforcing rule issuing the error below at build time:
[ERROR] extensions/grpc/runtime/src/main/resources/META-INF/quarkus-extension.yaml metadata must contain a list of keywords with at least "camel" present.

It may not be necessary as the word camel [is already present in the extension name](https://github.com/apache/camel-quarkus/pull/1051#discussion_r404961873).

We should assess the need for this rule, remove the rule (groovy/maven-plugin ?), remove references in docs (JVM Only to native promotion guide) and maybe remove from all quarkus-extension.yaml files.

**Comment by jamesnetherton** [comment]
The validation check for keywords was removed in 8888ad53fe9c9ac35da10fa3bda646cdbb317495. So this isn't an issue anymore.
