### ISSUE TITLE
Reinstate MongoDB extensions

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#1064]
Extensions mongodb & debezium-mongodb are currently disabled because Qarukus 1.3.x does not support the Mongo 4.x client.

We can enable them again for Quarkus 1.4.x.

**Comment by ppalaga** [comment]
The mongo modules need to be re-enabled in integration-tests/pom.xml and extensions/pom.xml. integration-tests/mongo/pom-disbaled-issue-1064.xml needs to be renamed back to pom.xml

**Comment by jamesnetherton** [comment]
Also need to add the itest module reference back into the CI build config.
