### ISSUE TITLE
Perform basic testing of aws extension through localstack

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1071]

**Comment by oscerd** [comment]
Let me assign this to myself for the moment

**Comment by lburgazzoli** [comment]
There's localstack support from testcontainers https://www.testcontainers.org/modules/localstack/

**Comment by oscerd** [comment]
The behaviour is not the same. We already seen this on camel-k with kinesis and other stuff

**Comment by lburgazzoli** [comment]
but could be enough to have some smoke tests ? 
just to be sure that for example the integration can start and connect

**Comment by lburgazzoli** [comment]
@oscerd @ppalaga I think this can be closed right ?

**Comment by oscerd** [comment]
Yes, I think so

**Comment by ppalaga** [comment]
Some AWS2 extensions still do not have proper tests, but I know which ones they are, so no problem with closing this one.
