### ISSUE TITLE
Add Camel-Aws-SSM extension

### ISSUE THREAD

**Issue by matheus-meneses** [apache/camel-quarkus#108]

**Comment by oscerd** [comment]
Ssm? There is no component in camel for ssm

**Comment by matheus-meneses** [comment]
Is there a possibility to add?

**Comment by oscerd** [comment]
Raise a JIRA here: https://issues.apache.org/jira/browse/CAMEL

**Comment by oscerd** [comment]
if it is the related to SSM Agent, I don't know what use cases you see to use that in camel. So add some information about this.

**Comment by oscerd** [comment]
let us know by the way

**Comment by ppalaga** [comment]
Closing for now. Please feel free to reopen with an explanation what tasks should the requested AWS SSM extension fulfill

**Comment by IstvanSzilagyi** [comment]
Hello i would also like to request SSM component.

Use case is the following.

U store secrets in AWS SSM, and u would like to download it to your app and use it with the SFTP Component to reach the server to download files. This would solve the issue of storing private keys for Camel, instead now this would download SSM keys automatically for your application.
