### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#109]

**Comment by ppalaga** [comment]
I'd add a minimalistic user guide (todayish) unless you guys hurry up too much?

**Comment by lburgazzoli** [comment]
We are likely to start the process tomorrow

**Comment by oscerd** [comment]
I'm starting the process now.

**Comment by ppalaga** [comment]
Yeah, do not wait for me. The user guide turned out to be too hard to write without working examples.

**Comment by lburgazzoli** [comment]
done

**Comment by lburgazzoli** [comment]
thank you @oscerd for taking care of the release
