### ISSUE TITLE
Read lock options for files are ignored

### ISSUE THREAD

**Issue by philschaller** [apache/camel-quarkus#1105]
**Describe the bug**
I created a minimal integration test in a separate branch of my fork:
https://github.com/philschaller/camel-quarkus/tree/readLockFails

The route in the test should only move files with a minimal length. But it moves an empty file. Debugging the application showed that it always falls back to generic behavior in `GenericFileExclusiveReadLockStrategy.getExclusiveReadLockStrategy`.

I also tried to convince the route to use the right read lock strategy by setting the option
`exclusiveReadLockStrategy=org.apache.camel.component.file.strategy.FileChangedExclusiveReadLockStrategy`.

But it does not change the result. Actually, it does not even load that class, thus it may be some class loading issue. But that is only a wild guess.

**Expected behavior**
Respect the read locks.

**Workaround**
No general one to my knowledge. But I can mitigate the problem in my application.

**Environment**
Camel Quarkus 1.0.0-M6 and master branch
JDK 11

**Comment by lburgazzoli** [comment]
does this happen in native or jvm mode ?

**Comment by philschaller** [comment]
Hi
JVM mode, never tried it in native mode. I am not sure if it ever worked with Quarkus or Camel 3.x...or if I am doing something completely wrong.

**Comment by lburgazzoli** [comment]
I think you need to reference a bean from a registry, like with

    exclusiveReadLockStrategy=#myStrategy

where `myStrategy` is the name of a bean inf the camel registry or sue something like

    exclusiveReadLockStrategy=#class:org.apache.camel.component.file.strategy.FileChangedExclusiveReadLockStrategy

**Comment by davsclaus** [comment]
readLock=change is actually one of the out of the box implementations, so you should NOT use it together with exclusiveReadLockStrategy as that is for using a custom implementation. And if you really want to use that, then use the style luca says with the `#` lookup for bean id.

**Comment by philschaller** [comment]
I can try that. But even without any explicit strategy it should work. While debugging it never cared about `readLock=changed`.

**Comment by philschaller** [comment]
Just to make this clear: it shows the same behavior without the option `exclusiveReadLockStrategy`.

While debugging the test `FileTest.fileReadLock_minLength()` it always hits `GenericFileProcessStrategyFactory.getExclusiveReadLockStrategy` and returns `null`. I would expect it to run through `FileProcessStrategyFactory.getExclusiveReadLockStrategy` and parse `readLock` and `readLockMinLength`.

**Comment by davsclaus** [comment]
Works on camel master (not camel-quarkus) so if there is something wrong then its in camel-quarkus.

Its the FileProcessStrategyFactory that should be used as it has the file only strategy such as changed, so you are debugging the wrong class.

**Comment by philschaller** [comment]
Thanks for testing with Camel!

I would like to debug `FileProcessStrategyFactory`, but it is never called...

**Comment by philschaller** [comment]
Another short round of debugging revealed this:
The strategy factory is supposed to be found in the method `GenericFileEndpoint.createGenericFileStrategy`. But the the factory finder resolver method `FastFactoryFinderResolver.findClass` does not find a corresponding entry in its `classMap` variable for the key `META-INF/services/org/apache/camel/component/strategy.factory.file`.

I do not know if the key itself is correct, but there is not even a class `FileProcessStrategyFactory` in the `classMap`. Thus it falls back to the `GenericFileProcessStrategyFactory` which means that this setup will never care about the `readLock=changed`.

Something is broken. Either my setup or this part of class loading in Camel Quarkus. I tried it with two different systems (Windows, Linux).

**Comment by lburgazzoli** [comment]
@philschaller ok I see what the problem could be, do you mind sending a PR with a filing test ?
