### ISSUE TITLE
Investigate removing reflective class configuration for components that extend AbstractApiComponent

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#1108]
Follow up to https://github.com/apache/camel-quarkus/issues/843.

As noted in https://github.com/apache/camel-quarkus/issues/699, utilizing `AbstractApiComponent`, results in any of its supporting classes that use `@UriParams` to be registered for reflection. Currently this applies to extensions:

* Box
* Braintree
* Olingo4

It'd be good to investigate whether we can fix this.

**Comment by ppalaga** [comment]
I have filed an issue in Camel https://issues.apache.org/jira/browse/CAMEL-15119

**Comment by davsclaus** [comment]
I am working on this and have also created a ticket
https://issues.apache.org/jira/browse/CAMEL-15224

**Comment by davsclaus** [comment]
Okay so in Camel 3.5 we have removed the reflection in those api components. @jamesnetherton you are surely welcome to test with camel master if you can native compile and have those configuration classes no longer registerered for reflection

**Comment by ppalaga** [comment]
> @jamesnetherton you are surely welcome to test with camel master

I'll do, it is my responsibility this week.

**Comment by jamesnetherton** [comment]
I gave this a quick test with 3.5.0-SNAPSHOT and unfortunately hit some issues in native mode.

Seems we still have some logic that relies on reflective access to the component configuration classes.

https://github.com/apache/camel/blob/master/core/camel-support/src/main/java/org/apache/camel/support/component/AbstractApiProducer.java#L171

@davsclaus do you think that can be fixed?

**Comment by davsclaus** [comment]
@jamesnetherton yeah can you try with this commit (rebuild camel-core)
https://github.com/apache/camel/commit/96034dd0f964a31f1e8ee72409dcd848b78ef560

**Comment by jamesnetherton** [comment]
Tested box, braintree & olingo4 and they now all work fine in native mode without the configuration classes registered for reflection :+1: 

Probably a separate discussion to this issue, but we could also remove the policy extension as proposed in https://github.com/apache/camel-quarkus/issues/699.
