### ISSUE TITLE
Revisit factory finder set-up

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1112]
The current factory finder set-up does not take into account additional service defined from the factory file using prefixes, as example, the factory file content of the file component defines two services:

```ini
class=org.apache.camel.component.file.FileComponent
strategy.factory.class=org.apache.camel.component.file.strategy.FileProcessStrategyFactory
````

but the current implementation puts an instance if the FileComponent class into the registry and blindly ignore strategy.factory.class, in addition, the current selector can't distinguish between REGISTER and DISCOVERY at service factory property level.

We should allow to define on which key the filter is applied i.e:

- register the service identified by the property `class` in the service factory file (note that `class` is the default and can be omitted)
```java
    new CamelServicePatternBuildItem(
        CamelServiceDestination.REGISTRY,
        true,
        "META-INF/services/org/apache/camel/component/file@class"))
```

- make the service identified by the property `strategy.factory.class` discoverable through the factory finder  (note that `class` is the default and is automatically added if not present)
```java
    new CamelServicePatternBuildItem(
        CamelServiceDestination.DISCOVERY,
        true,
        "META-INF/services/org/apache/camel/file@strategy.factory.class");
```

Notes:
1. the same syntax can be used in the configuration files
2. pattern are still supported, like `META-INF/services/org/apache/camel/component/**@class`

References: 
- #1105 
- #1110

**Comment by davsclaus** [comment]
We could also make the file/ftp components in Camel use separate files for this so they are all just one key. I can't recall if anyone other component is doing this in camel

**Comment by lburgazzoli** [comment]
I'm fine with that as long as we remove the prefix option on the FactoryFinder otherwise there still the chance to this to happen

**Comment by davsclaus** [comment]
Just checked camel source and its only the file component doing this, so lets remove the prefix option and use another file for the file strategy so its all the same

**Comment by davsclaus** [comment]
Created a ticket in Camel
https://issues.apache.org/jira/browse/CAMEL-14936

**Comment by lburgazzoli** [comment]
not an issue any more
