### ISSUE TITLE
Leverage camel-platform-http-vertx in platform-http extension

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#1144]
Most of the platform HTTP code now lives in the Camel main project. So it makes sense to reuse as much as is possible and remove the duplicated code from this project

**Comment by jamesnetherton** [comment]
The slightly tricky aspect to this is preserving the camel-quarkus behaviour where the attachments support is optional.

Before I try to figure out how to implement that on the Camel side, do we actually need (or want) to continue doing that. The overall saving on the native image footprint seems trivial to me (500 - 600KB).

@lburgazzoli @ppalaga WDYT?

**Comment by lburgazzoli** [comment]
I'm fine with bringing the attachments back and see if there's a better option to make them optional on Camel side later on. 

Maybe we can use the extension mechanism that components provide and let the discovery of the attachment support happening at runtime in camel and at build time in camel-quarkus.

**Comment by jamesnetherton** [comment]
Ok - that was pretty much how I was going to approach things. Get the attachment support added in the 'traditional' way, then have a follow up issue to optimize it.
