### ISSUE TITLE
Intermittent failure of HystrixTest

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#1146]
The error below keeps popping up, so for now I'll disable the test when running in GitHub CI.

```
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.442 s <<< FAILURE! - in org.apache.camel.quarkus.component.hystrix.it.HystrixTest
[ERROR] testHystrixFallback  Time elapsed: 1.655 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Response body doesn't match expectation.
Expected: is "Hello Camel Quarkus Hystrix"
  Actual: Fallback response

	at org.apache.camel.quarkus.component.hystrix.it.HystrixTest.testHystrixFallback(HystrixTest.java:37)
```

Maybe we should drop this extension once we upgrade to Camel 3.3.0 and replace with the new `camel-microprofile-fault-tolerance`.

**Comment by davsclaus** [comment]
Yeah switch and maybe we should not have hystrix extension as its EOL and we have 2 other implementations now with resilience4j and microprofile

**Comment by davsclaus** [comment]
Yeah we are dropping hystrix

**Comment by ppalaga** [comment]
> we are dropping hystrix

Is there any agreed-upon time frame for that? I do not see Hystric being deprecated on https://camel.apache.org/components/latest/eips/hystrix-eip.html ?

**Comment by davsclaus** [comment]
It says deprecated now

**Comment by ppalaga** [comment]
Hm... there is also https://camel.apache.org/components/latest/others/hystrix.html that neither links to https://camel.apache.org/components/latest/eips/hystrix-eip.html nor says it is deprecated.

On the Camel Quarkus side, I think we should deprecate it now with 1.0.0.CR2 and remove it in 1.0.0.CR2+2. WDYT?

**Comment by davsclaus** [comment]
Its deprecated in the component 
https://github.com/apache/camel/blob/master/components/camel-hystrix/pom.xml#L32
https://github.com/apache/camel/blob/master/components/camel-hystrix/src/generated/resources/hystrix.json#L7

**Comment by davsclaus** [comment]
We can remove it asap, its not a LTS release of camel-quarkus and we are not 1.0 GA yet.

**Comment by jamesnetherton** [comment]
Closing as per https://github.com/apache/camel-quarkus/issues/3698.
