### ISSUE TITLE
Disable tests (unit and integration) while doing a release

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1155]
Doping a release of ~700 modules (and we still have to add support for many components) is quite time expensive so we should disable unit and integration tests by default when running with the release profile

**Comment by lburgazzoli** [comment]
We can probably also disable some additional plugins such as:

- groovy
- enforcer
- formatter

**Comment by ppalaga** [comment]
Groovy checks, enforcer, formatter and tests should be all skipped with both `release:prepare` and `release:perform` after https://github.com/apache/camel-quarkus/pull/1162
