### ISSUE TITLE
ClassNotFoundException JAXBContext in camel-core-impl

### ISSUE THREAD

**Issue by galderz** [apache/camel-quarkus#1161]
Seeing the following with OpenJDK 11 based GraalVM:

```
Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.apache.camel.quarkus.core.FastCamelContext.createModelJAXBContextFactory()
Parsing context:
	parsing org.apache.camel.impl.engine.AbstractCamelContext.getModelJAXBContextFactory(AbstractCamelContext.java:3716)
	parsing com.oracle.svm.reflect.AbstractCamelContext_getModelJAXBContextFactory_477828eef27cc93cb9372a4eb40fd739c75455ee_1093.invoke(Unknown Source)
	parsing java.base@11.0.8-internal/java.lang.reflect.Method.invoke(Method.java:566)
...
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBContext
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.getDeclaredMethods(HotSpotResolvedObjectTypeImpl.java:932)
```

[Longer output](https://gist.github.com/galderz/f11f7e6ecd2a36a31976f148cbdc8029)

**Comment by galderz** [comment]
This should be solvable adding jaxb dependency. 

Note what I said in a similar situation [here](https://github.com/quarkusio/quarkus/pull/8185#discussion_r398523136). Adding such dependency has no influence in the final image, it's just to make the pointsto analysis JVMCI layer used in stock OpenJDK 11 work.

**Comment by lburgazzoli** [comment]
@davsclaus do you think can hide this even better ? 
The culprit is https://github.com/apache/camel-quarkus/blob/master/extensions-core/core/runtime/src/main/java/org/apache/camel/quarkus/core/DisabledModelJAXBContextFactory.java#L19

**Comment by davsclaus** [comment]
@lburgazzoli yes already done
https://github.com/apache/camel/blob/master/core/camel-api/src/main/java/org/apache/camel/spi/ModelJAXBContextFactory.java

https://issues.apache.org/jira/browse/CAMEL-14829

**Comment by galderz** [comment]
Oh nice, great timing @davsclaus. Would a `3.3.0-SNAPSHOT` camel version work with the current `camel-quarkus`?

**Comment by lburgazzoli** [comment]
We have [branch](https://github.com/apache/camel-quarkus/tree/camel-master)  but it does not target quarkus snapshots, guess we can add a workaround for now and reference this issue to remove it when migrating to camel 3.3.x

**Comment by galderz** [comment]
Sounds good. I'll try to fix it with a workaround and see how it goes...

**Comment by galderz** [comment]
The workaround (https://github.com/galderz/camel-quarkus/commit/3da275e7560d080eab7b229869b5518198e20d48) worked. I'm letting the testsuite continue and see what else comes up.

**Comment by ppalaga** [comment]
To fix this, it should be enough to remove the workaround in https://github.com/apache/camel-quarkus/pull/1185/files#diff-93052fe9a22c86587a36da3725c66eb4R52-R55 and https://github.com/apache/camel-quarkus/pull/1185/files#diff-8fa2182cc03b4d845ad00fa7138e1d3bR59-R62 after upgrading to Camel 3.3.0

**Comment by jamesnetherton** [comment]
@galderz FYI - this change seems to increase the time taken to complete the integration test native builds by around 50%. Our CI build takes around twice as long to complete now. I've not dug into the specifics around why there's such a dramatic change.

Since the Camel 3.3.0 release is imminent, we can probably live with it for now, or at least work around it.

**Comment by galderz** [comment]
@jamesnetherton How imminent is the Camel 3.3.0 release?

**Comment by jamesnetherton** [comment]
@galderz It's available now and we already upgraded the master branch.

**Comment by galderz** [comment]
I'll give master a go and see how it goes.
