### ISSUE TITLE
Unresolved type Base64 in camel-jira native test

### ISSUE THREAD

**Issue by galderz** [apache/camel-quarkus#1166]
* jdk11u-dev/master
* graal/master
* quarkus/master
* camel-quarkus/master

```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: com.google.api.client.repackaged.org.apache.commons.codec.binary.Base64. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing org.apache.camel.component.jira.oauth.JiraOAuthAuthenticationHandler.getOAuthRsaSigner(JiraOAuthAuthenticationHandler.java:72)
Call path from entry point to org.apache.camel.component.jira.oauth.JiraOAuthAuthenticationHandler.getOAuthRsaSigner(String):
	at org.apache.camel.component.jira.oauth.JiraOAuthAuthenticationHandler.getOAuthRsaSigner(JiraOAuthAuthenticationHandler.java:72)
```

[Longer output](https://gist.github.com/galderz/2013fdb89063fb4ecc99ca35d51f31c1)

**Comment by lburgazzoli** [comment]
@claudio4j  can we replace [this](https://github.com/apache/camel/blob/master/components/camel-jira/src/main/java/org/apache/camel/component/jira/oauth/JiraOAuthAuthenticationHandler.java#L31) with Java's libraries instead of the repackaged commons-codec class ?

**Comment by claudio4j** [comment]
Yes it can be replaced. I will do it today or tomorrow, then will let you know here.

**Comment by claudio4j** [comment]
PR in place https://github.com/apache/camel/pull/3785

**Comment by galderz** [comment]
Thanks @claudio4j for the quick fix!

**Comment by galderz** [comment]
@claudio4j I'm trying to verify the fix, but have not yet managed to do so.

Last week patched camel 3.2.x with the fix (see [branch](https://github.com/galderz/camel/tree/t_base64_32x)), but was unable to get to the test failure. I encountered https://github.com/quarkusio/quarkus/issues/9103 and @ppalaga's PR didn't work when I first tried it. I'm trying again now that @ppalaga has a new fix and he's rebased the branch.

**Comment by galderz** [comment]
Somehow things have changed for Camel Jira native tests. They're now skipped unless you start a JIRA instance (e.g. docker) and set the right env variables. Can't find a CI run that would show an example so maybe Camel Jira native tests are not run? Discussion [here](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Camel.20jira.20native.20tests.20not.20running.3F).

**Comment by claudio4j** [comment]
The camel-jira tests in camel repo are all mockito tests, no need for a running jira instance. 
But I see the [JiraTest](https://github.com/apache/camel-quarkus/blob/master/integration-tests/jira/src/test/java/org/apache/camel/quarkus/component/jira/it/JiraTest.java) requires a running jira instance, however I didn't write the camel-jira quarkus code, so I am unsure about it.
Can you try run a docker jira server ?

**Comment by ppalaga** [comment]
@galderz could you please check whether this issue is still occurring? apache/camel#3785 mentioned above is a part of Camel 3.3.0 to which we upgraded recently.

**Comment by galderz** [comment]
How do you test this now? Seems like JIRA tests are now disabled. Do you have a profile in the maven tests that starts JIRA and tests this?

**Comment by galderz** [comment]
Actually, I think the issue is fixed based on testing I did before. I'll verify again. What happens is that even if JIRA tests are skipped, this issue happened during image generation, which happens regardless. I'll give it another spin in the next few days.

**Comment by galderz** [comment]
Fixed.
