### ISSUE TITLE
Need an archetype for Camel Quarkus

### ISSUE THREAD

**Issue by weimeilin79** [apache/camel-quarkus#1173]
For maven users, having an archetypes comes in handy when starting a new project from scratch.

**Comment by ppalaga** [comment]
We indeed do not have a Maven Archetype, but there are two other ways to scaffold new projects:

1. https://code.quarkus.io/

2. `quarkus-maven-plugin` can scaffold projects also for Camel Quarkus:
 
```
mvn io.quarkus:quarkus-maven-plugin:1.4.1.Final:create     -DprojectGroupId=org.acme     -DprojectArtifactId=camel-timer-quickstart     -DclassName="org.acme.rest.json.FruitResource"     -Dpath="/fruits"     -Dextensions="camel-quarkus-timer"
```

Do you think @weimeilin79 1. and 2. are missing some functionality against an archetype?

**Comment by lburgazzoli** [comment]
I think the main issue is that those tools do not generate a camel specific set-up so i.e. they do generate a JAX-RS application whereas it would be nice to have a sample route

**Comment by davsclaus** [comment]
Yes I think its part of a bigger picture. How to let extensions / influence the generated projects - its not only a Camel thing. What if you add hibernate extension then you may want it to setup some jpa/hibernate stuff, and so for other extensions.

But its the same at spring boot, it also generates an empty/shallow project.

A maven archetype is cumbersome to use and also a big ugly with all the parameters you need to specify. There is a reason why those get started websites are popular.

**Comment by ppalaga** [comment]
The Quarkus folks are working on a solution for the extensions to co-scaffold starter projects: https://groups.google.com/d/msg/quarkus-dev/yUcOM8jwIvY/5ZQXK7ZlDwAJ

**Comment by ppalaga** [comment]
I'd say this is a clear won't fix now that we aim at having Quarkus codestarts.
