### ISSUE TITLE
Decide how to maintain examples

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#118]
Followup of the discussion in https://github.com/apache/camel-quarkus/issues/112 and https://github.com/apache/camel-quarkus/pull/115

What we agreed upon with @lburgazzoli :

* We need examples
* Integration tests may test aspects that have no didactic value for the app developers so keeping the distinction between itests and examples makes sense
* Examples should have tests

Open questions:

1. Where should the examples be hosted? `camel-quarkus` (preferred by @ppalaga ) or elsewhere?

2. Should the tests in example projects be run for every PR in `camel-quarkus`? 

* @ppalaga: yes definitely, to have a tight feedback and responsibility loop
* @lburgazzoli: no daily is enough, otherwise the CI would take long

**Comment by lburgazzoli** [comment]
@ppalaga would be ok to test examples in jvm mode and native daily  ? I'm also ok to build everything every time but I remember you were concerned about build taking too long so if you are fine, I'm fine too

**Comment by ppalaga** [comment]
OK, sounds like we agree about 1.: the examples should live in `camel-quarkus` git repo, in an new directory called `examples`.

For 2: Yes, I have the concerns about the build times. That's why I hold the view that we should avoid having similar projects in itests and examples. I prefer starting with testing the native mode in examples on every PR and I am open to revisit this when we feel the builds take too long.

**Comment by kameshsampath** [comment]
@ppalaga  @lburgazzoli  - I will try to add few examples based on https://github.com/apache/camel/tree/master/examples and see how many i can migrate as few components might need quarkizing

**Comment by davsclaus** [comment]
It would be good to get a few basic examples added soon so when we do releases we can point new users to this so they can easily see how to use camel and quarkus, and also that they can quickly try out themselves
