### ISSUE TITLE
Kudu IT failing

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1206]
The Kudu IT tests are failing on my environment:

```
2020-05-11 08:37:33,800 INFO  [org.apa.cam.qua.com.kud.it.KuduResource] (executor-thread-1) Calling createTable
2020-05-11 08:37:33,957 ERROR [org.apa.cam.pro.err.DefaultErrorHandler] (executor-thread-1) Failed delivery for (MessageId: C9BC00A8CDBDC43-0000000000000000 on ExchangeId: C9BC00A8CDBDC43-0000000000000000). Exhausted after delivery attempt: 1 caught: org.apache.kudu.client.NonRecoverableException: not enough live tablet servers to create a table with the requested replication factor 1; 0 tablet servers are alive
```

**java -version**
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment 18.9 (build 11.0.6+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10, mixed mode, sharing)
```

**docker info**
```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 66
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: journald
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: /usr/libexec/docker/docker-init
 containerd version: 
 runc version: fbdbaf85ecbc0e077f336c03062710435607dbf1
 init version: 
 Security Options:
  seccomp
   Profile: default
  selinux
 Kernel Version: 5.6.8-300.fc32.x86_64
 Operating System: Fedora 32 (Thirty Two)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.27GiB
 Name: mars
 ID: FPGA:3ODP:AUFU:MPTP:K6AO:2X4Q:Q4JU:5YEA:ZIXZ:JXZH:THS6:Y77V
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true

```

**Comment by aldettinger** [comment]
@lburgazzoli, darn, I thought I got them ok as it was running on CI and my machine. Those Kudu itests are using a somewhat tricky testcontainer setup.

`Not enough live tablet server` would indicate that the tablet server is not running, or that tablet and master containers are not able to communicate.

Could you please attach full logs from the build ? Maybe, there is something simple, worst case I will disable them by default.

**Comment by lburgazzoli** [comment]
here the full log:

[build.log](https://github.com/apache/camel-quarkus/files/4608531/build.log)

**Comment by aldettinger** [comment]
I've disabled Kudu itests as testcontainer is not able to bridge master and tablet server container on some platforms/configurations.

**Comment by lburgazzoli** [comment]
@aldettinger do you have some details ?

**Comment by aldettinger** [comment]
@lburgazzoli I don't have much details, but let me share my findings.

From the logs of a non-working configuration you've shared above, the first meaningful difference is that line:
`client connection to 192.168.96.2:7051: connect: No route to host (error 113)`
It means that from the 2 containers involved in this test, the tablet server one is not able to communicate with the master one.

In a working configuration however the communication between containers is working. This is the purpose of the shared org.testcontainers.container.Network instance in the `KuduTestResource` class. From there, I was not able to find anything meaningful.

I'm happy to investigate if you have anything to share.

**Comment by lburgazzoli** [comment]
Seems to be related to https://github.com/moby/moby/issues/32138 so I think we should re-enable te tests and link this issue

**Comment by aldettinger** [comment]
@lburgazzoli moby/moby#32138 quote an issue on RHEL 7 while I'm able to run tests without issue on RHEL 7 here.
I'm ok to restore tests but were you able to sort it out in your environment ?

**Comment by lburgazzoli** [comment]
Yes, the issue is related to firewalld + docker which in my set-up does not allow containers to communicate even if they are on the same network and this happens also outside camel-quarkus for some other projects (and I have a reproducer for it).

I can workaround it locally by disabling firewalld or by patching in with one of the workarounds mentioned in the issue.

**Comment by aldettinger** [comment]
Ok, thanks for sharing this tip. I'm re-enabling tests and adding a troubleshooting section.
