### ISSUE TITLE
Cute Extension - Add options for allowing template via header/context map

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#1212]
The latest two CAMEL tickets should also be implemented in the cute extensions
https://github.com/apache/camel-quarkus/blob/master/extensions/qute/component/src/main/java/org/apache/camel/component/qute/QuteEndpoint.java

https://issues.apache.org/jira/browse/CAMEL-15013
https://issues.apache.org/jira/browse/CAMEL-15050

**Comment by zhfeng** [comment]
@davsclaus I can take a look with the qute extension. please assign to me.

**Comment by davsclaus** [comment]
Thanks and you are welcome to ping me if you need more details.
