### ISSUE TITLE
Revert workaround for @EnabledIf after upgrade to Quarkus 1.5.x

### ISSUE THREAD

**Issue by gnodet** [apache/camel-quarkus#1222]
Revert https://github.com/apache/camel-quarkus/commit/08e65aea9aa2058a3f286cec00fa01d0bce3d882 when https://github.com/quarkusio/quarkus/issues/9273 is fixed somehow.

**Comment by ppalaga** [comment]
Changed the title, because https://github.com/quarkusio/quarkus/issues/9273 seems to be fixed
