### ISSUE TITLE
Add support for MicroProfile Fault Tolerance

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#1234]
https://camel.apache.org/components/latest/others/microprofile-fault-tolerance.html

**Comment by jamesnetherton** [comment]
After this has been added, what do we think about deprecating / removing the Hystrix extension? Do we want to support multiple fault tolerance implementations?

**Comment by lburgazzoli** [comment]
+1 for deprecating hystrix

**Comment by oscerd** [comment]
Don't we have also resilience4j?
