### ISSUE TITLE
Add enforce rule to avoid extension depending on camel-quarkus-xml-io or camel-quarkus-xml-jaxb directly 

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1277]
As follow up of #1275, we should add an enforcer rule to to avoid extension depending on `camel-quarkus-xml-io` or `camel-quarkus-xml-jaxb` directly

**Comment by lburgazzoli** [comment]
This is not needed any more after https://github.com/apache/camel-quarkus/pull/1292

**Comment by ppalaga** [comment]
Not necessary after https://github.com/apache/camel-quarkus/pull/1292
