### ISSUE TITLE
Examples should have use Quarkus Main Application 

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#1280]
eg the new in 1.5 about QuarkusApplication as a main class so you can run it easily without having to use mvn quarkus:dev etc.

**Comment by lburgazzoli** [comment]
Depends on:
- https://github.com/apache/camel-quarkus/issues/1128
- https://github.com/apache/camel-quarkus/issues/1037

**Comment by davsclaus** [comment]
Thanks Luca, yeah so it seems its a bigger work but IMHO needed to make camel-quarkus as a more first class citizen in Quarkus. The command mode is going to be what users do, as its ala Spring Boot, and easy to reason about because there is a Main class of their own.

**Comment by lburgazzoli** [comment]
I do agree and the aim #1128 was exactly aimed to let user choose their preferred way of running camel

**Comment by lburgazzoli** [comment]
We have now an example that uses quarkus main

     https://github.com/apache/camel-quarkus/tree/master/examples/timer-log-main

however there's an issue https://github.com/quarkusio/quarkus/issues/10147 that prevent to start it from the IDE.

**Comment by Delawen** [comment]
I can take a look at this. Should I migrate all examples or just a selection of them?

**Comment by jamesnetherton** [comment]
Maybe this issue should be closed. `mvn quarkus:dev` is pretty much the standard dev workflow. Command mode is not.

IMO it's enough to have a single example that demonstrates the Quarkus command mode stuff. Which we already have here:

https://github.com/apache/camel-quarkus-examples/tree/main/timer-log-main
