### ISSUE TITLE
Drop the Jaxb based XMLRoutesDefinitionLoader

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1291]
We have now two engine that can load routes written in xml:

- xml-io
- xml-jaxb

Since the jaxb based one does not give any benefit over the xmlio one, I'd propose to drop the support for loading routes using jaxb

**Comment by lburgazzoli** [comment]
Draf PR #1292 is open in case you agree with this proposal

**Comment by davsclaus** [comment]
+1 
Yeah that is a good idea
