### ISSUE TITLE
OpenAPI Java extension cannot handle non-default API context path  

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#1309]
I think it only happens when used in conjunction with the `platform-http` component.

If you try to configure paths other than the default `/openapi.json` or `/openapi.yaml`, then you get a HTTP 204 response because the logic to figure out the `CamelContext` & `RestConfiguration` fails. Probably due to `PlatformHttpConsumer` setting the `CamelHttpPath` header. None of the other REST API components seem to be doing that, hence it works ok with those.

**Comment by lburgazzoli** [comment]
Does this impact camel in general ? i.e. the VertxPLatformHttp

**Comment by jamesnetherton** [comment]
Yes, it has the same logic in the consumer IIRC. I've not tested it but the same issue is likely present.

**Comment by jamesnetherton** [comment]
Fixed in Camel 3.4.1 with [CAMEL-15277](https://issues.apache.org/jira/browse/CAMEL-15277).
