### ISSUE TITLE
Add support for quarkus provided event loop

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#131]
We should back camel-core with event loop from quarkus, as example:

    https://github.com/quarkusio/quarkus/blob/master/extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyProcessor.java#L57-L72

Or vert.x

**Comment by cescoffier** [comment]
Quarkus should provides:

* a Vert.x instance (produced by the quarkus-vertx extension)
* a way to access the netty event loop using https://vertx.io/docs/apidocs/io/vertx/core/Vertx.html#nettyEventLoopGroup-- (we may simplify the usage)

**Comment by lburgazzoli** [comment]
So we should definitively try to back camel with vert.x using bits from https://github.com/apache/camel/tree/master/components/camel-reactive-executor-vertx
