### ISSUE TITLE
[Camel 3.5] Exclude debezium-embedded dependencies

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1340]
the `camel-quarkus-support-debezium` depends on `debezium-embedded` which brings a ton of kafka connect related dependencies :

```
[INFO] +- io.debezium:debezium-embedded:jar:1.1.2.Final:compile
[INFO] |  +- org.apache.kafka:connect-api:jar:2.5.0:compile
[INFO] |  |  +- org.apache.kafka:kafka-clients:jar:2.5.0:compile
[INFO] |  |  |  +- com.github.luben:zstd-jni:jar:1.4.4-7:compile
[INFO] |  |  |  +- org.lz4:lz4-java:jar:1.7.1:compile
[INFO] |  |  |  \- org.xerial.snappy:snappy-java:jar:1.1.7.3:compile
[INFO] |  |  \- javax.ws.rs:javax.ws.rs-api:jar:2.1.1:compile
[INFO] |  +- org.apache.kafka:connect-runtime:jar:2.5.0:compile
[INFO] |  |  +- org.apache.kafka:kafka-tools:jar:2.5.0:compile
[INFO] |  |  |  +- org.apache.kafka:kafka-log4j-appender:jar:2.5.0:compile
[INFO] |  |  |  |  \- org.slf4j:slf4j-log4j12:jar:1.7.30:compile
[INFO] |  |  |  |     \- log4j:log4j:jar:1.2.17:compile
[INFO] |  |  |  \- net.sourceforge.argparse4j:argparse4j:jar:0.7.0:compile
[INFO] |  |  +- org.apache.kafka:connect-transforms:jar:2.5.0:compile
[INFO] |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.10.4:compile
[INFO] |  |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.10.4:compile
[INFO] |  |  |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.10.4:compile
[INFO] |  |  |     +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
[INFO] |  |  |     \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[INFO] |  |  +- org.glassfish.jersey.containers:jersey-container-servlet:jar:2.28:compile
[INFO] |  |  |  +- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.28:compile
[INFO] |  |  |  |  \- org.glassfish.hk2.external:jakarta.inject:jar:2.5.0:compile
[INFO] |  |  |  +- org.glassfish.jersey.core:jersey-common:jar:2.28:compile
[INFO] |  |  |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
[INFO] |  |  |  +- org.glassfish.jersey.core:jersey-server:jar:2.28:compile
[INFO] |  |  |  |  +- org.glassfish.jersey.core:jersey-client:jar:2.28:compile
[INFO] |  |  |  |  +- org.glassfish.jersey.media:jersey-media-jaxb:jar:2.28:compile
[INFO] |  |  |  |  \- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO] |  |  |  \- jakarta.ws.rs:jakarta.ws.rs-api:jar:2.1.5:compile
[INFO] |  |  +- org.glassfish.jersey.inject:jersey-hk2:jar:2.28:compile
[INFO] |  |  |  \- org.glassfish.hk2:hk2-locator:jar:2.5.0:compile
[INFO] |  |  |     +- org.glassfish.hk2.external:aopalliance-repackaged:jar:2.5.0:compile
[INFO] |  |  |     +- org.glassfish.hk2:hk2-api:jar:2.5.0:compile
[INFO] |  |  |     \- org.glassfish.hk2:hk2-utils:jar:2.5.0:compile
[INFO] |  |  +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO] |  |  |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] |  |  +- javax.activation:activation:jar:1.1.1:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-server:jar:9.4.18.v20190429:compile
[INFO] |  |  |  +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] |  |  |  +- org.eclipse.jetty:jetty-http:jar:9.4.18.v20190429:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-io:jar:9.4.18.v20190429:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-servlet:jar:9.4.18.v20190429:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-security:jar:9.4.18.v20190429:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-servlets:jar:9.4.18.v20190429:compile
[INFO] |  |  |  +- org.eclipse.jetty:jetty-continuation:jar:9.4.18.v20190429:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-util:jar:9.4.18.v20190429:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-client:jar:9.4.18.v20190429:compile
[INFO] |  |  +- org.reflections:reflections:jar:0.9.12:compile
[INFO] |  |  \- org.apache.maven:maven-artifact:jar:3.6.3:compile
[INFO] |  |     +- org.codehaus.plexus:plexus-utils:jar:3.2.1:compile
[INFO] |  |     \- org.apache.commons:commons-lang3:jar:3.9:compile
[INFO] |  +- org.apache.kafka:connect-json:jar:2.5.0:compile
[INFO] |  |  \- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.10.4:compile
[INFO] |  \- org.apache.kafka:connect-file:jar:2.5.0:compile
```

Do we need them ?

**Comment by oscerd** [comment]
I think so, it's explicitly used in camel-debezium-common, we can check with a tuned exclusions, but we need some help from @omarsmak

**Comment by JiriOndrusek** [comment]
I think that a lot of these dependencies could be excluded. (they shouldn't be used) I'll try it.

**Comment by JiriOndrusek** [comment]
I've removed some of dependencies in https://github.com/apache/camel-quarkus/pull/1351
Current status is

>+- io.debezium:debezium-embedded:jar:1.1.2.Final:compile
[INFO] |  +- org.apache.kafka:connect-api:jar:2.5.0:compile
[INFO] |  |  +- org.apache.kafka:kafka-clients:jar:2.5.0:compile
[INFO] |  |  |  +- com.github.luben:zstd-jni:jar:1.4.4-7:compile
[INFO] |  |  |  +- org.lz4:lz4-java:jar:1.7.1:compile
[INFO] |  |  |  \- org.xerial.snappy:snappy-java:jar:1.1.7.3:compile
[INFO] |  |  \- javax.ws.rs:javax.ws.rs-api:jar:2.1.1:compile
[INFO] |  \- org.apache.kafka:connect-json:jar:2.5.0:compile
[INFO] |     \- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.10.4:compile
[INFO] +- org.apache.kafka:connect-runtime:jar:2.5.0:compile

**Comment by omarsmak** [comment]
@JiriOndrusek @oscerd @lburgazzoli indeed, that is one of the reasons Debezium folks deprecated Debezium Embedded and instead, brought the newer Debezium APIs instead which should be lighter and agnostic from Kafka Connect stuff. e.g: a lot of these Kafka Connect stuff are not needed which cause a lot of these unnecessary imports. I am planning to work on it on the next Camel 3.5 iteration tracked in this JIRA https://issues.apache.org/jira/browse/CAMEL-14777
In the mean time  as @JiriOndrusek mentioned, I think many of these Connect stuff are not really in used and could be excluded.

**Comment by ppalaga** [comment]
This can be revisited now that https://github.com/apache/camel/pull/3965 is in Camel master.

**Comment by ppalaga** [comment]
This can be revisited as we have Camel 3.5 in Camel Quarkus master.

**Comment by JiriOndrusek** [comment]
Dependencies listed in the summary are transitive dependencies of  `debezium-embedded`. Fix of https://issues.apache.org/jira/browse/CAMEL-14777 doesn't remove this dependency, it is still required (see [doc](https://debezium.io/documentation/reference/1.3/development/engine.html#_dependencies)).
Camel-quarkus due  the limitations (see [doc](https://camel.apache.org/camel-quarkus/latest/reference/extensions/debezium-mysql.html#_camel_quarkus_limitations)) does not need any of the transitive dependencies from `org.apache.kafka:connect-runtime`.  

Commt https://github.com/JiriOndrusek/camel-quarkus/commit/d70defcec0e2fcb7c2ce9e80c39b297ad5748bd9 removes the unnecessary dependencies. Fix is already merged. This issue could be closed.

(here is a list of dependencies, which are removed by the above fix:
>[INFO] |  |  +- org.apache.kafka:kafka-tools:jar:2.5.0:compile
[INFO] |  |  |  +- org.apache.kafka:kafka-log4j-appender:jar:2.5.0:compile
[INFO] |  |  |  |  \- org.slf4j:slf4j-log4j12:jar:1.7.30:compile
[INFO] |  |  |  |     \- log4j:log4j:jar:1.2.17:compile
[INFO] |  |  |  \- net.sourceforge.argparse4j:argparse4j:jar:0.7.0:compile
[INFO] |  |  +- org.apache.kafka:connect-transforms:jar:2.5.0:compile
[INFO] |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.10.4:compile
[INFO] |  |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.10.4:compile
[INFO] |  |  |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.10.4:compile
[INFO] |  |  |     +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
[INFO] |  |  |     \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[INFO] |  |  +- org.glassfish.jersey.containers:jersey-container-servlet:jar:2.28:compile
[INFO] |  |  |  +- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.28:compile
[INFO] |  |  |  |  \- org.glassfish.hk2.external:jakarta.inject:jar:2.5.0:compile
[INFO] |  |  |  +- org.glassfish.jersey.core:jersey-common:jar:2.28:compile
[INFO] |  |  |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
[INFO] |  |  |  +- org.glassfish.jersey.core:jersey-server:jar:2.28:compile
[INFO] |  |  |  |  +- org.glassfish.jersey.core:jersey-client:jar:2.28:compile
[INFO] |  |  |  |  +- org.glassfish.jersey.media:jersey-media-jaxb:jar:2.28:compile
[INFO] |  |  |  |  \- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO] |  |  |  \- jakarta.ws.rs:jakarta.ws.rs-api:jar:2.1.5:compile
[INFO] |  |  +- org.glassfish.jersey.inject:jersey-hk2:jar:2.28:compile
[INFO] |  |  |  \- org.glassfish.hk2:hk2-locator:jar:2.5.0:compile
[INFO] |  |  |     +- org.glassfish.hk2.external:aopalliance-repackaged:jar:2.5.0:compile
[INFO] |  |  |     +- org.glassfish.hk2:hk2-api:jar:2.5.0:compile
[INFO] |  |  |     \- org.glassfish.hk2:hk2-utils:jar:2.5.0:compile
[INFO] |  |  +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO] |  |  |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] |  |  +- javax.activation:activation:jar:1.1.1:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-server:jar:9.4.18.v20190429:compile
[INFO] |  |  |  +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] |  |  |  +- org.eclipse.jetty:jetty-http:jar:9.4.18.v20190429:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-io:jar:9.4.18.v20190429:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-servlet:jar:9.4.18.v20190429:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-security:jar:9.4.18.v20190429:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-servlets:jar:9.4.18.v20190429:compile
[INFO] |  |  |  +- org.eclipse.jetty:jetty-continuation:jar:9.4.18.v20190429:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-util:jar:9.4.18.v20190429:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-client:jar:9.4.18.v20190429:compile
[INFO] |  |  +- org.reflections:reflections:jar:0.9.12:compile
[INFO] |  |  \- org.apache.maven:maven-artifact:jar:3.6.3:compile
[INFO] |  |     +- org.codehaus.plexus:plexus-utils:jar:3.2.1:compile
[INFO] |  |     \- org.apache.commons:commons-lang3:jar:3.9:compile
)

**Comment by JiriOndrusek** [comment]
@ppalaga Can be closed, see previous comment.
