### ISSUE TITLE
List all the configuration properties onthe website

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1350]
Similar to https://quarkus.io/guides/all-config

**Comment by davsclaus** [comment]
Yeah we have this Camel JIRA that is related to this
https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-15190

**Comment by davsclaus** [comment]
There is a table now for camel-main
https://github.com/apache/camel/blob/master/core/camel-main/src/main/docs/main.adoc

**Comment by ppalaga** [comment]
The linked PR does not add an all-config style page, it rather lists the options relevant for the given extension on its page. 

Here is an example: https://camel.apache.org/camel-quarkus/latest/extensions/core.html (There are some visual and procedural glitches there, for which I am going to file folow-ups)

Do we still want an all-config style page?
