### ISSUE TITLE
Investigate intermittent build failures due to port conflicts

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#1370]
Despite randomising ports we occasionally still hit conflicts on CI runs. E.g like this one:

https://github.com/quarkusio/quarkus/issues/8593#issuecomment-645785210

It'd be good if we can figure out the root cause of the problem.

**Comment by jamesnetherton** [comment]
Fortunately this just reoccurred on the quarkus-master nightly job [here](https://github.com/apache/camel-quarkus/runs/786736342?check_suite_focus=true). Looking at the logs, all of the random ports allocated by the `build-helper-maven-plugin` look unique:

32769
32983
34241
37135
41365
41481
43313
44435
44505
45503
45859
46267

I wonder if the [plugin](https://github.com/mojohaus/build-helper-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/buildhelper/ReserveListenerPortMojo.java#L133) should do `setReuseAddress(true)` on the `ServerSocket` it creates? IIRC, `close()` potentially does not immediately free the socket. It may be in left in `TIME_WAIT` for some period. Perhaps when the tests run and attempt to use the port, it has still not been freed.

**Comment by lburgazzoli** [comment]
yes it should, we do that in our `AvailablePortFinder`

**Comment by jamesnetherton** [comment]
I guess the real problem is with the thing that tries to rebind to the port. E.g the vertx HTTP server. There is a [`so-reuse-port`](https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus.http.so-reuse-port) config option, but only available if using the native transport.

**Comment by ppalaga** [comment]
@jamesnetherton could you please sum up what needs to be done here?

**Comment by jamesnetherton** [comment]
It's like I said. I think the issue is with vertx trying to bind on the port that was discovered by the `build-helper-maven-plugin`. So we could try the [`so-reuse-port`](https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus.http.so-reuse-port) config option.

Or, maybe we don't actually need the `build-helper-maven-plugin` to do the free port discovery at all. If we configure the vertx HTTP ports to '0', that should result in binding on random ports.

**Comment by ppalaga** [comment]
So setting `setReuseAddress(true)` on the `ServerSocket` in the `build-helper-maven-plugin` would not help?

`quarkus.http.so-reuse-port` would have to be set to `false`, right? 
It would have to be set in every single test's `application.properties`?

**Comment by lburgazzoli** [comment]
> Or, maybe we don't actually need the `build-helper-maven-plugin` to do the free port discovery at all. If we configure the vertx HTTP ports to '0', that should result in binding on random ports.

but I think that wouldn't work as we then need to grab the port and configure rest assured ports.

**Comment by jamesnetherton** [comment]
> So setting `setReuseAddress(true)` on the `ServerSocket` in the `build-helper-maven-plugin` would not help?

Yeah, I don't think so. I've not proved it....

> `quarkus.http.so-reuse-port` would have to be set to `false`, right?

It'd need to be `true`. It also needs native transport to be enabled. E.g via `quarkus.vertx.prefer-native-transport`. They could just be set as system properties instead of polluting every `application.properties` file.


> > Or, maybe we don't actually need the `build-helper-maven-plugin` to do the free port discovery at all. If we configure the vertx HTTP ports to '0', that should result in binding on random ports.
> 
> but I think that wouldn't work as we then need to grab the port and configure rest assured ports.

That may not be an issue. I think that's handled by Quarkus:

https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java#L890-L893

I just ran the all itests in JVM mode and everything passed with the port(s) configured as 0.

**Comment by ppalaga** [comment]
Has anybody seen happening this recently? Could we perhaps close this?
