### ISSUE TITLE
Mybatis Component native support

### ISSUE THREAD

**Issue by janwaros** [apache/camel-quarkus#1384]
Related issues:

- 1. https://github.com/quarkusio/quarkus/issues/1958
- 2. https://github.com/quarkusio/quarkus/issues/6490

**Comment by ppalaga** [comment]
A contribution is welcome! Please follow https://camel.apache.org/camel-quarkus/latest/contributor-guide/create-new-extension.html

**Comment by ppalaga** [comment]
A JVM-only extension (without a proper test) is underway.

**Comment by zhfeng** [comment]
The quarkus mybatis extension has been moved to https://github.com/quarkiverse/quarkiverse-mybatis and I'm working on it.

**Comment by zhfeng** [comment]
The camel-mybatis native support could be related to https://github.com/quarkiverse/quarkus-mybatis/issues/9 which supports the XML configuration.
