### ISSUE TITLE
Turn off bean removal by ArC 

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1387]
By default ArC [removes unused beans](https://quarkus.io/guides/cdi-reference#remove_unused_beans) but that does not work very well with Camel as it does use `BeanManager` behind the scenes to look-up beans from the container and ArC can't be aware of what Camel need.

We probably need to discuss this topic with the Quarkus team and see if through a build item it could be possible to reverse the behaviour so not to remove beans unless that feature is turned on explicitly.

Taken from: https://github.com/apache/camel-quarkus/pull/1344#discussion_r440015225

**Comment by jamesnetherton** [comment]
I'll close this as it's superseded by https://github.com/apache/camel-quarkus/issues/2822.
