### ISSUE TITLE
Observe Camel's Lifecycle events

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1399]

**Comment by lburgazzoli** [comment]
There's some overlap between life-cycle and management events:

- [LifecycleStrategy](https://github.com/apache/camel/blob/master/core/camel-api/src/main/java/org/apache/camel/spi/LifecycleStrategy.java)
- [CamelEvent](https://github.com/apache/camel/blob/master/core/camel-api/src/main/java/org/apache/camel/spi/CamelEvent.java)

@jamesnetherton wonder if we should limit life-cycle events to _onComponent_ (add/remove) and _onEndpoint_ (add/remove) and wrap them as custom `CamelEvent`

**Comment by lburgazzoli** [comment]
@jamesnetherton @davsclaus a possible implementation proposed as #1404

**Comment by davsclaus** [comment]
Okay so if we only listen for component add/remove endpoint add/remove is there a special reason for this? Just wonder

**Comment by lburgazzoli** [comment]
I was thinking about have just a single set of events, as example you can listen for Context start event with both a life-cycle callback and with a management event so there's some duplication and I didn't want to expose both to avoid confusion.

Relates to: https://issues.apache.org/jira/browse/CAMEL-11566?filter=12334535

**Comment by lburgazzoli** [comment]
@davsclaus added the missing non overlapping events

**Comment by davsclaus** [comment]
Ah okay, so you wanted to present this to the camel-quarkus end users as a uniform api using standard java events. So you dont need to choose when to use lifecycle vs events.

Yeah ideally events should be for end users, and lifecycle for component developers where you need some special integration (spi interface).

But historically then there was only lifecycle in the start of Camel and events was added later, that was a bit tied to jmx events in the start.

However would likely be good to make end users go for events in camel-core over lifecycle.
