### ISSUE TITLE
Asterisk not escaped in Quarkus config docs

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1402]
E.g. in https://camel.apache.org/camel-quarkus/latest/extensions/core.html the asterisk in the examples is rendered as `<strong>` where it should rather be verbatim.

**Comment by oscerd** [comment]
I think it's antora

**Comment by ppalaga** [comment]
No, I'd say it is the Quarkus tooling extracting the field JavaDoc and transforming it to AsciiDoc

**Comment by ppalaga** [comment]
Some class in the `io.quarkus.annotation.processor.generate_doc` package.

**Comment by ppalaga** [comment]
Fixed by upgrade to Quarkus 1.6.0.Final
