### ISSUE TITLE
Don't bind auto-discovered beans to the registry if they are produced by the user

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1406]
Assuming we have a the following code from the user applications code:

```java
@ApplicationScoped
public class Configurations {
    /**
     * Produces a {@link LogComponent} instance with a custom exchange
     * formatter set-up.
     */
    @Named
    LogComponent log() {
        DefaultExchangeFormatter formatter = new DefaultExchangeFormatter();
        formatter.setShowExchangePattern(false);
        formatter.setShowBodyType(false);

        LogComponent component = new LogComponent();
        component.setExchangeFormatter(formatter);

        return component;
    }
}
```

This will end-up overriding the auto discovered log component bound to the registry by camel-quarkus' build steps during the augmentation phase and as we have a way to query the build context about the known beans, then we should avoid to register the auto discovered one to avoid wasting memory.

**Comment by jamesnetherton** [comment]
Unless I'm missing something obvious, I thought we already did this? I.e via this [filter](https://github.com/apache/camel-quarkus/blob/39c2d2476044c3765ce038207d63185122791afd/extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/CamelRegistryProcessor.java#L77).

**Comment by lburgazzoli** [comment]
I've missed it :D
