### ISSUE TITLE
Merge camel-quarkus-bom-deployment into camel-quarkus-bom

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1413]
Quarkus will probably deprecate quarkus-bom-deployment and merge its content into quarkus-bom [1], should we do the same ?

[1] https://github.com/quarkusio/quarkus/pull/10182

**Comment by ppalaga** [comment]
Let's wait for the result of the discussion on quarkus-dev ML.

**Comment by ppalaga** [comment]
The chance that the deployment BOM is going to survive is close to zero now.

**Comment by ppalaga** [comment]
The relevant discussions, for the record: 
* https://groups.google.com/forum/#!topic/quarkus-dev/3uibBAc9g0c
* https://groups.google.com/forum/#!topic/quarkus-dev/LhQz9hRfYUA
* https://groups.google.com/forum/#!topic/quarkus-dev/UQ-KIt-kBSo

**Comment by ppalaga** [comment]
Quarkus is keeping their deployment BOM as an alias of their runtime BOM.

I guess we can remove the deployment BOM, because we are not assuming any third party depends on it?

**Comment by lburgazzoli** [comment]
We are not yet a 1.0 so - IMHO - we can safely do such kind of changes

**Comment by ppalaga** [comment]
Fixed via 4810732c14e20ef65e16f103e9fddb1fbdc3a57f
