### ISSUE TITLE
Upgrade to Debezium 1.2.0.Final

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1418]
We should try to upgrade DBzium to 1.2.0.Beta2 because that's the version Quarkus platform is about to standardize on.

**Comment by davsclaus** [comment]
They just release 1.2 final
https://debezium.io/releases/1.2/

So the quarkus folks ought to use that

**Comment by JiriOndrusek** [comment]
Please, assign to me. I'll try to upgrade this version.
