### ISSUE TITLE
Document JTA extension usage

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1428]
It would be nice to have `extensions/jta/runtime/src/main/doc/usage.adoc` either showing a minimal example or containing a link to a page where a basic example can be found.

**Comment by ppalaga** [comment]
@zhfeng I cannot assign to you unless you add a comment

**Comment by zhfeng** [comment]
please assign this issue to me

**Comment by zhfeng** [comment]
Or is it possible I can assign to myself ?
