### ISSUE TITLE
Cannot build project on Windows

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1429]
Mentioned in https://issues.apache.org/jira/browse/SUREFIRE-1809?focusedCommentId=17147443&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17147443 :

```
[ERROR] Failed to execute goal org.codehaus.gmaven:groovy-maven-plugin:2.1.1:execute (sanity-checks) on project camel-quarkus-build-parent: Execution sanity-checks of goal org.codehaus.gmaven:groovy-maven-plugin:2.1.1:execute failed: Impossible to read the text content from file://C:/vcs/github/camel-quarkus/tooling/scripts/validate-dependencies.groovy: Unknown host C -
```

**Comment by jamesnetherton** [comment]
Fixing this uncovers a whole bunch of different problems building on Windows. Mainly around path, line separator and Docker differences.
