### ISSUE TITLE
Create a Camel AMQP extension

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#143]

**Comment by zhfeng** [comment]
@lburgazzoli do you still work on this issue ? I think it could be similar with the mqtt issue https://github.com/apache/camel-quarkus/issues/171. I can take a look at the this one.

**Comment by lburgazzoli** [comment]
please go ahead

**Comment by zhfeng** [comment]
The camel-amqp 3.0.0-RC1 has  org.springframework:spring-context version 5.1.9.RELEASE but the io.quarkus:quarkus-bom 0.21.2 has 5.1.8.RELEASE.

It looks like we need to wait the alignment of spring-context in quarkus-bom

**Comment by zhfeng** [comment]
https://github.com/quarkusio/quarkus/pull/4044

**Comment by zhfeng** [comment]
we have to wait for the https://github.com/quarkusio/quarkus/issues/3436

**Comment by lburgazzoli** [comment]
@zhfeng I' not very sure about the need of wait for https://github.com/quarkusio/quarkus/issues/3436 as camel-jms uses quite a log of Spring API so it may work investigating what alternative options we do have.

maybe we can do something similar to camel-sjms but for the amqp protocol.

**Comment by zhfeng** [comment]
OK, I will take a look at the camel-sjms

**Comment by lburgazzoli** [comment]
@zhfeng are you working on this component ?

**Comment by zhfeng** [comment]
@lburgazzoli yeah, I still work on this component but do not have much time currently.

**Comment by jamesnetherton** [comment]
@zhfeng if it's ok with you, I can take this issue. I have a basic test working in native mode.

**Comment by zhfeng** [comment]
sure, @jamesnetherton and re-assign this issue to you.

**Comment by zhfeng** [comment]
I think both camel-jms and camel-amqp are based on the spring. So is this still the problem with the quarks and I think the https://github.com/quarkusio/quarkus/issues/3436 I met before ?
