### ISSUE TITLE
Extension for camel-threadpoolfactory-vertx

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#1430]
In Camel 3.5 we have a new module that would be good to make camel-quarkus use. We could consider having it by default in camel-quarkus or add an extension for it so users can add it or not.

This example was updated
https://github.com/apache/camel-examples/commit/014f9081122e32a1308621062f2099a7ec08c5ec

So basically it allows to use vertx worker threads for EIPs that are using concurrency (if they dont use a custom thread pool). 
https://github.com/apache/camel/blob/master/components/camel-threadpoolfactory-vertx/src/main/docs/reactive-threadpoolfactory-vertx.adoc

This requires Camel 3.5 onwards

**Comment by JiriOndrusek** [comment]
Please, assign to me. 

I'll try to use it in camel-quarkus. I'll try to add this module as an extension, having it by default in camel-quarkus can be the next step.
