### ISSUE TITLE
Question regarding AWS Credentials without XML beans

### ISSUE THREAD

**Issue by gus-maurizio** [apache/camel-quarkus#1431]
This is a question, any help appreciated. Migrating from Spring boot, I have some specific needs to define for AWS-S3 a client configuration. In XML DSL is like this:
`<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">

  <bean id="awsDefaultCredentialsProviderChain" class="com.amazonaws.auth.DefaultAWSCredentialsProviderChain" />
  <bean id="awsClientConfigEndpoint" class="com.amazonaws.ClientConfiguration">
  </bean>
  <bean id="s3"                     class="org.apache.camel.component.aws.s3.S3Component" />
  <bean id="vpcs3Client-us-east-1"  class="com.amazonaws.services.s3.AmazonS3Client">
    <constructor-arg index="0"    ref="awsClientConfigEndpoint" />
    <property name="endpoint"     value="${client.s3.us-east-1}" />
  </bean>

</beans>

`
I have been trying to migrate this to Java DSL to no avail, this is as far as I could get, but cannot make it work:
`mport org.apache.camel.builder.RouteBuilder;

import javax.inject.Inject;
import java.io.File;
import java.util.List;

// import software.amazon.awssdk.services.s3.S3Client;
import com.amazonaws.ClientConfiguration;
import com.amazonaws.Protocol;
import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.auth.AWSCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.auth.InstanceProfileCredentialsProvider;
import com.amazonaws.http.IdleConnectionReaper;
import com.amazonaws.internal.StaticCredentialsProvider;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3Client;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.S3ClientOptions;
import com.amazonaws.regions.Regions;

import org.apache.camel.CamelContext;
import org.apache.camel.spi.Registry;
import org.apache.camel.impl.SimpleRegistry;
import org.apache.camel.impl.CompositeRegistry;

public class CamelRouteS3 extends RouteBuilder {

	// @Inject
	// S3Client s3Client;

    // @Inject
    // CamelContext camelContext;

    // AWSCredentials awsCredentials = new BasicAWSCredentials("myAccessKey", "mySecretKey");

    // ClientConfiguration clientConfiguration = new ClientConfiguration();
    // clientConfiguration.setProxyHost("http://myProxyHost");
    // clientConfiguration.setProxyPort(8080);

    AmazonS3 s3client = AmazonS3ClientBuilder.standard().withRegion(Regions.US_EAST_1).build();

    SimpleRegistry registry = new SimpleRegistry();
    registry.put("s3client", (AmazonS3)s3client);
    CamelContext ctx = new DefaultCamelContext(registry);

    // SimpleRegistry registry = new SimpleRegistry();
    // ((SimpleRegistry)registry).put("bean-name", new SomeBean());
    // registry.put("s3client", s3client);
    // CamelContext camelContext = getContext();
    // camelContext.getRegistry(CompositeRegistry.class).addRegistry(registry);

    // CamelContext camelContext = getContext();
    // SimpleRegistry registry = new org.apache.camel.impl.SimpleRegistry();
    // CompositeRegistry compositeRegistry = new CompositeRegistry();
    // compositeRegistry.addRegistry(camelContext.getRegistry());
    // compositeRegistry.addRegistry(registry);
    // registry.bind("s3Client", s3client);
    // camelContext.getRegistry().bind("s3Client", s3client);
    // registry.bind("s3client", s3client);    

    public void configure() {
    	
    	// from("aws-s3://helloBucket?prefix=hello.txt&useIAMCredentials=true&region={{camel.aws.region}}&proxyHost={{camel.proxy.host}}&proxyPort={{camel.proxy.port}}&proxyProtocol={{camel.proxy.protocol}}")
    	// from("aws-s3://{{camel.bucket}}?prefix={{camel.object}}&useIAMCredentials=true&region={{camel.aws.region}}")
        from("aws-s3://{{camel.bucket}}?prefix={{camel.object}}&amazonS3Client=#s3Client&useIAMCredentials=true")
        .routeId("s3read")
        .streamCaching()
        .to("log:s3?level=INFO&showAll=true");

    }
}`

I understand the beans.xml cannot be used as such. Any hints or pointers will be appreciated.

**Comment by gus-maurizio** [comment]
original beans.xml
`<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">

  <bean id="awsDefaultCredentialsProviderChain" class="com.amazonaws.auth.DefaultAWSCredentialsProviderChain" />
  <bean id="awsClientConfigEndpoint" class="com.amazonaws.ClientConfiguration">
  </bean>
  <bean id="s3"                     class="org.apache.camel.component.aws.s3.S3Component" />
  <bean id="vpcs3Client-us-east-1"  class="com.amazonaws.services.s3.AmazonS3Client">
    <constructor-arg index="0"    ref="awsClientConfigEndpoint" />
    <property name="endpoint"     value="${client.s3.us-east-1}" />
  </bean>

</beans>

`

**Comment by lburgazzoli** [comment]
There are a number of ways you can use to configure AWS S3 component, a simple one is to use properties, like [here](https://github.com/apache/camel-quarkus/blob/master/integration-tests/aws/src/main/resources/application.properties#L25-L27) but for a more advanced use case you can use a CDI producer, something like:

```java
@ApplicationScoped
public class S3Customizer {
    @Produces
    public static AmazonS3 s3Client() {
        return AmazonS3ClientBuilder
            .standard()
            .withEndpointConfiguration(...)
            .withCredentials(...)
            .withPathStyleAccessEnabled(...)
            .build();
    }
}
```

**Comment by gus-maurizio** [comment]
Thanks! I added your code and I get the following messages:
Caused by: org.apache.camel.PropertyBindingException: Error binding property (amazonS3Client=#s3Client) with name: amazonS3Client on bean: aws-s3://c7n.phoenix.cloudx.api.us-east-1?amazonS3Client=%23s3Client with value: #s3Client
...
Caused by: org.apache.camel.NoSuchBeanException: No bean could be found in the registry for: s3Client of type: com.amazonaws.services.s3.AmazonS3

Below are the pieces of code:
`
    @Override
    public void configure() {
    	
        from("aws-s3://{{camel.bucket}}?amazonS3Client=#s3Client")
        .routeId("s3read")
        .streamCaching()
        .to("log:s3?level=INFO&showAll=true");
    }

package com.example;

import javax.enterprise.context.ApplicationScoped;
import javax.ws.rs.Produces;

import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;

@ApplicationScoped
public class AWSCustomizer {
    @Produces
    public static AmazonS3 s3Client() {
        return AmazonS3ClientBuilder
            .standard()
            .build();
    }
}
`

**Comment by lburgazzoli** [comment]
yeah, to access named beans you need to add @Named to the producer method

**Comment by gus-maurizio** [comment]
same error. I must be doing something wrong

`
package com.example;

import javax.enterprise.context.ApplicationScoped;
import javax.ws.rs.Produces;

import javax.inject.Named;
import io.quarkus.runtime.annotations.RegisterForReflection;

import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;

@ApplicationScoped
@Named("s3Client")
public class AWSCustomizer {
    @Produces
    public static AmazonS3 s3Client() {
        return AmazonS3ClientBuilder
            .standard()
            .build();
    }
}
`

**Comment by lburgazzoli** [comment]
`@Named` should be on the method, like:

```java
@ApplicationScoped
public class S3Customizer {
    @Named
    @Produces
    public static AmazonS3 s3Client() {
        return AmazonS3ClientBuilder
            .standard()
            .withEndpointConfiguration(...)
            .withCredentials(...)
            .withPathStyleAccessEnabled(...)
            .build();
    }
}
```

**Comment by gus-maurizio** [comment]
that worked. Thanks!!! 
If I need to add more AWS clients, like AmazonSNS, can I leverage multiple methods (with Named and Produces in the same class? or do I need to add multiple classes?

**Comment by lburgazzoli** [comment]
same class is fine

**Comment by gus-maurizio** [comment]
Awesome

**Comment by davsclaus** [comment]
@lburgazzoli camel-quarkus based on camel-main ought to be able to auto discover those AWS Client beans that have been registered via @Produces (with or without @Named).

The option camel.main.autowireComponentProperties=true 
https://camel.apache.org/components/latest/others/main.html

is supposed to do that by scanning the components for options that hasn't been set and scan in registry if there is a single instance of the same type. 

It may be that camel-quarkus has disabled this - but its a great convention over configuration

**Comment by lburgazzoli** [comment]
No it is not disabled but if you set it explicit like in this case:
 
    amazonS3Client=#s3Client

the producer should be marked as `@Named` otherwise it cannot be discovered by name

**Comment by davsclaus** [comment]
Ah yeah sure, so basically if @gus-maurizio removed the ?amazonS3Client=#s3Client from the endpoint uri, then camel-quarkus would auto detect his @produces bean and use it on the component level automatic.

You can see this as Camel has a log summary of what was wired when it startup
