### ISSUE TITLE
[QUESTION] is there an equivalent in Quarkus/Kotlin to application.properties:camel.springboot.duration-max-seconds?

### ISSUE THREAD

**Issue by gus-maurizio** [apache/camel-quarkus#1441]
In spring boot there are two properties that stop the camel processes:
application.properties:camel.springboot.duration-max-seconds=20
application.properties:camel.springboot.duration-max-messages=5

Is there an equivalent for camel-quarkus (java or kotlin)?

**Comment by lburgazzoli** [comment]
There will be support in the next release 1.0.0.RC3 so if you add the camel-quarkus-main extensiosn to your dependencies, then you can do something like:

    camel.main.duration-max-seconds = 20

**Comment by gus-maurizio** [comment]
This is great news. Any hint on a date we can expect this? Is there documentation about this and other similar parameters like max-messages?

**Comment by davsclaus** [comment]
The options are listed here
https://camel.apache.org/components/latest/others/main.html

**Comment by gus-maurizio** [comment]
I assume this is not yet available on quarkus. Is there an example of how to use camel-main (ideally without the rest usual helloworld)?

**Comment by lburgazzoli** [comment]
There's the canonical timer to log example:  https://github.com/apache/camel-quarkus/tree/master/examples/timer-log-main
