### ISSUE TITLE
Document how to use mock in JVM mode tests

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1449]
It would be nice to have `extensions/mock/runtime/src/main/doc/usage.adoc` with an example showing that a mock endpoint can be injected into JVM test.

It would also be nice to have `extensions/mock/runtime/src/main/doc/limitations.adoc` informing that the above does not work (and why) in native mode.

**Comment by JiriOndrusek** [comment]
Please, assign to me.
