### ISSUE TITLE
@Handler on Bean does not resolve method

### ISSUE THREAD

**Issue by Namphibian** [apache/camel-quarkus#1459]
Hi Team.

Busy working on another example and came across the following error when using the ```@Handler``` on a bean.

Route below:
```
    @Override
    public void configure() throws Exception {
        camelContext.setMessageHistory(true);
        fromF("timer:foo?period=%s", period)
                .to("bean:greeterBean")
                .to("log:example");

    }
```

The bean definition:

```
@ApplicationScoped
@Named("greeterBean")
@RegisterForReflection
public class Greeter {

    public String greet(Exchange exchange) {
        return "greet hello world";
    }

    @Handler
    public String say(Exchange exchange) {
        return "say hello world";
    }
}
```

The following exception is thrown.

```
 org.apache.camel.component.bean.AmbiguousMethodCallException: Ambiguous method invocations possible: [public java.lang.String org.acme.sedaInterceptLog.Greeter_ClientProxy.greet(org.apache.camel.Exchange), public java.lang.String org.acme.sedaInterceptLog.Greeter_ClientProxy.say(org.apache.camel.Exchange)] on the exchange: Exchange[]
        at org.apache.camel.component.bean.BeanInfo.chooseMethod(BeanInfo.java:614)
```

Seems like ```@Handler``` is ignored completely.

If I change the bean definition to:

```
  
@ApplicationScoped
@Named("greeterBean")
@RegisterForReflection
public class Greeter {

    @Handler
    public String say() {
        return "say hello world";
    }
}
```

I get the following exception:
```
Caused by: [java.lang.IllegalStateException - No method invocation could be created, no matching method could be found on: org.acme.sedaInterceptLog.Greeter@946f731]
```

Is the ```@Handler``` annotation going to be used going forward? I can get the example to work just wondering about the annotations going forward.

**Comment by lburgazzoli** [comment]
We need to make it working, I guess the issue is because the of the proxy generated by ArC.

I think you can make it working by removing the CDI annotations and by binding the bean to the the context like with a static method on your route builder class:, something like:


```java
@BindToRegistry
public static Greeter greeterBean() {
    return new Greeter();
}
```

In the meantime we’ll investigate the issue with the `@Handler` annotation

**Comment by Namphibian** [comment]
Hi Team.

I can get it to work by changing the method to:

```
public class Greeter {

    
    public String say(Exchange exchange) {
        return "say hello world";
    }
}
```

However the ```@Handler``` is definitely buggy as the following code **wont work:**

```
  @Handler
    public String say() {
        return "say hello world";
    }
```

Seems like _method selection is working based on the parameters passed_ to methods. If there is no parameters it should use the ```@Handler``` to select the method. Specifying the bean method in the bean Uri like this ```to('bean:greeter?method=say')```also works.

**Comment by lburgazzoli** [comment]
@Namphibian the issue is cause by the Greeter bean to be a proxy to the real bean and the annotations are lost, whilse I'm looking on how to solve the issue, do you mind having a look at https://github.com/apache/camel-quarkus/pull/1461 and see if using @BindToRegistry works for you ?

**Comment by lburgazzoli** [comment]
Raised an issue on on Camel: https://issues.apache.org/jira/browse/CAMEL-15278

**Comment by Namphibian** [comment]
Hey @lburgazzoli 

I have tried using the static binding method as you have detailed in the open pull [1461](https://github.com/apache/camel-quarkus/pull/1461  ) however this is not working on my side.

I am getting the following exception:

```Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: bean://withHandler due to: No bean could be found in the registry for: withHandler```


I try and reproduce with your example later today but in my example it is not working at the moment.

**Comment by lburgazzoli** [comment]
@Namphibian can you please provide a reproducer ?

**Comment by gnodet** [comment]
I've created https://github.com/apache/camel-quarkus/issues/1459 as a fix but a reproducer would be handy to make sure the synthetic flag is correctly set on the proxy class.

**Comment by lburgazzoli** [comment]
@gnodet I've created a reproducer here: https://github.com/apache/camel-quarkus/pull/1465

**Comment by gnodet** [comment]
The PR https://github.com/apache/camel-quarkus/issues/1459 seems to fix the test @lburgazzoli , so I'll go ahead and commit the fix in camel.

**Comment by lburgazzoli** [comment]
cool, mind backporting to 3.4.x ?

**Comment by Namphibian** [comment]
@lburgazzoli 

Apologies I had a production issue yesterday and was stuck on that till early this morning. Do you still need a reproducer for the issue?

**Comment by gnodet** [comment]
> cool, mind backporting to 3.4.x ?

Done

**Comment by lburgazzoli** [comment]
@Namphibian you said that the workaround I provided with the `@BindToRegistry` does not work so it would be nice to have a reproducer for that.

**Comment by Namphibian** [comment]
Hey Team. 

Had some resourcing issues due to Covid thus only catching up now. Do you need a reproducer still? I am going to produce some more examples for the repo shortly.
