### ISSUE TITLE
Unable to build from source release zip

### ISSUE THREAD

**Issue by zhfeng** [apache/camel-quarkus#1460]
Currently, run ```./mvnw clean install -DskipTest``` in the download directory after unzip the release file. It will fail with
```
./mvnw: line 276: /home/zhfeng/Downloads/camel-quarkus-1.0.0-CR3/.mvn/wrapper/maven-wrapper.properties: No such file or directory
/home/zhfeng/Downloads/camel-quarkus-1.0.0-CR3/.mvn/wrapper/maven-wrapper.jar: No such file or directory
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain

```

**Comment by jamesnetherton** [comment]
I was about to raise the same issue. In addition, validation checks fail. Specifically the one that checks that each itest module was added to `test-categories.yaml`. Currently, we don't include the `.github` directory in the source bundle so this check fails.
