### ISSUE TITLE
Add Camel AS2 Modules as Quarkus Extension

### ISSUE THREAD

**Issue by ulrikian** [apache/camel-quarkus#1471]
Hello, 
most camel components are available as Quarkus extension, however AS2 is missing. We would appreciate if it was added as well. 
Best regards, uli

**Comment by oscerd** [comment]
@JiriOndrusek would you mind having a look? Thank you!

**Comment by JiriOndrusek** [comment]
Please, assign to me.
I'll look into it during following week.
