### ISSUE TITLE
org.apache.camel.NoTypeConversionAvailableException: No type converter available to convert from type: java.util.HashMap to the required type: java.nio.ByteBuffer with value {name=e}

### ISSUE THREAD

**Issue by dhanendras** [apache/camel-quarkus#1475]
java.lang.RuntimeException: org.apache.camel.NoTypeConversionAvailableException: No type converter available to convert from type: java.util.HashMap to the required type: java.nio.ByteBuffer with value {name=e}

I am trying to upload form data from postman and below is my Quarkus-camel code

  rest() .description("Upload Multiple Report via camel and netty")
		  .post("/submitodc")
		  .bindingMode(RestBindingMode.off)
		  .consumes(MediaType.MULTIPART_FORM_DATA)
		  .to("direct:uploadReportProcessor");
		  
		  from("direct:uploadReportProcessor")
		  .routeId("uploadProcessorRouteId") .process(OdcFileProcessor);
		 

Please let me know what am I missing over here.

**Comment by lburgazzoli** [comment]
you probably need to convert the result of your processor to the required type if you want to reply back with some data.

I doubt this is a camel-quarkus issue but in any case, a reproducer would help

**Comment by aldettinger** [comment]
Hi @dhanendras, and thanks for sharing you experience with camel-quarkus. I agree with Luca's view on this ticket.
I played a bit with a route like:
```
rest().post("/submitodc").consumes(MediaType.MULTIPART_FORM_DATA).to("direct:uploadReportProcessor");
from("direct:uploadReportProcessor").process(e -> e.getMessage().setBody(Map.of("name", "e")));
```
And indeed, we hit an issue as there are no pre-registered [converters](https://camel.apache.org/manual/latest/type-converter.html) to translate a `Map` to a `ByteBuffer`.

In such situation, one may end up using [camel-quarkus-gson](https://camel.apache.org/camel-quarkus/latest/extensions/gson.html) as below:
```
process(...).marshal().json(JsonLibrary.Gson);
```

Or maybe a [custom converter](https://camel.apache.org/manual/latest/type-converter.html#TypeConverter-Addtypeconverterclassesatruntime) similar to this:
```
public void configure() {
  getContext().getTypeConverterRegistry().addTypeConverters(new MyCustomConverters());
  ...
}

@Converter
public static class MyCustomConverters implements TypeConverters {
  @Converter
  public ByteBuffer toByteBuffer(HashMap<?, ?> map) {
    return ByteBuffer.wrap(...);
  }
}
```
Does it make sense for you ?

**Comment by aldettinger** [comment]
@dhanendras The post above may explain how to deal with such cases.
I'm going to close this ticket now but one is very welcome to reopen it if necessary.
