### ISSUE TITLE
Add camel-master extension

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-quarkus#1476]
The [camel-master](https://camel.apache.org/components/latest/master-component.html) component has no corresponding extension in camel-quarkus.

**Comment by jamesnetherton** [comment]
Duplicate of https://github.com/apache/camel-quarkus/issues/711.

**Comment by nicolaferraro** [comment]
I see @dhirajsb was working on that, should we close this?

**Comment by jamesnetherton** [comment]
Yeah let's close. I'll add the other issue to the GA milestone so that we don't forget about it.

@dhirajsb are you planning to work on #711?

**Comment by jamesnetherton** [comment]
Closing as its a dupe. I'll work on #711.
