### ISSUE TITLE
Publish snapshots for quarkus-master and camel-master branches

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1486]
To add functionalities to the camel-k-runtime that may require a camel or quarkus version not yes supported by any camel-quarkus release, I need to build the whole chain which is ok but having snapshots available - even with all the limitations snapshots have - would help doing quick experiments.

We could have some versioning like:
- 999-SNAPSHOT --> camel-quarkus master
- XX-SNAPSHOT --> camel-quarkus vs quarkus master
- YYY-SNAPSHOT --> camel-quarkus vs camel master

**Comment by lburgazzoli** [comment]
@jamesnetherton I think we can close this one right ?

**Comment by jamesnetherton** [comment]
The build is here:

https://ci-builds.apache.org/job/Camel/job/Camel%20Quarkus%20SNAPSHOT%20Deploy/

I fixed a little issue this morning. I was going to wait till SNAPSHOTs from each branch had been published before closing. But if you want to close now, go ahead.

**Comment by jamesnetherton** [comment]
Snapshot builds for all branches are working now:

`master` branch - 1.1.0-SNAPSHOT
`camel-master` branch -  1.1.0-CAMEL-MASTER-SNAPSHOT
`quarkus-master` branch -  1.1.0-QUARKUS-MASTER-SNAPSHOT
