### ISSUE TITLE
Debezium test fails on branch camel-master

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#1490]
There is a failure in integration-tests/debezium.

>2020-07-21 14:00:35,137 INFO  [org.apa.kaf.con.sto.FileOffsetBackingStore] (Camel (camel-1) thread #0 - DebeziumConsumer) Starting FileOffsetBackingStore with file /tmp/DebeziumPostgresTestResource-store-17093730932408244836
2020-07-21 14:00:35,141 ERROR [io.deb.emb.EmbeddedEngine] (Camel (camel-1) thread #0 - DebeziumConsumer) null
2020-07-21 14:00:45,142 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /debezium-postgres/receive failed, error id: 21b10f09-ecd8-45d1-b314-fe08f0ce3ab4-1: org.jboss.resteasy.spi.UnhandledException: java.lang.NullPointerException
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
...
> [INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   DebeziumPostgresTest>AbstractDebeziumTest.testDelete:132->AbstractDebeziumTest.receiveResponse:147 1 expectation failed.
Expected status code <204> but was <500>.
>
>[ERROR]   DebeziumPostgresTest>AbstractDebeziumTest.testInsert:87 1 expectation failed.
Expected status code <200> but was <500>.
>
>[ERROR]   DebeziumPostgresTest>AbstractDebeziumTest.testUpdate:109->AbstractDebeziumTest.receiveResponse:147 1 expectation failed.
Expected status code <200> but was <500>.
>
>[INFO] 
[ERROR] Tests run: 11, Failures: 3, Errors: 0, Skipped: 8

Same error could be seen on PR for camel-master branch https://github.com/apache/camel-quarkus/pull/1462.

Reason is probably a version conflict, as it seems that one depricated class is missing.

**Comment by JiriOndrusek** [comment]
Please, assign to me.

**Comment by JiriOndrusek** [comment]
Test is successful on master branch.

**Comment by JiriOndrusek** [comment]
Reason is one issue in debezium 1.2.0.Final version, which is solved in 1.2.1.Final version. https://issues.redhat.com/browse/DBZ-2302

**Comment by jamesnetherton** [comment]
I updated the camel-master branch to use 1.2.1.Final. But there are still issues with native mode.

I had to register `io.debezium.embedded.ConvertingEngineBuilderFactory` for reflection and add `META-INF/services` for debezium-embedded to the native image. But some of the tests fail with an NPE.

**Comment by JiriOndrusek** [comment]
@jamesnetherton I'm looking into it now. I suppose that there will be needed some changes in debezium extension. (debezium 1.2.1 possible fixes one issue but bring several more)

**Comment by jamesnetherton** [comment]
This has been fixed on the camel-master branch.
