### ISSUE TITLE
Add tests to example projects

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#1501]
We should add some basic tests to each example project to validate that they work.

**Comment by ppalaga** [comment]
In addition, I'd vote for not accepting new examples unless they have tests.

**Comment by Namphibian** [comment]
Hey Team.

I am about to submit a new pull request with a new example project. My example does not have a test case yet and I am keen to get this in. However the only examples of test cases I have seen so far is using the REST interfaces in other words the camel routes are exposed as REST endpoints. Do we have examples of how to stop and start a route by itself and writing a unit test for that? In short I have not found documentation or examples showing me how to test a stand-alone camel route.Once I have an idea of how to do it I can proceed to add it to other examples where applicable.

**Comment by jamesnetherton** [comment]
I added some basic tests to the example projects.
