### ISSUE TITLE
@BindToRegistry not working with @ApplicationScoped route builders

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#1505]
This behaviour could be reproduced in camel-grok itests route by attempting to replace [explicit `bindToRegistry` calls](https://github.com/apache/camel-quarkus/blob/master/integration-tests/grok/src/main/java/org/apache/camel/quarkus/component/grok/it/GrokRoute.java#L32..L34) with `@BindToRegistry`.

The route can't start as @BindToRegistry Grok patterns are not present in the registry when GrokDataFormat.start() is called.
As far as I could tell, it seems to me that bean post processing never occurs in this scenario. So we may have even more annotations that are not working.

Would one agree it's an issue ? Would adding bean processing in this scenario be the solution ? where/when ?

**Comment by lburgazzoli** [comment]
I think this is expected as back in the earlier days we decided that if you rely on CDi then you should use @Produces as it is more idiomatic

**Comment by aldettinger** [comment]
Thanks for sharing Luca, I was able to achieve this effect with [qualified producer fields](https://github.com/apache/camel-quarkus/commit/7736d416e0333cb41ce0bbd5652a803ca80a118a).
