### ISSUE TITLE
Add core extension to the list of extensions documentation

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#1510]
On the extension list docs page, info about the `core` extension is kinda hidden behind links for other things like `simple`, `constant` etc.

We should add it as its own entry into the list, since it documents a lot of camel-quarkus [configuration properties](https://camel.apache.org/camel-quarkus/latest/extensions/core.html#_additional_camel_quarkus_configuration) that folks may find useful.

**Comment by ppalaga** [comment]
There was a discussion on dev@camel.apache.org https://www.mail-archive.com/dev@camel.apache.org/msg50968.html about whether the "List of Extensions" page should honor its name. Nobody seemed to oppose that idea. This issue could be solved by implementing it.
