### ISSUE TITLE
Add entry in Quarkus MAINTAINERS.adoc

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1523]
We should mention camel here: https://github.com/quarkusio/quarkus/blob/master/MAINTAINERS.adoc

**Comment by lburgazzoli** [comment]
@jamesnetherton @ppalaga are you ok if I put you as primary contact ?

**Comment by ppalaga** [comment]
No problem

**Comment by jamesnetherton** [comment]
> @jamesnetherton @ppalaga are you ok if I put you as primary contact ?

Fine with me.

**Comment by lburgazzoli** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/11316
