### ISSUE TITLE
http related tests rely on external service that may sometimes be down

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1538]
https://restcountries.eu/rest/v2/alpha/cz is used by http tests but it may be down (as now) and break the tests

**Comment by ppalaga** [comment]
Time to fix restcountries?

**Comment by lburgazzoli** [comment]
wonder if we should use [mockserver](https://www.testcontainers.org/modules/mockserver/) module

**Comment by oscerd** [comment]
That project is mostly dead, there is a guy working on a fork of the apilayer restcountries API and he is providing a new url with the service up and running

**Comment by oscerd** [comment]
https://restcountries.com/v2/alpha/cz

**Comment by jamesnetherton** [comment]
> wonder if we should use [mockserver](https://www.testcontainers.org/modules/mockserver/) module

Or just locally stub out whatever endpoint(s) we need with a JAX-RS resource class.

**Comment by lburgazzoli** [comment]
I think the only reason we use restcountries is because of the ssl

**Comment by lburgazzoli** [comment]
I don't know how simple it is to have an ssl and a non ssl endpoint in quarkus

**Comment by lburgazzoli** [comment]
I'm switching to the `restcountries.com/v2/alpha/cz` for the moment, then we need a better solution

**Comment by ppalaga** [comment]
Yeah, SSL was the main motivation for using restcountries
