### ISSUE TITLE
AWS 2 Kinesis native support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1571]

**Comment by Jeansen** [comment]
Next for me ;-)

**Comment by ppalaga** [comment]
Optional: it would be great if there was some test assertions for Kinesis that would be run only if the AWS credentials were set in the environment - something like we have for Twitter https://github.com/apache/camel-quarkus/blob/master/integration-tests/twitter/src/test/java/org/apache/camel/quarkus/component/twitter/CamelTwitterTest.java#L30 It is a long standing TODO for all existing AWS extensions and we will have to address it at some point.

**Comment by Jeansen** [comment]
OK, I'll keep that in mind when trying to resolve this one.

**Comment by gitmalong** [comment]
Is this the reason I'm facing that issue https://stackoverflow.com/questions/64189831/getting-status-code-500-errors-when-accessing-localstack-kinesis-stream-with-ca

**Comment by oscerd** [comment]
This is with aws sdk v2, so probably no, it isn't

**Comment by oscerd** [comment]
If nobody is working on this, I can add this one.

**Comment by Jeansen** [comment]
I am sorry, I know, I've actually wanted to implement this but other "things" currently consume more time than anticipated.

**Comment by ppalaga** [comment]
BTW, AWS 2 Kinesis now has a test https://github.com/apache/camel-quarkus/tree/master/integration-tests-aws2/aws2-kinesis

**Comment by ppalaga** [comment]
I dared to send a PR https://github.com/apache/camel-quarkus/pull/2252

**Comment by oscerd** [comment]
Thanks, I started to work on something last week but no problem
