### ISSUE TITLE
Consider importing camel-bom in camel-quarkus-bom

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#159]
Consider importing camel-bom in camel-quarkus-bom instead of managing the Camel components ourselves. 

Pros:

* This would make the life easier to us (camel-quarkus)
  * by having to maintain less lines of code in camel-quarkus-bom
  * by not having to add the camel libs when adding new extensions
* This would make the live easier to our users when using components that do not have an extension yet.

Cons: 

* The Camel BOM contains some stuff that we and our users do not need, such as `*-starter` s. Not sure this could be harmful in any situation.

WDYT?

**Comment by ppalaga** [comment]
Not a good idea, because availability of all Camel components might be misunderstood by the end user as all those components being supported on Camel Quarkus. The create-extension mojo should rather be extended to (optionally) add the given Camel component.

**Comment by ppalaga** [comment]
Sent https://github.com/quarkusio/quarkus/pull/3836 that adds `CreateExtensionMojo.additionalRuntimeDependencies` that can be used to add the Camel component dependency to the runtime BOM and to the runtime extension module.

**Comment by lburgazzoli** [comment]
I would revisit this decision as:
- camel spring boot support has it's own repo
- camel-k project generation relies on boms to support multiple camel version so if a dependency is missing in the quarkus bom when it generates quarkus images, then the project would fail to build

**Comment by ppalaga** [comment]
We should consider how this would impact the Quarkus platform because it imports our bom

**Comment by ppalaga** [comment]
I think we have found a middle-ground. Our top level pom inherits from `org.apache.camel:camel-dependencies` and we wrap their `<artifactId>-version` properties into our `<artifactId>.version` props so that we keep an overview which exact versions come from Camel. I am quite content with this solution and I do not see a need to import Camel BOM at this time.

**Comment by ppalaga** [comment]
@lburgazzoli would Camel K still benefit from us importing the Camel BOM in any way?

**Comment by lburgazzoli** [comment]
since we switched to camel quarkus as the only supported runtime, I think we do not require to import the camel bom anymore
