### ISSUE TITLE
Speed up the CI

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1602]
Here an idea what we could do:

## Current state

* The initial build on Java 11 runs with tests `./mvnw -V -ntp ${BRANCH_OPTIONS} clean install` 
* As a consequence of that all the other jobs have to wait for the JVM tests (40+ mins IIRC) to finish

## Proposed state

* The initial build on Java 11 should skip the tests and Quarkus mojos:
`./mvnw -V -ntp ${BRANCH_OPTIONS} clean install -DskipTests -Dquarkus.build.skip` 
* The skipped tests should be run in three (groups of) separate jobs:

1. Functional unit tests (under `extensions-core` and `extensions` directories) 
2. JVM tests under `extensions-jvm`
3. JVM and native tests under `integration-tests`

The group 3. is covered by the current `native-tests` job. I think there is no need to change it.

Groups 1. and 2. are new.

### How would this play with alternative JVM Jobs? 

We currently both build and JVM-test on alternative JVMs (8 and 14). I think it would be enough to test on both, re-using the artifacts built by the initial job. Intead of `mvn clean verify` in the root dir, we could do something like `cd extensions-jvm && mvn test` and `cd integration-tests && mvn test`. I think there is no need to run the functional tests on Java 8 and 14.

### I hope the groups 1., 2., and 3. cover all tests we have?

WDYT?

**Comment by jamesnetherton** [comment]
Sounds ok to me in principal. 

> I hope the groups 1., 2., and 3. cover all tests we have?

Some of the examples have itests, so maybe we should run those in their own group?
