### ISSUE TITLE
Provide a quick profile

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1607]
As mentioned in [this](https://github.com/apache/camel-quarkus/pull/1606#discussion_r476512634) comment, it would be nice to have a `quick` profile that can be used to quickly install camel-quarkus

**Comment by ppalaga** [comment]
Candidates for an exclusion from a quick profile:

* enforcer:enforce
* impsort:sort
* formatter:format
* (some?) groovy:execute
* license:check
* camel-quarkus:update-extension-doc-page
* quarkus:build

The caveat id that not having the mojo in the build at all is even faster than skipping it through its property. Alone the instantiation of some mojos is quite slow. Let me figure out if we can remove them from the default profile-less build and have them only in a special profile (let's call is `full`) that would be enabled by default and disabled by `-Dquickly`
