### ISSUE TITLE
support camel-box

### ISSUE THREAD

**Issue by claudio4j** [apache/camel-quarkus#162]

**Comment by davsclaus** [comment]
camel-box is deprecated if its this component? And if so then we will not do this, otherwise tell us a bit more what you are looking for

**Comment by tadayosi** [comment]
Is camel-box deprecated?  I couldn't find any information about that.

**Comment by davsclaus** [comment]
Ah sorry its dropbox, we should have named it camel-dropbox. We used to have some old box stuff for a camel "blackbox" thingy that was deprecated very long time

**Comment by johnpoth** [comment]
I can take a look at this
