### ISSUE TITLE
FOP native support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1642]

**Comment by JiriOndrusek** [comment]
Please, assign to me.

**Comment by JiriOndrusek** [comment]
It s not possible to creative native extension for camel-fop.
The effort is blocked by this error (during native execution):

>Error: No instances of sun.nio.ch.FileChannelImpl are allowed in the image heap as this class should be initialized at image runtime. Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked.
Trace: Object was reached by 
	reading field sun.font.TrueTypeFont$TTDisposerRecord.channel of
		constant sun.font.TrueTypeFont$TTDisposerRecord@2c7b7d19 reached by 
	reading field java.util.Hashtable$Entry.value of
		constant java.util.Hashtable$Entry@66aeea4 reached by 
	indexing into array
		constant java.util.Hashtable$Entry[]@7be2410f reached by 
	reading field java.util.Hashtable.table of
		constant java.util.Hashtable@33cc3b6c reached by 
	scanning method sun.java2d.Disposer.addObjectRecord(Disposer.java:250)

I was able to debug some calls to TrueTypeFont (in case of conversion into pcl, png). This showed me some calls from fop, which causes initialization of these classes.
E.g.: https://github.com/apache/xmlgraphics-fop/blob/trunk/fop-core/src/main/java/org/apache/fop/render/java2d/InstalledFontCollection.java#L79, https://github.com/apache/xmlgraphics-fop/blob/trunk/fop-core/src/main/java/org/apache/fop/render/java2d/Java2DFontMetrics.java#L318
But unfortunately there are a lot of other calls to similar awt classes from fop (or from batik - which is dependency of fop)


My WIP is here: https://github.com/JiriOndrusek/camel-quarkus/tree/1642-FOP-native
(JVM test is working, native fails with above error)

**Comment by JiriOndrusek** [comment]
There is a fop issue about quarkus support: https://issues.apache.org/jira/browse/FOP-2967

**Comment by JiriOndrusek** [comment]
I'll look into suggested solution to avoid awt fonts (https://issues.apache.org/jira/browse/FOP-2967?focusedCommentId=17190197&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17190197)
