### ISSUE TITLE
HBase native support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1648]

**Comment by ppalaga** [comment]
Even a JVM extension is hard to do due to dependency alignment issues and due to the fact that there is no way to configure the component not to connect to the cluster at startup. Here my today's attempt that basically works, but is not good enough to be merged: https://github.com/ppalaga/camel-quarkus/commit/f2401f3feb8563b80b3b72a739b206fdd7017b61

**Comment by ppalaga** [comment]
The dependency hell was not that bad after all, at least the extension part - so I solved it with the usual means. The test module was a bit worse due to the mess in the transitive dependencies of `hbase-testing-util` (used to start the test cluster). For that one, was able to keep dependencyManagement config in the test module.

**Comment by ppalaga** [comment]
The native mode is partly finished in #1906, I gave up when I found out that HBase has a shaded Netty.

**Comment by ppalaga** [comment]
The shaded Netty is version 3.x and in addition to that there is Netty 4.x in the client class path. Therefore the unshading trick we applied in #2008 won't work here. 

I tied with trial and error strategy a bit, but did not come too far without understanding the hbase client internals. Here is my last state: https://github.com/ppalaga/camel-quarkus/tree/i1648.2

**Comment by jamesnetherton** [comment]
HBase was removed in Camel 4.x.
