### ISSUE TITLE
Google PubSub example

### ISSUE THREAD

**Issue by raphaelchaula** [apache/camel-quarkus#1659]
I request more examples in examples repo especially Google PubSub if possible

**Comment by ppalaga** [comment]
Indeed, there is no Google PubSub example yet. That's related to the fact that the Google PubSub component is supported only in JVM mode so far. @jamesnetherton might want to consider creating an example once he fixes #1041 ?

**Comment by raphaelchaula** [comment]
Thank you so much @ppalaga
