### ISSUE TITLE
camel-quarkus-activemq extension broker url configuration

### ISSUE THREAD

**Issue by jwwallin** [apache/camel-quarkus#1661]
There doesn't seem to be any good way of configuring the ActiveMQ broker url for this extension. At the very least there is no documentation on how to do this.

**Comment by lburgazzoli** [comment]
Configuring component is not different from plain camel, depending on your set-up you can have multiple options.

- If you have `camel-quarkue-main` among the dependencies of your ptoject, you can use the property `camel.component.activemq.broker-url`
- If you run on plain CDI you can create your custom instance of the component see the [bootsrtap](https://camel.apache.org/camel-quarkus/latest/user-guide/bootstrap.html) guide

**Comment by jwwallin** [comment]
Thanks for the quick answer. I resorted to using the second option you gave as it was the only one I could find on my own. 

I do still think this information should be clearly stated in the documentation for this extension. There is no indication that you would need to use either of these two approaches.

**Comment by lburgazzoli** [comment]
we can add it but in general components follow the same rules regardless of the runtime and if not, the difference are documented.

in this example, the documentation about this extension https://camel.apache.org/camel-quarkus/latest/reference/extensions/activemq.html redirects to the component guide as there are no difference

**Comment by jwwallin** [comment]
True, it does point to the components documentation, but that doesn't help me if the way to use that information isn't clearly stated. My point here is that the necessary information should really be easy to access, easiest way being **clearly stated** in the context it applies. That could also just be a link to a tutorial on using `camel-quarkus-main`. My problem with this is solved so I'll close this issue.

**Comment by lburgazzoli** [comment]
We probably need to reorganize the documentation in some areas, do you mind open an issue with some suggestions to the main camel project ?

**Comment by jwwallin** [comment]
I'll happily do that but I didn't quite understand where exactly you mean. What do you mean by the "main camel project"?

**Comment by lburgazzoli** [comment]
Well, as you know camel-quarkus is a sub-project of Apache Camel and since this issue is not quarkus specific, I'd recommend opening an issue against Camel (https://issues.apache.org/jira/projects/CAMEL)
