### ISSUE TITLE
Make mvn -N cq:format remove empty application.properties files

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#1676]

**Comment by aldettinger** [comment]
The application.properties file may not be needed most of the time, more context [here](https://github.com/apache/camel-quarkus/pull/1674#discussion_r482195714).

**Comment by ppalaga** [comment]
Hm... this is certainly a valid issue, but I must say I find it handy to have the file when I want to add something into it. 

How about modifying the formatting mojo (that people should invoke before sending a PR anyway) to remove empty property files?

**Comment by aldettinger** [comment]
Yes, that would make sense. I don't see any case where keeping a properties file with just header comment would be needed.
