### ISSUE TITLE
A tool to check/sync dependency versions with camel & quarkus 

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1684]
The version properties in our top level pom.xml are maintained manually ATM. We should have some sort of a tool for that.
Followup of https://github.com/apache/camel-quarkus/pull/1682#issuecomment-686409318

**Comment by lburgazzoli** [comment]
I think we have something in use for camel kafka connector made by @oscerd

**Comment by oscerd** [comment]
We have the camel-dependencies module in the main camel-repo. You can do as we are doing in camel-karaf/camel-spring-boot/camel-kafka-connector https://github.com/apache/camel-kafka-connector/blob/master/pom.xml#L26

You'll get the properties placeholder of Camel in your POM and this POM will use the Apache POM as parent POM.

**Comment by ppalaga** [comment]
ca3514e solves the issue with Camel, but not with Quarkus

**Comment by ppalaga** [comment]
Or the problem with Quarkus does not exist anymore?

**Comment by jamesnetherton** [comment]
You're right, it solves the camel part but not the Quarkus part.

It's not immediately obvious which of the version properties are actually supposed to be aligned with Quarkus.

**Comment by ppalaga** [comment]
In between we started using `@sync` annotation in the top pom.xml. The annotated props can then be update by running `mvn cq:sync-versions -N` manually. I think we can close this issue.
