### ISSUE TITLE
Move examples to a separate git repository

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1691]
Followup of https://github.com/apache/camel-quarkus/pull/1689#issuecomment-687582603

**Comment by ppalaga** [comment]
@oscerd I hope I recollect it right, that you can create new repos under the apache GH org? Could you please create `camel-quarkus-examples` ?

**Comment by oscerd** [comment]
Sure I'll do it. There is 4 hours before we'll be able to write on it anyway

**Comment by ppalaga** [comment]
> There is 4 hours before we'll be able to write on it anyway

It is not that urgent :). Thanks!

**Comment by oscerd** [comment]
https://github.com/apache/camel-quarkus-examples

We can add an .asf.yml file with description and notice, license etc. I can do that.

**Comment by oscerd** [comment]
It was faster than last time, it's already writable I guess
