### ISSUE TITLE
Be able to determine that the test was run against external service or not

### ISSUE THREAD

**Issue by llowinge** [apache/camel-quarkus#1717]
There exist some tests which are run against mocked services (eg. SlackTest) by default. If we set ENV property, it should be run against external service but we cannot say that with 100%, becasue eg. ENV property can change the name and so the test would be run against mocked service only.

Suggested way would be adding some property eg. -Dtest.external.service=true, which would skip the test, if the needed ENV properties are not set.

**Comment by ppalaga** [comment]
Fixed via https://github.com/apache/camel-quarkus/pull/1818
