### ISSUE TITLE
[Camel 3.6?] Improve the camel-bean extension by not using an alias for BeanAnnotationExpressionFactory

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#1725]
We should be able to remove the BeanAnnotationExpressionFactory alias in camel-bean when the fix for [this upstream issue](https://issues.apache.org/jira/browse/CAMEL-15506) has been shipped. It should happen when adopting camel >= 3.6.0.

**Comment by ppalaga** [comment]
Fixed in 1.3.0 via 96f1c0acee7d1ebd6ee344993a2b57ebe7abd77e
