### ISSUE TITLE
[Camel 3.6?] Remove createEndpoint method override in QuarkusVertxWebsocketComponent

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#1737]
Depends on https://issues.apache.org/jira/browse/CAMEL-15501.

**Comment by ppalaga** [comment]
> Depends on https://issues.apache.org/jira/browse/CAMEL-15501.

- that's Camel 3.6-ish, right?

**Comment by jamesnetherton** [comment]
Yep it'll be in Camel 3.6. I'll probably fix it as part of the upgrade on the `camel-master` branch, once the new SNAPSHOT is available.

**Comment by oscerd** [comment]
The new snapshot for 3.6.0 should be available in Asf snapshot repo

**Comment by ppalaga** [comment]
Fixed in 1.3.0 via 330056bd640ef4bd50eb93ebb62e6bfb4582ee15
