### ISSUE TITLE
JSLT native support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1740]

**Comment by egekaraosmanoglu** [comment]
Is there any plan for the JSLT native support?

Regards

**Comment by aldettinger** [comment]
Hey @egekaraosmanoglu, thanks for sharing your interest in the native support for this extension. No one is currently working on this but we really love contributions :) Would you like to have a try helped with this [contributor guide](https://camel.apache.org/camel-quarkus/latest/contributor-guide/promote-jvm-to-native.html) ?

**Comment by aldettinger** [comment]
Implementation done. @egekaraosmanoglu, you are welcome to test in the coming 1.4.0 next version.

**Comment by egekaraosmanoglu** [comment]
> Implementation done. @egekaraosmanoglu, you are welcome to test in the coming 1.4.0 next version.

thanks a lot!  i will test it for sure.
