### ISSUE TITLE
camel-quarkus-main - Uses reflection for setting its name

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#1765]
Notice this in the http-log example

2020-09-09 13:52:20,310 INFO  [org.apa.cam.imp.eng.DefaultBeanIntrospection] (Quarkus Main Thread) Invoked: 1 times (overall) [Method: setProperty, Target: org.apache.camel.quarkus.core.FastCamelContext@5a2266eb, Arguments: [name, quarkus-camel-example-http-log]]

This is with master branch (eg camel 3.5 as of today)

**Comment by davsclaus** [comment]
So FastCamelContext needs to either have a custom generated configurer or we need to make it an instanceof ExtendedCamelContext which would have configurer out of the box.

**Comment by davsclaus** [comment]
@lburgazzoli there is some fast factory finder resolver that causes it to not find ExtendedCamelContext.class - maybe its due its using FQN name now?

**Comment by lburgazzoli** [comment]
it is likely that, will have a look

**Comment by davsclaus** [comment]
Okay the example can run native compiled (I guess its because the FastCamelContext is open for reflection)

**Comment by davsclaus** [comment]
(main) Stopping BeanIntrospection which was invoked: 1 times

**Comment by lburgazzoli** [comment]
The issue is caused by the fact that the configurer for the ExtendedCamelContext has a wrong factory file which is `org.apache.camel.impl.ExtendedCamelContext` instead of `org.apache.camel.ExtendedCamelContext`

Opened an issue upstream https://issues.apache.org/jira/browse/CAMEL-15518
