### ISSUE TITLE
Adding Changelog generated automatically through gh action

### ISSUE THREAD

**Issue by oscerd** [apache/camel-quarkus#1772]
We are using this gh action on camel-k, camel-k-runtime and camel-kafka-connector.

I think the result is really useful to track the activities.

Do we want to introduce it here too?

https://github.com/apache/camel-kafka-connector/blob/master/CHANGELOG.md

**Comment by ppalaga** [comment]
I see quite a lot of `Updated CHANGELOG.md` commits in the Kafka connector log https://github.com/apache/camel-kafka-connector/commits/master I must say, I'd prefer having as little commits of this kind as possible. Perhaps having one just before the release would be sufficient.
How is the action triggered?

**Comment by oscerd** [comment]
On schedule each night

**Comment by oscerd** [comment]
From a couple of days. Before it was done on each pr merged, issue closed etc

**Comment by ppalaga** [comment]
I see. I could live with one commit a day (if there is some activity on that day). But anyway, it would be handy to be able to trigger an update manually before cutting a release. Would something like that be possible?

**Comment by ppalaga** [comment]
... and yes, having a way to auto-assemble a change log is useful. Thanks for proposing it!

**Comment by oscerd** [comment]
I never heard of possibility of running gh action manually but maybe @jamesnetherton knows more

**Comment by jamesnetherton** [comment]
> I never heard of possibility of running gh action manually but maybe @jamesnetherton knows more

I think you'd need to have a personal access token set up to do that.

One option could be to trigger the changelog action whenever a new tag is pushed.

**Comment by ppalaga** [comment]
> One option could be to trigger the changelog action whenever a new tag is pushed.

I thought that would be too late for the new tag to appear in the change log, when the change log is referenced via the given tag. But apparently it works somehow for Kafka connector - release 0.5.0 is listed as of 'camel-kafka-connector-0.5.0' tag of the change log https://github.com/apache/camel-kafka-connector/blob/camel-kafka-connector-0.5.0/CHANGELOG.md
The workflow run preceding the tag knew somehow magically that the tag is going to happen https://github.com/apache/camel-kafka-connector/commit/fe8aae3e87c29dae1e2c9843210238f7e2c6f085#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR3
I wonder how is that possible?

**Comment by oscerd** [comment]
The tag was created and then removed :-) because we had problem with the release
