### ISSUE TITLE
Suggestion: Add column for native supported version in camel quarkus extensions list

### ISSUE THREAD

**Issue by Jeansen** [apache/camel-quarkus#1781]
Currently, there is only one column referencing the version since when an extension is available -> https://camel.apache.org/camel-quarkus/latest/reference/index.html

But an extension can have two stages: JVM and NATIVE.

I suggest adding a second column which reflects the version since when native support is available for an extension.

In addition I would suggest that instead of three tags on each extension page, there should only be two. For instance:

JVM: 1.0.0
NATIVE: not supported

And then later, when native is supported:
JVM 1.0.0
NATIVE: 1.1.0

**Comment by ppalaga** [comment]
I like the proposal. We are in the middle of changing how the reference pages are generated - see https://github.com/apache/camel-quarkus/issues/1557 and https://github.com/apache/camel-quarkus/pull/1777 We may implement this as a part of that or after that.

**Comment by ppalaga** [comment]
Done via https://github.com/apache/camel-quarkus/pull/1777
* https://camel.apache.org/camel-quarkus/latest/reference/index.html
* https://camel.apache.org/camel-quarkus/latest/reference/components.html
* https://camel.apache.org/camel-quarkus/latest/reference/dataformats.html
* https://camel.apache.org/camel-quarkus/latest/reference/languages.html
* https://camel.apache.org/camel-quarkus/latest/reference/others.html
