### ISSUE TITLE
Add integration tests for camel-quarkus-kafka + sasl 

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1783]
Follow up for https://github.com/quarkusio/quarkus/issues/11411#issuecomment-690987909

**Comment by orpiske** [comment]
Hey @lburgazzoli, I'll ping you Monday when I get back, but just in case: I have moved some of the CKC kafka test infra: https://github.com/apache/camel/pull/4242. 

I believe this might give the basics to implement a test on Camel Quarkus as well.

**Comment by jamesnetherton** [comment]
I did this as part of https://github.com/apache/camel-quarkus/commit/6e440e02573a2ae136983454f345424e85cd0083.
