### ISSUE TITLE
Generate documentation to be included in quarkus

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#183]

**Comment by ppalaga** [comment]
Any refs. what the docs should look like?

**Comment by lburgazzoli** [comment]
We should have some minimal documentation to be shown in the quarkus guides, it should not be complete but a sort of quick start, for in depth doc we should redirect to camel main website

**Comment by ppalaga** [comment]
I mean an example of this kind of docs for some Quarkus'es own extension would be helpful.

Should that be a per extension `.adoc` file?

**Comment by lburgazzoli** [comment]
Something similar to guides available here: 

    https://github.com/quarkusio/quarkus/tree/master/docs/src/main/asciidoc

**Comment by gnodet** [comment]
https://github.com/quarkusio/code.quarkus.io#update-the-extensions-list

**Comment by ppalaga** [comment]
> Something similar to guides available here:
> 
> ```
> https://github.com/quarkusio/quarkus/tree/master/docs/src/main/asciidoc
> ```

So the docs you ask for would be published anlong the Quarkus guides under https://quarkus.io/guides/ ?  If so, a single generic (not per Camel Quarkus extension) Camel guide would be enough, right?

**Comment by lburgazzoli** [comment]
Correct, a generic doc and a link to camel-quarkus website is enough

**Comment by ppalaga** [comment]
Plz. assign to me.

**Comment by ppalaga** [comment]
https://github.com/quarkusio/quarkus/pull/4521

**Comment by ppalaga** [comment]
https://github.com/quarkusio/quarkusio.github.io/pull/312

**Comment by ppalaga** [comment]
The Camel page on quarkus.io is online since a couple of weeks  https://quarkus.io/guides/camel

This issue can be closed.
