### ISSUE TITLE
Leverage platform http service

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#184]
As today to leverage the http service provided by quarkus we do rely on `servlet` but we can do much better and bypass the servlet engine.

To do so we need to create a sort of "platform http component" that leverage what the platform camel runs on has to offer i.e.

- quarkus --> vertx-web
- spring --> ???
- widfly --> undertow/servlet
 
I would start by creating such component and quarkus binding here and once we have a stable enough API we can move the common part to main camel repository.

**Comment by ppalaga** [comment]
Sounds reasonable. Feel free to assign to me.

**Comment by ppalaga** [comment]
BTW, what is the relationship to the new quarkus router engine?

**Comment by ppalaga** [comment]
How should the URI scheme be called? `http-server` maybe?

**Comment by ppalaga** [comment]
> How should the URI scheme be called? `http-server` maybe?

Going with `platform-http` after a discussion with @lburgazzoli

**Comment by davsclaus** [comment]
Btw is there anything that makes this http-platform component quarkus specific? I am asking as it may be something we should eventually move to upstream main Camel so it can be used elsewhere too.

**Comment by lburgazzoli** [comment]
There is a SPI for platform specific code so yes, the component should be moved to mian Camel as soon as the SPI is stable enough (there is still some work to be done to i.e. make this component usable for the rest dsl)
