### ISSUE TITLE
Duplicate license headers in Velocity test templates

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1843]
We have two license headers for some reason here and elsewhere.

_Originally posted by @ppalaga in https://github.com/apache/camel-quarkus/pull/1804#discussion_r494977020_

**Comment by ppalaga** [comment]
@JiriOndrusek could you please pick this one?

**Comment by JiriOndrusek** [comment]
Please, assign to me. I see the reason, it was caused by my bad revert of the test code.
