### ISSUE TITLE
Shiro native support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1844]

**Comment by JiriOndrusek** [comment]
Please, assign to me.

**Comment by JiriOndrusek** [comment]
To overcome problems with serialization in native (see https://github.com/oracle/graal/issues/460), small enhancement has to be implemented in camel-shiro component (see https://issues.apache.org/jira/browse/CAMEL-15619). I'll propose a change in camel-shiro and after that, I'll finish this extension.

**Comment by ppalaga** [comment]
Fixed in 1.3.0 via 62b3a1b40b5cb2cff0a79bbc0ed240758bfa8d88
