### ISSUE TITLE
JCache native support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1846]

**Comment by javaduke** [comment]
@zbendhiba @ppalaga I sort of made jcache work in native mode, but I only tested it with Caffeine JCache and there are some limitations - i.e. I had to explicitly instantiate and inject the caching provider.
See my code here: https://github.com/javaduke/camel-quarkus/tree/jcache-native
Not sure if it's ready for PR but would like to hear your feedback.

**Comment by ppalaga** [comment]
@javaduke thanks, this looks very promising. The tests are especially valuable. 

Here some notes:

* `com.github.ben-manes.caffeine:caffeine` is already managed in `io.quarkus:quarkus-bom` `com.github.ben-manes.caffeine:jcache` is missing, the right place for it is `camel-quarkus-bom` using a new version property `caffeine.version` that  we need to bind to the version used in Quarkus through the `@sync` statement, something like 

```
<caffeine.version></caffeine.version><!-- @sync io.quarkus:quarkus-bom:${quarkus.version} dep:com.github.ben-manes.caffeine:jcache -->
```

and run `mvn cq:sync-versions -N -e` afterwards.

* No change is required iin `camel-quarkus-bom-test`
* I wonder if all reflection registrations done in JcacheCaffeineReflectionConfiguration would be still needed if we add a dependency on `io.quarkus:quarkus-caffeine`? 
* `JcacheProcessor` should make the JCache SPI `javax.cache.spi.CachingProvider` honored via `ServiceProviderBuildItem`. Something like

```
    @BuildStep
    void nativeResources(BuildProducer<ServiceProviderBuildItem> services,
            BuildProducer<NativeImageResourceBuildItem> nativeResources) {
        Stream.of("javax.cache.spi.CachingProvider")
                .forEach(service -> {
                    try {
                        Set<String> implementations = ServiceUtil.classNamesNamedIn(
                                Thread.currentThread().getContextClassLoader(),
                                "META-INF/services/" + service);
                        services.produce(
                                new ServiceProviderBuildItem(service, implementations));
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                });
```

After doing that, the minimal setup with just `.policy(new JCachePolicy())` mentioned on [camel docs](https://camel.apache.org/components/3.18.x/jcache-component.html#_find_cachemanager) could perhaps work (given that com.github.ben-manes.caffeine:jcache is in class path).

**Comment by javaduke** [comment]
Also, I didn't want to add caffeine dependency to the extension itself because in theory it should work with any JSR107 implementation, not just caffeine.

**Comment by javaduke** [comment]
OK, I made some changes:

- I added your `ServiceProviderBuildItem` so the CachingProvider is now discovered;
- I removed most of the reflection configuration but `com.github.benmanes.caffeine.jcache.copy.JavaSerializationCopier` is still needed;
- There are no `caffeine-jcache` dependencies in the bom nor in extension, because in theory it should work with any compatible cache implementation - but the test uses caffeine and that's what's recommended;
- Removed explicit caching provider injection from the routes.

Can you please take a look and if everything looks good, I will submit a PR.

**Comment by javaduke** [comment]
@ppalaga I just submitted a PR, and later I'll work on `camel-quarkus-jcache-caffeine` and maybe other caches like Hazelcast and EHcache too.

**Comment by javaduke** [comment]
Yes, I believe it can be closed, thank you for all your help!

**Comment by aldettinger** [comment]
Ok, I see a follow up for #4092 is already opened. Closing this one.
Many thanks @javaduke awesome to see some contributions :+1:
