### ISSUE TITLE
Master broken

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#185]
The master branch at 8f1dde4548b701d9ee49c467b8f19c768cca6397 seems to be broken. Fails on my laptop as well as on the CI, e.g. in https://github.com/apache/camel-quarkus/pull/181

@gnodet could you please check what is the problem and eventually consider sending a PR and wait for CI instead of pushing directly?

**Comment by gnodet** [comment]
Sure, I've raised https://github.com/apache/camel-quarkus/pull/186 as an attempt to fix the problem.  If it does not work, I'll revert and use several PRs instead.

**Comment by gnodet** [comment]
Reverted and raising PRs...
