### ISSUE TITLE
Test Geocoder with Google maps mock API if GOOGLE_GEOCODER_API_KEY is not provided

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1860]
If GOOGLE_GEOCODER_API_KEY is not provided, the test should run against a mock API, something like we do with Telegram and elsewhere. If a mock testcontainer is available we should use it. Perhaps a change is needed in Camel to make the API base URL configurable (like in Telegram).

**Comment by zbendhiba** [comment]
Can you assign this one to me ?

**Comment by zbendhiba** [comment]
impossible because the URI is hard-coded inside the GeocodingApi used by Camel

**Comment by zbendhiba** [comment]
related to https://issues.apache.org/jira/browse/CAMEL-15632

**Comment by ppalaga** [comment]
Fixed in 1.3.0 via 6649cc3ad04ec10ea953abc3c76bb009e7764335
