### ISSUE TITLE
AWS properties not picked up

### ISSUE THREAD

**Issue by gitmalong** [apache/camel-quarkus#1871]
In my application.properties I'm setting `aws.cborEnabled=false` but it is not being set as `System.getenv("aws.cborEnabled"` returns `null`.

Using amel-quarkus-aws2-kinesis

```
		<compiler-plugin.version>3.8.1</compiler-plugin.version>
		<maven.compiler.parameters>true</maven.compiler.parameters>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<quarkus-plugin.version>1.8.1.Final</quarkus-plugin.version>
		<quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
		<quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
		<quarkus.platform.version>1.8.1.Final</quarkus.platform.version>
		<surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
	</properties>
```

**Comment by oscerd** [comment]
I'll have a look but it shouldn't be an env variable

**Comment by oscerd** [comment]
With AWS2-Kinesis extension or with the the aws-kinesis extension?

With v2 the aws.cborEnabled is a system property not an env variable.

https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md#61-environment-variables-and-system-properties

**Comment by oscerd** [comment]
If you're using the aws-kinesis extension you need to set the AWS_CBOR_DISABLED as env property or the com.amazonaws.sdk.disableCbor as system property.

**Comment by oscerd** [comment]
Also it's not completely clear if you're using the camel extension or not. Please add more details.

**Comment by ppalaga** [comment]
Closing as stale
