### ISSUE TITLE
Make xml and jaxb disabled by default and opt-in when depending on camel

### ISSUE THREAD

**Issue by gnodet** [apache/camel-quarkus#188]

**Comment by lburgazzoli** [comment]
@gnodet in quarkus master there is a new annotation `@Overridable` that could help here to provide a specialized implementation with xml support.

Here a very simple example: https://github.com/lburgazzoli/quarkus-conditional-buildstep/blob/master/deployment/src/main/java/com/github/lburgazzoli/quarkus/playground/DeploymentProcessor.java

**Comment by lburgazzoli** [comment]
Also note that with https://github.com/quarkusio/quarkus/pull/4405/files#diff-3, `JaxbEnabledBuildItem` is not more there in quarkus master

**Comment by gnodet** [comment]
Working on it, i just need a minor adaption in camel https://github.com/apache/camel/pull/3234

**Comment by lburgazzoli** [comment]
Done by https://github.com/apache/camel-quarkus/pull/249
