### ISSUE TITLE
Remove JtaProcessor.registerNarayanaReflectiveClass when quarkusio/quarkus#10180 gets fixed

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1895]
Blocked by https://github.com/quarkusio/quarkus/issues/10180 
cc @zhfeng

**Comment by zhfeng** [comment]
Thanks @ppalaga and assign it to me please.

**Comment by zhfeng** [comment]
The upstream fix has been in quarkus  1.10.3.Final
