### ISSUE TITLE
Be listed in code.quarkus.io

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#190]
We should have camel-quarkus related extensions listed in code.quarkus.io

This depends on #183

**Comment by lburgazzoli** [comment]
@ppalaga @gnodet, @ia3andy can help on this

**Comment by ia3andy** [comment]
We are currently creating the process to have a new extension listed in Code Quarkus. 
A good first step would be to have it accepted on the Quarkus repo.

**Comment by lburgazzoli** [comment]
@ia3andy you are talking about being part of the quarkus platform right ? the camel quarkus extension won't join the quarkus repo, in fact we moved out quite recently :)

**Comment by ia3andy** [comment]
@lburgazzoli ok, I just got up to speed with the soon coming Quarkus Platform, sorry about that. The platform is not out there yet, so the idea is to temporary add your extension to the list (in the Quarkus repo). I am currently creating an issue for you in there.

Once that done, I'll update you, but you'll be really close to have your extension listed in code.quarkus.io :)

**Comment by emmanuelbernard** [comment]
Note that there are a few sources today unfortunately:
- the extensions.json list that is consumed by the CLI
- the extension and category file that is hosted in code.q.io that also need to be updated
- the bom file which needs to reference the Camel extensions

So it's not jsut a code.quarkus.io change unfortunately

**Comment by lburgazzoli** [comment]
![image](https://user-images.githubusercontent.com/1868933/68283241-7c9f1800-007b-11ea-96e2-df0dda96e750.png)
