### ISSUE TITLE
PostgresSQL Event : add usage of Quarkus AgroalDatasource 

### ISSUE THREAD

**Issue by zbendhiba** [apache/camel-quarkus#1909]
Improve the camel pgevent component in order to make it possible to use Quarkus ArgoalDatasource in the PostgresSQL Event extension

**Comment by zbendhiba** [comment]
Can you please assign this one to me  ?

**Comment by zbendhiba** [comment]
To use Quarkus ArgoalDatasource  in the PostgresSQL Event extension, we need to have first a support for pgjdbc-ng driver in Agroal. the pgjdbc-ng used in our extension for pgevent camel component is not compatible with postgres driver.

**Comment by ppalaga** [comment]
Shouldn't we file a Quarkus issue asking for pgjdbc-ng driver support in Agroal (unless one exists already9%

**Comment by zbendhiba** [comment]
I've filed an issue for Agroal team  https://issues.redhat.com/browse/AG-152
