### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [apache/camel-quarkus#1913]
https://github.com/apache/camel-quarkus/blob/c5e3e0c78dff36a9845f79a87f74d5b9e67c744a/integration-tests/http/src/main/java/org/apache/camel/quarkus/component/http/it/HttpRoute.java#L41

The program can potentially fail to release a system resource.

**Comment by ppalaga** [comment]
Thanks for the report, @QiAnXinCodeSafe and thanks for the fix, @aldettinger !
