### ISSUE TITLE
Openstack native support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1943]

**Comment by JiriOndrusek** [comment]
Please, assign to me.

**Comment by oscerd** [comment]
I wouldn't waste so much time on this component. The java library is really old and nobody is taking care of it. I would first try to aling to the latest version on the Camel side.

**Comment by ppalaga** [comment]
Blocked by https://github.com/apache/camel/pull/4629

**Comment by aldettinger** [comment]
I've finally investigated a last option to configure an openstack cluster within a reasonable timeframe to no avail.
So in case of issue, the path is to simulate the user traffic as for other integration tests.
