### ISSUE TITLE
Olingo integration test is throwing SSLPeerUnverifiedException

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#1972]
Seems something changed on the test service:

https://services.odata.org/TripPinRESTierService

I'll disable the test for now until it gets resolved or there's an alternative available.

**Comment by llowinge** [comment]
@jamesnetherton Thank you that you've documented the issue in the @Disabled annotation, so i found it as it failed in our automation as well. But started to work again automatically.
