### ISSUE TITLE
NATS integration test failure - Unable to connect to NATS servers

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#1978]
See build failure here on quarkus-platform here:

https://github.com/quarkusio/quarkus-platform/pull/143#issuecomment-719628915

I also mentioned it previously here:

https://github.com/apache/camel-quarkus/issues/1803#issuecomment-694932811

Seems to be an intermittent thing. Not sure if it's a platform specific thing...

**Comment by aldettinger** [comment]
Even more verbose output are on the [way](https://issues.apache.org/jira/browse/CAMEL-15837).

**Comment by aldettinger** [comment]
So, after multiple experiments in jvm, native, jdk8 and jdk11, it looks there is no simple way to reproduce this issue.
I've then tuned the configuration to generate far more verbose output, so there will be hopefully more information on next occurrence.

**Comment by jamesnetherton** [comment]
There was a recent failure on the `quarkus-master` branch. Not sure if that'll have the debugging info you need though:

https://github.com/apache/camel-quarkus/runs/1378659048?check_suite_focus=true

**Comment by jamesnetherton** [comment]
Failed CI run on the `camel-master` branch yesterday:

https://github.com/apache/camel-quarkus/runs/1384548575?check_suite_focus=true

**Comment by aldettinger** [comment]
Thanks for reporting occurrences @jamesnetherton, it provides a lot of information.
So this intermittent issue could be reproduced locally by running nats tests under a bit of O/S stressing using `stress --cpu 8 --io 10 --timeout 200`.
The most likely explanation at this stage is intermittent TLS handshake timeout occurring under stressed O/S condition.
Raising the timeout seems to be a reasonable option but I'm facing a [nats issue](https://github.com/nats-io/nats-server/issues/1704). Let's see whether the nats guys could help.

**Comment by aldettinger** [comment]
Ok, I'm gonna push a fix that is working locally. I propose to wait a bit before removing the ultra verbose output, so that we can be sure that the fix is working meanwhile.

**Comment by jamesnetherton** [comment]
Seems there may still be a problem. Build failures were reported on quarkus-platform with 1.4.0:

https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=17090&view=logs&j=24123ccf-4eff-5770-8191-b6b1f004311e&t=fbff3817-001b-52f8-fa34-b76c2106f7d9&l=32266

**Comment by aldettinger** [comment]
The build failure on quarkus-platform does not exhibit the exact same stack trace but it could well be the TLS timeout value.
I will raise the TLS timeout once more so that we could see if it's going well on next quarkus-platform PR.

**Comment by jamesnetherton** [comment]
After the Quarkus folks are done with the 1.10 release, we could consider doing some testing with camel-quarkus SNAPSHOTs on quarkus-platform. E.g open a PR with the Apache SNAPSHOT repo enabled, do a few CI runs and see what happens.

**Comment by aldettinger** [comment]
After in-depth investigation, the TLS timeout issue is very unlikely to exhibit the stack trace we have seen on quarkus-platform, so opening another issue in #2061 .
