### ISSUE TITLE
Complete nagios extension tests

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#1992]
Tests for the nagios extension are currently using a mock tcp server based on camel-netty [here](https://github.com/apache/camel-quarkus/blob/master/integration-tests/nagios/src/test/java/org/apache/camel/quarkus/component/nagios/it/NagiosTestResource.java). But it would be great to go beyond that.

**Comment by ppalaga** [comment]
Esp. we should decide whether it is necessary to make the test configurable to run against a real NSCA server. WDYT @llowinge ?

**Comment by mcada** [comment]
Any QE commitment needs to go through PM and planning, @ppalaga feel free to create ENTESB jira with your request.

**Comment by jamesnetherton** [comment]
Closing as per https://github.com/apache/camel-quarkus/issues/3698.
