### ISSUE TITLE
[Camel 3.7] Investigate reason of the explicit registration of some resources in CamelProcessor

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#1995]
There is a change in camel-quarkus (https://github.com/apache/camel-quarkus/pull/1984) forced by the recent changes in camel (https://issues.apache.org/jira/browse/CAMEL-15784).

Addition of the following code into `CamelProcessor` seems unnecessary,

> @BuildStep
    NativeImageResourceBuildItem initResources() {
        return new NativeImageResourceBuildItem(
                "META-INF/services/org/apache/camel/bean-processor-factory",
                "META-INF/services/org/apache/camel/rest-registry-factory");
    }

because there is a similar code already there:

>    @BuildStep
    void coreServicePatterns(BuildProducer<CamelServicePatternBuildItem> services) {	    void coreServicePatterns(BuildProducer<CamelServicePatternBuildItem> services) {
        services.produce(new CamelServicePatternBuildItem(	        services.produce(new CamelServicePatternBuildItem(
                CamelServiceDestination.REGISTRY,	                CamelServiceDestination.REGISTRY,
                true,	                true,
                "META-INF/services/org/apache/camel/component/*",	                "META-INF/services/org/apache/camel/component/*",
                "META-INF/services/org/apache/camel/language/constant",	                "META-INF/services/org/apache/camel/language/constant",
                "META-INF/services/org/apache/camel/language/file",	                "META-INF/services/org/apache/camel/language/file",
                "META-INF/services/org/apache/camel/language/header",	                "META-INF/services/org/apache/camel/language/header",
                "META-INF/services/org/apache/camel/language/ref",	                "META-INF/services/org/apache/camel/language/ref",
                "META-INF/services/org/apache/camel/language/simple"));	                "META-INF/services/org/apache/camel/language/simple"));
        services.produce(new CamelServicePatternBuildItem(	        services.produce(new CamelServicePatternBuildItem(
                CamelServiceDestination.DISCOVERY,	                CamelServiceDestination.DISCOVERY,
                true,	                true,
                "META-INF/services/org/apache/camel/*",	                "META-INF/services/org/apache/camel/*",
                "META-INF/services/org/apache/camel/management/*",	                "META-INF/services/org/apache/camel/management/*",
                "META-INF/services/org/apache/camel/model/*",	                "META-INF/services/org/apache/camel/model/*",
                "META-INF/services/org/apache/camel/configurer/*",	                "META-INF/services/org/apache/camel/configurer/*",
                "META-INF/services/org/apache/camel/language/*",	                "META-INF/services/org/apache/camel/language/*",
                "META-INF/services/org/apache/camel/dataformat/*",	                "META-INF/services/org/apache/camel/dataformat/*",
                "META-INF/services/org/apache/camel/send-dynamic/*",	                "META-INF/services/org/apache/camel/send-dynamic/*",
                "META-INF/services/org/apache/camel/urifactory/*"));	                "META-INF/services/org/apache/camel/urifactory/*"));
    }	    }

Without this change, some integration tests (`bean`, `slack`, `openpi-java` and others) fails.

This change should be investigated properly.

**Comment by ppalaga** [comment]
Fixed in the camel-master branch
