### ISSUE TITLE
[Camel 3.7] Camel main autowire properties by type has been removed 

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2002]
Relates to https://issues.apache.org/jira/browse/CAMEL-15826.

It breaks a number of itests that rely on component options being auto configured. E.g the ElasticSearch REST client, JMS `ConnectionFactory`, Infinispan cache, `ValidationFactory` etc.

I have worked around the problem to get the `camel-master` branch building again. Ideally we need to get following issue solved in time for Camel 3.7.0 GA:

https://issues.apache.org/jira/browse/CAMEL-15836

Some more info here:

https://camel.zulipchat.com/#narrow/stream/257298-camel/topic/Main.20autowire.20by.20type

**Comment by davsclaus** [comment]
It was added back with a new feature where you mark the options that can be autowired

**Comment by jamesnetherton** [comment]
I'll close as this is now working again on the `camel-master` branch.
