### ISSUE TITLE
Investigate replacing bouncycastle support extension with Quarkus bouncycastle 

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2005]
Quarkus now has a bouncycastle extension. Maybe we can use it, remove our own extension and contribute anything that's missing if required.

**Comment by ppalaga** [comment]
Also related to bouncy castle: https://github.com/apache/camel-quarkus/issues/2673

**Comment by sberyozkin** [comment]
> Quarkus now has a bouncycastle extension

Not yet - right now Quarkus only indirectly facilitates the creation of BC providers in its `quarkus-security` extension; perhaps we can indeed introduce a dedicated extension
