### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#203]
We have a couple of new components to show.

**Comment by oscerd** [comment]
Release process was failing for failIfNoTests missing for surefire and now

[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy-file (deploy-reusable-test-jar) on project camel-quarkus-integration-test-core-parent: The parameters 'url' for goal org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy-file are missing or invalid -> [Help 1]

**Comment by oscerd** [comment]
@ppalaga FYI.

**Comment by ppalaga** [comment]
Thanks for the heads up, I can have a look tomorrow (on PTO today).

**Comment by oscerd** [comment]
It fails anyway

[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy-file (deploy-reusable-test-jar) on project camel-quarkus-integration-test-core-parent: The parameters 'url' for goal org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy-file are missing or invalid -> [Help 1]

**Comment by ppalaga** [comment]
Strange. I think I need to reproduce this deploying to a local filesystem repo.

**Comment by ppalaga** [comment]
I was able to reproduce using local file:// URLs for distribution management and scm.

**Comment by oscerd** [comment]
It's not enough. The signature of the integration tests seems to be invalid. 


typeId | signature-staging
-- | --
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-jdbc-tests/0.2.0/camel-quarkus-integration-test-jdbc-tests-0.2.0.pom.asc' does not exist for 'camel-quarkus-integration-test-jdbc-tests-0.2.0.pom'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-jdbc-tests/0.2.0/camel-quarkus-integration-test-jdbc-tests-0.2.0.jar.asc' does not exist for 'camel-quarkus-integration-test-jdbc-tests-0.2.0.jar'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-paho-tests/0.2.0/camel-quarkus-integration-test-paho-tests-0.2.0.pom.asc' does not exist for 'camel-quarkus-integration-test-paho-tests-0.2.0.pom'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-paho-tests/0.2.0/camel-quarkus-integration-test-paho-tests-0.2.0.jar.asc' does not exist for 'camel-quarkus-integration-test-paho-tests-0.2.0.jar'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-core-cdi-tests/0.2.0/camel-quarkus-integration-test-core-cdi-tests-0.2.0.pom.asc' does not exist for 'camel-quarkus-integration-test-core-cdi-tests-0.2.0.pom'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-core-cdi-tests/0.2.0/camel-quarkus-integration-test-core-cdi-tests-0.2.0.jar.asc' does not exist for 'camel-quarkus-integration-test-core-cdi-tests-0.2.0.jar'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-infinispan-tests/0.2.0/camel-quarkus-integration-test-infinispan-tests-0.2.0.jar.asc' does not exist for 'camel-quarkus-integration-test-infinispan-tests-0.2.0.jar'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-infinispan-tests/0.2.0/camel-quarkus-integration-test-infinispan-tests-0.2.0.pom.asc' does not exist for 'camel-quarkus-integration-test-infinispan-tests-0.2.0.pom'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-netty-http-tests/0.2.0/camel-quarkus-integration-test-netty-http-tests-0.2.0.pom.asc' does not exist for 'camel-quarkus-integration-test-netty-http-tests-0.2.0.pom'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-netty-http-tests/0.2.0/camel-quarkus-integration-test-netty-http-tests-0.2.0.jar.asc' does not exist for 'camel-quarkus-integration-test-netty-http-tests-0.2.0.jar'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-csv-tests/0.2.0/camel-quarkus-integration-test-csv-tests-0.2.0.pom.asc' does not exist for 'camel-quarkus-integration-test-csv-tests-0.2.0.pom'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-csv-tests/0.2.0/camel-quarkus-integration-test-csv-tests-0.2.0.jar.asc' does not exist for 'camel-quarkus-integration-test-csv-tests-0.2.0.jar'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-zipfile-tests/0.2.0/camel-quarkus-integration-test-zipfile-tests-0.2.0.pom.asc' does not exist for 'camel-quarkus-integration-test-zipfile-tests-0.2.0.pom'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-zipfile-tests/0.2.0/camel-quarkus-integration-test-zipfile-tests-0.2.0.jar.asc' does not exist for 'camel-quarkus-integration-test-zipfile-tests-0.2.0.jar'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-microprofile-metrics-tests/0.2.0/camel-quarkus-integration-test-microprofile-metrics-tests-0.2.0.pom.asc' does not exist for 'camel-quarkus-integration-test-microprofile-metrics-tests-0.2.0.pom'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-microprofile-metrics-tests/0.2.0/camel-quarkus-integration-test-microprofile-metrics-tests-0.2.0.jar.asc' does not exist for 'camel-quarkus-integration-test-microprofile-metrics-tests-0.2.0.jar'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-core-tests/0.2.0/camel-quarkus-integration-test-core-tests-0.2.0.pom.asc' does not exist for 'camel-quarkus-integration-test-core-tests-0.2.0.pom'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-core-tests/0.2.0/camel-quarkus-integration-test-core-tests-0.2.0.jar.asc' does not exist for 'camel-quarkus-integration-test-core-tests-0.2.0.jar'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-bean-tests/0.2.0/camel-quarkus-integration-test-bean-tests-0.2.0.jar.asc' does not exist for 'camel-quarkus-integration-test-bean-tests-0.2.0.jar'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-bean-tests/0.2.0/camel-quarkus-integration-test-bean-tests-0.2.0.pom.asc' does not exist for 'camel-quarkus-integration-test-bean-tests-0.2.0.pom'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-mail-tests/0.2.0/camel-quarkus-integration-test-mail-tests-0.2.0.jar.asc' does not exist for 'camel-quarkus-integration-test-mail-tests-0.2.0.jar'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-mail-tests/0.2.0/camel-quarkus-integration-test-mail-tests-0.2.0.pom.asc' does not exist for 'camel-quarkus-integration-test-mail-tests-0.2.0.pom'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-aws-tests/0.2.0/camel-quarkus-integration-test-aws-tests-0.2.0.pom.asc' does not exist for 'camel-quarkus-integration-test-aws-tests-0.2.0.pom'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-aws-tests/0.2.0/camel-quarkus-integration-test-aws-tests-0.2.0.jar.asc' does not exist for 'camel-quarkus-integration-test-aws-tests-0.2.0.jar'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-core-impl-tests/0.2.0/camel-quarkus-integration-test-core-impl-tests-0.2.0.pom.asc' does not exist for 'camel-quarkus-integration-test-core-impl-tests-0.2.0.pom'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-core-impl-tests/0.2.0/camel-quarkus-integration-test-core-impl-tests-0.2.0.jar.asc' does not exist for 'camel-quarkus-integration-test-core-impl-tests-0.2.0.jar'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-twitter-tests/0.2.0/camel-quarkus-integration-test-twitter-tests-0.2.0.jar.asc' does not exist for 'camel-quarkus-integration-test-twitter-tests-0.2.0.jar'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-twitter-tests/0.2.0/camel-quarkus-integration-test-twitter-tests-0.2.0.pom.asc' does not exist for 'camel-quarkus-integration-test-twitter-tests-0.2.0.pom'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-salesforce-tests/0.2.0/camel-quarkus-integration-test-salesforce-tests-0.2.0.pom.asc' does not exist for 'camel-quarkus-integration-test-salesforce-tests-0.2.0.pom'.
failureMessage | Missing Signature: '/org/apache/camel/quarkus/camel-quarkus-integration-test-salesforce-tests/0.2.0/camel-quarkus-integration-test-salesforce-tests-0.2.0.jar.asc' does not exist for 'camel-quarkus-integration-test-salesforce-tests-0.2.0.jar'.

**Comment by oscerd** [comment]
I'm dropping the release and go back to 0.2.0-SNAPSHOT

**Comment by oscerd** [comment]
Actually the integration test poms are a complete mess, my proposal is to leave them out of the release.

**Comment by oscerd** [comment]
Release 0.2.0 is now on vote.

**Comment by oscerd** [comment]
Done
