### ISSUE TITLE
Debezium-mongodb - observe issue DBZ-2831, which blocks integration tests.

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#2060]
Issue [DBZ-2831](https://issues.redhat.com/browse/DBZ-2831) blocks creation of integration tests for debezium-mongodb (therefore  blocks https://github.com/apache/camel-quarkus/issues/1190)

**Comment by JiriOndrusek** [comment]
Please, assign to me. DBZ issue is fixed, I'll verify it with snapshot version.

**Comment by JiriOndrusek** [comment]
This issue could be closed.
Version 1.4.0.Beta1 works correctly - verified on manual test from https://github.com/JiriOndrusek/debezium-reproducer-port
I'm returning to debezium-mongodb extension - https://github.com/apache/camel-quarkus/issues/1190. Hopefully there will be no other blocker.

**Comment by ppalaga** [comment]
Can this be closed, @JiriOndrusek ?

**Comment by JiriOndrusek** [comment]
@ppalaga yes, it could be closed.
