### ISSUE TITLE
The synthetic test poms are missing signatures

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#207]
... and therefore closing the staging repository fails with messages listed in https://github.com/apache/camel-quarkus/issues/203#issuecomment-533786828

**Comment by lburgazzoli** [comment]
@ppalaga do you think we can have a fix for this soon ?

**Comment by ppalaga** [comment]
Yes, working on a maven plugin to do the stuff comfortably on the Quarkus side.

**Comment by lburgazzoli** [comment]
Do we have any ETA ?

**Comment by ppalaga** [comment]
tomorrowish

**Comment by ppalaga** [comment]
Released 0.1.0 https://github.com/ppalaga/repackage-tests-maven-plugin

**Comment by ppalaga** [comment]
This will be done on the Quarkus side using the rpkgtests-maven-plugin

**Comment by lburgazzoli** [comment]
@ppalaga what should we do with this issue ?

**Comment by ppalaga** [comment]
Close
