### ISSUE TITLE
How to use CamelContextCustomizer ?

### ISSUE THREAD

**Issue by gulecroc** [apache/camel-quarkus#2074]
Hello,

I would like to customize CamelContext on startup and i see the CamelContextCustomizer class.
How to use it with Quarkus ?

Thanks
Guillaume

**Comment by ppalaga** [comment]
`CamelContextCustomizer` would help only if you are writing your own Quarkus extension. It cannot be used from an application code.

What kind of CamelContext customizations would you like to perform?

**Comment by gulecroc** [comment]
Ok that's why there no documentation :)

I would like to customize MDC to add information, like in this example :
https://stackoverflow.com/questions/29045419/apache-camel-mdc-add-field-from-body

**Comment by lburgazzoli** [comment]
You can achieve what you are looking for by listen for a `org.apache.camel.spi.CamelEvent` event, as example:

```java 
@ApplicationScoped
public static class EventHandler {
    public void onRouteStarted(@Observes CamelContextStartingEvent event) {
        doSomething(event.getContext());
    }
}
````

**Comment by gulecroc** [comment]
@lburgazzoli works perfectly.

I found also that providing a bean of UnitOfWorkFactory works too :
https://camel.apache.org/manual/latest/advanced-configuration-of-camelcontext-using-spring.html
