### ISSUE TITLE
DataSonnet language support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2078]
DataSonnet language is new in Camel 3.7 https://camel.apache.org/components/latest/languages/datasonnet-language.html

**Comment by aldettinger** [comment]
Thanks for expressing interest in cq-datasonnet. It could be interesting.
People are quite busy those days, so it's just a matter of finding a contributor with time.

There are pages indicating how to contribute:
https://camel.apache.org/camel-quarkus/2.7.x/contributor-guide/create-new-extension.html
Would you like to have a try ?

**Comment by javaduke** [comment]
Well, I suppose I'll give it a try then, if no one else does :)

**Comment by aldettinger** [comment]
Thanks for stepping in @javaduke.

Maybe a good first step could be to create an empty datasonnet extension helped by the guide:
https://camel.apache.org/camel-quarkus/2.7.x/contributor-guide/create-new-extension.html.

Then, maybe testing the documented features from the camel doc:
https://camel.apache.org/components/3.16.x/languages/datasonnet-language.html
Well, starting simple with the first example could be a good target.

On top of my mind, there are no special difficulties with creating an extension for a language. It has already been done in this ticket for instance https://github.com/apache/camel-quarkus/issues/739. Anyway, you may find help in the contributor doc or even zulip chat :)

**Comment by javaduke** [comment]
Here's the PR https://github.com/apache/camel-quarkus/pull/3686
