### ISSUE TITLE
jOOR language native support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2083]
https://camel.apache.org/components/latest/languages/joor-language.html

**Comment by ppalaga** [comment]
A JVM only extension is underway https://github.com/apache/camel-quarkus/pull/2643

**Comment by essobedo** [comment]
Waiting for https://github.com/apache/camel-quarkus/pull/4428

**Comment by essobedo** [comment]
The corresponding PR https://github.com/apache/camel-quarkus/pull/4440
