### ISSUE TITLE
Upgrade to Quarkus 0.23.0

### ISSUE THREAD

**Issue by oscerd** [apache/camel-quarkus#209]

**Comment by oscerd** [comment]
This fails for enforcement rules

[INFO] --- maven-enforcer-plugin:1.4.1:enforce (camel-quarkus-enforcer-rules) @ camel-quarkus-infinispan ---
[WARNING] 
Dependency convergence error for org.jgroups:jgroups:4.1.1.Final paths to dependency are:
+-org.apache.camel.quarkus:camel-quarkus-infinispan:0.2.1-SNAPSHOT
  +-org.infinispan:infinispan-core:10.0.0.Beta5
    +-org.jgroups:jgroups:4.1.1.Final
and
+-org.apache.camel.quarkus:camel-quarkus-infinispan:0.2.1-SNAPSHOT
  +-org.apache.camel:camel-infinispan:3.0.0-RC1
    +-org.jgroups:jgroups:4.0.18.Final

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability the error(s) are [
Dependency convergence error for org.jgroups:jgroups:4.1.1.Final paths to dependency are:
+-org.apache.camel.quarkus:camel-quarkus-infinispan:0.2.1-SNAPSHOT
  +-org.infinispan:infinispan-core:10.0.0.Beta5
    +-org.jgroups:jgroups:4.1.1.Final
and
+-org.apache.camel.quarkus:camel-quarkus-infinispan:0.2.1-SNAPSHOT
  +-org.apache.camel:camel-infinispan:3.0.0-RC1
    +-org.jgroups:jgroups:4.0.18.Final

Camel Cannot update to infinispan 10 in beta version.

**Comment by lburgazzoli** [comment]
Blocking issue: https://github.com/quarkusio/quarkus/issues/4248
