### ISSUE TITLE
Skipped tests on CI (eg. hystrix)

### ISSUE THREAD

**Issue by llowinge** [apache/camel-quarkus#2091]
I can see hystrix being skipped on CI https://github.com/apache/camel-quarkus/commit/0f8271653aaf6d9ab1658dff416b35b448ac81e5. QE is using this file https://github.com/apache/camel-quarkus/blob/master/tooling/scripts/test-categories.yaml for running Native tests in parallel. It includes hystrix as well. We could add `CI=true` to our pipeline, which i don't think is good idea. Do you think better approach is to skip hystrix on our side in our pipeline ?

**Comment by llowinge** [comment]
@ppalaga @jamesnetherton FYI

**Comment by ppalaga** [comment]
In case it is not clear from the description, @llowinge would prefer us to remove hystrix from test-categories.yaml and stop relying on the `CI` env var. I would not mind doing it. WDYT, @jamesnetherton ?

**Comment by jamesnetherton** [comment]
I'm fine with removing it from `test-categories.yaml`. I originally disabled the test because there's a race condition that pops up intermittently and I was struggling to replicate the problem locally.
