### ISSUE TITLE
Submodule for support extensions

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#213]
All the extension are now part of the `extension` module but as we use a short name, it is unclear if an extension relates to a camel component or it is a support extension. 

As example we have a `jetty` extension which relates to `camel-jetty` but also a `jetty-common` which targets generic `jetty` classes. At the same time we have `http-common` which target the `camel-http-common` classes which makes things a little confusing (IMHO).

As we may need to add additional `support` extensions, I'd propose to group them under `extensions/support` and reflect the change in the artefact name too. 

As long term plan, they may/should be moved to `quarkus` main repo.

**Comment by ppalaga** [comment]
No problem with that. 

> reflect the change in the artefact name too

Will there be a single naming convention for all support extensions?

How about integration testing? I think every extension incl. support extensions should be covered directly or indirectly by at least one integration test. WDYT?

**Comment by lburgazzoli** [comment]
> No problem with that.
> 
> > reflect the change in the artefact name too
> 
> Will there be a single naming convention for all support extensions?
> 

I would say yes

> How about integration testing? I think every extension incl. support extensions should be covered directly or indirectly by at least one integration test. WDYT?

We should not allow to have extension for things not used in camel so I think all the support extensions will be tested indirectly by testing the camel extensions. I f sopmething specific is not covered, we can of course add specific tests.
