### ISSUE TITLE
camel-quarkus-csimple package not exists but presented in documentation

### ISSUE THREAD

**Issue by mrk-andreev** [apache/camel-quarkus#2131]
In camel-quarkus documentation https://camel.apache.org/camel-quarkus/latest/reference/extensions/csimple.html we can found maven dependency `org.apache.camel.quarkus:camel-quarkus-csimple` but maven central does not present this package. 

```
<dependency>
    <groupId>org.apache.camel.quarkus</groupId>
    <artifactId>camel-quarkus-csimple</artifactId>
</dependency>
```

**Comment by jamesnetherton** [comment]
Yes it's incorrect for the 1.5.0 release where csimple support is integrated into `camel-quarkus-core`. For the upcoming 1.6.0 release there will be a dedicated `camel-quarkus-csimple` extension. See related notes in https://github.com/apache/camel-quarkus/pull/2103 & https://github.com/apache/camel-quarkus/issues/2098.

**Comment by mrk-andreev** [comment]
When I call `quarkus:build` I got exception 

```
[error]: Build step org.apache.camel.quarkus.core.deployment.CSimpleRouteDefinitionProcessor#configureCSimpleLanguage threw an exception: java.lang.NoClassDefFoundError: org/apache/camel/language/csimple/CSimpleLanguage
```

How I can exclude `CSimpleRouteDefinitionProcessor` (If I use `LambdaRouteBuilder`)? Or any other solution to solve this problem?


ps: Sorry that this question is not directly related to issue topic.

**Comment by jamesnetherton** [comment]
If you're not using csimple, try setting the following in `application.properties`:
```
quarkus.camel.native.csimple.on-build-time-analysis-failure = ignore
```

**Comment by ppalaga** [comment]
Yes, sorry, @mrk-andreev there is nothing better to recommend for Camel Quarkus 1.5.0 than `quarkus.camel.native.csimple.on-build-time-analysis-failure = ignore`. We have moved the CSimple stuff to a separate extension exactly to solve issues like you mention.

**Comment by mrk-andreev** [comment]
`quarkus.camel.native.csimple.on-build-time-analysis-failure = ignore` does not solve this problem.  Class `CSimpleLanguage` can not be founded by `org.apache.camel.quarkus.core.deployment.CSimpleRouteDefinitionProcessor`. So may be problem in wrong dependencies version in my `pom.xml`. 

I solved this problem when I downgraded camel to `1.4.0` :(

**Comment by ppalaga** [comment]
Could you please attach a reproducer?

**Comment by mrk-andreev** [comment]
@ppalaga 

https://github.com/mrk-andreev/example-quarkus-csimple-bug

**Comment by jamesnetherton** [comment]
You have a mix of camel and camel-quarkus versions because `quarkus-universe-bom:10.0.5.Final` is aligned with camel-quarkus 1.4.0.

```
$ mvn dependency:tree | grep camel
[INFO] +- org.apache.camel.quarkus:camel-quarkus-log:jar:1.5.0:compile
[INFO] |  \- org.apache.camel:camel-log:jar:3.6.0:compile
[INFO] |     \- org.apache.camel:camel-support:jar:3.6.0:compile
[INFO] +- org.apache.camel.quarkus:camel-quarkus-core:jar:1.5.0:compile
[INFO] |  +- org.apache.camel.quarkus:camel-quarkus-support-common:jar:1.4.0:compile
[INFO] |  +- org.apache.camel:camel-base:jar:3.6.0:compile
[INFO] |  |  +- org.apache.camel:camel-api:jar:3.6.0:compile
[INFO] |  |  +- org.apache.camel:camel-management-api:jar:3.6.0:compile
[INFO] |  |  \- org.apache.camel:camel-util:jar:3.6.0:compile
[INFO] |  +- org.apache.camel:camel-componentdsl:jar:3.6.0:compile
[INFO] |  +- org.apache.camel:camel-core-catalog:jar:3.6.0:compile
[INFO] |  |  \- org.apache.camel:camel-tooling-model:jar:3.6.0:compile
[INFO] |  |     \- org.apache.camel:camel-util-json:jar:3.6.0:compile
[INFO] |  +- org.apache.camel:camel-core-engine:jar:3.6.0:compile
[INFO] |  +- org.apache.camel:camel-core-languages:jar:3.6.0:compile
[INFO] |  +- org.apache.camel:camel-core-processor:jar:3.7.0:compile
[INFO] |  |  \- org.apache.camel:camel-base-engine:jar:3.7.0:compile
[INFO] |  +- org.apache.camel:camel-endpointdsl:jar:3.6.0:compile
[INFO] |  \- org.apache.camel:camel-microprofile-config:jar:3.6.0:compile
[INFO] +- org.apache.camel.quarkus:camel-quarkus-timer:jar:1.5.0:compile
[INFO] |  \- org.apache.camel:camel-timer:jar:3.6.0:compile
[INFO] +- org.apache.camel.quarkus:camel-quarkus-main:jar:1.5.0:compile
[INFO] |  \- org.apache.camel:camel-main:jar:3.6.0:compile
```

Try importing `camel-quarkus-bom` before the `quarkus-platform-bom` in `dependencyManagement` like:

```
  <dependencyManagement>
    <dependencies>
      <dependency>
          <groupId>org.apache.camel.quarkus</groupId>
          <artifactId>camel-quarkus-bom</artifactId>
          <version>${quarkus.camel.version}</version>
          <type>pom</type>
          <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

**Comment by mrk-andreev** [comment]
Thanks, that works! You are cool!

**Comment by ppalaga** [comment]
Issues like this one happening from time to time is a clear sign that we are lacking on documentation about dependency management. Let me file a new issue for that.

**Comment by ppalaga** [comment]
Filed https://github.com/apache/camel-quarkus/issues/2136 please feel free to review/improve the text
