### ISSUE TITLE
Release: Update Apache Committee Report Helper for camel-quarkus-1.6.0 released on 2021-01-18

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2149]
Could please some @ PMC member take this?

**Comment by zregvart** [comment]
I've updated the list of releases [via](https://reporter.apache.org/addrelease.html?camel). The authentication prompt said 'Apache Commiter', @ppalaga might want to check if you can add those too.

**Comment by ppalaga** [comment]
Thanks for the info @zregvart , I'll try next time
