### ISSUE TITLE
JFR Native support

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#2151]
This is for Java Flight Recorder.

The extension can at build time then pre configure the ExtendedCamelContext.setStartupStepRecorder(new JavaInflight...)
And have the recorder use the configuration values from the supported values which we have in `camel-main`.

Its all the `camel.main.startupRecorder` options that can be used for configuration, such as duration, profile, dir etc.

**Comment by jamesnetherton** [comment]
Native support currently blocked by https://github.com/oracle/graal/issues/3608.
