### ISSUE TITLE
Re-introduce Changelog GH Action

### ISSUE THREAD

**Issue by oscerd** [apache/camel-quarkus#2189]
I did this on subprojects of camel.

https://github.com/apache/camel-kafka-connector/commit/0fb9ee45431e75ed013bc704712c451fa3cb0069

Do we all agree it is useful for camel-quarkus too?

**Comment by oscerd** [comment]
cc @jamesnetherton @ppalaga

**Comment by jamesnetherton** [comment]
I'm fine with adding it back. Will it run daily like it used to?

**Comment by oscerd** [comment]
Yes, as in the past, but I leave the possiblity of running it manually. We just need to create a git submodule point to the latest tag of the changelog. I'll open a PR tomorrow.
