### ISSUE TITLE
platform-http component should return 204 for success and no body

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#220]
Yeah ideally we should get the http components aligned. They should IMHO not return a hardcoded text, eg this is in english, then chinese users get english text etc. But lets log a ticket upstream at Apache Camel

_Originally posted by @davsclaus in https://github.com/apache/camel-quarkus/timeline_

**Comment by davsclaus** [comment]
This is being worked on upstream in Camel 3.0 GA where the http server components will return 204 for empty body (no content)

**Comment by ppalaga** [comment]
Plz. assign to me.

@davsclaus could you plz point me to the tests verifying the requested behavior in Camel (if they exist)?
