### ISSUE TITLE
Upgrading to Jackson 2.12.1 via Quarkus BOM 1.12 breaks Azure SDK v12 extensions 

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2207]
Steps to reproduce: Run the azure-eventhubs test with Azure credentials set, making sure that you are on Quarkus 1.12.

Blocked by https://github.com/Azure/azure-sdk-for-java/issues/18876

**Comment by ppalaga** [comment]
Workarounds: force Jackson 2.11.3 or stay on Quarkus 1.11

**Comment by davsclaus** [comment]
Is quarkus 1.12 using jackson 2.12.x by default?

We are still on 2.11.x on Camel 3.8 as many of the components using jackson are using 2.11, and haven't upgraded to 2.12 yet. I am not sure if 2.12 is binary compatible with 2.11, so it a drop in replacement is possible.

**Comment by ppalaga** [comment]
> Is quarkus 1.12 using jackson 2.12.x by default?

Yes, that's what they have in their master.

> We are still on 2.11.x on Camel 3.8 as many of the components using jackson are using 2.11, and haven't upgraded to 2.12 yet. I am not sure if 2.12 is binary compatible with 2.11, so it a drop in replacement is possible.

Eventhubs test is the only one known to me so far to have this problem. @jamesnetherton might know of others?

**Comment by jamesnetherton** [comment]
> @jamesnetherton might know of others

That's the only issue I've seen. I need to fix up the` quarkus-master` branch so that we can get a full build to double check.

**Comment by ppalaga** [comment]
https://github.com/apache/camel-quarkus/pull/2208 forces jackson 2.11.3 in Azure tests

**Comment by ppalaga** [comment]
I have posted a reproducer in https://github.com/Azure/azure-sdk-for-java/issues/18876 .

**Comment by ppalaga** [comment]
This can be fixed by upgrading to azure-bom 1.0.3 - see the linked PR. Some native compilation issues need to get fixed there. The upgrade to azure-bom 1.0.3 also fixes another, so far unreported problem mentioned by @llowinge.
