### ISSUE TITLE
AWS2 components have to set client.endpointOverride() to work on Localstack

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2216]
This holds at least for the AWS2 SQS component (and does not hold for at least AWS2 S3 component which already has the `camel.component.aws2-s3.uri-endpoint-override` option). The symptoms and fix are described in https://github.com/localstack/localstack/issues/1318 .

This needs to be fixed in Camel, but I am filing it here for now because I need to figure out which components are affected.

**Comment by oscerd** [comment]
Maybe you need to have a look at test-infra folder on main camel. There is the possibility to re-use that stuff in quarkus too. The endpoint override can be added to the components where it makes sense, but if it is just for the sake of testing, I think it worths to look at how the tests are done in main camel repo.

It may be I don't get the issue, but all the test suite in camel for aws2 is using localstack and the endpoint override mechanism has been implemented only on kinesis and s3. So I believe it is not mandatory.

**Comment by ppalaga** [comment]
> Maybe you need to have a look at test-infra folder on main camel. There is the possibility to re-use that stuff in quarkus too. 

Thanks for the pointer, I was not aware of Localstack being used there. 

As far as I can see, Localstack is integrated via a custom client set in the component config  https://github.com/apache/camel/blob/master/components/camel-aws2-sns/src/test/java/org/apache/camel/component/aws2/sns/localstack/Aws2SNSBaseTest.java#L38

That's a bit complicated, IMO. Having `uri-endpoint-override` on all AWS2 components would make the testing easier in Camel Quarkus. It is because in that way, we can set it from the `TestResource` which declares the environment for the test app. While it is easy to set a primitive type property (such as `uri-endpoint-override`), it is impossible to pass an object (such as custom client), because the `TestResource` may potentially run in a process distinct from the test app.

While adding `uri-endpoint-override` options to all AWS2 component is my preference, I still acknowledge that testing-only options might be seen as polluting the API. So I am open to other proposals or even adopting the custom client approach on the Camel Quarkus side.

**Comment by oscerd** [comment]
If we look at this from the perspective of having some configuration features parity in all the AWS2 components, it makes sense to have the uri override approach in all the components. In terms of effort I think it is less work on the camel side than doing the stuff on quarkus, in the end we are talking about two endpoint options for components. Can you create an issue on Camel JIRA for this and assign it to me? For 3.9 I'll have some work to do, like removing the camel-aws components and focus on AWS2 ones, so I'll have time to add the options.

**Comment by ppalaga** [comment]
Thanks, filed https://issues.apache.org/jira/browse/CAMEL-16171

**Comment by ppalaga** [comment]
Since Camel 3.9.0 all AWS 2 components have `uri-endpoint-override` (thanks, @oscerd !) and we can leverage it Camel Quarkus.

**Comment by oscerd** [comment]
Happy to help :-)
