### ISSUE TITLE
camel-zookeeper-master - Avoid osgi lookup

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#2221]
When upgrading to Camel 3.9 then we can register in the registry DefaultManagedGroupFactory as then it avoids the strategy that attempts to lookup in OSGi and use OSGi factory. 

https://issues.apache.org/jira/browse/CAMEL-16155

**Comment by zbendhiba** [comment]
Hello @davsclaus is this for porting the extension in native, or do we need to do something also for the existing JVM extension ?

**Comment by davsclaus** [comment]
Ah this is no longer needed as we created a special camel-zookeeper-master-osgi in the camel-karaf project.

So we can close this

**Comment by zbendhiba** [comment]
@davsclaus thanks :)
