### ISSUE TITLE
Test LRA extension with the latest Narayana LRA coordinator

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2285]
I found some problems when testing with the latest Narayana LRA coordinator, so for now, tests are performed against an outdated version. We should upgrade when they are resolved.

https://issues.apache.org/jira/browse/CAMEL-16253
https://issues.redhat.com/browse/JBTM-3433

**Comment by ppalaga** [comment]
CAMEL-16253 is resolved, but JBTM-3433 is not. Should we perhaps ping them again?
Is this something for Camel Quarkus 2.0?

**Comment by jamesnetherton** [comment]
> Is this something for Camel Quarkus 2.0?

Not strictly because we can bump the version of the LRA container image used in the itests at any time. But it'd be nice to get a fix ASAP.

I dropped a comment into the JBTM issue to ask for an update. There is still the (not ideal) workaround of using the older LRA coordinator.

I could also look into tweaking camel-lra to see if it's possible to at least work around the problem.

**Comment by zhfeng** [comment]
I think the LRA got the Final 1.0 release recently and it needs to check with it. I'd like to take a look.

**Comment by zhfeng** [comment]
The lastest lra-coordinator 5.12.0.Final image looks good and it was built by using Quarkus. We also need to take a look when the quarkus lra extension gets merged in upstream.
