### ISSUE TITLE
main: add an option to ignore command line arguments

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#2293]
If you run a camel quarkus application with camel-quarkus-main then it will intercept the command line arguments and eventually fail if as example, some parameter are unknown to camel-main. 

We should make this behavior optional or find a better way to handle command line option, i.e. not to fail if an option is unknown.

**Comment by ppalaga** [comment]
Related https://github.com/quarkusio/quarkus/issues/15416

**Comment by ppalaga** [comment]
There are two workarounds for the wrong ordering of `-jar` and `-cp` args by the `quarkus-openshift` extension:

* Set `quarkus.package.type=uber-jar` will avoid adding the `-cp` arg. This works on Quarkus 1.12+ thanks to https://github.com/quarkusio/quarkus/pull/15076/files
* Copy the generated resources from `target/kubernetes` to `src/main/kubernetes` and remove the `-cp` argument there.

**Comment by jamesnetherton** [comment]
Need to reopen this as the original fix isn't quite right. The call to `completed()` in `parseArguments()` should only happen if the failure remedy is `fail`. Otherwise the Camel application is prematurely terminated.
