### ISSUE TITLE
CI job integration-tests-alternative-jvm (15) failing against a valid PR

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#2300]
This PR https://github.com/apache/camel-quarkus/pull/2298 includes changes in **extensions** folder as well as **integration-tests** folder. A local build with JDK 15 is ok.

However, the integration-tests-alternative-jvm (15) job is failing. I think the job is executing itests from PR against extension without PR as only [the integration-tests folder seems to be built](https://github.com/apache/camel-quarkus/pull/2298/checks?check_run_id=2006498552#step:9:2).

**Comment by jamesnetherton** [comment]
The extensions are pre-built in the `initial-mvn-install` step, the maven repo is compressed and uploaded as a GitHub artifact which is then downloaded and restored in `integration-tests-alternative-jvm`. Hence the build can simply cd into the itests module and run all of the tests.

**Comment by aldettinger** [comment]
Thanks for explanation @jamesnetherton. So the job may not be the root cause of the failure. I'm closing this one.
