### ISSUE TITLE
[camel-master] Support for new DSLs

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#2301]
relates to https://github.com/apache/camel-quarkus/issues/2294

**Comment by lburgazzoli** [comment]
https://github.com/apache/camel-quarkus/pull/2308

**Comment by lburgazzoli** [comment]
We need to add support for the groovy and kotlin one.

@ppalaga @jamesnetherton are you ok if I add support on quarkus after upgrading to camel 3.9.0 ?

**Comment by jamesnetherton** [comment]
Fine with me - are you planning to get this in for the 1.8.0 release? Quarkus 1.13.0.Final should be out today, so we'll need to cut 1.8.0 soon(ish).

**Comment by lburgazzoli** [comment]
I'd like to get them in 1.8.0 so I can try to leverage them in camel-k ad get rid of the loader we have there (or at least see what is missing). 

I don't think to have time today, eventually tomorrow but if you have time, feel free to go ahead (the new DSL are JVM only and  I think you can probably use the tests in the camel-k-runtime project)

**Comment by lburgazzoli** [comment]
Fixed in  #2308
