### ISSUE TITLE
Investigate integration test usage of quarkus.ssl.native

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2306]
Currently the Salesforce itest manually sets `quarkus.ssl.native=true` which is not great for the UX.

**Comment by ppalaga** [comment]
Uh oh, grepping for `quarkus.ssl.native` in the whole source tree shows even more of this 😱

**Comment by jamesnetherton** [comment]
> Uh oh, grepping for `quarkus.ssl.native` in the whole source tree shows even more of this

I think some of them are probably fine. I can turn this issue into a generic investigate `quarkus.ssl.native` in tests and fix all of the necessary cases.
