### ISSUE TITLE
Unable to use Salesforce DTOs in native mode

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2312]
The Salesforce integration test only verifies the producer via the `rawPayload` option. Which just returns the raw JSON or XML response from the Salesforce APIs.

Most folks are likely to be using DTOs and will rely on either Jackson or XStream to do the payload serialization / deserialization. We should ensure that this can work in native mode.

**Comment by lburgazzoli** [comment]
There is a plugin that can generate the DTOs according to the objects defined in your Salesforce instance, we may need to enhance such the plugin to mark the generated classes with `@RegisterForReflection`

**Comment by jamesnetherton** [comment]
> we may need to enhance such the plugin to mark the generated classes with `@RegisterForReflection`

Once I fix the extension to depend on `quarkus-jackson`, that should happen automatically since all of the generated classes have Jackson annotations (I think).

**Comment by lburgazzoli** [comment]
Ah in that case yes, we should be covered. If not, let fix the plugin :)

**Comment by lburgazzoli** [comment]
btw, we may have a similar issue for ServiceNow

**Comment by jamesnetherton** [comment]
> btw, we may have a similar issue for ServiceNow

Yeah, good point. I'll [check](https://github.com/apache/camel-quarkus/blob/master/integration-tests/servicenow/src/main/java/org/apache/camel/quarkus/component/servicenow/it/model/Incident.java#L26) it after I've dealt with Salesforce.
