### ISSUE TITLE
Document that AtlasMap user classes may need to be registered for reflection

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2319]
[this](https://github.com/apache/camel-quarkus/blob/master/integration-tests/atlasmap/src/main/java/org/apache/camel/quarkus/component/atlasmap/it/model/Person.java) class should be annotated with `@RegisterForReflection`, `quarkus-resteasy` is masking the issue because it is automatically registering `Person` for reflection.

We should add some notes into the AtlasMap extension docs about this requirement.

**Comment by zbendhiba** [comment]
@jamesnetherton I can do that. BTW, How did you notice that ?

**Comment by jamesnetherton** [comment]
> How did you notice that

Bindy had a similar problem and it got me thinking about other places where the issue may exist.

Basically, if you use the model class as the return type on the JAX-RS service methods, then the RestEasy extension will do the reflective class registration for that type, which is not what we want for our extensions.

There are probably other itests where this is happening, but it's a laborious task to track down every occurrence.
