### ISSUE TITLE
Add a daily job that test master agains quarkus snapshots

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#232]
It would be nice to have a (daily ?) job that builds master against quarkus snapshots (there's a profile for that) to catch issues as soon as possible.

@oscerd do you have time to take a look ?

**Comment by oscerd** [comment]
What's the profile?

**Comment by lburgazzoli** [comment]
quarkus-snapshots

**Comment by oscerd** [comment]
https://builds.apache.org/view/C/view/Apache%20Camel/job/camel-quarkus%20snapshot%20daily/job/master/3/console
