### ISSUE TITLE
Help with the creation of the Component Camel-Quarkus-JMS

### ISSUE THREAD

**Issue by Silvakilla** [apache/camel-quarkus#233]
I'm currently trying to add camel-jms as an camel component to camel quarkus, but so far it is not working. After ignoring several convergence errors (yes, not really good) I now get an error that the class: org.apache.camel.core.xml.util.jsse.ClientAuthenticationDefinition is missing. So far I couldn't find it in the existing jars of camel core xml. Was it just removed or war the package just changed? It's currently the only thing on hindering to complete a first try with the component.

And yes, I know there is an Active/ArtemisMQ JMS Extension from quarkus, but we can't really use it with old services which can't get away from IBM MQ.

**Comment by ppalaga** [comment]
Could you please share your code? - e.g. via Draft pull request?

**Comment by jamesnetherton** [comment]
Which version of Camel are you building against? I hit a similar issue some time ago and it was due to stale JAXB indexes. I should have cleaned those up as part of [CAMEL-13900](https://issues.apache.org/jira/browse/CAMEL-13900).

**Comment by Silvakilla** [comment]
I'm using Camel 3.0.0-RC1, which is the latest available release for me on mvn repo

**Comment by Silvakilla** [comment]
I still only see RC1, does it take time to get available on mvn?

**Comment by oscerd** [comment]
http://repo2.maven.org/maven2/org/apache/camel/camel-jms/3.0.0-RC2/

it's available already

**Comment by Silvakilla** [comment]
thanks for that and after adding it and still ignoring the convergence errors with spring, it works unti the still broken integration tests.
