### ISSUE TITLE
kafka: better integration with quarkus kafka extension

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#2333]
See: https://github.com/quarkusio/quarkus/issues/15631#issuecomment-796832487

**Comment by jamesnetherton** [comment]
@lburgazzoli please can you expand on this a bit?

Is the comment you refer to hinting that we should use the `Map` of Kafka properties produced by `quarkus-kafka-client` for configuring the Camel component?

**Comment by lburgazzoli** [comment]
I admin I've opened this mainly as a note to myself but never had the time to explore what exactly the `quarkus-kafka-client` provides beside the `Map` of kafka properties.

So yes, a first step would be to leverage the `Map` produced by the extension to configure the kafka component which would also bring support for service binding out of the box. 

Thinking a little bit more, I don't know if anything need to be changed on the `camel-kafka` component but in my mind the map retrieve from the Quarkus extension should be used to set-up the defaults but people should be able to override any of the provided configuration through i.e. endpoint options.
