### ISSUE TITLE
ActiveMQTestResource should not eat the exception

### ISSUE THREAD

**Issue by WillemJiang** [apache/camel-quarkus#234]
We'd better to log the exceptions when ActiveMQ Server start or stop, in the [ActiveMQTestResource](https://github.com/apache/camel-quarkus/commit/bf856616cf18c2ddb81286e13f9118d037f91021#diff-6a006df9400353640e04e51565bc48ba).

**Comment by lburgazzoli** [comment]
Fixed by https://github.com/apache/camel-quarkus/pull/235
