### ISSUE TITLE
Test autowiring of beans available in the CDI container to CamelContext and components

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2350]
E.g. if there is a single ExchangeFormatter instance in the CDI container, then it will automatically wire that bean to the LogComponent.

This is a feature of camel-quarkus-main, see https://camel.apache.org/camel-quarkus/latest/user-guide/bootstrap.html#_camel_main

**Comment by jamesnetherton** [comment]
I think we already have good coverage for this. E.g for the specific scenario mentioned:

https://github.com/apache/camel-quarkus/blob/master/extensions-core/main/deployment/src/test/java/org/apache/camel/quarkus/main/deployment/CamelMainAutoConfigurationTest.java

And elsewhere for the individual components that use the `autowired` metadata on configuration options.

**Comment by ppalaga** [comment]
Thanks, actually I found that one as I started to merge main to core.
