### ISSUE TITLE
Use in an example: autowiring of beans available in the CDI container to CamelContext and components

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2351]
E.g. if there is a single ExchangeFormatter instance in the CDI container, then it will automatically wire that bean to the LogComponent.

This is a feature of camel-quarkus-main, see https://camel.apache.org/camel-quarkus/latest/user-guide/bootstrap.html#_camel_main

**Comment by jamesnetherton** [comment]
I think we already have more than enough coverage for this. The `ExchangeFormatter` scenario is tested in core and various itests use autowiring to inject beans created by Quarkus extensions into camel components (ElasticSearch, Infinispan, Jackson, Google cloud bits etc).

**Comment by ppalaga** [comment]
This asks for an example, not for additional test coverage. But when thinking of it, I do not think this important enough for one. I guess I was carried away by the initial enthusiasm when answering the questions about examples.
