### ISSUE TITLE
Test file language

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2356]
https://camel.apache.org/components/latest/languages/file-language.html

**Comment by KurtStam** [comment]
I'm working on this one

**Comment by vkasala** [comment]
@KurtStam @ppalaga Please, can you back-port it also to old 1.8.1?

**Comment by KurtStam** [comment]
> @KurtStam @ppalaga Please, can you back-port it also to old 1.8.1?
@vkasala sure will do
