### ISSUE TITLE
Revisit core, main and foundation integration tests

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2362]
Things to improve:

* Minimize the dependencies (timer, log might get removed from the core test)
* Consider splitting some of the modules to Increase isolation, e.g. timer, and log do not have their isolated modules
* Consider introducing a grouped test to execute all modules at once on the CI
* Make sure we have both consumer and producer assertions for `direct`

**Comment by JiriOndrusek** [comment]
@ppalaga I'd like to be sure, that I understand this issue correctly:

- We should try to create separate test modules for e.g. log, timer and therefore remove this dependencies from core test
- We should verify that producer and consumer cases are tested for `direct`
- I probably don't understand what does grouped test mean in this case - do you mean to introduce grouped test, which will contain core tests and these separated ones (like timer, log, ..)?
