### ISSUE TITLE
Direct component example

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2363]
None of our current examples is using camel-quarkus-direct. We could perhaps change switch some from timer to direct. 
It would be nice if the example would demo both producer and consumer

**Comment by jamesnetherton** [comment]
https://github.com/apache/camel-quarkus-examples/blob/master/file-bindy-ftp/pom.xml#L79-L82

Producer:

https://github.com/apache/camel-quarkus-examples/blob/a129dfe052ad7c49e18ae515c180560d5ab44986/file-bindy-ftp/src/main/java/org/apache/camel/example/Routes.java#L42

Consumer:

https://github.com/apache/camel-quarkus-examples/blob/a129dfe052ad7c49e18ae515c180560d5ab44986/file-bindy-ftp/src/main/java/org/apache/camel/example/Routes.java#L45

**Comment by ppalaga** [comment]
Oh, sorry, I was grepping on an outdated master. Sorry for the confusion.
