### ISSUE TITLE
Store the association between Camel Quarkus Catalog items and Camel Catalog items

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#2368]
This would be useful because as today in camel-k you can declare a dependency by using the artifact id, so as example, to include the direct component you can use

    kamel run integration.yaml -d camel-direct

With quarkus, you need to use the quarkus one, like:

    kamel run integration.yaml -d camel-quarkus-direct

But since the runtime is an implementation detail, it would be nice to let users declaring dependencies using the camel artifact id and to make it possible we need to have the information about the artifact the extension has been created from.

**Comment by ppalaga** [comment]
A Camel Quarkus extension can depend on zero to *n* Camel artifacts. Do you have an idea where/how to store that info? 
Not sure adding a field to `org.apache.camel.tooling.model.ArtifactModel` is the best way to go. It would have little to no meaning in the context of Camel Core. Maybe we should add a free form map for this kind of ad hoc attributes that are only meaningful for Camel subprojects?

**Comment by lburgazzoli** [comment]
I don't have any opinion about where to store such info, so generic attributes would work for me

**Comment by ppalaga** [comment]
Created https://issues.apache.org/jira/browse/CAMEL-16557

**Comment by ppalaga** [comment]
Blocked by https://github.com/apache/camel/pull/5471

**Comment by ppalaga** [comment]
Looking at this in greater detail, the entries (components, languages and data formats) in camel quarkus catalog have zero or one camel artifact they come from. I am implementing something like this:
![image](https://user-images.githubusercontent.com/1826249/119336522-0a5a4c80-bc8e-11eb-88d3-fd06c62a718c.png)

**Comment by ppalaga** [comment]
Fixed via a1260cb1ed0b19dbfe6010621532e9be326df489
