### ISSUE TITLE
[Camel 3.10] jsonpath: Getting rid of json-smart as explicit and transitive dependency

### ISSUE THREAD

**Issue by zbendhiba** [apache/camel-quarkus#2435]
The JIRA from camel : [CAMEL-16375](https://issues.apache.org/jira/browse/CAMEL-16375)
The json-smart has been removed from camel-jsonpath see commit : [b59a96ddf1ba647b979f937f5bd956bba32173ee](https://github.com/apache/camel/commit/b59a96ddf1ba647b979f937f5bd956bba32173ee)  

These classes are not compiling anymore : [JSONValueSubstitution](https://github.com/apache/camel-quarkus/blob/master/extensions/jsonpath/runtime/src/main/java/org/apache/camel/quarkus/component/json/path/JSONValueSubstitution.java) and [JSONWriterSubstitution](https://github.com/apache/camel-quarkus/blob/master/extensions/jsonpath/runtime/src/main/java/org/apache/camel/quarkus/component/json/path/JSONWriterSubstitution.java)

**Comment by zbendhiba** [comment]
temporarly [reintroduced json-smart ](https://github.com/apache/camel-quarkus/commit/6f455245247d819e148e8ae0870917461f43573e) to make CI build work. 
It need to be fixed for 3.10

**Comment by zbendhiba** [comment]
since Graalvm needs json-smart at build time, move the version to 2.4.7, that fixes the CVE

**Comment by jamesnetherton** [comment]
Reopening as per https://github.com/apache/camel-quarkus/pull/2669#issuecomment-847927434.

**Comment by zbendhiba** [comment]
@jamesnetherton  I still don't know how to substitute those ValueNode and JsonNode classes. 
Is there a way to delete imported classes with substitution ? I try to substitute the methods, but I get those kind of errors in compilation
`Error: Class initialization of com.jayway.jsonpath.internal.filter.ValueNodes$JsonNode failed. Use the option --initialize-at-run-time=com.jayway.jsonpath.internal.filter.ValueNodes$JsonNode to explicitly request delayed initialization of this class.
Original exception that caused the problem: java.lang.NoClassDefFoundError: net/minidev/json/parser/ParseException`

**Comment by jamesnetherton** [comment]
@zbendhiba can you share a branch with your WIP so I can take a look?

**Comment by zbendhiba** [comment]
@jamesnetherton  https://github.com/zbendhiba/camel-quarkus/commits/jsonpath2

**Comment by jamesnetherton** [comment]
@zbendhiba I took a look and I cant see an easy solution.

Sorry for wasting your time working on it. I really thought it'd be simple(ish) to cut out json-smart. I guess for now we're stuck having to include the dependency.

**Comment by zbendhiba** [comment]
So I can close this one then
