### ISSUE TITLE
CamelContext.getVersion() always returns an empty string

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#247]

**Comment by davsclaus** [comment]
I think @gnodet fixed something a while back where the version was empty when native compiled but was shown when in JVM mode

**Comment by gnodet** [comment]
That may be have been before the donation actually. And it may be a regression.
The version is extracted from the `/META-INF/maven/org.apache.camel/camel-core/pom.properties` resource and cached, so we need to either:
  * force the load at init time by calling `context.getVersion()` just after the context has been created
  * or include the needed time by providing a `SubstrateResourceBuildItem`

**Comment by lburgazzoli** [comment]
The resource should be already included, at least according to the code:

    https://github.com/apache/camel-quarkus/blob/master/extensions/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/SubstrateProcessor.java#L131-L132

**Comment by jamesnetherton** [comment]
> The resource should be already included, at least according to the code

Yep - but it depends on camel-core being on the classpath, and I don't think that's the case for most (maybe all) of our extensions.

`AbstractCamelContext` is in camel-base. So maybe we just update [this](https://github.com/apache/camel/blob/master/core/camel-base/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java#L2194) path to point to `/META-INF/maven/org.apache.camel/camel-base/pom.properties` and afterwards update `SubstrateResourceBuildItem` accordingly.

**Comment by lburgazzoli** [comment]
Ah, yes, we have changed a number of things in core/* so that could be a leftover :)
