### ISSUE TITLE
Add info about Camel IDE plugins to the documentation

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2470]
We list Quarkus specific plugins on https://camel.apache.org/camel-quarkus/latest/user-guide/first-steps.html#_ide_plugins but we do not mention any Camel specific ones. 
Here is the AsciiDoc source of the page https://github.com/apache/camel-quarkus/blob/main/docs/modules/ROOT/pages/user-guide/first-steps.adoc

**Comment by apupier** [comment]
For Camel URL support:
- [VS Code Language support for Camel](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-apache-camel) which is part of the [Camel extension pack](https://marketplace.visualstudio.com/items?itemName=redhat.apache-camel-extension-pack)
- [Eclipse Desktop Language Support for Camel](https://marketplace.eclipse.org/content/language-support-apache-camel) which is part of Jboss Tools and CodeReady Studio
- [Apache Camel IDEA plugin](https://plugins.jetbrains.com/plugin/9371-apache-camel-idea-plugin) /!\ not always maintained
- all [IDEs that can configure a Language Server](https://microsoft.github.io/language-server-protocol/implementors/tools/) by using the [Camel Language Server](https://github.com/camel-tooling/camel-language-server) /!\ requires manual configuration by users

**Comment by ppalaga** [comment]
> * possible to use Eclipse Che/CodeReady Containers but will surely require to configure a bit a devfile (and have a lot of memory available)

Is there any web page about using Che/CodeReady with Camel that we could refer to in our docs? The above sentence is not specific enough to be really usable for the docs.

**Comment by apupier** [comment]
> > * possible to use Eclipse Che/CodeReady Containers but will surely require to configure a bit a devfile (and have a lot of memory available)
> 
> Is there any web page about using Che/CodeReady with Camel that we could refer to in our docs? The above sentence is not specific enough to be really usable for the docs.

There's none related to both Camel and Quarkus. Some work would need to be done also to test having both Quarkus and Camel to ensure that it is working.

For Camel only, there is this old article https://developers.redhat.com/blog/2019/05/21/apache-camel-development-on-eclipse-che-7/
For Quarkus only, there is this old article https://developers.redhat.com/blog/2019/08/19/get-started-with-eclipse-che-7-and-quarkus-an-overview/

**Comment by ppalaga** [comment]
OK, thank, let's leave it out of the docs for now then.
