### ISSUE TITLE
Dev Mode: rests xml resources seems ignored

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#2476]
See https://github.com/quarkusio/quarkus/issues/16402 for more context. Let's reproduce this in itests.

A workaround is to use `quarkus.live-reload.watched-resources = rests/rests.xml` in `application.properties`.
Apparently, it would be possible to have this set by extensions using LiveReloadBuildItem.

**Comment by lburgazzoli** [comment]
FWIW, this was working in the past: https://github.com/apache/camel-quarkus/blob/main/extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/main/CamelMainHotDeploymentProcessor.java#L35-L56

**Comment by aldettinger** [comment]
Thanks for pointing out Luca. Now I'm thinking it may be linked to camel-main merged in core or maybe I messed up something in my project. Will try to reproduce first :)

**Comment by aldettinger** [comment]
Finally, it was just that resources with classpath prefix and without prefix were not hot watched. It fixed now.
