### ISSUE TITLE
Create a Camel Netty TCP extension

### ISSUE THREAD

**Issue by dhartford** [apache/camel-quarkus#248]
Create camel netty-tcp extension in order to support lower-level TCP payloads in camel/EIP-style solutions.

**Comment by dhartford** [comment]
note - I'm barely ready to contribute, so if someone can fast track and build on top of it, please do!

**Comment by oscerd** [comment]
The idea should be to simply create a camel-netty extension.

**Comment by ppalaga** [comment]
Contributions are welcome! @dhartford you or anybody else may want to try to implement this following https://camel.apache.org/camel-quarkus/latest/contributor-guide.html Feel free to ask if you have specific questions.

**Comment by dhartford** [comment]
Reviewing, I was hoping for a sample init commit of just the netty-http to see what the scope was, but no luck. Reviewing these, let me know if I missed something from a scope point of view for 'writing a new quarkus-camel extension':

> sample extension scope:
> 
> https://github.com/apache/camel-quarkus/tree/master/extensions/netty-http
> https://github.com/apache/camel-quarkus/tree/master/integration-tests/netty-http/
> 
> And parent-pom and documentation additions:
> https://github.com/apache/camel-quarkus/search?q=netty-http&unscoped_q=netty-http
>

**Comment by ppalaga** [comment]
Yes you need to add:

* 3 new modules under https://github.com/apache/camel-quarkus/tree/master/extensions : netty-parent, netty runtime and netty deployment
* An integration test under https://github.com/apache/camel-quarkus/tree/master/integration-tests
* Entries to poms/bom/pom.xml and to poms/deployment/pom.xml

Special in this case is that camel-netty-http already depends on camel-netty, so actually the existing camel-quarkus-netty-http should be refactored to depend on your new camel-quarkus-netty extension.

**Comment by dhartford** [comment]
Pre-review request - I've started doing the integration tests directly with Socket code, which feels incorrect, but I didn't want to burden with unnecessary test dependencies/libraries.

Is there a recommendation/preference from the team of how to do TCP testing (whereas RestAssured is currently the preferred HTTP testing framework)?

https://github.com/dhartford/camel-quarkus/blob/camel-quarkus-netty/integration-tests/netty/src/test/java/org/apache/camel/quarkus/component/netty/it/NettyTest.java

**Comment by ppalaga** [comment]
I'd be fine with using a `java.net.Socket` directly, but I am not the highest instance here. WDYT, @lburgazzoli and others?

**Comment by dhartford** [comment]
I'll keep moving forward with Socket, thanks for the double-check.  I simulated the Poem test from the original camel-netty tests and is working fine with normal java, but failing in native with this. I'm still tracking it down, just sharing status update or if this is an issue previously experienced in other camel projects:

`org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: netty://tcp://localhost:8999?sync=true&textline=true due to: There are 2 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{sync=true, textline=true}]`

**Comment by lburgazzoli** [comment]
using sockets is fine but you can use netty too (i.e. to resuse some pre-defined handers/codecs.

about the exception in native mode is usually because of a reflective access to a class so you need to add it to the reflective class list

**Comment by dhartford** [comment]
Alright, native tests pass, adding the the reflective classes with an additional dependency camel-endpointdsl was the solution.

**Comment by ppalaga** [comment]
This can be closed.

**Comment by ppalaga** [comment]
And once again, @dhartford, many thanks for the contribution!
