### ISSUE TITLE
[Camel 3.10] Improve KafkaClientFactory integration

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2486]
In https://github.com/apache/camel-quarkus/commit/6e440e02573a2ae136983454f345424e85cd0083 I had to do a little [workaround](https://github.com/apache/camel-quarkus/blob/6e440e02573a2ae136983454f345424e85cd0083/extensions/kafka/runtime/src/main/java/org/apache/camel/quarkus/component/kafka/CamelKafkaRecorder.java#L43-L47) to get the `KafkaClientFactory` bound to the `KafkaComponent` due to [CAMEL-16500](https://issues.apache.org/jira/browse/CAMEL-16500).

It should eventually be possible to add the `KafkaClientFactory` to the registry and let Camel do the autowiring.

**Comment by ppalaga** [comment]
Camel 3.10 is in main now
