### ISSUE TITLE
Test bean binding

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2492]
We should test the use cases mentioned in https://camel.apache.org/manual/latest/bean-binding.html

**Comment by ppalaga** [comment]
Missing tests (TBD within this issue):
* Pass the method name via `CamelBeanMethodName` header
* `@org.apache.camel.Consume` https://camel.apache.org/manual/latest/pojo-consuming.html
* `@EndpointInject` https://camel.apache.org/manual/latest/pojo-producing.html#POJOProducing-EndpointInject
* `@org.apache.camel.Produce` https://camel.apache.org/manual/latest/pojo-producing.html#POJOProducing-HidingtheCamelAPIsFromYourCodeUsingProduce
* "the type of the body is used to find a matching method; an error is thrown if a single method cannot be chosen unambiguously."
* Use Exchange as the parameter itself, but then the return type must be void
* Return a CompletionStage implementation (e.g. a CompletableFuture)
* Have multiple params, e.g. `doSomething(String body, Registry r, Exchange e)`
* Parameter binding annotations https://camel.apache.org/manual/latest/parameter-binding-annotations.html
* Parameter literals `.bean(OrderService.class, "doSomething(*, true)")` - not sure this would work without simple language
* Param types to select the right overload `hello(String,String)`

TBD elsewhere:
* "If the bean can be converted to a Processor using the Type Converter mechanism, then this is used to process the message. " I do not think we need to test this specific scenario. But we should test Type Converters in general https://github.com/apache/camel-quarkus/issues/2537
* `org.apache.camel.component.bean.BeanInvocation` - does not exist anymore in Camel source tree, see https://issues.apache.org/jira/browse/CAMEL-16562

Scenarios covered already:
* `@Handler` https://github.com/apache/camel-quarkus/blob/main/integration-tests/bean/src/main/java/org/apache/camel/quarkus/component/bean/WithHandlerBean.java#L33

**Comment by ppalaga** [comment]
* Pass the method name via `CamelBeanMethodName` header
  * See `BeanTest.beanMethodInHeader()`
* "the type of the body is used to find a matching method; an error is thrown if a single method cannot be chosen unambiguously."
  * `NamedBean` has `hello(String)` and `hello(Integer)`. `BeanTest.named()` still hits `hello(String)` for a String payload.
* Use Exchange as the parameter itself, but then the return type must be void 
  * See `BeanTest.methodWithExchangeArg()`
* Return a CompletionStage implementation (e.g. a CompletableFuture)
  * See `BeanTest.completionStageBean()`
* Have multiple params, e.g. `doSomething(String body, Registry r, Exchange e)`
  * See `BeanTest.multiArgMethod()`
* Parameter binding annotations https://camel.apache.org/manual/latest/parameter-binding-annotations.html
* Parameter literals `.bean(OrderService.class, "doSomething(*, true)")` - not sure this would work without simple language
* Param types to select the right overload `hello(String,String)`

**Comment by aldettinger** [comment]
Great, we have some catches with @ EndpointInject and friends.

If I remember well, the overload selection mechanism may need to traverse a lot of classes.
On the top on my head, I would say the involved hierarchy then need @RegisterForReflection to be set by developers. So, I don't think more tests are needed at this stage.
