### ISSUE TITLE
[servlet-extension] Unrecognized configuration key "quarkus.camel.servlet.url-patterns" provided

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#251]
When running tests related to the servlet extension, the following warning is reported during augmentation phase:
 
    [WARNING] [io.quarkus.config] Unrecognized configuration key "quarkus.camel.servlet.url-patterns" provided

@ppalaga is that something that can be safely ignored or an indication on something wrong about how servlet extension configuration is handled ?

**Comment by ppalaga** [comment]
Plz assign to me.

**Comment by ppalaga** [comment]
I only see it happening in the twitter itest where I am going to fix it. Are you sure you see it happening in some servlet related test (which)?

**Comment by lburgazzoli** [comment]
Oh yes sorry, I've confused the tests, so yes saw it on twitter only
