### ISSUE TITLE
[Quarkus 2.0] Consider following the way how Quarkus handles Avro schemas

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2513]
With https://github.com/quarkusio/quarkus/pull/16169 and a couple of other related PRs Quarkus introduced a new approach for compiling Avro schemas. They are now compiled using `generate-code` and `generate-code-tests` mojos of `quarkus-maven-plugin`. I wonder whether we should recommend the same to our end users and maybe deprecate our `@BuildTimeAvroDataFormat` annotation?

**Comment by ppalaga** [comment]
WDYT @aldettinger ?

**Comment by ppalaga** [comment]
I guess we should at least document the new option.

**Comment by aldettinger** [comment]
Indeed, I think deprecating `@BuildTimeAvroDataFormat` + documenting the new option is good.

**Comment by ppalaga** [comment]
Thanks, I think we can do this once we have Quarkus 2.0.x in our `main` branch.

**Comment by jamesnetherton** [comment]
I moved this to the 2.0.0 milestone as I think it'd be good to get this done.

Would also be good if we could cover the different schema types avdl, avpr & avsc.
