### ISSUE TITLE
Once quarkiverse extension upgrades google-cloud-storage to 1.113.8, remove exclusion in google-storage extension

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#2526]
Camel and quarkiverse google-storage are not aligned with `google-cloud-storage` library. (`1.113.4` vs `1.113.8`) Issue in quarkiverse is reported as https://github.com/quarkiverse/quarkus-google-cloud-services/issues/113

If quarkiverse extension is upgraded, remove exclusios in google-storage/runtime extension.

**Comment by jamesnetherton** [comment]
Out of date since we no longer use the `quarkus-google-cloud-services` extensions.
