### ISSUE TITLE
Build time property to register classes for reflection

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#253]
Users may need to register additional classes for reflection i.e. provided by 3th party artefacts while writing routes and as today they have the following options:

- write an extension
- create a reflection configuration file as described [here](https://quarkus.io/guides/writing-native-applications-tips#registering-for-reflection) 

Both the options are possible but wondering if we could further ease the process for simple cases by providing a build time property to list classes that need to be registered for reflection.

**Comment by ppalaga** [comment]
+1 That will surely be helpful when investigating issues.

Does this not belong to Quarkus itself actually?

**Comment by lburgazzoli** [comment]
I know that they are thinking about something but not sure about if they will actually make it, when and how. 

I'll investigate a little bit and eventually I'll implement an interim solution.

**Comment by ppalaga** [comment]
`@RegisterForReflection` can actually be used also to register third party classes https://github.com/quarkusio/quarkus/blob/master/core/runtime/src/main/java/io/quarkus/runtime/annotations/RegisterForReflection.java#L25-L32

I'd say that's enough and we do not need to do anything on the Camel Quarkus side. WDYT, @lburgazzoli ?

**Comment by lburgazzoli** [comment]
I'm aware of that class however it may be more practical if we have a configuration property as i.e. it would be much more practical in camel-k so a user do not nee to write any java code and we don't need to store any additional java file in the CR just for the need to list classes that need to be registered for reflection

**Comment by ppalaga** [comment]
> it would be much more practical in camel-k

I suspected you are going to come with something like this :). Moving `quarkus.camel.resources.*` to `quarkus.camel.native.resources.*` and putting this new opt. there seems like optimal variant. Would you please upvote https://github.com/apache/camel-quarkus/pull/983 if you think so?
