### ISSUE TITLE
Once quarkiverse extension (google-cloud-storage) allows optional and multiple client registration, change google-storage extension accordingly

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#2534]
There is an issue https://github.com/quarkiverse/quarkus-google-cloud-services/issues/114.

If this enhanced client registration options are available, google-storage extension/test could be changed.

**Comment by jamesnetherton** [comment]
Out of date since we no longer use the `quarkus-google-cloud-services` extensions.
