### ISSUE TITLE
Support @EndpointInject and @Produce

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2539]
* `@org.apache.camel.EndpointInject` https://camel.apache.org/manual/latest/pojo-producing.html#POJOProducing-EndpointInject
* `@org.apache.camel.Produce` https://camel.apache.org/manual/latest/pojo-producing.html#POJOProducing-HidingtheCamelAPIsFromYourCodeUsingProduce

**Comment by ppalaga** [comment]
I am adding some `@Disabled("https://github.com/apache/camel-quarkus/issues/2539")` tests to BeanTest

**Comment by ppalaga** [comment]
@davsclaus @lburgazzoli This seems to be doable, but before I invest more time into this: are there any reasons not to support any of the named annotations in Camel Quarkus?

**Comment by davsclaus** [comment]
No this would be great to have.

**Comment by ppalaga** [comment]
All the named annotations have `@Target({ ElementType.FIELD, ElementType.METHOD, ElementType.CONSTRUCTOR })` 
While there is a lot of field examples in Camel source tree, I do not see any for method or constructor. Are they really supported for methods?

**Comment by davsclaus** [comment]
Yeah pojo routing is on methods.
https://github.com/apache/camel-examples/tree/main/examples/pojo-messaging

However constructor dont really make much sense, only @EndpointInject could matter there.

**Comment by davsclaus** [comment]
Created a JIRA to fix those annotations
https://issues.apache.org/jira/browse/CAMEL-16571

**Comment by ppalaga** [comment]
Moved `@Consume` to https://github.com/apache/camel-quarkus/issues/2580
