### ISSUE TITLE
[Quarkus 2.0.0.Alpha2] Camel-main failure tests

### ISSUE THREAD

**Issue by zbendhiba** [apache/camel-quarkus#2566]
Test failure 
`Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 13.839 s <<< FAILURE! - in org.apache.camel.quarkus.main.CoreMainTest
Error:  testProperties  Time elapsed: 0.058 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Response body doesn't match expectation.
Expected: is "test"
  Actual: default`

**Comment by zbendhiba** [comment]
Related to this issue [quarkus-17103](https://github.com/quarkusio/quarkus/issues/17103)

**Comment by zbendhiba** [comment]
I'm going to temporary deactivate this test so that we can have a full build of camel-main branch

**Comment by ppalaga** [comment]
Thanks for fixing this, @zbendhiba! 

Note to myself: we'll need to add as similar snippet to this test's pom.xml in Quarkus Platform.
