### ISSUE TITLE
[Quarkus 2.0.0.Alpha2] upgrade to  GrpcService annotation

### ISSUE THREAD

**Issue by zbendhiba** [apache/camel-quarkus#2569]
gRPC integration tests are failing with upgrade to Quarkus 2.0.0.Alpha2, due to a rework of the gRPC annotations. The new annotation `GrpcService` seems to be mandatory.

Related issue from the Quarkus 2.0.0.Alpha2 release is : [quarkus-16872](https://github.com/quarkusio/quarkus/issues/16872)

Error from our CI build : 
`Error: ]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: javax.enterprise.inject.spi.DeploymentException: java.lang.IllegalStateException: A gRPC service bean must be annotated with io.quarkus.GrpcService: CLASS bean [types=[org.apache.camel.quarkus.grpc.runtime.CamelQuarkusBindableService, io.grpc.BindableService, org.apache.camel.quarkus.component.grpc.it.model.PingPongGrpc$PingPongImplBaseQuarkusMethodHandler, java.lang.Object, org.apache.camel.quarkus.component.grpc.it.model.PingPongGrpc$PingPongImplBase], qualifiers=[@Default, @Any], target=org.apache.camel.quarkus.component.grpc.it.model.PingPongGrpc$PingPongImplBaseQuarkusMethodHandler]`

**Comment by jamesnetherton** [comment]
Should be fixed here https://github.com/apache/camel-quarkus/commit/b8e81616d61476190ba9c8ae2b6a594e3ebabc96.
