### ISSUE TITLE
Shell scripts in the user guide documentation are not compatible with Mac OS X

### ISSUE THREAD

**Issue by coolbeevip** [apache/camel-quarkus#257]
```
cp -r camel-quarkus/integration-tests/servlet/ .
```

The following is the description of the -R parameter in the man pages for cp on Mac OS X:

If source_file designates a directory, cp copies the directory and the entire subtree connected at that point.  If the source_file  ends in a /, the contents of the directory are copied rather than the directory itself.  This option also causes symbolic links to be copied, rather than indirected through, and for cp to create special files rather than copying them as normal files.  Created directories have the same mode as the corresponding source directory, unmodified by the process' umask.

**Comment by ppalaga** [comment]
Thanks for the report, @coolbeevip . Could you please propose a shell command that works for you?

**Comment by ppalaga** [comment]
Sorry, I see the PR now.

**Comment by coolbeevip** [comment]
> Thanks for the report, @coolbeevip . Could you please propose a shell command that works for you?

I submitted a PR #258 for it
