### ISSUE TITLE
Fix ArangoDb warnings

### ISSUE THREAD

**Issue by zbendhiba** [apache/camel-quarkus#2575]
see these warnings and adapt tests
```
WARNING: Method com.arangodb.entity.MetaAware.<init>() not found.
WARNING: Could not resolve com.arangodb.entity.BaseDocumentTest for reflection configuration. Reason: java.lang.ClassNotFoundException: com.arangodb.entity.BaseDocumentTest.
WARNING: Method com.arangodb.entity.arangosearch.PrimarySort.<init>() not found.
WARNING: Method com.arangodb.entity.Entity.<init>() not found.
WARNING: Method com.arangodb.entity.arangosearch.FieldLink.<init>() not found.
WARNING: Method com.arangodb.entity.arangosearch.ConsolidationPolicy.<init>() not found.
WARNING: Method com.arangodb.entity.DocumentField.<init>() not found.
WARNING: Method com.arangodb.entity.arangosearch.CollectionLink.<init>() not found.
WARNING: Method com.arangodb.entity.arangosearch.StoredValue.<init>() not found.
WARNING: Method com.arangodb.entity.arangosearch.ArangoSearchPropertiesEntity.<init>() not found.
WARNING: Method com.arangodb.model.AqlQueryExplainOptions$1.<init>() not found.
WARNING: Method com.arangodb.model.AqlQueryOptions$1.<init>() not found.
```

**Comment by ppalaga** [comment]
Filed this one https://github.com/arangodb/arangodb-java-driver/issues/392

**Comment by ppalaga** [comment]
Hm... `--allow-incomplete-classpath` in their config https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/resources/META-INF/native-image/com.arangodb/arangodb-java-driver/native-image.properties#L2 looks scarry. I wonder whether we should prefer ignoring their config completely once Quarkus offers a programmatic way to do so https://github.com/quarkusio/quarkus/issues/17482

**Comment by ppalaga** [comment]
Filed https://github.com/arangodb/arangodb-java-driver/issues/397 for --allow-incomplete-classpath in their config https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/resources/META-INF/native-image/com.arangodb/arangodb-java-driver/native-image.properties#L2

**Comment by jamesnetherton** [comment]
No native warnings / errors in the latest builds.
