### ISSUE TITLE
Support JMS ObjectMessage

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2599]
Ultimately this issue likely belongs elsewhere (I.e Quarkus) and that there's a prerequisite that Quarkus provides support for GraalVM serialization. But we should at least document that usage of `javax.jms.ObjectMessage` is currently not supported in native mode since it relies on Java object serialization.

Maybe it's best fulfilled by some configuration option that enables a user to list the desired classes destined for Java serialization.

Perhaps also there's a conversation to be had as to whether it should be supported at all given that there are alternatives to Java serialization (JSON, XML etc).

**Comment by ppalaga** [comment]
I guess https://github.com/quarkusio/quarkus/pull/15380 would help if it was merged?

**Comment by jamesnetherton** [comment]
Yeah it would be a first step at least...
