### ISSUE TITLE
Consider grouped tests for messaging components

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2605]
Right now we have a number of components tested together in the `messaging` itest module. We should consider breaking the tests down into individual modules for each extension and leverage grouping for the CI build.

**Comment by ppalaga** [comment]
We have split the old messaging test in between, but IIRC, grouping is not possible, because those tests have mutually incompatible deps (esp. message broker adapters). So I guess we can close this one, @jamesnetherton?

**Comment by jamesnetherton** [comment]
Yes, I'll close.
