### ISSUE TITLE
Messaging integration test for JMS topics is not working

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2608]
Turns out that topics have not actually ever been tested properly. The JAX-RS resource method for the test is missing an `@Consumes` annotation which seems to prevent the logic from being triggered.

However, when adding this, the tests fail anyway and I couldn't track down what the cause of the issue is after a quick investigation.

Not sure if it's related to the dockerized Artemis instance configuration in some way. Since we're using an out-of-date & deprecated image, perhaps we should use the `EmbeddedActiveMQ` in `ActiveMQTestResource`? We could inherit `artemis-server` from the `quarkus-bom` and that way we don't have to worry about additional maintenance on our side.

**Comment by jamesnetherton** [comment]
@zhfeng Would you be able to take a look at this?

**Comment by zhfeng** [comment]
@jamesnetherton yeah, please assign to me.

**Comment by zhfeng** [comment]
I'd tried to use ```EmbeddedActiveMQ``` but it did not resolve the issue. Only one endpoint of the topic receives a message. I will keep investigating.

**Comment by zhfeng** [comment]
@jamesnetherton I think I get the root cause of the issue which we can not reslove the destination name correcly and always use ```createQueue```. It could be better to raise a other issue to replace the out-of-date docker artemis image with ```EmbeddedActiveMQ``` from ```artemis-server```.

**Comment by jamesnetherton** [comment]
I completely forgot about the custom destination resolver. Thanks for fixing it @zhfeng!

We can take care of the docker image in another issue.

**Comment by zhfeng** [comment]
yeah, I raise https://github.com/apache/camel-quarkus/issues/2727 and I can take a look since this image has also been used in jta integration tests.
