### ISSUE TITLE
camel-jackson-avro data format native support

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-quarkus#2610]
These are two new dataformats added to Camel 3.10 that are needed in Kamelets.

**Comment by ppalaga** [comment]
Moved and camel-jackson-protobuf to a separate issue https://github.com/apache/camel-quarkus/issues/2615

**Comment by ppalaga** [comment]
A JVM only extension is underway https://github.com/apache/camel-quarkus/pull/2643
