### ISSUE TITLE
[camel 3.10] load selected list of kamelets definitions at build time

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#2618]
Old draft PR here: https://github.com/apache/camel-quarkus/pull/2549
Can leverage the new kamelet loader: https://github.com/apache/camel/blob/main/dsl/camel-yaml-dsl/camel-yaml-dsl/src/main/java/org/apache/camel/dsl/yaml/KameletRoutesBuilderLoader.java

**Comment by ppalaga** [comment]
@valdar if this was implemented already could you please paste a link to PR or commit and close?

**Comment by valdar** [comment]
Done in https://github.com/apache/camel-quarkus/pull/2799
