### ISSUE TITLE
Reinstate camel integration tests to the Quarkus Platform nightly SNAPSHOT build

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2621]
I am temporarily removing Camel since we do not yet have a Quarkus 2 compatible release.

**Comment by jamesnetherton** [comment]
Here's the script that will need tweaking:

https://github.com/quarkusio/quarkus-platform/blob/main/.github/quarkus-ecosystem-test#L8-L9

**Comment by ppalaga** [comment]
Now we have Quarkus 2.0.0.x in our main branch

**Comment by jamesnetherton** [comment]
Fixed when platform was upgraded to CQ 2.0.0.
