### ISSUE TITLE
Expand MongoDb test coverage

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#2622]
Add additional test coverage for:

- ~Configuration of database in Spring XML.~ EDITED
- Override an operation with dynamic operation. (Producer)
- Tailable cursor consumer
- Tailable cursor consumer with persistent tail tracking
- Change streams consumer
- Included converter

**Comment by jamesnetherton** [comment]
I think we can leave out testing for the Spring XML config.

**Comment by JiriOndrusek** [comment]
@jamesnetherton this was my idea either. But it could be theoretically possible and because it is the first chapter in component doc, I kept it there. But if standard way is to ignore this and go only woth quarkus like configuration, no problem here.

**Comment by jamesnetherton** [comment]
> go only with quarkus configuration

Yeah that's the default test strategy. A lot of the component docs will mention Spring XML, but it's not our focus here so much. Also, not all of the Spring stuff will work since we do not fully support the framework.

**Comment by JiriOndrusek** [comment]
ok, then I'm remopving this item from the summary, thanks for confirmation.
