### ISSUE TITLE
Test creating a subscription of an SQS Queue to an SNS Topic

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2624]
https://camel.apache.org/components/3.9.x/aws2-sns-component.html#_create_a_subscription_between_an_aws_sns_topic_and_an_aws_sqs_queue

**Comment by JiriOndrusek** [comment]
@ppalaga It seems, that this test is already present:

-  Subscription of an SQS Queue to an SNS Topic is [here](https://github.com/apache/camel-quarkus/blob/main/integration-test-groups/aws2/aws2-sqs-sns/src/main/java/org/apache/camel/quarkus/component/aws2/sqs/it/Aws2SqsSnsResource.java#L97)
-  Consume messages coming from SNS Topic through your SQS Queueis [here](https://github.com/apache/camel-quarkus/blob/main/integration-test-groups/aws2/aws2-sqs-sns/src/main/java/org/apache/camel/quarkus/component/aws2/sqs/it/Aws2SqsSnsResource.java#L110 ) 
- Both endpoints are used by [this test](https://github.com/apache/camel-quarkus/blob/main/integration-test-groups/aws2/aws2-sqs-sns/src/test/java/org/apache/camel/quarkus/component/aws2/sqs/it/Aws2SqsSnsTest.java#L68) amd by new FIFO test [here](https://github.com/apache/camel-quarkus/pull/2960)

**Comment by ppalaga** [comment]
Thanks for checking, @JiriOndrusek! Indeed `subscribeSNStoSQS=true` is there.
