### ISSUE TITLE
Unregister MongoDb's ChangeStreamDocument from reflection once it is provided by Quarkus

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#2649]
Follows https://github.com/apache/camel-quarkus/issues/2622
See more details in https://github.com/apache/camel-quarkus/pull/2642#issue-649783790.

Quarkus mongodb extension does not contain reflection registration of `ChangeStreamDocument`. It is reported as https://github.com/quarkusio/quarkus/issues/17432

Once https://github.com/quarkusio/quarkus/issues/17432 is fixed, registration in `MongoDbProcessor` could be removed.

**Comment by ppalaga** [comment]
The blocking issue seems to be fixed. Let's wait for the next Quarkus milestone.

**Comment by ppalaga** [comment]
Fix is underway.
