### ISSUE TITLE
Class loader issues in AvroRpcTest with Quarkus 2.0.0.Alpha3

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2651]
A variant of https://github.com/apache/camel-quarkus/issues/2514 

`quarkus.test.flat-class-path=true` is a workaround

**Comment by ppalaga** [comment]
Related: https://github.com/quarkusio/quarkus/issues/17463

**Comment by JiriOndrusek** [comment]
Problem is caused by issue in jetty. Wrong classloader is set in jetty. Issue was reported as https://github.com/eclipse/jetty.project/issues/6399

**Comment by ppalaga** [comment]
I wonder what we can do for 2.0.0 that will happen before Camel 3.11? Could you @JiriOndrusek perhaps check the feasibility of having the Undertow based `org.apache.avro.ipc.Server` impl. here in Camel Quarkus for now? We could do it properly once we have the necessary changes in Camel.

**Comment by JiriOndrusek** [comment]
Change in Camel is proposed as https://issues.apache.org/jira/browse/CAMEL-16740 (PR is created - https://github.com/apache/camel/pull/5714)

@ppalaga I'll try to find a way of fixing it in meantime in camel-quarkus only, as you suggested.
