### ISSUE TITLE
vert-x http client failing for HTTPS with Quarkus 2.0.0.Alpha3

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2656]
To reproduce, uncomment `/*, "vertx-http"*/` in HttpTest.

**Comment by jamesnetherton** [comment]
Quarkus has already moved on to Vert.x 4.1.x, Camel 3.10 is aligned with 4.0.x and there are some differences that affect the way in which the vertx-http component sets up keystore / truststore support.

It's an easy problem to work around, so for now, I'll make some mods to get the itest working and we can add a release note for CQ 2.0.0.
