### ISSUE TITLE
Adapt Observability docs page to Quarkus 2.0.0

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2659]
https://camel.apache.org/camel-quarkus/latest/user-guide/observability.html the Quarkus endpoints are now prefixed with `/q` we should perhaps also explain that the change happened with Quarkus 2.0

**Comment by ppalaga** [comment]
The same holds for rest-openapi extension page

**Comment by jamesnetherton** [comment]
We'll probably need to update some of the examples READMEs too. I'll take a look.
