### ISSUE TITLE
camel-quarkus-jacksonxml:JsonView annotations take no effect in native mode

### ISSUE THREAD

**Issue by ffang** [apache/camel-quarkus#2681]
Can't control the xml payload(with selected properties), seems somehow JsonView doesn't work in native mode only

**Comment by ffang** [comment]
It turns out to be that JsonView annotation relys on the reflection to load class like
```
@JsonView(Views.Weight.class)
    private int weight = 70;
```
And the class here(Both inner class and outer class should be marked as @RegisterForReflection during runtime)

**Comment by ppalaga** [comment]
Fixed via 5d2ef77f7fb56379a77eaad55fbe8ab029f92e20
