### ISSUE TITLE
Problem with dashed queryParams

### ISSUE THREAD

**Issue by ruromero** [apache/camel-quarkus#2685]
When defining routes using the rest dsl I have not been able to use query parameters with hyphen. Only when removing such hyphens the route seems to be properly loaded.

The following doesn't work:
```
        rest()
            .id("example")
            .get("/hello/{my-param}")
            .param()
                .name("my-param")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
            .endParam()
            .to("direct:hello");
        from("direct:hello").to("log:hello?level=INFO");
```
This is how it appears in the logs: `Started route159 (rest://get:/hello/%7Bmy-param%7D)`

Whereas after removing the hyphen in the queryParam name, the route works as expected.

**Comment by jamesnetherton** [comment]
The REST HTTP consumer is backed by Vert.x. The [documentation](https://vertx.io/docs/vertx-web/java/#_capturing_path_parameters) states the following:

> The placeholders consist of : followed by the parameter name. Parameter names consist of any alphabetic character, numeric character or underscore. In certain cases this is a bit limited, so users may switch to an extended name rule which includes 2 extra characters - and $. The extended param rule is enabled as a system property `-Dio.vertx.web.route.param.extended-pattern=true`

I tested with the system property and the endpoint works properly.

**Comment by jamesnetherton** [comment]
Guess I should drop a note into our docs about that....

**Comment by ruromero** [comment]
Does it have any side effect? Why isn't enabled by default?

**Comment by jamesnetherton** [comment]
Seems there was a concern that enabling the behaviour by default could effectively be a breaking change:

https://github.com/quarkusio/quarkus/issues/15185#issuecomment-788895884

**Comment by ruromero** [comment]
Very interesting, thanks @jamesnetherton 
Do you want to keep the issue open until you add that note to the docs? Otherwise we can close it.

**Comment by jamesnetherton** [comment]
Lets keep it open and I'll add some docs. Thanks for reporting the problem :+1:

**Comment by ruromero** [comment]
Adding here for reference that I was using camel-quarkus 1.8.1 that depends on Vert.x 3.x
The solution provided by @jamesnetherton refers to 2.0.x depending on Vert.x 4.x
Therefore the `extended-pattern` property is not valid for camel-quarkus 1.8.1
