### ISSUE TITLE
Split with AggregationStrategy

### ISSUE THREAD

**Issue by chengkuangan** [apache/camel-quarkus#2690]
How to use AggregationStrategy for Split? 
It seems org.apache.camel.processor.aggregate.AggregationStrategy is not in the core or any other maven repo for quarkus

**Comment by ppalaga** [comment]
`org.apache.camel.processor.aggregate.AggregationStrategy` is in `org.apache.camel:camel-core-processor` that in turn is transitively available via `org.apache.camel.quarkus:camel-quarkus-core`. Does that answer your question?

**Comment by chengkuangan** [comment]
@ppalaga Thank you so much
