### ISSUE TITLE
demonstrate how to configure quarkus-jackson extension's own ObjectMapper instance and reuse it in our jackson test

### ISSUE THREAD

**Issue by ffang** [apache/camel-quarkus#2706]
quarkus-jackson extension produces it's own ObjectMapper instance which can be configured by  CDI beans of ObjectMapperCustomizer type.  We better demonstrate this usage in our integration-test

**Comment by ppalaga** [comment]
Fixed via da360444233e3692de5aa3c876320b2b16bf48cb
