### ISSUE TITLE
Test both camel and quarkus configuration of underlying component quarkus client

### ISSUE THREAD

**Issue by llowinge** [apache/camel-quarkus#2712]
I can see eg. infinispan https://github.com/apache/camel-quarkus/blob/main/integration-tests/infinispan/src/test/java/org/apache/camel/quarkus/component/infinispan/InfinispanServerTestResource.java#L54-L61 is being tested only with quarkus configuration. But we should test camel as well (for Camel K purpose).

**Comment by llowinge** [comment]
Elastic-search can be another component for consideration https://github.com/apache/camel-quarkus/blob/1.8.1/integration-tests/elasticsearch-rest/src/test/java/org/apache/camel/quarkus/component/elasticsearch/rest/it/ElasticSearchTestResource.java#L52

**Comment by ppalaga** [comment]
@llowinge could you please create separate issues each component?

**Comment by llowinge** [comment]
@ppalaga Yes, i will do.

**Comment by llowinge** [comment]
infinispan https://github.com/apache/camel-quarkus/issues/2713

**Comment by llowinge** [comment]
elastic-search https://github.com/apache/camel-quarkus/issues/2714
