### ISSUE TITLE
Add missing use cases into MongoDb test coverage

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#2715]
Follows https://github.com/apache/camel-quarkus/issues/2622.

- DocumentList outputType is not tested.
- Configuring via `application.properties` is not tested .
- Mongo version is hardcoded for 4.0, it would be better to use the latest one, which is 4.4

**Comment by jamesnetherton** [comment]
> * Configuring via `application.properties` is not tested .

Do we really need that? `MongoDbTestResource` sets the configuration properties for the application under test, which should be good enough.

**Comment by JiriOndrusek** [comment]
I'd like to add another client using property `quarkus.mongodb.<name>.connection-string` because it is described in doc. Current test is using `quarkus.mongodb.<name>.hosts`. May be I should modify formulation of this issue, to be clear.
