### ISSUE TITLE
Fix JSON Jackson jacksonConversionPojo test

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2726]
Seem comment here:

https://github.com/apache/camel-quarkus/blob/f65f3b92610cdc577403fde5fbaf846ae7a58965/integration-tests/dataformats-json/src/main/java/org/apache/camel/quarkus/component/dataformats/jackson/json/JacksonJsonResource.java#L515-L520

**Comment by ffang** [comment]
Hi @jamesnetherton,

FYI, I believe this has been fixed by https://github.com/apache/camel-quarkus/issues/2677 already.
Sorry, I forget to re-enable this test. I will send a PR to re-enable this test soon.

Best Regards
Freeman

**Comment by ppalaga** [comment]
Any update, @ffang ?
