### ISSUE TITLE
Use EmbeddedActiveMQ in messaging and jta integration tests 

### ISSUE THREAD

**Issue by zhfeng** [apache/camel-quarkus#2727]
Since we're using an out-of-date & deprecated image, we should use the EmbeddedActiveMQ in ActiveMQTestResource and could inherit artemis-server from the quarkus-bom and that way we don't have to worry about additional maintenance on our side.

**Comment by zhfeng** [comment]
The quarkus bom does not include ```org.apache.activemq:artemis-mqtt-protocol```, so I just raise https://github.com/quarkusio/quarkus/issues/17720 to add it. All the tests should be OK.

**Comment by ppalaga** [comment]
https://github.com/quarkusio/quarkus/pull/17721 was merged.

**Comment by zhfeng** [comment]
Great - and is it possible to take these changes to ```quakrus-main``` branch first to see if it works ? But I find the "Daily Build Quarkus main" is still failing.

**Comment by ppalaga** [comment]
> Great - and is it possible to take these changes to `quakrus-main` branch first to see if it works ? 

Yes, please feel free to send a pull request against quarkus-main

> But I find the "Daily Build Quarkus main" is still failing.

Sorry about that, it is was my fault. I have fixed the branch now.

**Comment by ppalaga** [comment]
https://github.com/apache/camel-quarkus/pull/2751 was cherry-picked to `quarkus-main`
