### ISSUE TITLE
Add Kamelet example

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#2731]
We should add this as a quarkus example
https://github.com/apache/camel-spring-boot-examples/tree/main/kamelet-chucknorris

We have this chuck norris example on other runtimes such as standalone, osgi, spring boot, and we need to have this for quarkus also at
https://github.com/apache/camel-quarkus-examples

**Comment by zhfeng** [comment]
I'd like to take a look and please assign it to me.

**Comment by zhfeng** [comment]
https://github.com/apache/camel-quarkus-examples/pull/42

**Comment by aldettinger** [comment]
Many thanks @zhfeng :+1:  the build is ok. It might be safe to delete the PR branch now.
I'm going to close the ticket as I think everything is complete, feel free to re-open in case of miss.
