### ISSUE TITLE
Native support for kamelet.yaml discovery

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2733]
See discovery section in the Kamelet component docs:

https://camel.apache.org/components/latest/kamelet-component.html#_discovery

It should be possible to discover any `.kamelet.yaml` files and add them to the native image.

**Comment by lburgazzoli** [comment]
There is also this PR https://github.com/apache/camel-quarkus/pull/2549 to pre-laod some kamelets
AFAIK @valdar should be working to adapt it tot he latest changes.

**Comment by valdar** [comment]
Yep 👍
