### ISSUE TITLE
Resume release command needs to be performed from target/checkout directory

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2736]
We should mention in our release guide https://camel.apache.org/camel-quarkus/latest/contributor-guide/release-guide.html#_releaseprepare_and_releaseperform that that resume command needs to be run from `target/checkout`

**Comment by ppalaga** [comment]
Credits: @valdar

**Comment by valdar** [comment]
I am very sorry about committing without opening a PR, it was a genuine miss click.
Feel free to revert it.

**Comment by ppalaga** [comment]
Thanks for fixing, no problem at all in this case.
