### ISSUE TITLE
Avoid duplicating code in `org.apache.camel.quarkus.core.BaseModel`

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2752]
The overhead of maintaining `BaseModel` is such that we often miss critical changes in Camel that need to be sync'd back to our implementation.

We should try to find a solution to avoid having to duplicate and sync code from Camel.

**Comment by lburgazzoli** [comment]
Same may apply to the FastCamelContext

**Comment by jamesnetherton** [comment]
I don't see anything in `org.apache.camel.quarkus.core.BaseModel` that is special or optimized for camel-quarkus so we could make `FastModel` extend `DefaultModel` and if we ever need to do customizations, then we do them in `FastModel`.

How should we handle `FastCamelContext`? Extend `DefaultCamelContext` and keep our CQ specific overrides? Or is there a better way?

**Comment by lburgazzoli** [comment]
> I don't see anything in `org.apache.camel.quarkus.core.BaseModel` that is special or optimized for camel-quarkus so we could make `FastModel` extend `DefaultModel` and if we ever need to do customizations, then we do them in `FastModel`.
> 

Maybe we can just remove FastModel/BaseModel and we can introduce it only if when it is needed ?

> How should we handle `FastCamelContext`? Extend `DefaultCamelContext` and keep our CQ specific overrides? Or is there a better way?

I think that would be fine as far as I remember, most of the time it is about to provide specif implementation or some service/factory-finders. If we'll find out that we need some specific hooks, we may think to enhance the *CamelContext in Camel so we don't need copy and paste nay more.

**Comment by jamesnetherton** [comment]
> Maybe we can just remove FastModel/BaseModel and we can introduce it only if when it is needed ?

Yes, makes sense.

> I think that would be fine as far as I remember, most of the time it is about to provide specif implementation or some service/factory-finders.

Thanks - I'll investigate further.
