### ISSUE TITLE
Add OpenTracing extension

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#276]
Since we now have support for health & metrics, it'd be nice to expand this to include tracing.

Unlike the health and metrics extensions, I don't see any specific need to create a dedicated MicroProfile tracing component over at the main Camel project.

I was thinking that we could leverage the Quarkus SmallRye Tracing extension and reuse the `Tracer` instance that it creates to automatically setup a Camel `OpenTracingTracer` provided by `camel-opentracing`.

After a little hacking, it was easy enough to get spans generated by a simple timer based route to show up in the web UI.

![tracing](https://user-images.githubusercontent.com/4721408/66834082-eaf92a80-ef54-11e9-97b3-a719bb36a659.png)

If this is an acceptable way forwards, I can continue to work on it.

**Comment by lburgazzoli** [comment]
+1

**Comment by ppalaga** [comment]
+1
