### ISSUE TITLE
camel.main.dump-routes = true does not work

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#2761]
In Camel 3.10 you can configure Camel to dump the routes on startup. 

This requires this dependency

        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-xml-jaxb</artifactId>
        </dependency>

But when running with camel quarkus this does not work. A vanilla Camel started via camel:run works fine for the same example.

**Comment by jamesnetherton** [comment]
`FastCamelContext` does not override and implement the empty default method for `doDumpRoutes` from `AbstractCamelContext` so we'll need to fix that.

**Comment by jamesnetherton** [comment]
This can eventually be fixed by the work done for https://github.com/apache/camel-quarkus/issues/2752.

Something I noticed about `JaxbHelper` is that it does this:

https://github.com/apache/camel/blob/02e553d77ff0b4dcbb9e674feddb8dcabf4e463e/core/camel-xml-jaxb/src/main/java/org/apache/camel/xml/jaxb/JaxbHelper.java#L108

Meaning `XmlConverter` is instantiated reflectively. Can we avoid that?

**Comment by davsclaus** [comment]
I created a general ticket to look at if we can source code generate non reflective FactoryFinder in camel core itself then we get this out of the box
https://issues.apache.org/jira/browse/CAMEL-16706

**Comment by davsclaus** [comment]
Oh I also think we can just make the xml. converter created via new XmlConverter as the camel context does not give anything additional in this use case and camel-xml-jaxb uses camel-xml-jaxp so the JAR dependencies are always requires and we can then use good old regular Java with new constructor.

However the FactoryFinder in general could benefit from being non-reflection

**Comment by davsclaus** [comment]
Okay its fixed for 3.11 to be non reflection for that xml converter

**Comment by jamesnetherton** [comment]
BTW on camel-quarkus you also need to add `camel-quarkus-xml-jaxp` to get route dumping to work.
