### ISSUE TITLE
Apple M1 cannot build the camel-quarkus project

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#2762]
Its due to the grpc extension does not have mac aarch64 binary, so you need to disable this, we do this at the camel-grpc component
https://github.com/apache/camel/blob/main/components/camel-grpc/pom.xml#L164

**Comment by jamesnetherton** [comment]
Opened an enhancement request to see if aarch64 could be supported https://github.com/quarkusio/quarkus/issues/17886.

**Comment by jamesnetherton** [comment]
This was fixed in https://github.com/apache/camel-quarkus/commit/cb05578bdb99db11b90a8b55eaadb64f062676d0.
