### ISSUE TITLE
add affinity dependency in a mac profile for camel-hazelcast extension

### ISSUE THREAD

**Issue by ffang** [apache/camel-quarkus#2800]
so that we can build native image on mac as well when using camel-hazelcast extension

**Comment by ffang** [comment]
Close this issue as this is fixed at quarkus-hazelcast-client side(version 2.0.0)
https://github.com/hazelcast/quarkus-hazelcast-client/issues/189
and now we synced up to that version

**Comment by essobedo** [comment]
A fix to remove the maven profile https://github.com/apache/camel-quarkus/pull/5025
