### ISSUE TITLE
Missing versions/dependancies in rest json example

### ISSUE THREAD

**Issue by basis42** [apache/camel-quarkus#281]
Hi all,

as a total newbee to quarkus I'm trying to follow the route described here: 
https://camel.apache.org/camel-quarkus/latest/user-guide.html

Unfortunately, I'm running into problems at a relatively early stage. When I change the parent in the pom of the rest json example(as proposed in the above documentation) to:
```
<parent>
        <groupId>org.apache.camel.quarkus</groupId>
        <artifactId>camel-quarkus-bom</artifactId>
        <version>0.2.0</version>
</parent>
```

the below dependancies can't be resolved:
```
        <dependency>
            <groupId>org.apache.camel.quarkus</groupId>
            <artifactId>camel-quarkus-platform-http</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-jackson</artifactId>
        </dependency>
```
Looking into the bom artifact for version 0.2.0 both versions are missing, in fact they came in later ... I also tried to leave the version for the bom artifact untouched(0.2.1-SNAPSHOT) and compile/install a clean checkout of the latest master branch. Unfortunately I get 2 failing tests:

```
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <404>.
	at org.acme.rest.json.RestJsonTest.fruits(RestJsonTest.java:39)
[ERROR] legumes  Time elapsed: 0.013 s  <<< FAILURE!
legumes  Time elapsed: 0.013 s  <<< FAILURE!

java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <404>.
	at org.acme.rest.json.RestJsonTest.legumes(RestJsonTest.java:66)
2019-10-17 13:05:09,471 INFO  [io.quarkus] (main) Quarkus stopped in 0.041s

```
Any hints how I get the example working?

**Comment by ppalaga** [comment]
Thanks for the report, @basis42 !

Sorry for that, the docs on https://camel.apache.org updates with the master, while it is written for a release that does not exist yet. 

If you do not mind using SNAPSHOTs in your work, you may do the following:

```
cd camel-quarkus
git reset --hard upstream/master # where upstream is github.com/apache/camel-quarkus
mvn clean install -DskipTests
```

and proceed with the steps in the guide using the current master SNAPSHOT version instead of 0.2.0 where the `platform-http` component is not available yet.

**Comment by basis42** [comment]
I'm just fiddling around, so I absolutly can go with a snapshot. Thanks, with skipping the tests on the snapshot it works like a charm!

**Comment by shoaibjdev** [comment]
Hi,
Seems there is still some mismatch with BOM and dependencies.
Getting error:

`Could not find artifact org.apache.camel.quarkus:camel-quarkus-bom:pom:0.3.1-SNAPSHOT`

**Comment by ppalaga** [comment]
@shoaibjdev this issue has been closed. If your problem persists, please file a new issue with proper steps to reproduce. The bottom line is that Camel Quarkus 0.3.0 should be released these days (will be announced via https://twitter.com/ApacheCamel and dev@camel.apache.org ) and using SNAPSHOT will thus not be necessary anymore.
