### ISSUE TITLE
onException in xml dsl

### ISSUE THREAD

**Issue by jstakun** [apache/camel-quarkus#2842]
Hi Quarkus experts!
I'm porting existing xml dsl camel logic into camel quarkus, and I couldn't find the way to reuse onException clause which was present in my camel context definition in the xml dsl. I only found possibility to create onException java code in RouteBuilder class but this doesn't seem to be right solution for me. Can you advice how can I implement it having routes definition is xml dsl?

**Comment by davsclaus** [comment]
This is an issue tracker for bugs, new features etc.

For getting help with how to use Camel then see here
https://camel.apache.org/community/support/

A great place to get help is the chat room
https://camel.zulipchat.com/

Ask in the camel-quarkus stream
