### ISSUE TITLE
Document the need of @RegisterForReflection in Bean doc

### ISSUE THREAD

**Issue by llowinge** [apache/camel-quarkus#2844]
When using CDI bean used in camel-bean component, we need for native mode the annotation @RegisterForReflection which is not documented (see eg. https://github.com/apache/camel-quarkus/blob/main/integration-test-groups/foundation/bean/src/main/java/org/apache/camel/quarkus/component/bean/NamedBean.java#L31).

**Comment by jamesnetherton** [comment]
Seems we have this covered already. The usage section of the bean docs link to the CDI guide, which mentions native requirements.

https://camel.apache.org/camel-quarkus/latest/reference/extensions/bean.html#_usage
