### ISSUE TITLE
Give some guidance to end users which messaging extensions they should use in which situation

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2856]
Statement by @jamesnetherton 

> Ideally, we'd use these extensions based on the broker / protocol:
> 
> For AMQ - camel-quarkus-activemq
> For AMQP - camel-quarkus-amqp
> For Artemis - camel-quarkus-jms + quarkus-artemis
> For everything else - camel-quarkus-jms + some vendor specific JMS client libraries

The first two points are rather trivial and I guess end users will be able to discover those extensions by themselves. The second two points contain some interesting information that could perhaps go to the [JMS extension page](https://camel.apache.org/camel-quarkus/latest/reference/extensions/jms.html). WDYT, @jamesnetherton?

**Comment by jamesnetherton** [comment]
Yes, we can add some more docs on this. Perhaps create a dedicated 'messaging' page and link to it from the JMS / SJMS extension docs.
