### ISSUE TITLE
Make `quarkus.artemis.url` optional

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2857]
Filed here so that we do not forget about https://github.com/quarkusio/quarkus/issues/18231 and possibly take the initiative to fix it. After it is fixed in Quarkus, we should add a test (a io.quarkus.test.QuarkusUnitTest-based one should be enough) for an app configuring its custom ConnectionFactory without providing quarkus.artemis.url

**Comment by zhfeng** [comment]
I just move the upstrem quarkus issue to https://github.com/quarkiverse/quarkus-artemis/issues/36
