### ISSUE TITLE
Combine build sanity checks into a single script

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2869]
Since https://github.com/apache/camel-quarkus/pull/2866, I was thinking that to keep the build nice and speedy, we should perhaps avoid having an ever increasing number of 'sanity check' Groovy scripts and `groovy-maven-plugin` executions. So we could combine the checks into a single script.

E.g [this](https://github.com/apache/camel-quarkus/blob/main/tooling/scripts/validate-dependencies.groovy) & [this](https://github.com/apache/camel-quarkus/blob/main/tooling/scripts/validate-jvm-native-since.groovy).

**Comment by zhfeng** [comment]
I will check them.
