### ISSUE TITLE
Think about consolidating enforcing rules

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#293]
As we now have some tooling already in place we should think about consolidating enforcer scripts in a dedicate mojo or enforcer rule

**Comment by gnodet** [comment]
What about having the camel-quarkus plugin extends the camel `package-maven-plugin` ? That would remove the duplication of the model / helpers code.

On the enforcer rules, which rules are you talking about ? Code formatting and such ? The `buildingtools` stuff in `camel` ?

**Comment by oscerd** [comment]
I think it would makes sense to extend the package-maven-plugin from Camel.

For the enforcing, yeah, I think we are talking about formatting. I think it's not crucial, but if it creates problems when we find some warnings about formatting we can also think about autoformatting the code.

On Camel we avoid this.

**Comment by lburgazzoli** [comment]
About enforcing rules I was thinking about the groovy scripts we now have to enforce

- the presence of some content in the extension metadata
- the fact that dependencies declaration should not include the artifact version

As we are using maven and we already have a maven plugin I think it could make sense to consolidate such features in a plugin

**Comment by oscerd** [comment]
You weren't clear :-D

**Comment by lburgazzoli** [comment]
As usual :)

**Comment by gnodet** [comment]
Raised #336 and #337

**Comment by ppalaga** [comment]
> As we are using maven and we already have a maven plugin I think it could make sense to consolidate such features in a plugin

Could you please name some benefits, that would eventually outweight the longer build times, a bit more code to maintain and the migration effort?

I am not against Maven plugins in general, I like writing them and I actively maintain some. I just fail to see the benefits of this pattern of having a plugin inside the repo that is used only inside the same repo given that there are cheaper alternatives such as ad hoc groovy, ant, or hosting the plugin/enforcer rules elsewhere.

**Comment by oscerd** [comment]
What are the advantage of an ad hoc groovy instead?

**Comment by ppalaga** [comment]
> What are the advantages of an ad hoc groovy instead?

* Less code (no extra maven module), less dependencies
* Faster build times (no need to clean, compile, package, install, ... the jar)
* Groovy is more flexible for some tasks, such as json and XML processing

**Comment by oscerd** [comment]
I still believe, since we use maven, a maven plugin is the correct solution.

**Comment by oscerd** [comment]
I mean, to me an ad-hoc groovy is an hacky solution in this context. I vote for the maven plugin for this.

**Comment by lburgazzoli** [comment]
The scripts are good for quick fix but as long term solution a plugin feels more appropriate.

One of the problem I had with scripts in the past was that some scripts were applied according to the name of the artifact or based of a presence of a file and that logic is embedded into the script instead of being declarative through XML and I spent quite a few time finding out the reason of my build not doing what I was supposed.

If groovy is a better tool for some tasks, I think there's no problem to write maven plugins or part of them with groovy.

**Comment by ppalaga** [comment]
> One of the problem I had with scripts in the past was that some scripts were applied according to the name of the artifact or based of a presence of a file and that logic is embedded into the script instead of being declarative through XML and I spent quite a few time finding out the reason of my build not doing what I was supposed.

Thanks for explaining why you believe that the plugin solution is better.

I think the property of being poorly written is not inherent to groovy scripts. It is rather a mistake of some particular author (maybe me). I dare to say that the same kind of mistake can happen when writing a plugin.

I see that there is a clear majority for migrating the checks to plugin mojos and I am not going to force my view. Still, it would be nice to see the benefits. 

Yes, this is Maven and the most common way to perform tasks is to write plugins. Does that mean that we need a plugin for every single task? You seem to affirm, I do not. Having ad hoc groovy scripts is OK. They are easier to write and maintain, they are faster to run compared to a self-hosted plugin. That's it. Thanks for hearing me :-).

**Comment by oscerd** [comment]
A groovy script in a maven project for doing what a plugin can already do is just forced.. it seems to me this is just a matter of taste..

**Comment by lburgazzoli** [comment]
guess we can close this one at this stage
