### ISSUE TITLE
java script: automatically add --language:js among additional build args

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#2964]
The camel-quarkus-js-dsl extension should automatically set

    quarkus.native.additional-build-args=--language:js

**Comment by jamesnetherton** [comment]
@lburgazzoli Do we still need this? This is now further complicated by the fact that from GraalVM 2.22.0, JS support is not included by default. It's an addon that needs to be installed via the `gu` tool.

**Comment by lburgazzoli** [comment]
I think it would be enough to document it. 
Also, maybe it should be a JVM only extension ?

**Comment by jamesnetherton** [comment]
JS-DSL will be marked as deprecated in Camel 4.6.0 / CQ 3.11.0. So there's not much value in investing time here IMO.
