### ISSUE TITLE
Add observability example

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#297]
Thought it'd be good to add a little example project to demonstrate Camel Quarkus observability extensions:

* MicroProfile Health
* MicroProfile Metrics
* OpenTracing

**Comment by davsclaus** [comment]
James are you by any chance able to do this example this week, before thursday. I am going to give a Camel talk and would like to demo something like this

**Comment by jamesnetherton** [comment]
I'll try - I'm planning to make it similar to the existing Camel OpenTracing example with simple client / server apps. That should be enough to demo a realistic looking example of tracing.

**Comment by davsclaus** [comment]
Thanks, and if there are instructions how to use it, together with visual tools like jaeger then that is a great bonus
