### ISSUE TITLE
Platform HTTP component under load won't serve health endpoints anymore

### ISSUE THREAD

**Issue by tstuber** [apache/camel-quarkus#2974]
We are stress-testing a camel container that exposes a HTTP endpoint via platform HTTP. The container calls some legacy backend services - a single process might take some seconds.
However, if we invoke a lot of request (>500), than the container is not anymore able to serve the liveness probe on OpenShift and will be killed. 

Potential workarounds:
- Changing liveness probe to run some bash script (but we would like to use the camel-health endpoint)
- Expose the API with Netty on a separate endpoint. This works fine, but this is somehow not that nice.

**Comment by tstuber** [comment]
See also [this](https://camel.zulipchat.com/#narrow/stream/257302-camel-quarkus/topic/Platform.20HTTP.20component.20under.20load) discussion on Camel zulip chat.

**Comment by jamesnetherton** [comment]
A dedicated management interface (running on its own server / port) is coming in the next Quarkus release.
