### ISSUE TITLE
Aws2-ddb: Document usage of quarkus-amazon-dynamodb for client creation (and limitations)

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#2989]
See item 3 (and 2) from this [PR](https://github.com/apache/camel-quarkus/pull/2988) for more details.

Shortly: `quarkus-amazon-dynamodb` can be used with aws2-ddb extension, but there is a limitation on the type of http client (only apache one works). See https://quarkus.io/guides/amazon-dynamodb#configuring-dynamodb-clients.

**Comment by ppalaga** [comment]
The usage of Quarkus client is documented now: https://camel.apache.org/camel-quarkus/next/reference/extensions/aws2-ddb.html#_optional_integration_with_quarkus_amazon_dynamodb

The batch consumer paragraph was removed from Camel docs while it does not work https://github.com/apache/camel/commit/2fa2758fd921550157616cc821897498a5d530e2

Hence this issue can be closed.
