### ISSUE TITLE
Use Camel's async processor in platform-http

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#299]
We currently always add our handler as non-blocking https://github.com/apache/camel-quarkus/blob/master/extensions/platform-http/runtime/src/main/java/org/apache/camel/quarkus/component/platform/http/runtime/QuarkusPlatformHttpConsumer.java#L95-L108

Shouldn't we have an URI parameter for the user to decide whether `io.vertx.ext.web.Route.blockingHandler()` should be called instead of `io.vertx.ext.web.Route.handler()`?

**Comment by lburgazzoli** [comment]
Maybe we need to use camel's async processor and always use the non blocking one, something like: https://github.com/apache/camel-k-runtime/blob/master/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpConsumer.java#L85-L137

**Comment by ppalaga** [comment]
Plz assign to me.
