### ISSUE TITLE
Live reload of Kotlin routes does not work

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3010]
Start a Kotlin based app in dev mode, tweak the route source and no hot reload happens. The app continues to run unmodified.

It seems to be working on a simple non-camel Kotlin JAX-RS app, and it also works when modifying `application.properties`. Not sure why reloads do not trigger for the Camel bits.

**Comment by languitar** [comment]
For me hot reload starts in this case and remains in an endless loop. This makes the dev mode completely unusable then.
