### ISSUE TITLE
JdbcAggregationRepository build error by spring JtaTransactionManager 

### ISSUE THREAD

**Issue by neoxu999** [apache/camel-quarkus#3054]
JdbcAggregationRepository requires  org.springframework.transaction.jta.JtaTransactionManager;

The spring requires spring-text. So when build the app, it will show an error
 Caused by: java.lang.NoClassDefFoundError: org/springframework/jndi/JndiTemplate
 
```
 JdbcAggregationRepository aggregationRepository = new JdbcAggregationRepository(
                new JtaTransactionManager(userTransaction, tm), "aggregation", dataSource);
                
                
.aggregate(constant(true),new MyAggregationStrategy()).completionSize(5).aggregationRepository(aggregationRepository)
```

**Comment by zhfeng** [comment]
This error is happening in native building ? I think we have a integration test with JdbcAggregationRepository and please check it with https://github.com/apache/camel-quarkus/blob/main/integration-tests/sql/src/main/java/org/apache/camel/quarkus/component/sql/it/SqlRoutes.java

Also you should depend on ```camel-quarkus-sql``` and ```camel-quarkus-jta```.

**Comment by ppalaga** [comment]
@neoxu999 I am missing the reproducer. One option would be to modify the integration test in https://github.com/apache/camel-quarkus/blob/main/integration-tests/sql so that it fails due to your issue. Alternatively, you could attach a self-contained reproducer - a ZIP file with a Maven project or a a git repository URL containing a reproducer project.

**Comment by neoxu999** [comment]
Hi @zhfeng , I tried native and JVM. Both didn't work with JdbcAggregationRepository

By the way, there is another issue with native "mvn clean package -Dnative"
No instances of java.net.SocksSocketImpl are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.SocksSocketImpl.

It complains the class SocksSocketImpl. I looks like related to camel-quarkus-jta. For this kind build issue, do you have any suggestion please?

**Comment by neoxu999** [comment]
Hi @ppalaga , thanks for the suggestion. I will download the source code and try it.

**Comment by zhfeng** [comment]
Thanks @neoxu999 and it seems that you open a socket for listening at the build time which is not allowed in the native mode. Anyway, as @ppalaga mentioned, it would be very helpful for providing a reproducer for us. We can take a further look at the issue.

**Comment by neoxu999** [comment]
problem fixed by latest version. Thanks, @zhfeng , @ppalaga .

**Comment by ppalaga** [comment]
You are welcome and thanks for reporting anyway!
