### ISSUE TITLE
Create a SQL / JDBC example project

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3056]
Seems that configuration for `DataSource` and general usage of it with `camel-quarkus-jdbc` & `camel-quarkus-sql` is a frequent source of confusion. So it'd be nice to go beyond pointing folks at integration tests and have a dedicated example that shows how to use the default `DataSource`, use a named `DataSource` etc.

**Comment by vkasala** [comment]
@jamesnetherton Do you have any reuqirements for such an example?
 * Configure DataSource via Quarkus Datasource
 * on OpenShift environment, use the Service Binding?

**Comment by jamesnetherton** [comment]
My initial thought was to keep it simple and just demo having the `DataSource` configured via the Quarkus config properties.

But I guess it could / should be extended to support having the config driven from the service binding bits.

**Comment by zbendhiba** [comment]
Maybe have a separate one for service binding. As the README gets confusing with different use cases ?

**Comment by Delawen** [comment]
I can add them.

**Comment by Delawen** [comment]
Is this what you were looking for?
