### ISSUE TITLE
Allow disabling periodic scan functionality

### ISSUE THREAD

**Issue by Root-2k** [apache/camel-quarkus#3078]
Hello,

please provide a possibility to disable the timer, which periodically scans the file system for changes.

See _CamelHotReplacementSetup_ (_org.apache.camel.quarkus.core.devmode_)

The dev mode should behave like for a "plain" Quarkus project. When accessing a resource, the modifications should be applied. When this happens automatically/periodically, the server runs into problems when executing Maven goals (e.g. clean install).
A periodic update/scan does not make sense in our case (or possibly in general) and should therefore be configurable.

At the moment we have to remove all the Camel functionality because of this timer.

**Comment by ppalaga** [comment]
@gnodet what was the original idea behind scanning periodically? I guess we could scan when a message passes any route, similar like they do with Kafka https://github.com/quarkusio/quarkus/blob/main/extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/devmode/KafkaStreamsHotReplacementSetup.java

**Comment by lburgazzoli** [comment]
As far as I recall, at that time the hot replacement stuffs were not so advanced, thus the timer was the most suitable solution.

btw: shouldn't the HotReplacementSetup be invoked only when using the dev mode ?

**Comment by ppalaga** [comment]
> When this happens automatically/periodically, the server runs into problems when executing Maven goals (e.g. clean install).

I also wonder what do you mean by this. The periodic scan should happen only when in dev mode, e.g invoked by `mvn quarkus:dev`. You mean other Maven invocations issued in parallel against the same source tree cause your problems?

**Comment by Root-2k** [comment]
We have a [multi-module](https://quarkus.io/guides/maven-tooling#multi-module-maven) Maven project where the server-project is running in dev-mode. When we execute for example a _mvn clean install_ on a referenced module (dependency), we run into different problems - depending on the timing of the reload. We execute the Maven commands, because for example we execute annotation processors using Maven.

Without the Camel dependency or when overriding the mentioned code, we can execute our Maven goals and get the result for example when refreshing the web-app - so in a manual executed step.

**Comment by ppalaga** [comment]
Thanks for the explanation @Root-2k, it is much cleaner to me now. Yes, let's try to implement triggering a scan when a message passes any route.

**Comment by timonzi** [comment]
The scan is already triggered by Quarkus when I access a resource (e.g. the frontend). So beside of the possibility to disable the **periodic** scan, no change is needed in my opinion.

**Comment by jamesnetherton** [comment]
> At the moment we have to remove all the Camel functionality

Since Quarkus 2.x you can toggle live reloads by pressing `l`, and if you need to, force a restart with `s`. That's one way that would enable you to keep the Camel functionality.

> implement triggering a scan when a message passes any route

The problem with that for some scenarios is that you have to send messages to 'stale' endpoints to trigger the reload. E.g if I start with `from("file:/foo")` and update it to `from("file:/bar")`, I'd have to drop a file into `/foo` for the reload to trigger.

**Comment by timonzi** [comment]
> Since Quarkus 2.x you can toggle live reloads by pressing l, and if you need to, force a restart with s.
As I don't want to toggle every time the live reload in order to prevent errors or (partly) endless loops, I would prefer to have the option to disable the scan using an application property. If I need to reload the sources with a disabled period scan functionality, I can use the option to restart if needed.

**Comment by lburgazzoli** [comment]
IMHOI, providing some option to configure the live reload behavior would be a good think but I think here what we are looking for is probably [quarkus:run](https://github.com/quarkusio/quarkus/issues/9315) rather than quarkus:dev

**Comment by jamesnetherton** [comment]
`quarkus:run` was added in Quarkus 3.2.0.
