### ISSUE TITLE
Improve native support for `org.apache.http.impl.client.BasicAuthCache`

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3079]
`BasicAuthCache` attempts to do object serialization, so we need to handle that.

https://github.com/apache/httpcomponents-client/blob/rel/v4.5.13/httpclient/src/main/java/org/apache/http/impl/client/BasicAuthCache.java#L97-L146

Usage of the class is mentioned in the camel-http docs, so we should try to get it working properly in native mode.

**Comment by aldettinger** [comment]
In couchdb, we ended up doing a substitution:
https://github.com/apache/camel-quarkus/blob/main/extensions/couchdb/runtime/src/main/java/org/apache/camel/quarkus/couchdb/BasicAuthCacheAlias.java

Whatever the fix is, it's worth considering aligning solution.

**Comment by aldettinger** [comment]
There is also a comment in httpclient jira stating that serialization is [not a hard requirement for BasicAuthCache](https://issues.apache.org/jira/browse/HTTPCLIENT-2070?jql=project%20%3D%20%22HttpComponents%20HttpClient%22%20and%20reporter%20%3D%20aldettinger).

**Comment by jamesnetherton** [comment]
> In couchdb, we ended up doing a substitution:

Then that fix probably belongs in `camel-quarkus-support-httpclient`.

**Comment by aldettinger** [comment]
Indeed, and maybe it's just a matter of configuring the serialization of AuthSchemes now that camel-quarkus supports serialization.

**Comment by ppalaga** [comment]
I wonder why this has not been popping up in our HttpTest.basicAuth() test?

**Comment by aldettinger** [comment]
I was thinking maybe it's used only for preemptive auth but was not able to prove it with a test.

**Comment by jamesnetherton** [comment]
> I wonder why this has not been popping up in our HttpTest.basicAuth() test?

Because we don't explicity configure the `BasicAuthCache` in the tests and I guess the Camel component does not do so either.
