### ISSUE TITLE
Move infinispan integration-tests out of core

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#31]

**Comment by ppalaga** [comment]
I clearly see the benefit of testing separately and having a separate project for each component that can serve as a basic quickstart. 

OTOH, each separate integration test module will prolong the build by ~2 minutes. Do we really want that? My personal limit for CI is ~40mins. Now we are at ~28mins, IIRC. So we can basically do this, but maybe for the future, we should think of some sort of policy that would keep the CI run times reasonable. Testing several extensions in one IT module is actually one possible solution, so once again the question, is it really worth splitting now?

**Comment by oscerd** [comment]
I think a reasonable time for CI can be more than 40 minutes.

**Comment by ppalaga** [comment]
> I think a reasonable time for CI can be more than 40 minutes.

I wonder what is your upper bound for a CI job that verifies pull requests?

**Comment by oscerd** [comment]
it depends on the dimension of a project: in camel we cannot do a full build because it's too much stuff for a single PR. I think up to 90 minutes is reasonable.

**Comment by lburgazzoli** [comment]
> I clearly see the benefit of testing separately and having a separate project for each component that can serve as a basic quickstart.
> 
> OTOH, each separate integration test module will prolong the build by ~2 minutes. Do we really want that? My personal limit for CI is ~40mins. Now we are at ~28mins, IIRC. So we can basically do this, but maybe for the future, we should think of some sort of policy that would keep the CI run times reasonable. Testing several extensions in one IT module is actually one possible solution, so once again the question, is it really worth splitting now?

There's no rush to move them out of core *now* but we should provide more tests for every extensions to aver better coverage for native compiled code (as today the tests we have for nett4-http and infinispan are the bare minimum).

BTW, nothing is written in stones and we can always rethink our decisions and group modules when it make sense but IMHO, testing component extension inside the core one is just bad.

**Comment by ppalaga** [comment]
Yes, there is no doubt that more coverage is better.
