### ISSUE TITLE
Docs xref check failures

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3109]
Lots of xref check failures, probably due to things being reorganised on the Camel side.

To reproduce:

```
cd docs
mvn clean verify
```

**Comment by djencks** [comment]
The xref checker doesn’t support the symlinks we’re using now, so it can’t find any content.  I’ll look into upgrading this build to Antora 3.

Are there other sub-project partial doc builds that are likely to have the same problem?

Is this the cause of the recent “failed quarkus build” emails I’ve been seeing?

David Jencks

**Comment by jamesnetherton** [comment]
> Is this the cause of the recent “failed quarkus build” emails I’ve been seeing?

Yes, most likely. We run the xref checks on the CI build.

**Comment by jamesnetherton** [comment]
This appears to be failing again.

https://github.com/apache/camel-quarkus/pull/3118/checks?check_run_id=3650176002

**Comment by djencks** [comment]
Well, this was a completely different problem, but https://github.com/apache/camel-quarkus/pull/3119 seems to fix it for me.
