### ISSUE TITLE
Google-Storage Extension: Cannot set serviceAccountKey because of Quarkiverse extension

### ISSUE THREAD

**Issue by oscerd** [apache/camel-quarkus#3131]
I think this part of the quarkiverse extension

https://github.com/quarkiverse/quarkus-google-cloud-services/blob/main/storage/runtime/src/main/java/io/quarkiverse/googlecloudservices/storage/runtime/StorageProducer.java#L35

In this way we cannot use different configuration coming from:

https://github.com/apache/camel/blob/main/components/camel-google/camel-google-storage/src/main/java/org/apache/camel/component/google/storage/GoogleCloudStorageConnectionFactory.java

Because it will be always override by the credentials provider coming from the extension.

**Comment by jamesnetherton** [comment]
This will have been fixed by https://github.com/apache/camel-quarkus/pull/3188.
