### ISSUE TITLE
[Camel 3.12] Remove the reflection register for SunJaxb21NamespacePrefixMapper

### ISSUE THREAD

**Issue by zhfeng** [apache/camel-quarkus#3132]
following #2965 since [CAMEL-16891](https://issues.apache.org/jira/browse/CAMEL-16891) has been resolve in 3.12.0

**Comment by jamesnetherton** [comment]
I've already done this on the `camel-main` branch in https://github.com/apache/camel-quarkus/commit/9f3bb20664098a394125c93777e18e294ea01bc1.

**Comment by zhfeng** [comment]
Great - Thanks @jamesnetherton !
