### ISSUE TITLE
Register camel <--> CDI event bridges only when observers for the events are detected 

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#3149]
As today, the `CamelContextRecorder` configures the `CamelContext` to automatically bridge camel events to CDI events:

https://github.com/apache/camel-quarkus/blob/be5149cf3b17bd153d07d9edfb5839a30d25f38a/extensions-core/core/runtime/src/main/java/org/apache/camel/quarkus/core/CamelContextRecorder.java#L66-L67

But if no observers for such events are defined, the camel <--> CDI event bridges should not be installed.

**Comment by davsclaus** [comment]
Also pay attention that ideally the CamelManagementEventBridge should only return true for the events groups it wants to listen for.

Its "expensive" to listen for exchange events as they are fired many times during routing. However events for starting / stopping camel context / routes are light and no problem.

camel-core has been optimized to handle these two kinds and does special optimization if there are no exchange events in use.
