### ISSUE TITLE
Simplify the dependency management of examples using QuarkusProcessExecutor

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#3156]
Once the BOMs used in examples will get parametrized ( https://github.com/apache/camel-quarkus/issues/3123 ) there will be no `camel-quarkus.version` available in their poms. This is an issue for the few examples using `QuarkusProcessExecutor` from `camel-quarkus-integration-test-support` that is managed in `camel-quarkus-bom-test`. We'd have to keep and maintain `camel-quarkus.version` in the example poms because of this. 

Several options come to my mind:

A. Put `QuarkusProcessExecutor` and all code it depends on into a new module with a nicer name (e.g. `camel-quarkus-test-utils` ) and manage it in our application BOM.
B. Move `QuarkusProcessExecutor` to `quarkus-junit-5` or some similar module managed in `quarkus-bom`. Hard to say how well our `AvailablePortFinder` could be made portable/replaced?
C. Copy `QuarkusProcessExecutor.java` and all necessary code to the individual examples

Any opinions?

I think I prefer A.

**Comment by jamesnetherton** [comment]
From what I could see, there's no need for `QuarkusProcessExecutor` in any of the example projects. So I removed any usage of it.

If we face this problem again in the future, then I think I prefer option C. It's not great to duplicate code. But it's trivial to write code to start a WireMock server, run a process etc. I'd prefer to not have internal testing utils leak into the BOM if we can avoid it.
