### ISSUE TITLE
`quarkus.camel.main.shutdown.timeout`  doesn't work as intended

### ISSUE THREAD

**Issue by iqnev** [apache/camel-quarkus#3179]
The property 

> quarkus.camel.main.shutdown.timeout

  doesn't work when I tried to configure my application. Also I  tried with the following code to set graceful shutdown but It doesn't work, too.
```
camelContext
        .getShutdownStrategy()
        .setTimeout(66); 
```

While I was debugging my Camel application I realized, that the default graceful shutdown strategy is 

> NoShutdownStrategy

In Apache Camel the default strategy  is https://camel.apache.org/manual/latest/graceful-shutdown.html#_implementing_custom_component_or_shutdownstrategy

> DefaultShutdownStrategy

**Comment by JiriOndrusek** [comment]
@iqnev It is possible to set graceful shudown via property
```
camel.main.shutdownTimeout = 15
```
or via camel context.
```
camelContext
        .getShutdownStrategy()
        .setTimeout(66);
```

In development mode `NoShutdownStrategy` is used.

**Comment by iqnev** [comment]
@JiriOndrusek Thanks! I will try it.
