### ISSUE TITLE
Publish docs for the last stable release

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#3191]
We should make https://camel.apache.org/camel-quarkus/2.2.0/index.html available by changing this line https://github.com/apache/camel-website/blob/main/antora-playbook.yml#L53
and we should have step documented in the release guide https://camel.apache.org/camel-quarkus/2.0.0/contributor-guide/release-guide.html

**Comment by djencks** [comment]
I'll be pushing some changes to the website and most contributing projects in the next day or two and can easily include this.  I wouldn't expect it to cause me a problem if you'd rather do this first.

**Comment by djencks** [comment]
There seems to be a 2.3.x branch as well, is 2.2.x really the latest?
Should both 2.2.x and 2.3.x be in the website? It doesn't appear to cause any problems to have latest, 2.3.x, and 2.2.x. Including release/2.0.0 does cause problems after I fixed some tables.

The PR mentioning all the other related work is apache/camel-website#648. Soon there should be a preview at https://pr-648--camel.netlify.app showing 3 cq versions.

I haven't updated the release process documentation yet, I'll probably do that in a separate PR as there are already too many for me to keep track of.

**Comment by jamesnetherton** [comment]
I think this got resolved a long time back during the reorg of the Camel website.
