### ISSUE TITLE
Improve the Avro extension page

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#3194]
On https://camel.apache.org/camel-quarkus/latest/reference/extensions/avro.html#_additional_camel_quarkus_configuration the docs says

> Beyond standard usages known from vanilla Camel, Camel Quarkus adds the possibility to parse the Avro schema at build time both in JVM and Native mode via the @BuildTimeAvroDataFormat annotation.

`@BuildTimeAvroDataFormat` is also used in a code snippet.

We should fully qualify the class name either in both occurences or at least in the snippet.

**Comment by ppalaga** [comment]
There are also some fomatting issues on the page. `@BuildTimeAvroDataFormat` and all file paths/globs should be monospaced.

**Comment by ppalaga** [comment]
Maybe the page should explain "The build time class generation approach from quarkus-avro is preferred." in more detail. Esp. we should document that `quarkus-maven-plugin:generate-code` is needed: https://github.com/apache/camel-quarkus/blob/main/integration-tests/avro/pom.xml#L97

**Comment by jamesnetherton** [comment]
Do we even need to mention `BuildTimeAvroDataFormat` in the docs? It's deprecated. At a minimum we should give precedence to the `quarkus-maven-plugin` code generation.
