### ISSUE TITLE
[camel 3.13.0] `MllpTest.testCharsetFromMsh18` failure

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3225]
Possibly related to the MLLP refactoring done for [CAMEL-17122](https://issues.apache.org/jira/browse/CAMEL-17122).

I no longer see any way of having the charset being set via the HL7 message MSH 18. The default charset is always used and is not overridable like it used to be.

**Comment by ffang** [comment]
Hi @jamesnetherton ,

I will send a PR to fix CAMEL-17128 and then re-enable this test.

Cheers
Freeman
