### ISSUE TITLE
Reference Camel `azure-sdk-bom-version` property in `azure-sdk-bom.version`

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3229]
`azure-bom` has been removed from Camel, so we need to decide how best to handle it on our side. For now, on the `camel-main` branch, I have removed the `azure-bom-version` version property and replaced it with a hard coded version.

If we stop using `azure-bom` in CQ, then we need to manually manage & declare some of the azure dependencies in our `camel-quarkus-bom` to avoid convergence check errors.

**Comment by zbendhiba** [comment]
@jamesnetherton is this issue still up to date ?

**Comment by jamesnetherton** [comment]
Yeah still needs some thought. For now I'm just aligning `azure-bom` in CQ to match whatever versions of the individual Azure libs are being used in Camel.

We could maybe consider reintroducing `azure-bom` to Camel as the BOM now only contains Azure SDK dependencies and not extraneous third party stuff that was causing some issues.

**Comment by jamesnetherton** [comment]
The BOM has been added back to Camel now, so from 3.19.0 onwards we can simply reuse this version property:

https://github.com/apache/camel/blob/main/parent/pom.xml#L88
