### ISSUE TITLE
[Quarkus 2.5.0] Kafka SASL / SSL tests are failing

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3239]
Needs investigating properly, but I don't think the custom configs to apply the necessary security bits to the Kafka broker are working. It may be related to the testcontainers version bump from 1.16.0 to 1.16.2.

I'm disabling the tests for now.

**Comment by zhfeng** [comment]
@jamesnetherton I think you are right. This is related to testcontainers 1.6.2 changes with

https://github.com/testcontainers/testcontainers-java/blob/4df9b900e79e4a3033ef0975abacf9064a0e7353/modules/kafka/src/main/java/org/testcontainers/containers/KafkaContainer.java#L76-L86

it set ```KAFKA_ADVERTISED_LISTENERS``` with ```BROKER:localhost:9092``` explicitly. So Kafka SSL is not enabled when lauching the instance. 

I think this is a bug in testcontainers.

**Comment by zhfeng** [comment]
It should be a simple workaround to override ```protected void configure()``` to set ```KAFKA_ADVERTISED_LISTENERS``` with ```SSL://localhost:9093,BROKER://localhost:9092```. I've checked that it works on my local machine.

**Comment by zhfeng** [comment]
This should be fixed in ```quarkus-main``` branch.

**Comment by ppalaga** [comment]
I think we generally prefer marking issues as fixed only after they are merged in `main`. `quarkus-main` is an instable (is rebased regularly) branch and so the sha1 of the fix will change several times till it reaches `main`. I mean each fixed issue should contain a stable reference to the fix. This is important for both to be able to audit the fix at any time in the future and also to be able to port the fix to older branches.

**Comment by zhfeng** [comment]
OK, I get it. Let's reopen it.
