### ISSUE TITLE
Camel Rest DSL - Expose Rest DSL services to quarkus openapi

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#3251]
Quarkus can expose its REST servcices to swagger ui
https://quarkus.io/guides/openapi-swaggerui

We have something similar for camel on spring boot via camel-springdoc-starter
https://github.com/apache/camel-spring-boot/tree/main/components-starter/camel-springdoc-starter

This code that discovers the Camel Rest DSL and expose that, can be inspiration for something similar to camel-quarkus.

**Comment by navinyashende** [comment]
Does quarkus support camel rest dsl in xml?

**Comment by davsclaus** [comment]
Yeah its general Camel from the XML DSL

**Comment by zhfeng** [comment]
I got some time to investigate ```quarkus-smallrye-openapi``` and it seems that it leverages the ```AnnotationScannerExtension``` to scan ```JAXRS```, ```Spring```, ```Vert.x``` and generate the ```OpenAPI``` data model. So all of these happen at the build time.  But as far as I know, we can only produce the ```CamelContext```  and get the rest services at static init.

And I think we can use ```AddToOpenAPIDefinitionBuildItem``` to expose the DSL services but I wonder how we can get them at the build time ? especially if it get from the XML DSL.

**Comment by jamesnetherton** [comment]
> I wonder how we can get them at the build time

Maybe take a look at how the `csimple` extension does things. It processes routes at build time to extract the csimple expressions from XML. In theory a similar thing could be done for the REST DSL bits. Not sure if it'd be 100% reliable though...

**Comment by zhfeng** [comment]
Thanks @jamesnetherton - I will take a look.

**Comment by ppalaga** [comment]
Yes, what we do in csimple is rather a fragile misuse of JAXB annotations on the route model classes. A solid solution would require a proper build time route definition introspection API - see https://issues.apache.org/jira/browse/CAMEL-16212
