### ISSUE TITLE
camel.main.routes-include-pattern with a "*" wildcard may end up loading a route builder twice

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#3265]
When a camel-quarkus application is using `camel.main.routes-include-pattern` with a `*` wildcard, some 
 routebuilders/routeconfigurations resources might be loaded twice. Users may face error messages like below:
- `Failed to start route xyz because of Multiple consumers for the same endpoint is not allowed`
- `Route configuration already exists with id: xyz`

The simplest way to reproduce might be to amend the [main-yaml/src/main/resources/applications.properties](https://github.com/apache/camel-quarkus/blob/main/integration-tests/main-yaml/src/main/resources/application.properties) file with `camel.main.routes-include-pattern = classpath:routes/*.yaml`
Then, running the tests will show that route loading fails because of multiple consumers on a given endpoint. It might be due to the fact that a route is loaded twice.

The `DefaultPackageScanResourceResolver` seems guilty as a `DefaultPackageScanResourceResolver.findInClasspath("routes/", resources, "*.yaml")` returns a collection of 4 routes while only 2 are expected. It looks like the same underlying resource loaded from different class loaders are not equal. As such, the given resource can be returned twice in the `Set<Resource>`.

Not sure yet whether we could consider the issue to be in camel or camel-quarkus.

**Comment by jamesnetherton** [comment]
This is only an issue when the application is under test where multiple Quarkus class loaders are in play:

* Quarkus base runtime class loader
* Quarkus runtime class loader

At runtime there is just the `RunnerClassLoader`.

Maybe there should be an `else` clause added here to add the `BasePackageScanResolver` `ClassLoader` only if the TCCL was `null`:

https://github.com/apache/camel/blob/main/core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/BasePackageScanResolver.java#L44

That way you avoid adding multiple `ClassLoader` instances.

**Comment by aldettinger** [comment]
Great to see that @jamesnetherton. Many thanks for handling it.
