### ISSUE TITLE
Use InfinispanTestResource in the Infinispan integration tests

### ISSUE THREAD

**Issue by zbendhiba** [apache/camel-quarkus#3296]
Quarkus 2.5.Final is introducing newer version of Infinispan but also the Infinispan test resource. It could be relevant to use this testing class helper in our test integration class
More information here : https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/infinispan-client.adoc#testing-helpers

**Comment by ashwinair** [comment]
Hi @zbendhiba , can i work on this issue i'm new to open source.

**Comment by jamesnetherton** [comment]
> `InfinispanTestResource` does not seem to support setting a random port

Seems you can set the port via `initArgs` if needed.

**Comment by jamesnetherton** [comment]
> I can only set a constant

Yes, I think you're right...

**Comment by ppalaga** [comment]
So can we live with a fixed port, or we propose some change to InfinispanTestResource to use a random port (ideally by default)?

**Comment by jamesnetherton** [comment]
> So can we live with a fixed port

Probably in the short term. We do it for some other things out of necessity.

> propose some change to InfinispanTestResource to use a random port

I guess we should do that. Looking again at `InfinispanTestResource` I don't actually see the port arg being used at all to set up the container. I guess because [`InfinispanContainer`](https://github.com/infinispan/infinispan-test/blob/master/testcontainers/src/main/java/org/infinispan/test/testcontainers/InfinispanContainer.java#L27) hard codes the port to use.

**Comment by ppalaga** [comment]
> I don't actually see the port arg being used at all to set up the container. I guess because [`InfinispanContainer`](https://github.com/infinispan/infinispan-test/blob/master/testcontainers/src/main/java/org/infinispan/test/testcontainers/InfinispanContainer.java#L27) hard codes the port to use.

That's interesting! We should definitely report that.

**Comment by lburgazzoli** [comment]
I may be out of context and in such case, please discard my message, but isn't the test resource already using a random port ?

My understanding is that the call to `withExposedPorts(11222);` setting the port from the point of view of the container but  for the host, then it will be a random port and you can get it with `container.getMappedPort(11222)`. The test resource seems to do so here: https://github.com/quarkusio/quarkus/blob/main/test-framework/infinispan-client/src/main/java/io/quarkus/test/infinispan/client/InfinispanTestResource.java#L45-L46

**Comment by jamesnetherton** [comment]
> I may be out of context and in such case, please discard my message :) , but isn't the test resource already using a random port ?

Yeah, my bad. It should work as you describe.

**Comment by svkcemk** [comment]
@ppalaga can you please assign to me!

**Comment by jamesnetherton** [comment]
FYI - I already did some hacking on this when I recently added a bunch of new Infinispan tests:

https://github.com/jamesnetherton/camel-quarkus/commit/b9469594d8dd595e05d37251bbbb0608723a41a6

The reason I did not proceed with it is because `<metrics accurate-size="true"/>` is not set in the container Infinispan configuration, so the statistics tests fail. So either we need the Inifnispan / Quarkus folks to add an option to enable it, or we just live with asserting that the statistic values are all returned as `-1`.

**Comment by svkcemk** [comment]
Thanks @jamesnetherton I ll check with someone from the Quarkus team.

**Comment by zbendhiba** [comment]
Yes, I assumed at the beginning this could be easy.
Removing the "good first issue" flag

**Comment by zbendhiba** [comment]
@svkcemk  FYI [thread](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Infinispan.20Test.20Resource.20with.20Camel)

**Comment by karesti** [comment]
@zbendhiba @jamesnetherton we can totally add an option for the statistics size check in metrics. however size operation should be working and retrieving the accurate size. Using another assertion to check the size instead of the statistics, would work for this case?

**Comment by karesti** [comment]
@zbendhiba I created this issue https://issues.redhat.com/browse/ISPN-13810

**Comment by svkcemk** [comment]
Thanks @zbendhiba

**Comment by jamesnetherton** [comment]
> @zbendhiba @jamesnetherton we can totally add an option for the statistics size check in metrics. however size operation should be working and retrieving the accurate size. Using another assertion to check the size instead of the statistics, would work for this case?

We actually already do that. The Infinispan component supports a `size` and `stats` operation. They're two different things as I guess `stats` can provide some additional stuff outside of just getting cache size etc.

So if there's some way to enable `<metrics accurate-size="true"/>` in the container, it'd be useful for our testing.

**Comment by tristantarrant** [comment]
In my opinion, assertions based on statistics values should never be done. We may (and we do) cache stats for performance reasons, so they may never be accurate for tests. My suggestions is to change the tests not to rely on stats.

**Comment by jamesnetherton** [comment]
This was done for 3.8.0 in https://github.com/apache/camel-quarkus/commit/22b77edd4bc3bc7d8de3e1c0c0e751e6dbf81daf.
