### ISSUE TITLE
Better control what we manage in our BOM

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#3302]
Issues with the current setup:

1. Third party BOMs like Azure or Debezium may import tons of stuff none of our extensions needs
2. Two third party BOMs (e.g. Azure vs. Debezium) may both partly manage some group (e.g. io.dropwizard.metrics) in different versions which may lead to inconsitencies and incompatibilities in our own effective BOM
3. Our own entries in the BOM may become stale (no extension requires them anymore)

Perhaps we should have a tool that would be able to check whether the effective BOM is consistent and whether each of the entries is required by at least one of our extensions. We may want to flatten the BOM and remove any unneeded entries.

**Comment by ppalaga** [comment]
This came up as a result of the discussion in https://github.com/quarkusio/quarkus-platform/pull/371/files#r749595546

**Comment by ppalaga** [comment]
4. We should get more control over the transitive dependencies. We should probably manage as much as possible, perhaps on cost of removing some extensions that are hard to adapt. E.g. our extensions are currently pulling as much as six different versions of `org.xerial.snappy:snappy-java`. It could probably be one by managing it properly in our BOM.

**Comment by ppalaga** [comment]
4.1: We must manage all `org.apache.camel:camel-*` transitives. We currently miss `org.apache.camel:camel-cluster` and `org.apache.camel:camel-http-base`

**Comment by jamesnetherton** [comment]
In general I see a lot of the BOM imports as being quite problematic. Especially since the ones for the third party extensions import `quarkus-bom`.

Currently we have this mix of `quarkus-bom` versions being resolved in the build:

1.3.3.Final
2.0.0.Final
2.1.0.Final
2.2.3.Final
2.5.0.Final
2.5.1.Final
2.6.0.CR1

The main issue is that if something is removed from `quarkus-bom`, it ends up being silently added back again by one of the older BOM versions. Thus giving the potential for messing up our dependency management.

**Comment by ppalaga** [comment]
> Currently we have this mix of `quarkus-bom` versions being resolved in the build:
> 
> 1.3.3.Final 2.0.0.Final 2.1.0.Final 2.2.3.Final 2.5.0.Final 2.5.1.Final 2.6.0.CR1

I think all Quarkus Platform participants (including us) should stop importing Quarkus BOM into their BOMs. That would solve some problems on our side and also in the Platform. Have you ever thought of such a policy @aloubyansky?

**Comment by aloubyansky** [comment]
Depending on the use-case, they may get resolved anyway as long as they are imported by parent POMs or there is a dependency on a Quarkus artifact from 1.3.3.Final, for example, whose POM inherits the corresponding BOM.

**Comment by aloubyansky** [comment]
Checking how many versions of jboss-parent get resolved is another example.

**Comment by ppalaga** [comment]
> they may get resolved anyway as long as they are imported by parent POMs or there is a dependency on a Quarkus artifact from 1.3.3.Final, for example, whose POM inherits the corresponding BOM.

Yes, that's a good point. 

But the point made by @jamesnetherton above is still valid, isn't it?

> The main issue is that if something is removed from quarkus-bom, it ends up being silently added back again by one of the older BOM versions.

Platform participants not importing quarkus-bom into their BOMs would prevent that, no?

**Comment by aloubyansky** [comment]
No, that shouldn't happen. Did you actually see that happening?

**Comment by ppalaga** [comment]
> No, that shouldn't happen. Did you actually see that happening?

I know the Platform BOM generators prevents that actively. But it is still an issue in camel-quarkus-bom that we test with and Camel K uses it at runtime.
