### ISSUE TITLE
Sql derby - test exernal db if possible, remove workaround because of quarkus issue #21639

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#3327]
Follows https://github.com/apache/camel-quarkus/issues/3260

1. It should be investigated whether it is possible to run stored procedure est with external derby db
2. Issue https://github.com/quarkusio/quarkus/issues/21639 is already fixed, workaround (profile) can be removed.

**Comment by JiriOndrusek** [comment]
@ppalaga @aldettinger 
I'm investigating a possibility of running stored procedure test on external derby db. I now see that it would need to require  manual steps from user:

1. Jar with stored procedure has to be uploaded into the external file system, which db has access to. Then it is possible to add the jar into db classpath and then execute it as a stored procedure. 
2. Another possible complication: Camel quarkus has to be build with Java 11+. If external derby db contains only Java 8-, it won't be possible to use a jar created as a part of cq build. User would need to create the procedure jar with the right java.

Considering previous limitations, I would say that disabed stored procedure test for external derby is the right solution and it makes no sense to enable such test for external Derby db. What do you think?

Here are some commands required to make stored procedure on external db work:

Java class for procedure
```
package test;

public class App 
{
    public static void testProc(int a, int b) {
         ...
}
```

Commands to be executed via sql:
```
CALL sqlj.install_jar('/home/test-1.0-SNAPSHOT.jar', 'App' , 0);

call syscs_util.syscs_set_database_property('derby.database.classpath', 'DOCKERDB.APP');

CREATE PROCEDURE ADD_NUMS(IN a INTEGER, IN b INTEGER) PARAMETER STYLE JAVA LANGUAGE JAVA EXTERNAL NAME 'test.App.testProc';

call ADD_NUMS2(1, 2);
```

**Comment by aldettinger** [comment]
I think the jar would not forcely need to be rebuilt by quarkus, it could be stored as is in github. But then we should maybe have one compiled in java 8 and one in java 11. If it' s not possible to automate the db setup, then a test is pointless from my point of view.

Maybe we could find a docker image with a java stored proc already configured ? And just ensure that camel-quarkus can call it.

**Comment by JiriOndrusek** [comment]
@aldeinger it might be possible to use docker image (I suppose), upload jar there and test it. (I was able to do it manually with docker derby). I will try to automatize the process. With docker based test, we will use external derby db, even if it is not users's own derby. It should make coverage bigger. Thank you for suggestion!

**Comment by JiriOndrusek** [comment]
TODO make sure that tests with external dbs don't start devServices - it is not needed.
