### ISSUE TITLE
Run integration tests on Windows

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#3342]
Related https://github.com/apache/camel-quarkus/issues/1429

**Comment by zhfeng** [comment]
@ppalaga I think https://github.com/apache/camel-quarkus/issues/3374 should be related to ```camel-quarkus-integration-test-xml``` and in gerneral can we leverage the windows build with ```github action``` ?

**Comment by ppalaga** [comment]
Yes, I'd say jvm mode tests on Java 11 could be enough initially. Feel free to pick this if you like.
