### ISSUE TITLE
Better integration with Quarkus OpenAPI & OpenAPI Swagger UI

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#3346]
- [x] #3251
- [x] #383

**Comment by ppalaga** [comment]
@jamesnetherton could you please add a sentence of description?

**Comment by jamesnetherton** [comment]
Fixed by https://github.com/apache/camel-quarkus/commit/c8db766c2296d909f4157aa44d66fd95caebba0c.
