### ISSUE TITLE
`vertx-kafka` extension incompatible with `kafka-clients` 3.0.0

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3358]
Quarkus 2.6.0 uses `kafka-clients` 3.0.0 and the vertx-kafka itests show: 

```
Caused by: java.lang.NoSuchMethodError: 'long org.apache.kafka.clients.producer.RecordMetadata.checksum()'
	at io.vertx.kafka.client.common.impl.Helper.from(Helper.java:111)
	at io.vertx.core.impl.future.Mapping.onSuccess(Mapping.java:35)
	... 12 more
```

There's an open issue to update the `vertx-kafka-client` here:

https://github.com/vert-x3/vertx-kafka-client/issues/207

For now, I'll be disabling the vertx-kafka tests & native image build as I don't see a simple workaround to get things working.

We should consider removing this extension. Camel 3.14 has marked the camel component as deprecated. I don't think it's feasible for us to maintain multiple versions of `kafka-clients`.

**Comment by davsclaus** [comment]
yeah it can be removed, everybody uses the regular camel-kafka component
