### ISSUE TITLE
Make the maven plugin depend on the camel package-maven-plugin

### ISSUE THREAD

**Issue by gnodet** [apache/camel-quarkus#336]
And remove duplicate code around model objects / helpers, etc...

**Comment by ppalaga** [comment]
I am far from knowing all the details, but wouldn't it be even better to port the features we need here to Camel main and remove the plugin altogether from here?

**Comment by gnodet** [comment]
Sure, that can be investigated.  I haven't really checked how the model is used, but I don't think Camel should be tied to any Camel Quarkus concept, else it will be hard to maintain.
However, reusable code should stay in Camel, I agree.
Basically, we should keep the 2 mojos because they are specific to camel-quarkus and reuse the helpers and model classes from the camel plugin.  So we'd be left with `PrepareCatalogQuarkusMojo` and `UpdateDocExtensionsListMojo` classes.  Not sure we can do better.
