### ISSUE TITLE
[Quarkus 2.6.0.Final] Remove `software.amazon.awssdk:apache-client` dependency override 

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3366]
In Quarkus 2.6.0.CR1 there's an invalid dependency declaration in `quarkus-bom` for the AWS `apache-client`.

So for now, I've worked around it by specifying the dependency in our own BOM.

When 2.6.0.Final is available, we should be able to remove it.

**Comment by aldettinger** [comment]
The workaround evoked in the previous must be [here](https://github.com/apache/camel-quarkus/commit/77cee8366620ca5e774c38080b8cf9b98027a4da).
I guess we would need to revert only the change in `poms/bom/pom.xml`.

**Comment by ppalaga** [comment]
Now I see what is going on: the exclusion of `commons-logging` in the removed apache-client management entry makes the difference. We actually need to ban commons-logging altogether.

Using `mvn quarkus:dependency-tree` instead of `mvn dependency:tree` helped me to figure out what's going on.
