### ISSUE TITLE
Testing transacted routes with Quarkus and CamelTestSupport fails

### ISSUE THREAD

**Issue by radio042** [apache/camel-quarkus#3379]
Dear all, 

I have problems testing routes with CamelTestSupport in a Quarkus project when a transacted() definition is part of the route. 

**Describe the bug**

The exchanges do not seem to reach the endpoints, when "transacted()" is part of the route.

Snippets:

- Route: 
``` 
from("direct:in").transacted().to("mock:out");
```
- Test:
 ```
MockEndpoint mockEndpoint = getMockEndpoint("mock:out");
mockEndpoint.expectedMessageCount(1);
template.sendBody("direct:in", "hello");
assertMockEndpointsSatisfied();
```

Here's a Gist of my test setup and the pom.xml: https://gist.github.com/radio042/b71717d5634eaa634c9affc1021eacfb#file-transactedtest-java 

**Expected behavior** 

Messages sent to a route with a transacted() definition using CamelTestSupport in a Quarkus project reach the endpoints and the test is green.

**Actual behavior**

The test fails with `java.lang.AssertionError: mock://out Received message count. Expected: <1> but was: <0>`

**How to Reproduce?**

Run the test from the gist inside a Quarkus project

**Comment by zhfeng** [comment]
Well, I think we've not support the ```CamelTestSupport``` yet with Camel Quarkus. Is there any reason you can not use ```QuarkusTest``` for running this test ?

**Comment by radio042** [comment]
I can, but I'm getting the same behavior when annotating the Class with `@QuarkusTest`.

**Comment by zhfeng** [comment]
Please check with our [JtaTest](https://github.com/apache/camel-quarkus/blob/main/integration-tests/jta/src/test/java/org/apache/camel/quarkus/component/jta/it/JtaTest.java), or you can get more details about how to write a test with Quarkus from https://quarkus.io/guides/getting-started-testing

**Comment by radio042** [comment]
Thanks for the links! The thing is, I am trying to test a camel route that has the `transacted()` definition, not transactions in general. The test would work once "transacted()" is commented out, so I assume that either the test setup is incomplete or the combination "Quarkus + CamelTestSupport + `transacted()`" does not work as I expect.

By the way, is this the right place to raise the issue? I opened it here, because there are a lot of examples of similar tests with Spring online that allegedly work.

**Comment by zhfeng** [comment]
I understand and just create a [camel-test-demo]( https://github.com/zhfeng/camel-test-demo) to show how to use ```CamelTestSupport``` in camel-quarkus. Hope it is useful !

Free feel to give some feedback.

**Comment by zhfeng** [comment]
I'm not sure this is a good way but it just works.

**Comment by radio042** [comment]
Perfect, this solved my problem! Thanks a lot. :) I think it's a good solution, after all it does not matter which specific CamelContext instance a test uses.

**Comment by ppalaga** [comment]
> I understand and just create a [camel-test-demo](https://github.com/zhfeng/camel-test-demo) to show how to use `CamelTestSupport` in camel-quarkus. Hope it is useful !

What a cute hack, @zhfeng! Could you perhaps mention it in https://github.com/apache/camel-quarkus/issues/1981 where some folks asked for `CamelTestSupport`? 

Hm... on the same note, I wonder whether we could somehow set the context automatically. Either by having our own subclass of `CamelTestSupport` (ugly) or something nicer, like implementing a junit5 extension that would do it?

**Comment by zhfeng** [comment]
@ppalaga yeah, that could be a better way to have a junit5 extension. I will investigate it after the holidays.
