### ISSUE TITLE
Docs: Camel-quarkus 2.4.x docs don't show information in components/languages/dataformats and misc

### ISSUE THREAD

**Issue by oscerd** [apache/camel-quarkus#3387]
https://camel.apache.org/camel-quarkus/2.4.x/reference/components.html

**Comment by djencks** [comment]
I may propose a different way of constructing these tables, there are some faulty assumptions about the relationship between camel versions and camel quarkus versions in the current setup.

**Comment by djencks** [comment]
In particular, the tables emptied when camel-quarkus 2.3.x was removed: camel 3.12.x assumes that only camel-quarkus 2.3.x depends on it, so now that it's gone, the camel-quarkus info is no longer included in the camel components/etc pages.

**Comment by djencks** [comment]
I've described how I'll solve this in https://github.com/apache/camel-quarkus/issues/3396, and leave this one open until that is complete.

**Comment by zbendhiba** [comment]
The page now shows all those categories. I guess we can close this one. Example https://camel.apache.org/camel-quarkus/2.9.x/reference/dataformats.html
@djencks @oscerd  is that okay for you ?

**Comment by jamesnetherton** [comment]
Looks like this one got fixed back in https://github.com/apache/camel-quarkus/issues/3396.
