### ISSUE TITLE
Geocoder started returning "New York City" instead of "New York"

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#3389]
... and therefore our Geocoder test is failing when run with `GOOGLE_API_KEY` set.

**Comment by ppalaga** [comment]
Could please anybody with a Google Cloud account have a look? @zbendhiba maybe?

**Comment by ppalaga** [comment]
I guess it would be safer to change the test to some location where there no city/state ambiguity.

**Comment by aldettinger** [comment]
@djcoleman When one consider an issue finished (ci checked, branches deleted, backported, follow up created and whatnot...), then it's possible to add the ticket to the coming milestone and close the issue.
