### ISSUE TITLE
camel-quarkus-integration-test-js-dsl is failing on Quarkus 2.2.4

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#3390]
Originally reported here https://github.com/quarkusio/quarkus-platform/pull/405#issuecomment-994803271

**Comment by JiriOndrusek** [comment]
I tried to simulate problem locally. But with the recent platform and following quarkus and camel-quarkus versions, there is no failure.
I'd say that this issue can be closed.

```
        <quarkus.version>2.7.0.CR1</quarkus.version>
        <quarkus-bom.version>${quarkus.version}</quarkus-bom.version>

        <camel-quarkus.version>2.6.0</camel-quarkus.version>
```
