### ISSUE TITLE
camel.main.durationMaxSeconds is not honoured

### ISSUE THREAD

**Issue by gus-maurizio** [apache/camel-quarkus#3394]
I need the camel quarkus routes to terminate after a certain amount of seconds or processing a number of messages.
This was defined by the camel-quarkus-main, that seems not supported any longer. 
How do I achieve this?

**Comment by gus-maurizio** [comment]
Correction. MaxMessages and MaxIdleSeconds work, but durationMaxSeconds seems to be ignored.
camel.main.durationMaxIdleSeconds = 120
camel.main.durationMaxMessages = 300
camel.main.durationMaxSeconds = 30

**Comment by ppalaga** [comment]
Could you @gus-maurizio or anybody else please modify this integration test to reproduce the issue? https://github.com/apache/camel-quarkus/tree/main/integration-tests/main-command-mode

**Comment by gus-maurizio** [comment]
Thanks Peter, I created a pull request: Update CamelRoute.java #3408
Modified the application properties (to stop JVM after 10 seconds) and the timer settings (to delay 20 seconds) to show the issue.

**Comment by gus-maurizio** [comment]
I was not able to download and compile this to check, and I was using the latest stable version, so please verify,

**Comment by ppalaga** [comment]
> I was not able to download and compile this to check, and I was using the latest stable version, so please verify,

Should make no difference. Let's see whether the CI fails on the modified test https://github.com/apache/camel-quarkus/runs/4609110536?check_suite_focus=true

**Comment by gus-maurizio** [comment]
Let me know if you need anything else from me Peter. Thanks for your help. 

G

**Comment by aldettinger** [comment]
@gus-maurizio Reading #1441, could you please confirm that durationMaxSeconds was working in a previous camel-quarkus version ? which one please ? And then it stop working when you upgraded to 2.5.3.Final ?

**Comment by gus-maurizio** [comment]
Was working in 1.8.1.final

**Comment by aldettinger** [comment]
This issue can be reproduced with camel-quarkus 2.6.0 while it's working with pure camel 3.14.0, so the issue relies in camel-quakus.

After investigations:
 + A CamelMainRuntime is assembled and [started](https://github.com/apache/camel-quarkus/blob/main/extensions-core/core/runtime/src/main/java/org/apache/camel/quarkus/main/CamelMainRuntime.java#L49)
 + oacq.main.CamelMain.runEngine() calls [waitUntilCompleted()](https://github.com/apache/camel-quarkus/blob/main/extensions-core/core/runtime/src/main/java/org/apache/camel/quarkus/main/CamelMain.java#L150)
 + `durationMaxSeconds` is equals to zero in [oac.main.MainSupport.waitUntilCompleted()](https://github.com/apache/camel/blob/main/core/camel-main/src/main/java/org/apache/camel/main/MainSupport.java#L301..L304) while **it should not**

It looks that `durationMaxSeconds` should be set in [internalBeforeStart()](https://github.com/apache/camel/blob/main/core/camel-main/src/main/java/org/apache/camel/main/MainSupport.java#L66..L72) which is [private](https://github.com/apache/camel/blob/main/core/camel-main/src/main/java/org/apache/camel/main/MainSupport.java#L108..L112).

From there I wonder whether `internalBeforeStart()` should be made protected ? Or maybe `oacq.main.CamelMain` should be changed ?
@ppalaga @davsclaus  What do you think ?

**Comment by davsclaus** [comment]
Ah so you do not extend the camel-main class but do you own. Yeah then those methods needs to be protected so you can call them.

**Comment by gus-maurizio** [comment]
Just to provide a bit of context, along with congratulations to this team for working and finding the root cause.
This functionality is important in the context of running camel quarkus AWS lambda functions that are limited to at most 15 minutes. We leverage this and establish two criteria for termination, maxMessages (which is the preferred) and a fail-safe of maxDuration (to about 13 or 14 minutes) to ensure the routes can properly end what is in flight before being terminated by the underlying engine.
Merci bien Alexandre!

**Comment by gus-maurizio** [comment]
Any progress or ETA on this issue?

**Comment by aldettinger** [comment]
@gus-maurizio Not really from my side. I can resume as soon as I have time. Unless someone else is willing to pick it now.

**Comment by jamesnetherton** [comment]
It'd be nice to fix this for the 2.7.0 release. I can take a look into it.

Until we have a Camel version with the `protected` `internalBeforeStart()`, I guess we can work around it on our side by setting the relevant main config like `mainConfigurationProperties.setDurationMaxSeconds(someValue)`.

**Comment by aldettinger** [comment]
Sure @jamesnetherton , you are welcome to move this ahead.

**Comment by gus-maurizio** [comment]
Thanks to all the team! It is now working with the latest release.
