### ISSUE TITLE
Camel Rest / Quarkus Swagger UI / Url Issue from Quarkus Version 2.6.x

### ISSUE THREAD

**Issue by xjazzfreakx** [apache/camel-quarkus#3457]
Issue: Wrong URL for Service in Swagger UI  ( the context path appears twice e.g. /api/api/service/test )
It was correct for Version Q 2.4.2 but appears from Q Versions 2.6.x

Steps to reproduce: 

1. Camel Java Config: 
`restConfiguration() 
 .host("localhost")
 .apiHost("localhost")
 .contextPath("/api") 
 .port(8080)
 .apiContextPath("/api-docs");

   rest("/service")
 .get("/testing").description("Test Service")
 .outType(String.class)
 .to("direct:testing");
`
2. pom.xml:
using Q Version 2.6.2 +  camel-quarkus-openapi-java + camel-quarkus-rest + quarkus-smallrye-openapi
3.  application.properties : quarkus.swagger-ui.urls.camel=/api/api-docs/
4. http://localhost:8080/q/swagger-ui/
5. test service/testing -> url called will be http://localhost:8080/q/api/api/service/testing <- PROBLEM

**Comment by jamesnetherton** [comment]
Yes, there is a similar issue documented in [CAMEL-17457](CAMEL-17457).

It will be fixed in Camel 3.14.1 / Camel 3.15.0.

**Comment by jamesnetherton** [comment]
Actually my bad. It is still broken. The duplication of some of the path elements is fixed but the operation path is now being generated as `/testing` without the `/service` prefix. I'll open a new Camel ticket.

**Comment by xjazzfreakx** [comment]
The thing is rather -> the context path is duplicated ( **/api/api** )

**Comment by jamesnetherton** [comment]
https://issues.apache.org/jira/browse/CAMEL-17491

**Comment by zhfeng** [comment]
@xjazzfreakx I think this should be fixed in camel 3.15.0. Also you can try the new feature with [Camel Rest DSL - Expose Rest DSL services to quarkus openapi](https://github.com/apache/camel-quarkus/issues/3251) and just enable it by
```
quarkus.camel.openapi.expose.enabled=true
```
