### ISSUE TITLE
Extensions for camel-knative and camel-cloudevents

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#3459]
https://github.com/apache/camel-k-runtime/issues/752

Camel 3.15 comes with new components

- camel-knative
- camel-cloudevents

Camel K needs extensions for those, to be ported over from camel-k-runtime at
https://github.com/apache/camel-k-runtime/tree/main/camel-k-knative
https://github.com/apache/camel-k-runtime/tree/main/camel-k-cloudevents

**Comment by zbendhiba** [comment]
@davsclaus My understanding is that the workaround for native mode is already done in camel-k-runtime. And the idea is to port this here as extensions, right ?

**Comment by davsclaus** [comment]
Yeah camel-k-runtime has already quarkus extensions for these 2 components, so yes the ticket is about moving the source code over to camel-quarkus - so we can remove them from camel-k-runtime.

**Comment by zbendhiba** [comment]
I started working on this.
I'm not sure about this one [https://github.com/apache/camel-k-runtime/tree/main/camel-k-knative/impl](https://github.com/apache/camel-k-runtime/tree/main/camel-k-knative/impl)
what should I do for those 2 dependencies ?
```
  <dependency>
            <groupId>org.apache.camel.k</groupId>
            <artifactId>camel-k-apt</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.apache.camel.k</groupId>
            <artifactId>camel-k-annotations</artifactId>
            <optional>true</optional>
        </dependency>
```

**Comment by lburgazzoli** [comment]
I think the annotations should be removed, however we need to reason about how to replicate the same feature with quarkus constructs

**Comment by zbendhiba** [comment]
I unassigned myself. I don't think I understand fully what to do with knative, knative-consumer and knative-producer. Do we create 3 extensions or combine in one? I'm not sure porting the integration tests in the project is enough to test if this could work fine for camel-k

**Comment by zbendhiba** [comment]
As discussed with @lburgazzoli: 

- create 3 extensions : split the knative extension to 3 extensions : knative + knative-consumer  + knative-producer. The consumer and producer extensions will be empty and unse the knative one. Those are for camel-k usage. Check if this could be improved later
- leave the [impl](https://github.com/apache/camel-k-runtime/tree/main/camel-k-knative/impl) part in camel-k-runtime for now.

**Comment by zbendhiba** [comment]
Some notes : 

- For native compilation this fix is needed and will be available with camel 3.18.2: https://github.com/apache/camel/commit/beda73589fcb009efcea4ac9f29b3bc127b02d49
- I opened an issue for time Format and will be available with camel 3.18.3 : https://issues.apache.org/jira/browse/CAMEL-18473

**Comment by zbendhiba** [comment]
A JIRA to add to think about adjusting the documentation or later fix : https://issues.apache.org/jira/browse/CAMEL-18477

**Comment by oscerd** [comment]
What is the plan for the impl module? Do we want to move it in camel-quarkus since we would like to move the camel-k-runtime to it already?

**Comment by zbendhiba** [comment]
@oscerd  yes
