### ISSUE TITLE
camel-quarkus-opentelemetry component logs unresolved toD uri

### ISSUE THREAD

**Issue by michaelgarde** [apache/camel-quarkus#3461]
The camel-quarkus-opentelemetry component does not log the resolved uri of a toD when using dynamically generated uris . This is how one of our routes in Jaeger looks like:

![image](https://user-images.githubusercontent.com/6233262/149765369-284b9ef6-080a-42d4-8821-532277f39d3b.png)

It would be really useful if we were able to see, which jms queue it was actually sent to.

**Comment by jamesnetherton** [comment]
I opened a Camel ticket to investigate:

https://issues.apache.org/jira/browse/CAMEL-17512

**Comment by zbendhiba** [comment]
Fixed in Camel 3.17, so fixed in main branch. Will be OK for next release

**Comment by michaelgarde** [comment]
Well done. We will be testing this when Camel Quarkus 3.17 will be available with Red Hat support.
