### ISSUE TITLE
Remove camel-quarkus-spark

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#3466]
The Spark extension is hard to maintain due to its ancient netty 3 dependencies which clash with netty 4 available out of the box on Quarkus. Moreover, there is little hope that porting it to native is even possible.

Any concerns about removing this extension?

**Comment by jamesnetherton** [comment]
+1

**Comment by zbendhiba** [comment]
+1

**Comment by ppalaga** [comment]
Deprecation PR https://github.com/apache/camel-quarkus/pull/3544
