### ISSUE TITLE
Debezium mysql - passing additionalProperties results in wrong properties beeing passed

### ISSUE THREAD

**Issue by Tarjei400** [apache/camel-quarkus#3488]
I am using debezium component with mysql, I need to pass an additionaProperty, I am doing it according to documentation here: https://camel.apache.org/components/3.14.x/debezium-mysql-component.html 

Althought it seems that when I try to pass database.connectionTimezone=CET seems that property is read as database alone.
Here is my example:

     from("debezium-mysql:test?"

            + "databaseHostname={{database.hostname}}"
            + "&databasePort={{database.port}}"
            + "&databaseUser={{database.user}}"
            + "&databasePassword={{database.password}}"
            + "&databaseServerName=localhost"
            + "&databaseServerId=5500"
            + "&snapshotMode=when_needed"
            + "&databaseIncludeList={{database.schema}}"
            + "&tableIncludeList={{database.schema}}.test"
            + "&additionalProperties.database.connectionTimeZone=CET"
            + "&offsetStorage=org.apache.kafka.connect.storage.MemoryOffsetBackingStore")

And here is what I see in logs, as being passed to properties:

![image](https://user-images.githubusercontent.com/1921727/151160938-e487d616-0cb7-4f5f-a579-e0d77150ecf3.png)

**Comment by zbendhiba** [comment]
Hello @Tarjei400 Can you give information about which camel-quarkus version are you using ?

**Comment by Tarjei400** [comment]
Sorry, I am using version 2.6.0

**Comment by JiriOndrusek** [comment]
I've found that problem is caused by the camel. I reported it as https://issues.apache.org/jira/browse/CAMEL-17658

**Comment by jamesnetherton** [comment]
Was fixed back in the 2.8.0 release and backported for 2.7.x.
