### ISSUE TITLE
CamelTestSupport style of testing 

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#3511]
Based on the demand heart in https://github.com/apache/camel-quarkus/issues/1981 and elsewhere, we should provide a way for testing in the CamelTestSupport way known from other Camel runtimes.

This may include at least the following:

1. Offer our own CamelTestSupport class  overriding createCamelContext() override, so that end users do not need to copy it over and over again:

```
@QuarkusTest
public class TransactedTest extends CamelTestSupport {
    @Inject
    CamelContext context;

    @Override
    protected CamelContext createCamelContext() throws Exception {
        return this.context;
    }
}
```
 
2. We should have a couple of tests of this kind to both test that it works and for demo purposes. 
3. We should document this kind of testing (including the warning that it would not work in native mode).

**Comment by aldettinger** [comment]
Some users reported that demonstrating injection of MockEndpoint and usage of AdviceWith would be of interest. They see those camel tests as complement for integration tests, not replacement.
