### ISSUE TITLE
Incorrect version of `quarkus-maven-plugin` may be resolved

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3520]
See build failure on the `quarkus-main` branch:

https://github.com/apache/camel-quarkus/actions/runs/1792838270

It may be a consequence of https://github.com/apache/camel-quarkus/commit/b050497cf55391c416e2886f88c677f16d54f472. If you run the build from the project root directory, then the `quarkus-maven-plugin` version is resolved as `2.7.0.Final`. If the build is run from within the integration test project directory, then the version correctly resolves as `999-SNAPSHOT`.

**Comment by ppalaga** [comment]
@jamesnetherton which Maven version are you using? I saw similar issues with 3.8.1, but it worked for me with 3.8.4

**Comment by jamesnetherton** [comment]
Ok - then we need to bump the Maven version used by the wrapper. It's still pointing at 3.8.1.

**Comment by jamesnetherton** [comment]
Seems to be fixed with https://github.com/apache/camel-quarkus/commit/6111679cef631d091056a724f487ccf50e75f758.
