### ISSUE TITLE
[Quarkus 2.8.0] Leverage Strimzi dev services container in kafka-oauth integration tests

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3531]
See this commit for more details https://github.com/quarkusio/quarkus/commit/c19cedacaf718cb758ae015bb200feedab88ed57.

**Comment by zbendhiba** [comment]
I was testing this afternoon. I've done some the work already here https://github.com/zbendhiba/camel-quarkus/commit/ac0c73f97cb6d0d24d6a404c7820163d74348500
I'll push a PR when we move to Quarkus 2.8.0.CR1
