### ISSUE TITLE
Cannot build camel-quarkus-ipfs because repository.jboss.org is down

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#3532]
```
Error:  Failed to execute goal on project camel-quarkus-ipfs: Could not resolve dependencies for project org.apache.camel.quarkus:camel-quarkus-ipfs:jar:2.8.0-SNAPSHOT: Failed to collect dependencies at org.apache.camel:camel-ipfs:jar:3.14.1 -> io.nessus:nessus-ipfs-client:jar:1.0.0.Beta4: Failed to read artifact descriptor for io.nessus:nessus-ipfs-client:jar:1.0.0.Beta4: Could not transfer artifact io.nessus:nessus-ipfs-client:pom:1.0.0.Beta4 from/to jboss.thirdparty (https://repository.jboss.org
```

**Comment by ppalaga** [comment]
The same issue exists for Weka.

@tdiesler any chance to make the ipfs and weka artifacts available on Maven Central so that our builds are not hit by the flakiness of repository.jboss.org?

**Comment by aldettinger** [comment]
It actually generated issues on quarkus-platform. After discussion, maybe it's better to remove them in next 2.8.0 as we can't rely on the jboss repository.

**Comment by aldettinger** [comment]
However, we'll reinstate it in 2.7.x for branch stability purpose. If build stability is too much impacted, we might removed it there also.
