### ISSUE TITLE
How do you configure an InterceptStrategy in Quarkus?

### ISSUE THREAD

**Issue by josephearl** [apache/camel-quarkus#3552]
In Spring Boot it was as simple as having a bean that implements `InterceptStrategy`, but this doesn't seem to work with Quarkus - the bean is not used and I get a warning:

```
================================================================================
CDI: programmatic lookup problem detected
-----------------------------------------
At least one bean matched the required type and qualifiers but was marked as unused and removed during build

Stack frame: org.apache.camel.quarkus.core.RuntimeBeanRepository.getReferencesByTypeWithName(RuntimeBeanRepository.java:66)
Required type: interface org.apache.camel.spi.InterceptStrategy
Required qualifiers: []
Removed beans:
	- CLASS bean  [types=[class com.example.ExampleInterceptStrategy, interface org.apache.camel.spi.InterceptStrategy], qualifiers=null]
Solutions:
	- Application developers can eliminate false positives via the @Unremovable annotation
	- Extensions can eliminate false positives via build items, e.g. using the UnremovableBeanBuildItem
	- See also https://quarkus.io/guides/cdi-reference#remove_unused_beans
	- Enable the DEBUG log level to see the full stack trace
================================================================================
```

**Comment by jamesnetherton** [comment]
You can annotate the bean producer with `@Unremovable`. Or assign a name to bean with `@Named`, which automatically makes it unremovable.

**Comment by josephearl** [comment]
Thanks @jamesnetherton 

To actually add the interceptor I had to do it manually with:

```
getCamelContext().adapt(ExtendedCamelContext.class).addInterceptStrategy(new ExampleInterceptStrategy());
```

It would be nice for this to be configured automatically if there is one or more beans of type `InterceptStrategy` like it does for Spring Boot - https://camel.apache.org/manual/advanced-configuration-of-camelcontext-using-spring.html#_auto_configuration_of_optional_services

**Comment by jamesnetherton** [comment]
> It would be nice for this to be configured automatically

It should already work automatically. It's a feature of `camel-main`.

If you register a CDI bean of type `InterceptStrategy` it will be resolvable by lookups on the Camel registry.

E.g if I write a producer method like:

```java
@Named("test")
@Singleton
public InterceptStrategy test() {
    return new InterceptStrategy() {
        @Override
        public Processor wrapProcessorInInterceptors(CamelContext context, NamedNode definition, Processor target, Processor nextTarget) throws Exception {
            // Something useful here
        }
    };
}
``` 

On startup Camel reports:
```
Adding custom InterceptStrategy with id: test
```

**Comment by josephearl** [comment]
@jamesnetherton I had my class annotated with `@ApplicationScoped` like the following which did not work:

```
@ApplicationScoped
public class ExampleInterceptStrategy implements InterceptStrategy {
  // ...
}
```

**Comment by josephearl** [comment]
Adding the `@Named` to my previous example with `@ApplicationScoped` makes it work - not sure why the `@Named` is required with Quarkus and not Spring Boot?

**Comment by jamesnetherton** [comment]
> not sure why the `@Named` is required with Quarkus and not Spring Boot?

By default, Quarkus will remove what it considers to be 'unused' beans. E.g in this case, there's no injection point for your bean (since Camel does not need one), so it's removed.

I guess the enhancement here would be for Camel Quarkus to discover any beans of type `InterceptStrategy` and automatically make them 'unremovable'.

**Comment by josephearl** [comment]
I'll raise that as a separate request, thanks for all of your help @jamesnetherton
