### ISSUE TITLE
Feature request: make beans for configuration of optional services unremovable by default

### ISSUE THREAD

**Issue by josephearl** [apache/camel-quarkus#3553]
See https://github.com/apache/camel-quarkus/issues/3552#issuecomment-1041402892

By default, Quarkus will remove what it considers to be 'unused' beans. 

Camel Quarkus should discover any beans for configuration of optional services - e.g. https://camel.apache.org/manual/advanced-configuration-of-camelcontext-using-spring.html#_auto_configuration_of_optional_services - and make them unremovable so you do not have to explicitly add `@Named` or `@Unremovable` to the beans.

**Comment by zhfeng** [comment]
Hi @josephearl I just raise a PR to unremovable with InterceptStrategy. If it works, I think we can add the other optional services.
