### ISSUE TITLE
Issues in the List of extensions 

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#356]
The list of extensions: https://camel.apache.org/camel-quarkus/latest/list-of-camel-quarkus-extensions.html

* Some entries have bad Since version. The plugin should not assume 0.2 as a default. I think it should rather fail if `<firstVersion>` is not set for the given extension.
* The description of camel-quarkus-attachments and camel-quarkus-core-xml `Maven plugins configuration` is apparently inherited from the build parent. The plugin should not use the inherited value and I think it should rather fail if the description is not there in the runtime module.
* Not sure how the extensions are are assigned to the Misc. category, but at least opentracing, MP health and Platform HTTP seem to rather belong to Camel components category.

Fixing this should be coordinated with whoever works on the potentially conflicting #336

**Comment by ppalaga** [comment]
Plz. assign to me.

**Comment by davsclaus** [comment]
Misc category are correct, this should be for extensions that are NOT a
- regular Camel component
- regular Camel data format
- regular Camel language

In other words, all the other / misc stuff
