### ISSUE TITLE
Update dependency org.reflections:reflections in dependencyManagement of quarkus-camel-bom

### ISSUE THREAD

**Issue by albert0815** [apache/camel-quarkus#3569]
In quarkus-camel-bom currently version 0.9.12 of org.reflections:reflections is being used. This has a known issue which I am suffering now (https://github.com/ronmamo/reflections/issues/273). Are you planning for updating this in the dependency management of quarkus-camel-bom at some point in time?

**Comment by ppalaga** [comment]
Thanks for the report, @albert0815. 

Is the https://github.com/ronmamo/reflections/issues/273 issue triggered by Camel code? If so, which extension?

camel-quarkus-bom gets the version of org.reflections:reflections via imported io.debezium:debezium-bom:1.6.1.Final, line 502. 
So, ideally the fix should go there.

As a quick workaround, you can add the following before the BOM imports in your pom.xml:

```
...
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.reflections</groupId>
        <artifactId>reflections</artifactId>
        <version>0.10.2</version>
      </dependency>
      <!-- BOM imports here ... -->
    </dependencies>
  </dependencyManagement>
...
```

**Comment by albert0815** [comment]
Thanks for the hint about the workaround, this is how I solved this for now. Nevertheless I thought it would be useful to also have it updated in the source. And I assumed source would be here, but that seems wrong :). Somehow I can't create an issue in the debezium repo. Not sure whether you want to keep it here or close it, if this is not something which you can deal with this is fine for me. Thanks for letting me know!

**Comment by ppalaga** [comment]
You can file an issue for Debezium here https://issues.redhat.com/projects/DBZ
