### ISSUE TITLE
Missing link to Camel user manual in the CQ documentation

### ISSUE THREAD

**Issue by jirisimek98** [apache/camel-quarkus#3580]
In the Camel Quarkus documentation, there is no direct link to the Getting started with Camel section of the User manual. It would be nice to have a link either in the documentation or in the sidebar menu as the User guide only covers the specifics of Camel Quarkus and doesn't explain Camel in general.

**Comment by spatnity** [comment]
Hello, I would like to help with this issue, can someone please assign this issue to me? 
It will be my first time contributing, so please forgive if any mistakes are made.

**Comment by zhfeng** [comment]
Thanks @spatnity - Feel free to ask if you have any problem.

**Comment by jamesnetherton** [comment]
Fixed in https://github.com/apache/camel-quarkus/pull/4941.
