### ISSUE TITLE
[Camel 3.16.0] - camel-kafka uses some reflection for readiness health check

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#3592]
https://issues.apache.org/jira/browse/CAMEL-17727

The class KafkaFetchRecords and KafkaProducer in the camel-kafka component has some reflection code

**Comment by zhfeng** [comment]
It needs to add ```ReflectiveClassBuildItem``` for ```org.apache.kafka.clients.producer.KafkaProducer``` and ```org.apache.kafka.clients.consumer.KafkaConsumer```
