### ISSUE TITLE
Release first version of camel-quarkus

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#36]
Once #24 is fixed we should do a first version of camel-quarkus, drop camel bits from quarkus repo and get a new quarkus release that includes our camel bits

**Comment by ppalaga** [comment]
Update: To release camel-quarkus 0.0.1 we need:

* A Quarkus release (presumably 0.19.0) that contains the following fixes/changes:
  * Broken tests after package rename, PR https://github.com/quarkusio/quarkus/pull/3117 Issues: https://github.com/quarkusio/quarkus/issues/3094 alias #24
  * Remove Camel extensions from Quarkus: https://github.com/quarkusio/quarkus/issues/3095 , no PR yet

**Comment by oscerd** [comment]
Also we need to apply the ASF release style to the POM, like we have in camel-k-runtime or camel. At least we need to double check all is already aligned.

**Comment by ppalaga** [comment]
We can close this one after 0.0.2 was released.

**Comment by oscerd** [comment]
0.0.2 has been already released. As first version.
