### ISSUE TITLE
camel-quarkus-openapi-java not marking required boolean properties if variable prefixed with is

### ISSUE THREAD

**Issue by mbchangellc** [apache/camel-quarkus#3605]
I filed the bug report below with the Camel team and was told to report it here.  Camel bug report: [CAMEL-17765](https://issues.apache.org/jira/browse/CAMEL-17765).  Thanks.

Boolean properties are not marked as required in the openapi document if the respective member variable name is prefixed with is.  The Fruit class in the attached project contains two boolean properties described below which are treated differently if the member variable name is prefixed.

The property definition below doesn't appear as required in the openapi document although it's marked as required.  The expectation is that it would appear in the list of required properties.

```
@NotBlank
private boolean isNotWorking;

public boolean isNotWorking()
{ return isNotWorking; }

public void setNotWorking(boolean isNotWorking)
{ this.isNotWorking = isNotWorking; }
 
The property definition below does appear as required in the openapi document as expected.

@NotBlank
private boolean working;

public boolean isWorking()
{ return working; }

public void setWorking(boolean working)
{ this.working = working; }
```

Additionally, the text below is printed when viewing the openapi document.

2022-03-08 11:38:20,704 WARN  [org.apa.cam.ope.RestModelConverters] (vert.x-worker-thread-0) Encountered unexpected type boolean in processing schema

[camel-openapi-boolean-bug.zip](https://github.com/apache/camel-quarkus/files/8208446/camel-openapi-boolean-bug.zip)

**Comment by zhfeng** [comment]
So this issue should be fixed in upstream camel ?

**Comment by zbendhiba** [comment]
@mbchangellc this is now fixed, on Camel and Camel-Quarkus. I'll close this one.
Let us know if there's a pending issue.
Thanks for reporting this issue.
