### ISSUE TITLE
Support additional FHIR 2.x versions

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3615]
There are some config properties for enabling support for various FHIR versions:

https://camel.apache.org/camel-quarkus/2.7.x/reference/extensions/fhir.html#_additional_camel_quarkus_configuration

There are no options for:

* `DSTU2_HL7ORG`
* `DSTU2_1`

The relevant `hapi-fhir-structures` dependencies are missing on the Camel component. In general we can probably be a bit smarter with this in CQ and make things so that individual `hapi-fhir-structures` libs can be added to the classpath as per the users need. It could help to slim down the size of the generated application.

**Comment by ppalaga** [comment]
>  individual hapi-fhir-structures libs can be added to the classpath

Could you please check, whether we manage all necessary pieces in our BOM?

**Comment by jamesnetherton** [comment]
> Could you please check, whether we manage all necessary pieces in our BOM?

That will be part of this change.

**Comment by jamesnetherton** [comment]
> individual hapi-fhir-structures libs can be added to the classpath

Thinking about it a bit more, I wont do this initially. It potentially makes things more difficult for camel-k / kamelet usage.

For now, I'll keep the scope of this issue to just adding support for the versions I mentioned and ponder optimisations in a separate issue.
