### ISSUE TITLE
Camel can not support kafka transactions.

### ISSUE THREAD

**Issue by alexkazan87** [apache/camel-quarkus#3642]
I just started to use camel for a Kafka producer integration with the camel transacted and the JtaTransactionPolicy.
It works very well.

 
Besides it, I need the Kafka Transaction Manager too, so I added the following property:

camel.component.kafka.additional-properties[[transactional.id](http://transactional.id/)]=12345

but an error arises :

 **On delivery attempt: 0 caught: java.lang.IllegalStateException: Cannot perform a 'send' before completing a call to initTransactions when transactions are enabled.**

It seems that Kafka's transaction manager was enabled but it could not be initialized. Have you ever noticed such an error so far?

**Comment by alexkazan87** [comment]
Yes, you are right, `_Kafka transaction does not support JTA_`. 

The main problem is that I enabled the kafka transactions with transaction.id property for exactly once and the camel code before it sent any event, It did not initialize it.  This is not related to transacted(). if the camel team can solve this then we can move to other trouble for me.  

`_I assume that you want to do Kafka transaction within transacted() in camel?_` 
Yes, exactly!

 My main goal, in the end, is to synchronise the JTA(Narayana) with the Kafka transaction manager having only one compact transaction lifecycle through transacted(). This is something that I can manage later by injecting an alternative TransactionManager by using the KafkaTransactionManager. This is a unique feature not only in camel but also in quarkus  - kafka generally.

Code:

     @ApplicationScoped
     public class MyRoute extends RouteBuilder {
     private static final Queue<String> messageQueue = new LinkedBlockingQueue();

    @Inject
    RequiresNewJtaTransactionPolicy requiresNewJtaTransactionPolicy;

    @ConsumeEvent(Constants.MONEY_TRANSFER_EVENT)
    public void pushMoneyEvent(String order) {
        messageQueue .add(order);
    }

    @Override
    public void configure() {

        onException(CamelException.class)
                .backOffMultiplier(2)
                .maximumRedeliveries(5)
                .retryAttemptedLogLevel(LoggingLevel.INFO)
                .handled(true)
                .log("After 5 redeliveries send elk ${body}")
                .process(processor -> {
                            //elk....
                        }
                )
                .end();

        from("timer:foo?period={{timer.period}}&delay={{timer.delay}}")
                .routeId("FromTimer2Kafka")
                .process(exchange -> {
                    if (!messageQueue .isEmpty()) {
                        String pp = messageQueue .poll();
                        exchange.getIn().setHeader("NEW_EVENT", "CREATED");
                        exchange.getIn().setBody(pp);
                    }
                })
                .transacted()
                .policy(requiresNewJtaTransactionPolicy)
                .filter(header("NEW_EVENT").isEqualTo("CREATED"))
                .log("Before process! Event : \"${body}\" with headers  \"${headers}\" ")
                .doTry()
                    .to("kafka:{{kafka.topic.name}}")
                    .log("Message sent to the topic! : \"${body}\" ")
                .doCatch(Exception.class)
                    .log("Exception : ${exception.message}")
                    .process(exchange -> {
                        Exception cause = exchange.getProperty(Exchange.EXCEPTION_CAUGHT, Exception.class);
                        log.error("Exception:{}", cause.getMessage());
                        throw new CamelException(cause.getMessage());
                    })
                .end();
    }
}

**Comment by zhfeng** [comment]
Thanks @alexkazan87 - I will check these codes this week.

**Comment by zhfeng** [comment]
@alexkazan87 I think ```camel-kafka``` does not support transaction right now. So you can see such error message **On delivery attempt: 0 caught: java.lang.IllegalStateException: Cannot perform a 'send' before completing a call to initTransactions when transactions are enabled.**

So I wil take care of https://issues.apache.org/jira/browse/CAMEL-15016 at first to see how we can enable transaction in kafka producer.

**Comment by alexkazan87** [comment]
Thank you @zhfeng! I really appreciate it. If you need help please let me know to check and implement it together!

**Comment by zhfeng** [comment]
@alexkazan87 I rasie https://github.com/apache/camel/pull/7454 and can you take a review? 

```KafkaTransactionPolicy``` can be used just like
```
from("direct:test")
   .transacted().policy(new KafkaTransactionPolicy())
   .to("kafka:topic?additional-properties[transactional.id]=1234&additional-properties[enable.idempotence]=true&additional-properties[retries]=5");
```

**Comment by zhfeng** [comment]
@alexkazan87 I think it will release camel 3.17.0 soon which includes a fix to support kafka transaction. Please can you check it when it is availiable?

**Comment by alexkazan87** [comment]
Sure, thank you!

**Comment by zhfeng** [comment]
@alexkazan87 Camel 3.17.0 is out and will you get a chance to test with the lastest camel-quarkus 2.10.0-SNAPSHOT? I think it should work with `transacted()`, please check the camel-kafka transaction doc https://camel.apache.org/components/3.17.x/kafka-component.html#_kafka_transaction

**Comment by RiddhikChaudhuri** [comment]
@zhfeng  We are using spring-transaction Policy and camel-Kafka. We are using KafkaTransactionManagement inside spring transaction policy and for a simple route we
```
`from("direct:output")
	.transacated()
	.setHeader("EventType","Control)
	.toD("${header.OUTPUT_TOPIC})
	.process(exchange -> {
	throw new RunTimeException("");
	}).
	process(manualCommitProcessor);`
```
Once Runtime exception is thrown but still the Output Topic recieves the message
