### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#37]
- migrate doc from quarkusio here
- update quarkusio doc to point tofdoc here

**Comment by ppalaga** [comment]
I assume using the same asciidoc setup like they have in Quarkus is OK?

**Comment by oscerd** [comment]
No, it's not ok, because the information must be in a suitable format to be published on the camel website. So we need to take as example camel-k or camel

**Comment by ppalaga** [comment]
I am starting to copy the camel-k setup. Plz assign to me.
