### ISSUE TITLE
Reduce the noise in verbose flattened BOMs

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3702]
For me it's becoming a source of confusion / merge conflict pain when the line number comments in the verbose BOMs are constantly being shuffled around.

Is there any value in having the verbose BOMs (or even any of the generated BOMs) checked into git?

If not, maybe we output them to a known location in the `target` directory so that they can still be inspected if desired.

**Comment by ppalaga** [comment]
After thinking of it again, I'd say the line numbers are not useful at all. What matters are the versions and the origin BOM. Those are much more stable. 
Do you think removing the line numbers would reduce enough of the noise?

**Comment by jamesnetherton** [comment]
> Do you think removing the line numbers would reduce enough of the noise?

Yeah I think it would help. Lets try and see how it goes.

**Comment by ppalaga** [comment]
I'll also replace the current project's version literal with something like `${project.version}`. In that way I hope we can avoid any changes during releases.

**Comment by jamesnetherton** [comment]
I think we found an acceptable way forward with this. Much less noise generated since https://github.com/apache/camel-quarkus/commit/171483bdbecc0d1599deb7d3c128e333bd636bb6.
