### ISSUE TITLE
Reduce the number of `timer-log` example projects

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3708]
We could just have a single polyglot `timer-log` example that can demo CDI, Spring, Kotlin & XML in the same app, instead of having separate projects for each.

**Comment by svkcemk** [comment]
@jamesnetherton I would like work on this, can you please assign this to me? Thanks!

**Comment by jamesnetherton** [comment]
@svkcemk do you mind if I take over this task? I'm thinking of adding a new example project but I like to reduce the existing number before I do it.

**Comment by svkcemk** [comment]
Sure @jamesnetherton no worries.

**Comment by jamesnetherton** [comment]
Fixed in https://github.com/apache/camel-quarkus-examples/pull/93.
