### ISSUE TITLE
[Camel 3.17.0] Switch FTP / JSCH extensions to `com.github.mwiede:jsch`

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3711]
Clone of https://github.com/quarkiverse/quarkus-jsch/issues/23. If we don't get this for Camel 3.17.0 then we need to exclude ` com.github.mwiede:jsch` from `camel-ftp` & `camel-jsch`.

**Comment by zbendhiba** [comment]
> `quarkus-jsch` 2.0.0 is out, which is aligned with `com.github.mwiede:jsch`. So we should be all good for Camel 3.17.0.

Good news !
