### ISSUE TITLE
camel-quarkus-openapi-java ArraySchema not registered for reflection

### ISSUE THREAD

**Issue by mbchangellc** [apache/camel-quarkus#3737]
When running a native image, viewing the generated OpenAPI documentation results in a NullPointerException when a property of type List is encountered.  Registering ArraySchema for reflection resolves the issue.  The provided example will throw the exception below when the OpenAPI documentation is generated, if run as a native image.  If the RegisterForReflection annotation in the SwaggerReflectionConfiguration class is uncommented, the OpenAPI documentation is generated as expected, no exception.

Exception
`2022-04-19 19:32:01,381 WARN  [org.apa.cam.ope.RestOpenApiProcessor] (executor-thread-0) Error rendering OpenApi API due null: java.lang.NullPointerException
at org.apache.camel.openapi.RestModelConverters.processSchema(RestModelConverters.java:113)
at org.apache.camel.openapi.RestModelConverters.processSchema(RestModelConverters.java:144)
at org.apache.camel.openapi.RestModelConverters.lambda$processSchema$2(RestModelConverters.java:136)
at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
at org.apache.camel.openapi.RestModelConverters.processSchema(RestModelConverters.java:133)
at org.apache.camel.openapi.RestModelConverters.lambda$readClassOas30$0(RestModelConverters.java:82)
at java.util.TreeMap.forEach(TreeMap.java:1282)
at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1553)
at org.apache.camel.openapi.RestModelConverters.readClassOas30(RestModelConverters.java:79)
at org.apache.camel.openapi.RestModelConverters.readClass(RestModelConverters.java:62)
at org.apache.camel.openapi.RestOpenApiReader.appendModels(RestOpenApiReader.java:1438)
at org.apache.camel.openapi.RestOpenApiReader.parse(RestOpenApiReader.java:253)
at org.apache.camel.openapi.RestOpenApiReader.read(RestOpenApiReader.java:160)
at org.apache.camel.openapi.RestOpenApiSupport.renderResourceListing(RestOpenApiSupport.java:394)
at org.apache.camel.openapi.RestOpenApiProcessor.process(RestOpenApiProcessor.java:75)
at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
at org.apache.camel.component.rest.RestApiProducer.process(RestApiProducer.java:39)
at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:172)
at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:471)
at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:193)
at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:64)
at org.apache.camel.processor.Pipeline.process(Pipeline.java:184)
at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:399)
at org.apache.camel.component.platform.http.vertx.VertxPlatformHttpConsumer.lambda$handleRequest$2(VertxPlatformHttpConsumer.java:187)
at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:545)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:833)
at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)`

Environment:
macOS 12.3.1, Oracle JDK 17, ubi-quarkus-mandrel:22.0.0.2-Final-java17, Quarkus 2.8.0.Final

[camel-openapi-arrayschema-bug.zip](https://github.com/apache/camel-quarkus/files/8516160/camel-openapi-arrayschema-bug.zip)

**Comment by zhfeng** [comment]
Thanks @mbchangellc for reporing and the reproducer is very handy !

We register all of the openapi schema types but missing with ```methods = true```.
