### ISSUE TITLE
KeyStoreParameters is not in reflection list on Salesforce component.

### ISSUE THREAD

**Issue by ismailbaskin** [apache/camel-quarkus#3754]
Camel salesforce component uses KeyStoreParameters for OAuth JWT flow which is recommended way for production. [camel.component.salesforce.keystore](https://camel.apache.org/components/3.16.x/salesforce-component.html#_sb_option_camel_component_salesforce_keystore)

The problem is `org.apache.camel.support.jsse.KeyStoreParameters` is not in reflection list. So, if you want to use camel-salesforce with  OAuth JWT authantication, `KeyStoreParameters` class needs to be added [reflection-config.json](https://quarkus.io/guides/writing-native-applications-tips#including-resources).

**Comment by jamesnetherton** [comment]
How are you configuring the `keystore` option on the Salesforce component?

**Comment by jamesnetherton** [comment]
Also there is no need for `reflection-config.json`. You can use the `RegisterForReflection` annotation.

**Comment by ismailbaskin** [comment]
camel-salesforce [configures keystore](https://github.com/apache/camel/blob/b890d82f929cd79c3e37da7ccf6ae1482ef082d9/components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceLoginConfig.java#L166=) when these properties are available.

```
camel.component.salesforce.keystore.resource=${salesforce.keystore.file}
camel.component.salesforce.keystore.password=${salesforce.keystore.password}
```

It's been a long time since I used Quarkus and I was not aware of RegisterForReflection annotation usage for 3rd party classes. I'll definitely use it, Thank you. However, I don't like to use such workarounds for a library that has Quarkus support.
