### ISSUE TITLE
[Camel 3.17.0] Restore `jakarta-mail-version` placeholder in `jakarta.mail.version` property

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#3771]
Revert of https://github.com/apache/camel-quarkus/pull/3770 once camel is updated.

**Comment by jamesnetherton** [comment]
I'll take care of this on `camel-main` as part of the 3.17.0 upgrade.

**Comment by JiriOndrusek** [comment]
Thanks
