### ISSUE TITLE
Support camel-debug component

### ISSUE THREAD

**Issue by apupier** [apache/camel-quarkus#3775]
The camel-debug component allows an automatic enablement of the Camel debugger. i tis using JMX technology so I guess it woll work only in JVM mode but that would a first very good step.

side note: would it be possible to include the dependency automatically when launch with quarkus:dev?

**Comment by zbendhiba** [comment]
Hello @jamesnetherton : thanks for this contribution.
I'm having a question related to @apupier remark: is this dependency is automatically launched with quarkus:dev or de we need to add it to the pom.xml manually?

**Comment by jamesnetherton** [comment]
The dependency needs to be explicitly added to the project `pom.xml`. It's not really feasible to have this as part of the core.
