### ISSUE TITLE
net.openhft:affinity included in flattened BOM only on Mac

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3788]
Build the project on a Mac and an additional dependency will be mysteriously added to the generated BOMs.

```xml
<dependency>
    <groupId>net.openhft</groupId>
    <artifactId>affinity</artifactId>
    <version>3.20.0</version>
</dependency>
```

Seems it comes from `com.hazelcast:quarkus-hazelcast-client-bom`, presumably from this profile:

https://github.com/hazelcast/quarkus-hazelcast-client/blob/83bb56d193851a94cb21e74eb459de45223db05e/runtime/pom.xml#L101-L113

Not sure if it's possible to detect these types of scenario and prevent the dependencies being added to the BOM, or if we should manually add exclusions for them.

**Comment by ppalaga** [comment]
What happens here is that our tool resolves every single Camel Quarkus extension, it collects all their transitives and based on that set, it removes constraints from our effective BOM that are not relevant to us. Apparently the set of transitives is platform dependent. It this case, we'd want to keep that mac specific constraint in our BOM.

I do not see any way how I could run the resolution over all possible platform specific profiles. Have you encountered anything like this by any chance, @aloubyansky?

I guess, we could whitelist the known cases in the cq plugin config and perhaps also implement some sort of a trap that would check that the content of the profile in the given pom has not changed. That would not solve the detection part. 

Running the cq mojo on all supported platforms would uncover the diffs for sure. Not sure new cases like this are likely enough to add Mac build on our CI?

**Comment by jamesnetherton** [comment]
> Not sure new cases like this are likely enough to add Mac build on our CI?

Probably not. Just that this can be a [source of confusion / annoyance](https://github.com/apache/camel-quarkus/pull/3769#issuecomment-1120989583) for contributors.

**Comment by aloubyansky** [comment]
Right, it looks like a problem for the users of the extension in general.
