### ISSUE TITLE
Using custom camel componet into quarkus-camel

### ISSUE THREAD

**Issue by wuilmeryair** [apache/camel-quarkus#379]
I have a custom component that I want to use in camel-quarkus, how should I convert this component?

**Comment by lburgazzoli** [comment]
In JVM mode your component should work out of the box but if you want to take advantages, you may think creating an extension.

If you plan to contribute it to apache-camel and then add the related extension here, please have a look at: https://camel.apache.org/camel-quarkus/latest/contributor-guide.html or have a look at the extensions we provides in this repo.

**Comment by lburgazzoli** [comment]
@wuilmeryair can we close this issue ?

**Comment by wuilmeryair** [comment]
Yes this issue can be closed

Regards.
