### ISSUE TITLE
Improve camel-quarkus-velocity test coverage

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#3790]
Add tests for:

- Custom Velocity context
- Dynamic templates

**Comment by aldettinger** [comment]
I remember scenarios where velocity is using a lot of reflection. Then, I wonder if it would would be interesting to add more coverage based on camel tests above ?
https://github.com/apache/camel/blob/main/components/camel-velocity/src/test/java/org/apache/camel/component/velocity/VelocityMethodInvokationTest.java
https://github.com/apache/camel/blob/main/components/camel-velocity/src/test/java/org/apache/camel/component/velocity/VelocityBodyAsDomainObjectTest.java

**Comment by JiriOndrusek** [comment]
@aldettinger I can try that. I made the tests according to the documentation. 

Just for your information, there is a lot of coverage already in the repository. 
For example https://github.com/apache/camel-quarkus/blob/main/integration-tests/velocity/src/test/java/org/apache/camel/quarkus/component/velocity/it/VelocityTest.java#L79 and https://github.com/apache/camel-quarkus/blob/main/integration-tests/velocity/src/test/java/org/apache/camel/quarkus/component/velocity/it/VelocityTest.java#L129

(which at first glance should cover both tests you mentioned) 

This PR only adds 2 missing configuration options which were not covered so far.

**Comment by aldettinger** [comment]
@JiriOndrusek Good point. I've double-checked and actually the camel-quarkus `testBodyAsDomainObject` is already covering both. The involved classes just need to be marked as @RegisterForReflection.

I wonder if a cq-velocity specific doc statement would be needed to document that ?

**Comment by JiriOndrusek** [comment]
There is no mention of registering for reflection in the doc - https://github.com/apache/camel-quarkus/blob/main/extensions/velocity/runtime/src/main/doc/configuration.adoc
I'll add a chapter about it and ammend it to this PR.
