### ISSUE TITLE
Registry lookup for overridden `DefaultBean` types does not work

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3797]
The Quarkus Qpid JMS Extension exposes a `ConnectionFactory` `DefaultBean` which can be overridden by users.

If you try to do this in conjunction with the JMS extension, autowiring of the `ConnectionFactory` fails with:

```
IllegalArgumentException: connectionFactory must be specified
```

And the root cause is that the JMS component cannot figure out which `ConnectionFactory` bean to use:

```
Cannot autowire ConnectionFactory as 2 instances found in registry.
```

It seems that the Camel registry [lookup](https://github.com/apache/camel-quarkus/blob/ddf4d9fd2d05ec302deb95354da4063f8138b50a/extensions-core/core/runtime/src/main/java/org/apache/camel/quarkus/core/RuntimeBeanRepository.java#L44) for the `ConnectionFactory` returns both the original `DefaultBean` instance and the overridden one.

Not sure if that's a bug or intended behavior from the `BeanManager`. I noticed some alternate lookup methods on `Arc.container` and  `BeanManager` correctly return only the overridden bean.

**Comment by JiriOndrusek** [comment]
This is intended behavior. Quarkus returns `javax.enterprise.inject.spi.BeanManager`. We are calling method [getBeans](https://docs.oracle.com/javaee/7/api/javax/enterprise/inject/spi/BeanManager.html#getBeans-java.lang.String-) from our [lookup](https://github.com/apache/camel-quarkus/blob/ddf4d9fd2d05ec302deb95354da4063f8138b50a/extensions-core/core/runtime/src/main/java/org/apache/camel/quarkus/core/RuntimeBeanRepository.java#L44).
This method functionality is to return all beans which matches requirements.

```
Return the set of beans which have the given EL name and are available for injection in the module or library containing the class into which the BeanManager was injected or the Java EE component from whose JNDI environment namespace the BeanManager was obtained, according to the rules of EL name resolution.
```

To apply ambiguous dependency resolution (to remove @DefaultBeans), we need to call method [resolve](https://docs.oracle.com/javaee/7/api/javax/enterprise/inject/spi/BeanManager.html#resolve-java.util.Set-) afterwards.

```
Apply the ambiguous dependency resolution rules to a set of [beans](https://docs.oracle.com/javaee/7/api/javax/enterprise/inject/spi/Bean.html).
``` 

There is a catch, method `resolve` returns only 1 bean - not set (see [code](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/ArcContainerImpl.java#L583)). There is another method - which is not accessible through the javax interface, which does almost everything we need (see [code](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/ArcContainerImpl.java#L596)).

I see several options how to solve the problem:

1. In case that we want to solve only `@DefaultBeans`, we should add similar [code](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/ArcContainerImpl.java#L604-L612) into [RuntimeBeanRepository](https://github.com/jboss-fuse/camel-quarkus/blob/camel-quarkus-2.7.1-product/extensions-core/core/runtime/src/main/java/org/apache/camel/quarkus/core/RuntimeBeanRepository.java#L44)
2. In case we want also consider priorities and alternative beans, we have to incorporate more [code](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/ArcContainerImpl.java#L614-L630). 
3. Unfortunately I don't see a way of using existing code from Quarkus. (It is not-public)

From my PoV option 2 should allow users the maximum flexibility.
We might want to remove only `@DefaultBeans` and possibly `@Alternative`, but i'm not sure about it.

WDYT? @jamesnetherton
