### ISSUE TITLE
Changes in health endpoint with camel from Quarkus version 2.7.5 to version >=2.8.0

### ISSUE THREAD

**Issue by turing85** [apache/camel-quarkus#3799]
There were some changes wrt. to the health reporting from quarkus version 2.7.5 to version >=2.8.0.

With 2.7.5, the health endpoint reports:
```
{
  "status": "UP",
  "checks": [
    {
      "name": "camel-liveness-checks",
      "status": "UP"
    },
    {
      "name": "camel-readiness-checks",
      "status": "UP",
      "data": {
        "invocation.count": "1",
        "context.name": "camel-1",
        "success.count": "1",
        "invocation.time": "2022-05-11T21:27:33.92583+02:00[Europe/Berlin]",
        "context.version": "3.14.1",
        "context.status": "Started",
        "failure.count": "0",
        "context": "UP",
        "route.id": "failing-route",
        "route.context.name": "camel-1",
        "route.status": "Started",
        "route:failing-route": "UP",
        "consumer:failing-route": "UP"
      }
    }
  ]
}
```

With 2.8.0, it reports:
```
{
  "status": "UP",
  "checks": [
    {
      "name": "camel-routes",
      "status": "UP"
    },
    {
      "name": "context",
      "status": "UP",
      "data": {
        "context.name": "camel-1",
        "context.version": "3.16.0",
        "context.status": "Started"
      }
    },
    {
      "name": "camel-consumers",
      "status": "UP"
    }
  ]
}
```

### Reproducer:
- checkout [this github repo](https://github.com/turing85/quarkus-camel-circuit-breaker)
- run `./mvn quarkus:dev`
- access http://localhost:8080/q/health
- observe the current (unwanted) response
- in the [`pom,xml`, line 15](https://github.com/turing85/quarkus-camel-circuit-breaker/blob/main/pom.xml#L15), change the version to `2.7.5.FINAL`
- access http://localhost:8080/q/health
- observe the old (wanted) response

**Comment by jamesnetherton** [comment]
The response format was changed for [CAMEL-17426](https://issues.apache.org/jira/browse/CAMEL-17426).

**Comment by turing85** [comment]
@ppalaga @jamesnetherton so not a bug after all?

**Comment by jamesnetherton** [comment]
> @ppalaga @jamesnetherton so not a bug after all?

No it was an intentional change.

**Comment by turing85** [comment]
Okay 👍
