### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#38]
- include camel-quarkus among camel's projects in the upcoming camel [webside](https://camel.apache.org/staging/)
- create a website

**Comment by ppalaga** [comment]
PR sent https://github.com/apache/camel-website/pull/67

**Comment by ppalaga** [comment]
We are there on the staging website (that should go live next week):

* Under projects: https://camel.apache.org/staging/projects/camel-quarkus/
* Under Docs: https://camel.apache.org/staging/camel-quarkus/latest/

The current issue can be closed IMO.

**Comment by ppalaga** [comment]
The new Camel website is live: https://camel.apache.org/projects/camel-quarkus/ https://camel.apache.org/camel-quarkus/latest/
The current issue can be closed
