### ISSUE TITLE
Aws SQS: Remove unnecessary headers from the test because of CAMEL-18123

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#3803]
Fix of https://issues.apache.org/jira/browse/CAMEL-18123, makes some header parameters unnecessary for purge/delete queue actions (i.e. https://github.com/apache/camel-quarkus/blob/main/integration-test-groups/aws2/aws2-sqs/src/main/java/org/apache/camel/quarkus/component/aws2/sqs/it/Aws2SqsResource.java#L86)

**Comment by jamesnetherton** [comment]
The fix for this was merged with the Camel 3.18.0 upgrade in https://github.com/apache/camel-quarkus/commit/3fd34e34225664ad82eeb31bc96eed36a1b82071.
