### ISSUE TITLE
Configuration of ActiveMQ broker URL properties may require reflective access

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3809]
Observation from a stackoverflow.com post:

https://stackoverflow.com/questions/72366070/unable-to-pass-activemq-configuration-in-quarkus-native-build-with-camel-setup

AFAIK we do not test with many (or any) properties set in the broker URL. We are probably missing registering various classes for reflection to make it work properly.

**Comment by zhfeng** [comment]
Good catch! so @jamesnetherton you think we should apply these refections in that post into `camel-quarkus-activemq`?

**Comment by jamesnetherton** [comment]
> Good catch! so @jamesnetherton you think we should apply these refections in that post into `camel-quarkus-activemq`?

Maybe not all of them. `SSLSocketImpl` I assume would be registered if `quarkus.ssl.native=true`.

There is probably extra stuff that needs registering too. I've not looked at the full list of possible broker URL properties.

**Comment by zhfeng** [comment]
It looks like we need to add all implementor of `Transport` and `org.apache.activemq.command.ConsumerInfo`, maybe others.
`activemq` uses `IntrospectionSupport.setProperties` to do the reflection, I'm invesigating it is used.
