### ISSUE TITLE
foundation-grouped tests seems to be flaky since upgrade to camel 3.17.0

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#3819]
Spotted 3 occurences up to now:
https://github.com/apache/camel-quarkus/runs/6516157679?check_suite_focus=true#step:9:36230
https://github.com/apache/camel-quarkus/runs/6567639507?check_suite_focus=true#step:9:36249
https://github.com/apache/camel-quarkus/runs/6625038572?check_suite_focus=true#step:8:5764

Two times in `integation-tests-alternative-jdk` and once in `Native tests - group-03`.

**Comment by jamesnetherton** [comment]
I already raised tihis in https://github.com/apache/camel-quarkus/issues/3798 when I did the 3.17.0 upgrade.

**Comment by aldettinger** [comment]
Sure, I forgot to double check existing issues. I'm gonna close in favor of #3798. Thanks for reporting.
