### ISSUE TITLE
Support path parameters in platform-http

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#382]
I wonder if its in the rest-platform that we dont support rest-dsl with path placeholders

```
@ApplicationScoped
public class MyCamel extends RouteBuilder {

    @Override
    public void configure() throws Exception {
        rest("/camel/").produces("text/plain")
            .get("{id}").to("bean:myBean");
    }
}
```

You can then not do localhost:8080/camel/123

This works in regular Camel

**Comment by ppalaga** [comment]
This probably needs to get fixed in `QuarkusPlatformHttpConsumer`. I remember I ignored the path params because I had no idea how to use them from Camel.

**Comment by ppalaga** [comment]
I can fix this at some point unless somebody is faster than me.

**Comment by ppalaga** [comment]
Could you please rename this issue to e.g. "Support path parameters in platform-http"?

**Comment by lburgazzoli** [comment]
@ppalaga any chance you can look at this before we cut the next release ?

**Comment by ppalaga** [comment]
Yes, I can start looking today :)
