### ISSUE TITLE
rest-dsl - Integrate with quarkus-openapi

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#383]
If you create camel rest-dsl routes then we should have a way of integrating with quarkus openapi extension.

So when you do an /openapi then it can also include the camel rest-dsl services

**Comment by davsclaus** [comment]
We may need to create a camel-openapi component that supports spec v3
https://issues.apache.org/jira/browse/CAMEL-12619

**Comment by jamesnetherton** [comment]
Addressed by https://github.com/apache/camel-quarkus/commit/c8db766c2296d909f4157aa44d66fd95caebba0c.
