### ISSUE TITLE
Extend test coverage for aws-secrets-manager

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#3848]
Follows https://github.com/apache/camel-quarkus/issues/3741.

Refactor (to use LocalStack) does not cover all usecases from the [documentation](https://camel.apache.org/components/3.16.x/aws-secrets-manager-component.html).

There are 2 items, which are not covered:

- [SING AWS SECRETS MANAGER PROPERTY FUNCTION](https://camel.apache.org/components/3.16.x/aws-secrets-manager-component.html#_using_aws_secrets_manager_property_function)
- operation `replicateSecretToRegions`

**Comment by jamesnetherton** [comment]
Fix back in https://github.com/apache/camel-quarkus/commit/cf21d5a0ba1204f44253f3d6fcf5352b27c8f9a9.
