### ISSUE TITLE
Consider removing configuration for `camel.main.source-location-enabled`

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3858]
Thinking about https://github.com/apache/camel-quarkus/pull/3628, all of the magic to make the source location bits work seems to happen at runtime. 

I'm wondering what we gain by setting a simple `boolean` property on the `CamelContext` at build time?

Unless I'm missing something, It seems to be no different than simply having `camel.main.sourceLocation​Enabled = true` in `application.properties`. If that's the case, then our special CQ code is redundant.

**Comment by zhfeng** [comment]
I think `camel.main.sourceLocationEnabled` is only affected with `CamelMainRuntime`. There is a other simple implementation `CamelContextRuntime`, so I think `camel.quarkus.source-location-enabled` is still meaningful.

**Comment by zhfeng** [comment]
OK, I recall that @davsclaus mention in https://github.com/apache/camel-quarkus/issues/3432 that if we enable it, that can capture the source location : line-number for all the DSLs at build time. 

I agree to make it part of `CamelConfig`.

I don't remember that there is `camel.context.source-location-enabled` and it looks like `CamelContextRuntime` is never used now. Only `CamelMainRuntime` is default to create and bootstrap.

**Comment by zbendhiba** [comment]
@jamesnetherton @zhfeng We should definitely think of naming when we add a new property
