### ISSUE TITLE
@Inject CamelContext on RouteBuilder seems not working

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#386]
```
@ApplicationScoped
public class MyCamel extends RouteBuilder {

    @Inject
    private CamelContext camel;

    @Override
    public void configure() throws Exception {
        from("timer:foo").routeId("myRoute").
                process(exchange -> System.out.println(camel));
    }
}
```

This prints null

**Comment by lburgazzoli** [comment]
this is probably because it is loaded by classpath scanning thus it bay pass arc. We should have a way to distinguish between auto discovered routes from classpath and ‘runtime routes’.

**Comment by lburgazzoli** [comment]
remember the discussion about adding a custom annotation or leveraging BindToRegistry

**Comment by davsclaus** [comment]
Argh yeah this rings a bell.

**Comment by davsclaus** [comment]
See PR
https://github.com/apache/camel-quarkus/pull/358

**Comment by ppalaga** [comment]
Yes, there are issues with `@Inject` in RouteBuilder. But if you only need the CamelContext, you can call getContext() from `configure()`.

**Comment by davsclaus** [comment]
See ticket #136
