### ISSUE TITLE
Increase XSLT extension test coverage

### ISSUE THREAD

**Issue by zhfeng** [apache/camel-quarkus#3904]
- complete URL (classpath, file, http, ref, bean)
- different outputs (string, bytes, dom, file)
- using xsl:include to include files
- custom `XsltUriResolverFactory`
- custom `URIResolver`
- using `org.apache.camel.component.xslt.XsltAggregationStrategy`
- caching
- Being able to raise errors with xsl:message and messages getting into `Exchange.XSLT_ERROR`, `Exchange.XSLT_FATAL_ERROR`, or `Exchange.XSLT_WARNING`

**Comment by zhfeng** [comment]
`ref` and `bean` URI will generate xslt templates dynamically at runtime. So I think it could not be supported in native mode.

**Comment by ppalaga** [comment]
> ref and bean URI will generate xslt templates dynamically at runtime. So I think it could not be supported in native mode.

Yeah, those cases are harder, but still perhaps doable to some extent, as long as the XSLT stuff is known at build time. Of course, if the user generates XSLT resources dynamically at runtime, it won't work in native mode. But if he only has a `@Named` singleton bean that he uses in a `ref` URI, then it could perhaps work with some additional config or a new dedicated annotation, something like `@XsltResource("foo/bar.xsl")`. Then we could scan for those `@XsltResource` annotations at build time and simply replace `ref:beanName` for `classpath:foo/bar.xsl`. Maybe if we had [buildtime routes introspection API](https://issues.apache.org/jira/browse/CAMEL-16212) even the additional config/annotation would not be needed.
I am not sure how much cases we could cover like this and I am not sure at all whether this is worth the effort. Perhaps not at this time, we might have more important things to do.

**Comment by zhfeng** [comment]
There is a [CAMEL-18266](https://issues.apache.org/jira/browse/CAMEL-18266) issue with `xslt:bean` currently.
