### ISSUE TITLE
camel-validator component

### ISSUE THREAD

**Issue by ploef** [apache/camel-quarkus#391]
Hi,

I'm converting some of my Spring Boot services to Quarkus and see that the camel-validation-component is missing. I will try to create an extension for it.

**Comment by ppalaga** [comment]
Nice to hear that! Do not hesitate to ask here if you have specific questions. You might want to check https://camel.apache.org/camel-quarkus/latest/contributor-guide.html

**Comment by davsclaus** [comment]
Just mind you may need to add the new extensions to some pom files in the poms folder. The create extension tool dont get around doing all that 100%.

**Comment by ploef** [comment]
Thanks for the tip! I already managed to get it working locally.

**Comment by ploef** [comment]
Hmmm, the checks after the pull requests keep turning red. Locally everything seems fine. Code builds ok and tests are green. It looks like the dependency for camel-quarkus-support-xml is missing but it should be there.

**Comment by lburgazzoli** [comment]
It fails on JDK 11 because the class `com.sun.org.apache.xerces.internal.impl.dv.xs` is probably hidden in a module

**Comment by davsclaus** [comment]
Thanks for the work, you are welcome to work on more extensions.

**Comment by ploef** [comment]
Thanks. There was a little research involved so I hope everything is ok. :-D

**Comment by ppalaga** [comment]
Thanks from my side too. 

Is there anything we should improve to make contributions like yours easier? There is https://github.com/apache/camel-quarkus/issues/364 open for the improvements in the contributor guide.
