### ISSUE TITLE
Http Timeout Parameter Fails when compiled Natively 

### ISSUE THREAD

**Issue by DiegoBetancourtC** [apache/camel-quarkus#3924]
I have the following camel-quarkus code:

```
from("direct:service")
    .process(new Processor() {
        public void process(Exchange exchange) throws Exception {
            exchange.getIn().setBody("Test");
        }
    })
    .to("http://some-url?bridgeEndpoint=true&connectTimeout=2000&connectionsPerRoute=500&maxTotalConnections=1000&throwExceptionOnFailure=false)
    .log("Body : ${body}");

rest("/v1")
    .post("/something")
        .to("direct:service");
```

When I run the code using the command:

`./mvnw clean compile quarkus:dev`

everything works without any issue (even the timeout parameter), but when I compile the code natively with the command:

`./mvnw package -Pnative`

and I start the application, I get this error:

```
ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: http://some-url?bridgeEndpoint=true&connectTimeout=2000&connectionsPerRoute=500&maxTotalConnections=1000&throwExceptionOnFailure=false due to: There are 1 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{connectTimeout=2000}] 
```

**Camel Version:** 3.17.0
**Quarkus Version:** 2.10.2.Final
**JVM:** GraalVM 22.1.0.0-Final Java 11 Mandrel Distribution

Why it fails when compiled natively?

Thanks

**Comment by zhfeng** [comment]
Thanks @DiegoBetancourtC for reporting and I think we could miss some reflection configurations in the camel-quarkus-http extension. I will take a look.
