### ISSUE TITLE
[Quarkus 2.12.0] Figure out how to test `js-dsl` in native mode

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3961]
Quarkus has updated its `main` branch to GraalVM 22.2.0. In this release, JavaScript support is decoupled from the base GraalVM installation. Thus the exiting option we use to enable JS support no longer works:

```
<quarkus.native.additional-build-args>--language:js</quarkus.native.additional-build-args>
```

You now have to:

```
gu install js
```

The question is, how to do this for the CI build, where our native builds are done in Docker containers.

**Comment by zhfeng** [comment]
Is it possible to add it in 
https://github.com/quarkusio/quarkus-images/blob/main/modules/graalvm/22.2.0-java17/configure?
