### ISSUE TITLE
Duplicate BOM dependency declaration `org.apache.santuario:xmlsec`

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3978]
We now have two dependency declarations for `xmlsec`:

https://github.com/apache/camel-quarkus/blob/main/poms/bom/pom.xml#L10258-L10277

**Comment by javaduke** [comment]
I think it's my fault, sorry about it. The `quarkus-cxf` uses a newer version of `xmlsec` than the `camel-quarkus-xmlsecurity`.

**Comment by jamesnetherton** [comment]
Looks like this was fixed in https://github.com/apache/camel-quarkus/commit/21f9acb06451c79aa2f7532cb64abfec881d5ee9#diff-2cdf2d35793fae7cd8f70171d04de916f2a6c295b19f099a0aea50589be615b4.

**Comment by ppalaga** [comment]
Nothing escapes @jamesnetherton 's eagle's sight :)
