### ISSUE TITLE
Mapstruct: native support

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#3994]
There is a new component
https://github.com/apache/camel/tree/main/components/camel-mapstruct

Camel Quarkus could do build time optimization as we in the default implementation does classpath scanning to find mapstruct Mapper interfaces.
https://github.com/apache/camel/blob/main/components/camel-mapstruct/src/main/java/org/apache/camel/component/mapstruct/DefaultMapStructFinder.java#L100

Also maybe quarkus has some special mapstruct extension as well that does this, so the CEQ extension can use that.

**Comment by davsclaus** [comment]
There is also a plain camel example at
https://github.com/apache/camel-examples/tree/main/examples/mapstruct

**Comment by zbendhiba** [comment]
The extension was created in JVM only. This issue concerns the addition of native support and integration tests
