### ISSUE TITLE
Initial source code - Add license headers

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#4]
The source code should have ASF license headers in java / xml files etc, just like Apache Camel project

**Comment by ppalaga** [comment]
You mean the headers should be changed also in files coming from the Quarkus repo? I have `Thou shall not change license/copyright/authors headers when copying third party code` stored somewhere deep in my brain. What would be the legal reasoning to break this rule?

**Comment by davsclaus** [comment]
Yes after the initial port we should migrate it to have ASF license headers and packaging name and so on.

We cannot accept source code that is not ASF license header. And the code donation is where you give over the code to ASF

**Comment by lburgazzoli** [comment]
@ppalaga I'm taking it as I'm working to something related

**Comment by ppalaga** [comment]
> I'm taking it as I'm working to something related

No problem, just note that I am in the process of refactoring the package names and it would be hard for me solve any conflicts.

**Comment by lburgazzoli** [comment]
https://github.com/apache/camel-quarkus/pull/22
