### ISSUE TITLE
Provide a ready to use master component for kubernetes

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#4006]
I'm slowly working on the migration of camel-k-runtime to camel-quarkus and one of features that camel-k has is to provide a number of configuration options to enable a kubernetes based master component. 

```properties
camel.k.customizer.master.configMapName = lock
camel.k.customizer.master.labelKey = foo
camel.k.customizer.master.labelValue = bar
```

Moving this to camel-quarkus would be probably straightforward but I want to ask what is the right name for the properties to use:

```properties
quarkus.camel.master.kubernetes.name = lock
quarkus.camel.master.kubernetes.label-key= lock
quarkus.camel.master.kubernetes.label-value= lock
```

**Comment by lburgazzoli** [comment]
@davsclaus @ppalaga @jamesnetherton @zbendhiba what do you think ?

**Comment by jamesnetherton** [comment]
Does the component have any practical usage outside of camel-k? Wondering for anything camel-k specific that we should maybe keep the `camel.k` namespace? Otherwise `quarkus.camel.master.kubernetes` seems ok to me.

/CC @aldettinger who I think is about to start taking a deeper look into the 'normal' master component.

**Comment by lburgazzoli** [comment]
I think it make sense also outside camel-k
In fact what camel-k does is setting up the master component to use kubernetes as the cluster service that is sued behind the scenes and nothing more.

We can also use the same conventions to configure other cluster services, i.e in this [master test ](https://github.com/apache/camel-quarkus/blob/main/integration-tests/master/src/main/java/org/apache/camel/quarkus/component/master/it/MasterRoutes.java#L36-L40) we would be able to use properties instead of programmatic configuration

```properties
quarkus.camel.master.file.root = lock
quarkus.camel.master.file.acquire-lock-delay = 1s
quarkus.camel.master.file.acquire-lock-interval = 1s
```

**Comment by jamesnetherton** [comment]
> We can also use the same conventions to configure other cluster services

So this overlaps with https://github.com/apache/camel-quarkus/issues/3918?

**Comment by lburgazzoli** [comment]
> > We can also use the same conventions to configure other cluster services
> 
> So this overlaps with #3918?

oh I missed that, let me close this then

**Comment by lburgazzoli** [comment]
Duplicate of https://github.com/apache/camel-quarkus/issues/3918
