### ISSUE TITLE
Camel 3.19 - Add camel-cli-connector extension

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#4051]
We have this for SB at
https://github.com/apache/camel-spring-boot/tree/main/dsl-starter/camel-cli-connector-starter

We need an extension for quarkus.

There is an option you can configure to turn this on|off
https://github.com/apache/camel-spring-boot/blob/main/dsl-starter/camel-cli-connector-starter/src/main/java/org/apache/camel/springboot/cli/connector/CliConnectorConfiguration.java#L30

And this code will auto configure the `CliConnectorFactory` in the registry
https://github.com/apache/camel-spring-boot/blob/main/dsl-starter/camel-cli-connector-starter/src/main/java/org/apache/camel/springboot/cli/connector/CliConnectorAutoConfiguration.java

The quarkus extensions could do something similar.

**Comment by davsclaus** [comment]
This also requires camel-console to be made as an extension

**Comment by davsclaus** [comment]
See #4274

**Comment by svkcemk** [comment]
Hello I would like to work on this extension! feel free to assign, thanks !

**Comment by davsclaus** [comment]
@svkcemk are you working on this, if not, then IMHO it would be good to unassign as this is needed

**Comment by svkcemk** [comment]
@davsclaus I am working on it I will create a PR shortly, sorry for delays!

**Comment by svkcemk** [comment]
PR raised : https://github.com/apache/camel-quarkus/pull/4465
