### ISSUE TITLE
Springless JPA extension

### ISSUE THREAD

**Issue by zhfeng** [apache/camel-quarkus#4084]

**Comment by zhfeng** [comment]
We have to revert the current fix due to https://github.com/apache/camel-quarkus/issues/4279. It is because we introduce a fake `PlatformTransactionManager` to make graal native building happy. But it is incompatiable with the other extensions such as `camel-quarkus-jms` which depends on `spring-tx`.

Possible changes with came-jpa:

- Deprecated PlatformTransactionManger on camel-jpa component level in 3.x and remove it in camel 4.x
- All related set/get method should be moved to DefaultTransactionStrategy which depends on spring-tx to do the transaction operations (commit / rollback)
- Discuss these changes with the upstream community at first

**Comment by ppalaga** [comment]
@zhfeng is there any chance to get the required changes to Camel 4?

**Comment by zhfeng** [comment]
Yeah, I already deprecated `transactionManager` in [CAMEL-18742](https://issues.apache.org/jira/browse/CAMEL-18742) but have not got a chance to remove it in Camel 4. I will create a ticket on Camel to track it.

**Comment by zhfeng** [comment]
https://issues.apache.org/jira/browse/CAMEL-19225

**Comment by zhfeng** [comment]
I open an upstream PR to remve `transactionManager`
- https://github.com/apache/camel/pull/10954

**Comment by zhfeng** [comment]
This should be fixed.
