### ISSUE TITLE
[Camel 3.19.0] Kubernetes: tests + native has to be disabled until Quarkus 2.14

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#4095]
See more details in https://github.com/apache/camel-quarkus/issues/4083

The problem is caused by the fact that camel 3.19 upgraded kubernetes-client to 6.x and Quarkus 2.13 uses kubernetes-client 5.x

Clients 5.x and 6.x are not compatible. Quarkus 2.13 will stay on 5.x until Quarkus 2.14.

Once problem is gone, enable native build and enable the tests in the kubernetes tests extension.

**Comment by JiriOndrusek** [comment]
The same problem is with master-opensshift/.../MasterOpenShiftTest#testFailover

**Comment by jamesnetherton** [comment]
Closing as it's out of date now.
