### ISSUE TITLE
OGNL language support

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#410]
https://camel.apache.org/components/latest/ognl-language.html

**Comment by jamesnetherton** [comment]
This isn't so easy to get working in native mode. I forgot the ognl library relies heavily on javassist :disappointed:

**Comment by davsclaus** [comment]
I guess its the same with camel-groovy ?

**Comment by lburgazzoli** [comment]
plus you need to register your business classes for reflection

**Comment by ppalaga** [comment]
Let's JVM only.
