### ISSUE TITLE
[Camel 3.19.0] Google-secrets-manager: Remove workaround after fix of CAMEL-18520

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#4103]
`camel-main` can notbe compiled until https://github.com/apache/camel/pull/8388 is merged. For that reason I forced some versions in our pom (you can see all relevant changes here - https://github.com/JiriOndrusek/camel-quarkus/commit/dde8cbacf087734a0afa9bb1590d6869be9a3651)

Once https://github.com/apache/camel/pull/8388 is merged, please remove the workaround from `camel-main`.

**Comment by JiriOndrusek** [comment]
The same problem with google-functions. Remove workaround when https://issues.apache.org/jira/browse/CAMEL-18524 is fixed. (workaround adds

```
            <dependency>
                <groupId>com.google.auto.value</groupId>
                <artifactId>auto-value-annotations</artifactId>
                <version>${google-auto-value-annotations.version}</version>
            </dependency>
``` 
into the bom)

**Comment by JiriOndrusek** [comment]
Fixed is amended into `camel-main`. Issue could be closed.

**Comment by jamesnetherton** [comment]
Out of date.
