### ISSUE TITLE
Missing virtualDependencies in some integration tests support usage

### ISSUE THREAD

**Issue by llowinge** [apache/camel-quarkus#4107]
Eg. this dependency https://github.com/apache/camel-quarkus/blob/main/integration-test-groups/foundation/customized-log-component/pom.xml#L35 needs to have `-deployment` counterpart built first. Which is done via the virtualDependencies logic, which is missing.

**Comment by jamesnetherton** [comment]
Maybe we would need to tweak the `cq-maven-plugin` to do this.

Those 'support' extensions are excluded from processing:

https://github.com/apache/camel-quarkus/blob/main/pom.xml#L425

If we remove that exclusion, then we end up with redundant stuff added to `catalog/pom.xml`. Not sure if there's a way to prevent that. Maybe @ppalaga knows.

**Comment by ppalaga** [comment]
Sorry, I do not know from top of my head either. We probably need to split the set of extensions for Catalog generation from the set for adding virtual deps. A PR to the cq plugin would be welcome.

**Comment by jamesnetherton** [comment]
Fixed in the 3.0.0-M2 release here https://github.com/apache/camel-quarkus/pull/4829.
