### ISSUE TITLE
Can't authenticate using quarkus elasticsearch-rest

### ISSUE THREAD

**Issue by MarcoMartins86** [apache/camel-quarkus#4194]
Hi, I can't authenticate using elasticsearch-rest component with quarkus, it works without quarkus by defining in application.properties 
```
camel.component.elasticsearch-rest.user
camel.component.elasticsearch-rest.password
```
Not sure if I'm missing something but I have a reproducer.
https://github.com/MarcoMartins86/camel-quarkus-elasticsearch-rest -> Not working

For comparison, this is the same routes but without quarkus
https://github.com/MarcoMartins86/camel-elasticsearch-rest -> Working

**Comment by zbendhiba** [comment]
Hello @MarcoMartins86 
The camel-quarkus extension leverages the Quarkus elastic search extension, as described here : https://camel.apache.org/camel-quarkus/2.13.x/reference/extensions/elasticsearch-rest.html#extensions-elasticsearch-rest-usage

So either you disable authowiring, either you use Quarkus configuration
```
quarkus.elasticsearch.hosts
quarkus.elasticsearch.username
quarkus.elasticsearch.password
...
```

**Comment by MarcoMartins86** [comment]
Thank you for pointing me in the correct direction, I missed the Camel Quarkus documentation entirely and was only looking into the Camel one.
