### ISSUE TITLE
XmlTest.aggregate() test fails on the platform

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#4255]
... because it reads files from the local filesystem. Those files should either be copied from class path to a temp folder or even better should be passed to the route via RESTeasy to avoid the need for camel-file dependency altogether.

**Comment by zhfeng** [comment]
Hmm, it is only `aggregate()` failing? I think there are other tests which also reading file from local filesystem.

**Comment by ppalaga** [comment]
It was with CQ 2.13.1. Maybe we have more tests in 2.14.0? @zbendhiba just filed https://github.com/apache/camel-quarkus/issues/4258

**Comment by ppalaga** [comment]
I think https://github.com/apache/camel-quarkus/issues/4258 should be handled as a duplicate of this one.
