### ISSUE TITLE
[Quarkus 2.14] XML intergration tests are failing in Quarkus platform

### ISSUE THREAD

**Issue by zbendhiba** [apache/camel-quarkus#4258]
log
`2022-11-07 21:43:31,976 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /xml/xslt-file failed, error id: e7117980-b2c5-4cb1-b7f4-cb611f93b9ce-1: org.jboss.resteasy.spi.UnhandledException: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: xslt://file:src/main/resources/xslt/classpath-transform.xsl due to: javax.xml.transform.TransformerException: java.io.FileNotFoundException: src/main/resources/xslt/classpath-transform.xsl does not exists`

**Comment by zhfeng** [comment]
@zbendhiba is there any way to reproducer this platform test issue locally?

**Comment by zhfeng** [comment]
OK, I can run tests locally. 

I think `XmlTest` has a test to verify the `file` schema is working. So I wonder if we can extract these xsl files from the test bundle?

**Comment by zhfeng** [comment]
I tried to add the following plugin to unpack thest files:
```xml
     <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>unpack</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                     <groupId>org.apache.camel.quarkus</groupId>
                                     <artifactId>camel-quarkus-integration-test-xml</artifactId>
                                    <outputDirectory>src/main/resources</outputDirectory>
                                    <includes>**\/*.xsl</includes>
                                </artifactItem>
                                <artifactItem>
                                     <groupId>org.apache.camel.quarkus</groupId>
                                     <artifactId>camel-quarkus-integration-test-xml</artifactId>
                                     <type>test-jar</type>
                                     <classifier>tests</classifier>
                                     <outputDirectory>src/test/resources</outputDirectory>
                                     <includes>**\/*.xml</includes>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
       </plugin>
```

@ppalaga @zbendhiba Do you think this is a right way? I think can add this change in `src/main/resources/xslt/camel/test-pom.xsl`.

**Comment by zhfeng** [comment]
I test with this fix and it works locally.

**Comment by ppalaga** [comment]
No, any additional config in pom.xml makes it more complicated on the platform. I'd vote for either passing the XML content over RESTeasy to camel routes, or in case it does not make sense (because e.g. we test the ability of XSLT component to read local files) then the resources can be copied to some directory under target from the test code. In that way the test behaves in the same way in CQ and in the Platform.

**Comment by zhfeng** [comment]
Thanks @ppalaga and I see your point!
