### ISSUE TITLE
camel-json-path extension

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#426]

**Comment by aldettinger** [comment]
I will have a try with this one. If anybody is already working on it, please report.

**Comment by lburgazzoli** [comment]
@aldettinger do you have any update on this extension ?

**Comment by aldettinger** [comment]
yep, still on it. I think I will have time for this in the coming days.

**Comment by aldettinger** [comment]
Follow up on #610 and #611. Closing this ticket.
