### ISSUE TITLE
perf-regression: write the report to disk

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#4263]
My understanding is that the final report is only written to the console. I have run the benchmark yesterday, but forgot about it and I have shut down the PC without copying the report. I wonder if it would be possible to write final report to disk for forgetful people like me?

**Comment by ppalaga** [comment]
I wonder whether it is possible to transform these numbers from the two version log files into the console report @aldettinger ?

```
Version       Requests  duration     Latency Avg  Stdev    Max       Requests/sec
2.13.0 JVM    4834089   600.016 s    12.38 ms     2.17 ms  327.16 ms 8056.60
2.13.1 JVM    4756800   600.016 s    12.58 ms     1.87 ms  295.70 ms 7927.79
2.13.0 Native 3311342   600.024 s    18.09 ms     3.19 ms  52.17 ms  5518.68
2.13.1 Native 3296267   600.023 s    18.17 ms     3.03 ms  55.84 ms  5493.57
```

**Comment by aldettinger** [comment]
Writing the report to file by default would definitely provide value. There are already log files produced, I would tend to think that the final report should be produced in yet another file.
