### ISSUE TITLE
The used Quarkus version in camel-quarkus 2.13.1

### ISSUE THREAD

**Issue by bvahdat** [apache/camel-quarkus#4278]
Hi

Given the vote: https://lists.apache.org/thread/jsjgb6f0wbcbtp7hlsqrnspsqztkzdjs

`camel-quarkus:2.13.1` declares Quarkus `2.13.3.Final` as it´s runtime:

https://github.com/apache/camel-quarkus/blob/2.13.1/pom.xml#L62

However Quarkus `2.13.3.Final` seems to make use of `camel-quarkus:2.13.0` and not `camel-quarkus:2.13.1`, followng one dependency example for it:

https://github.com/quarkusio/quarkus-platform/blob/2.13.3.Final/generated-platform-project/quarkus-camel/bom/pom.xml#L2605

However looking at Quarkus `2.13.4.Final` for the same dependency, then the version seems to be correct:

https://github.com/quarkusio/quarkus-platform/blob/2.13.4.Final/generated-platform-project/quarkus-camel/bom/pom.xml#L2667

So shouldn´t `camel-quarkus:2.13.1` declare Quarkus `2.13.4.Final` as it´s target runtime?

**Comment by bvahdat** [comment]
If I would make use of Quarkus `2.13.3.Final` together with `camel-quarkus:2.13.1` as per VOTE statement I have seen above, then I would get conflicting camel versions, causing camel `3.18.2` become available on the classpath.

So are you suggesting to better make use of Quarkus `2.13.4.Final` together with `camel-quarkus:2.13.1`?

**Comment by jamesnetherton** [comment]
> So are you suggesting to better make use of Quarkus 2.13.4.Final together with camel-quarkus:2.13.1?

Yes. If you import `io.quarkus.platform:quarkus-camel-bom:2.13.4.Final` in your application you'll get those versions.

**Comment by bvahdat** [comment]
Thanks @jamesnetherton that's actually what I have already tried out which solves the Camel version conflicts we have run into after the upgrade, but the problem is that there is no matching version of `quarkus-pooled-jms` and `quarkus-artemis` to be used along the way together with `Quarkus 2.13.4.Final`.

- `quarkus-pooled-jms`: https://github.com/quarkiverse/quarkus-pooled-jms/blob/1.0.5/pom.xml#L23
- `quarkus-artemis`: https://github.com/quarkiverse/quarkus-artemis/blob/2.0.0/pom.xml#L32

The newer versions of the 2 extensions above make use of Quarkus `2.14.0.Final` which would push Camel `3.19.0` extensions into the classpath, a non-LTS version I don't want to go with.

So you see the problem? I wan to  stick to the same Quarkus version as for `camel-quarkus`, `quarkus-pooled-jms` and `quarkus-artemis` using the latest Camel LTS version, but this seems not to be possible.

**Comment by jamesnetherton** [comment]
> The newer versions of the 2 extensions above make use of Quarkus 2.14.0.Final which would push Camel 3.19.0 extensions into the classpath

Usually you would import `io.quarkus.platform:quarkus-bom:2.13.4.Final` & `io.quarkus.platform:quarkus-camel-bom:2.13.4.Final` before any other BOMs in `dependencyMangement`. That effectively fixes the Quarkus version used in the application.

So you could then proceed to add your `quarkus-pooled-jms:1.0.5` and `quarkus-artemis:2.0.0` dependencies. They should work ok with Quarkus 2.13.4.Final. Maybe @zhfeng can confirm.

**Comment by zhfeng** [comment]
yeah, I think it should work.

**Comment by zhfeng** [comment]
@bvahdat have you been trying to use `quarkus.artemis.enabled=true`? I think it needs to be enabled when upgrading to `quarkus-artemis:2.0.0`. see https://quarkiverse.github.io/quarkiverse-docs/quarkus-artemis/dev/index.html#_configuration_detection_at_build_time

**Comment by bvahdat** [comment]
Thanks @zhfeng that did the trick!

>The `autowired` property is not set on the `connectionFactory` property of `JmsConnectionFactory`, so wondering why it works in the first place when using Quarkus >2.13.3.Final or previous versions. Seems to be the magic happening in quarkus-pooled-jmsor something.

Can you please point me to the place where this "autowiring" is happening? Still can´t get my head around this.

**Comment by zhfeng** [comment]
yeah, it is happening in the camel. Please see https://camel.apache.org/components/3.18.x/jms-component.html#_component_option_allowAutoWiredConnectionFactory

**Comment by bvahdat** [comment]
> yeah, it is happening in the camel. Please see https://camel.apache.org/components/3.18.x/jms-component.html#_component_option_allowAutoWiredConnectionFactory

Thanks, indeed I´ve missed it where this´s happening:

https://github.com/apache/camel/blob/camel-3.19.0/components/camel-jms/src/main/java/org/apache/camel/component/jms/JmsComponent.java#L1046-L1051
