### ISSUE TITLE
Migrate camel-k-runtime quarkus extensions into camel-quarkus

### ISSUE THREAD

**Issue by claudio4j** [apache/camel-quarkus#4283]
camel-k-runtime used to host some camel components and its quarkus extensions suitable for camel-k project, however today all camel components are already in camel, only the quarkus extensions remained in camel-k-runtime project.

It seems appropriate to move all camel-k-runtime quarkus extensions into camel-quarkus project.

**Comment by claudio4j** [comment]
I plan to work on this by working on a personal branch and later requesting review.

**Comment by claudio4j** [comment]
Inspecting the camel-k-runtime project, these are the structure and aspects to be migrated to camel-quarkus
- `docs`: These pages lists the languages and how it works in Camel K, this is specific to Camel K and should not me migrated to camel-quarkus, but shoud go to Camel K documentation. They are [published in Camel K website](https://camel.apache.org/camel-k/next/languages/groovy.html)
- `examples`: Migrate to https://github.com/apache/camel-quarkus-examples
- `camel-k-*` quarkus extensions: Migrate to camel-quarkus, some of them like cloudevents, cron, knative, master,  webhook already exists in camel-quarkus, but are different. Other extensions as resume-kafka, runtime, are not present. These migrations are expected to be the main effort to bring into camel-quarkus
- `itests`: Migrate as the quarkus extensions above.
- `catalog`: Adapt to the camel-quarkus catalog and extend it whenever necessary.

There are some aspects relevant only to Camel K and we should not add these concerns to camel-quarkus, but look for ways to adapt Camel K to use camel-quarkus directly, this is yet to be discovered along the migration process.

**Comment by jamesnetherton** [comment]
> `examples`: Migrate to https://github.com/apache/camel-quarkus-examples

I don't see those camel-k-runtime projects adding any real value given that we have [camel-k-examples](https://github.com/apache/camel-k-examples).

**Comment by claudio4j** [comment]
A description of each module (comprising of code), worth migrating.

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-e18ceb0b-7fff-178a-18af-b1e5536c0b7c">

Component name | Notes
-- | --
camel-k-cloudevents | There is no customization in ck-runtime. Don't migrate.
camel-k-cron | @LoaderInterceptor @ConfigurerThere is CronShutdownStrategy to stop the camel context when there is a completed or failed event. Migrate CronShutdownStrategy to camel-quarkus and set a parameter to enable it ?
camel-k-knative | @LoaderInterceptor @Configurer
camel-k-master | @Customizer, @LoaderInterceptor \@Configurer annotations.
camel-k-resume-kafka | \@Customizer resume strategy
camel-k-runtimecamel-k-core | There are similar implementations in camel-quarkus, move them accordingly.
camel-k-webhook | Unsure if it's relevant to camel-k
support/  camel-k-annotations  camel-k-apt | What would be the augmentation in the build phase ?
support/  camel-k-catalog  camel-k-catalog-model  camel-k-maven-plugin | The Yaml catalog is the artifact used by camel-k-operator to resolve dependencies.The camel-k-maven-plugin generates the yaml catalog file.
camel-k-maven-logging | Structural log of maven output
camel-k-runtime-bom | This BOM is imported in the generated integration project created by camel-k-operator

</div>

**Comment by zbendhiba** [comment]
camel-k-master, there's a PR that has been merged already https://github.com/apache/camel-quarkus/commit/17c9fdcfed19b14b12cbde928cd88aad31bb50ff

**Comment by claudio4j** [comment]
I migrated the `camel-k-core` and `camel-k-runtime` and their respective tests [my camel-quarkus repository, branch merge_ckr](https://github.com/claudio4j/camel-quarkus/commit/71d486d1391a70288898480b2ba05535521e554f) for an early review

**Comment by claudio4j** [comment]
There are some parts that requires more investigation, like the use an existing camel-quarkus Runtime interface, instead of the one in the `k-core/api` package
Also, there are some tests disabled due to failures in the CamelContextCustomizer tests, which I am investigating.
There is the `ApplicationConfigSourceProvider` which I will see if it is really necessary to depend on microprofile config.
Any  feedback is welcome.

**Comment by jamesnetherton** [comment]
Wont do for now. The initial work was reverted in https://github.com/apache/camel-quarkus/pull/6388.

We have backups in the form the 3.14.x branch and the previous release tags.
