### ISSUE TITLE
[Camel 3.20.0] SmallRye Fault Tolerance 5.6.0 not compattible with Camel 3.20.0

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#4298]
The same problem as in `quarkus-main`, see https://github.com/apache/camel-quarkus/issues/4225

To make the `camel-main` pass in CI, `CoreFaultToleranceTest` and related route are disabled.

Enable both test and route once https://github.com/apache/camel-quarkus/issues/4225 is fixed.

---- EDITED -----

There are more changes, each of it is marked with comment `https://github.com/apache/camel-quarkus/issues/4298`.
Here is the list of changed files:

```
	modified:   integration-test-groups/foundation/core-fault-tolerance/pom.xml
	modified:   integration-test-groups/foundation/core-fault-tolerance/src/main/java/org/apache/camel/quarkus/core/faulttolerance/it/CoreFaultToleranceProducers.java
	modified:   integration-test-groups/foundation/core-fault-tolerance/src/main/java/org/apache/camel/quarkus/core/faulttolerance/it/CoreFaultToleranceResource.java
	modified:   integration-test-groups/foundation/core-fault-tolerance/src/main/java/org/apache/camel/quarkus/core/faulttolerance/it/CoreFaultToleranceRoutes.java
	modified:   integration-test-groups/foundation/core-fault-tolerance/src/test/java/org/apache/camel/quarkus/core/faulttolerance/it/CoreFaultToleranceTest.java
	modified:   integration-tests/foundation-grouped/pom.xml
```

The above changes could be probably solved in better way by allowing grouped test module to exclude module.
Please refactor above change in that way.

**Comment by JiriOndrusek** [comment]
The change is currently in separated commit - e8fe1cb99bea80fce9197f2506056c63a5677047 
The un-optimal change exists to make branch `camel-main` successful in the shortest possible time.

**Comment by jamesnetherton** [comment]
The Quarkus 2.15.0 upgrade has been merged to `main`. So if you rebase `camel-main`, you should then be able to revert my commit that disables the `microprofile-fault-tolerance` tests and hopefully everything will work with Camel 3.20.0.

**Comment by jamesnetherton** [comment]
Fixed in https://github.com/apache/camel-quarkus/commit/1198483801a5a66bf232a9c0a390e564dad2456a.
