### ISSUE TITLE
camel-quarkus-http - ClassNotFoundException - javax.servlet.http.HttpServletRequest

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#4300]
A user that uses CEQ with the http kamelet sink, cannot run the application due to class not found exception.

The servlet-api is required by camel-http-common as it comes with some type converters and whatnot that uses servlet. The pom.xml has scope=provided, and camel-http has dependency on servlet.

See details at
https://lists.apache.org/thread/bbt0fvm654x5kl0jplywyhpjm8z1wodc

**Comment by jamesnetherton** [comment]
The Servlet API should already be on the classpath because it's needed to satisfy the native compiler.  

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ code-with-quarkus ---
[INFO] org.acme:code-with-quarkus:jar:1.0.0-SNAPSHOT
[INFO] \- org.apache.camel.quarkus:camel-quarkus-http:jar:2.14.0:compile
[INFO]    \- org.apache.camel.quarkus:camel-quarkus-http-common:jar:2.14.0:compile
[INFO]       \- jakarta.servlet:jakarta.servlet-api:jar:4.0.3:compile
```

**Comment by davsclaus** [comment]
Yeah I cannot reproduce this. Works with 2.14.2 quarkus release and camel jbang 3.20
