### ISSUE TITLE
camel-quarkus-catalog - Make it possible to get the camel version

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#4301]
camel quarkus is released using quarkus version numbering, and this makes it harder to know what camel version it uses,

eg 2.14.0 uses ????

so we need to make the camel-quarkus-catalog have an API that returns the camel version

**Comment by ppalaga** [comment]
> camel quarkus is released using quarkus version numbering

A side note: There is no tight binding between CQ versions and Quarkus versions. The fact that major.minor match at the moment is a coincidence. It was not the case before 2.x and it may happen again in the future.

**Comment by zbendhiba** [comment]
we also need to know which version of Quarkus

**Comment by ppalaga** [comment]
I think the best way to provide the camel version would be to use the `org.apache.camel.tooling.model.ArtifactModel.getMetadata()` map. That's where we already store camel `groupId:artifactId` already: 
https://github.com/apache/camel-quarkus/blob/main/tooling/maven-plugin/src/main/java/org/apache/camel/quarkus/maven/PrepareCatalogQuarkusMojo.java#L169

I guess storing `groupId:artifactId:version` under the same key is not a good idea because Camel K may be using it. 
Introducing a new key, say `camelVersion` sounds safer. WDYT, @davsclaus?

**Comment by ppalaga** [comment]
> we also need to know which version of Quarkus

It would be easy to store also the Quarkus *core* version to `org.apache.camel.tooling.model.ArtifactModel.getMetadata()`.
Would that one really be useful? I guess Camel jbang rather needs the platform version for exporting a CQ project, but we do not know that one here in Camel Quarkus.

**Comment by davsclaus** [comment]
Yeah so in the camel-quarkus-catalog today we have the quarkus version, eg 2.14.0 in that artifact model.
What I need to know is what Camel version that this corresponds to, eg 3.18.x

```
 "component": {
    "kind": "component",
    "name": "activemq",
    "title": "ActiveMQ",
    "description": "Send messages to (or consume from) Apache ActiveMQ. This component extends the Camel JMS component.",
    "deprecated": false,
    "firstVersion": "1.0.0",
    "label": "messaging",
    "javaType": "org.apache.camel.component.activemq.ActiveMQComponent",
    "supportLevel": "Stable",
    "nativeSupported": true,
    "metadata": { "camelArtifact": "org.apache.camel:camel-activemq" },
    "groupId": "org.apache.camel.quarkus",
    "artifactId": "camel-quarkus-activemq",
    "version": "2.14.0",
    "scheme": "activemq",
    "extendsScheme": "jms",
    "syntax": "activemq:destinationType:destinationName",
    "async": true,
    "api": false,
    "consumerOnly": false,
    "producerOnly": false,
    "lenientProperties": false
  },
```

Today the only way I could find it was to use maven and grab the quarkus-camel-bom and inside the BOM find camel-core-engine and then grab the <version>

**Comment by davsclaus** [comment]
Maybe when you release camel-quarkus, then in camel-quarkus-catalog, there is a file written to the JAR that contains the camel version, and then we have an API in QuarkusCamelCatalog to get that version.

We could make such API in `CamelCatalog` so its present on all runtimes, as the other releases its easier as the version of the catalog JAR is also the version of the Camel, eg 3.18.3 of CSB is 3.18.3 of Camel.

**Comment by ppalaga** [comment]
Adding a dedicated method(s) on CamelCatalog or elsewhere in the Catalog Java API would be also fine. Just note that having a single Camel version per Catalog might not always work. There exist partial rebuilds of Camel, CQ and CSB where per component Camel artifact versions can be different, FWIW. So Camel version should rather hang on `org.apache.camel.tooling.model.ArtifactModel`. 

Using `org.apache.camel.tooling.model.ArtifactModel.getMetadata()` for this purpose as I did in https://github.com/apache/camel-quarkus/pull/4302 has the advantage that it can be done without waiting for changes Camel.
