### ISSUE TITLE
Remove azure-identity `IdentityClientBase` runtime initialization native configuration

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#4356]
After upgrade of `azure-identity` to 1.7.0, native build of extension `azure-eventhubs` and `azure-storage-blob` fails with

```
 org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.
```

Problem is caused by this [line](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClient.java#L1157) of code. 

Workaround - disabled native build for `azure-eventhubs`, `azure-storage-blob` and `azure-grouped` test.

With proper fix, please enable native profiles again.

**Comment by ppalaga** [comment]
In azure-identity 1.7.0, they moved the RANDOM field from `com.azure.identity.implementation.IdentityClient` to `com.azure.identity.implementation.IdentityClientBase`. I guess we need to produce a RuntimeInitializedClassBuildItem for IdentityClientBase in `AzureStorageBlobProcessor`.

Anyway, I have filed https://github.com/Azure/azure-sdk-for-java/issues/32744 . Let's see whether Azure SDK team is willing to stop instantiating `java.util.Random` in the static initializer.

**Comment by jamesnetherton** [comment]
I registered  `IdentityClientBase` for runtime initialization in [09d9d4d](https://github.com/apache/camel-quarkus/commit/09d9d4dfb5f98db02605d08d28bf49fd5a8afb01) and restored the native testing.

Looks like https://github.com/Azure/azure-sdk-for-java/issues/32744 is fixed already. So we can revert the change when we upgrade to the next `azure-identity` release.
