### ISSUE TITLE
[Quarkus 2.16]  Camel-kubernetes does not work in native (needs quarkus update) 

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#4357]
Camel-kubernetes requires kubernetes-client of version `6.3.1`
Quarkus from `main` branch contains version  `6.2.0`, but upgrade to 6.3.1is already part of the quarkus (see commit - [commit](https://github.com/quarkusio/quarkus/commit/f85e79dae01bc330d8d012aa8fb0af3abf8682e8) )

I'm disabling native builds of ` camel-quarkus-integration-test-master-openshift`, `camel-quarkus-examples-cluster-leader-election` and `camel-quarkus-examples-cluster-leader-election`.

Please enable native builds once problem is solved.

**Comment by zbendhiba** [comment]
We need to watch out for this one, and see how we can solve it for next version

**Comment by zbendhiba** [comment]
FYi @ppalaga @jamesnetherton @aldettinger 
@JiriOndrusek  Thanks for all the work around Camel 3.20. Let's check this one beginning of January.

**Comment by JiriOndrusek** [comment]
Kubernetes client upgrade is already available in Quarkus 2.16
Please enable native builds once after update to 2.16.0.CR1

**Comment by JiriOndrusek** [comment]
Enable example 'cluster-leader-election' - see https://github.com/apache/camel-quarkus-examples/pull/126
