### ISSUE TITLE
Groovy DSL native support

### ISSUE THREAD

**Issue by essobedo** [apache/camel-quarkus#4379]
To support routes written in Groovy language in Camel-K, we have to make the extension `groovy-dsl` compatible with the native mode.

**Comment by ppalaga** [comment]
It looks like Groovy could work to some extent. @essobedo do you know if your foreseen impl. will require `--allow-incomplete-classpath`? `--allow-incomplete-classpath` used to be a showstopper so far. Not sure we want to make an exception for groovy. What do others think?

**Comment by essobedo** [comment]
The corresponding [PR](https://github.com/apache/camel-quarkus/pull/4385)

**Comment by essobedo** [comment]
> It looks like Groovy could work to some extent. @essobedo do you know if your foreseen impl. will require `--allow-incomplete-classpath`? `--allow-incomplete-classpath` used to be a showstopper so far. Not sure we want to make an exception for groovy. What do others think?

I did not face this issue, do you have a reproducer?

**Comment by ppalaga** [comment]
> > It looks like Groovy could work to some extent. @essobedo do you know if your foreseen impl. will require --allow-incomplete-classpath? --allow-incomplete-classpath used to be a showstopper so far. Not sure we want to make an exception for groovy. What do others think?

> I did not face this issue, do you have a reproducer?

I explained in https://github.com/apache/camel-quarkus/issues/4393 what I meant
