### ISSUE TITLE
Do not include the source XSLT files into the application archive

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#438]
We compile the XSL template files into translets at build time so there is no point in having them in the archive. Let's exclude them once Quarkus provides means for that. Blocked by https://github.com/quarkusio/quarkus/issues/5576

**Comment by lburgazzoli** [comment]
I remember either the xls engine or camel try to access the file when the route starts, it is not more the case ?

**Comment by ppalaga** [comment]
> the xls engine or camel try to access the file when the route starts

That's solved in the upcoming fix for #428

**Comment by lburgazzoli** [comment]
so I think you only need to remove the build item that includes the xslt in the final native image

**Comment by ppalaga** [comment]
> you only need to remove the build item that includes the xslt in the final native image

+1, The current issue was rather meant for the JVM mode.

**Comment by ppalaga** [comment]
@lburgazzoli via chat:

> well, the resource folder can contain whatever the user put there
> I do mot know what the user wants
> maybe the file needs to be there for any reason
> we are not aware of, but by removing it
> we won’t let the user any choice
> it should be optional imho
> maybe we can remove it bu default and have an option to include it in both the images
> or vice versa

**Comment by lburgazzoli** [comment]
@ppalaga I think this can be closed, right ?

**Comment by ppalaga** [comment]
> @ppalaga I think this can be closed, right ?

Excluding unwanted resources from the runner.jar is still not possible. I'd keep this open.

**Comment by lburgazzoli** [comment]
So guess it need to be rephrased as it is general, not linked to xslt only any-more

**Comment by ppalaga** [comment]
Feel free to change the title. XSLT is the only known use case where it matters, so I'd be fine with keeping the current title.

**Comment by ppalaga** [comment]
I think this is not that important after all.
