### ISSUE TITLE
js-dsl - Improve the interoperability with Java code

### ISSUE THREAD

**Issue by essobedo** [apache/camel-quarkus#4407]
The JavaScript DSL already supports the native mode but it is really limited in terms of interoperability with Java code, the goal of this task is to improve the code to at least support the basic use cases available [in the Came code base](https://github.com/apache/camel/tree/camel-3.x/dsl/camel-js-dsl/src/test/resources/routes).

**Comment by jamesnetherton** [comment]
> The JavaScript DSL already supports the native mode

For reference:

* https://github.com/apache/camel-quarkus/issues/4285
* https://github.com/apache/camel-quarkus/issues/4241

**Comment by essobedo** [comment]
Thx for sharing, I'm aware of those tickets, but maybe we could simply add a note in the documentation indicating that it is experimental instead of dropping the native mode. 

I may be wrong but for me, the main purpose of Quarkus is to help us go to native so IMHO the goal of Camel Quarkus should be the same but for Camel components, don't you agree?

**Comment by jamesnetherton** [comment]
> don't you agree?

Yes, of course. But, given that the current builder container image for native apps is currently Mandrel, I'm assuming it wouldn't work for js-dsl? Because unlike GraalVM, Mandrel does not have / support the JS bits.

**Comment by essobedo** [comment]
I was not aware of that thx for the info. Do you mean that It will never be supported in Mandrel? If so why not?

**Comment by essobedo** [comment]
Anyway, my bad, I should have asked before, I will propose a PR since it is already done and feel free to merge it or not

**Comment by jamesnetherton** [comment]
> current builder container image for native apps is currently Mandrel

FWIW, that may eventually change. IIRC it was originally done due to some issues Quarkus encountered in GraalVM 22.3. So maybe they will revert back to GraalVM at some point....

**Comment by essobedo** [comment]
Related PR https://github.com/apache/camel-quarkus/pull/4409

**Comment by essobedo** [comment]
@zakkak Hi, AFAIU the js language is not supported in Mandrel, do you know if it is planned to support it?

**Comment by zakkak** [comment]
Hi @essobedo, no, no plans for supporting it for the time being.

**Comment by essobedo** [comment]
@zakkak thx for the answer, that's not good news for the project but ok

**Comment by ppalaga** [comment]
> > current builder container image for native apps is currently Mandrel
> 
> FWIW, that may eventually change. IIRC it was originally done due to some issues Quarkus encountered in GraalVM 22.3. So maybe they will revert back to GraalVM at some point....

Quarkus switched to Mandrel because of this issue in GraalVM 22.3.0 https://github.com/oracle/graal/issues/5303

GraalVM 22.3.1 is due next week https://www.graalvm.org/release-notes/release-calendar/ 

On a more practical note, we had js-dsl native tests disabled on GH actions for some time because they simply took too long. IIRC it was like tens of minutes for this single module.

**Comment by zakkak** [comment]
> GraalVM 22.3.1 is due next week https://www.graalvm.org/release-notes/release-calendar/

FYI in https://github.com/quarkusio/quarkus/issues/29252 we (the Mandrel team) propose switching permanently to Mandrel. Please provide feedback in that issue if you think it's a big issue.

**Comment by essobedo** [comment]
> FYI in [quarkusio/quarkus#29252](https://github.com/quarkusio/quarkus/issues/29252) we (the Mandrel team) propose switching permanently to Mandrel. Please provide feedback in that issue if you think it's a big issue.

Feedback provided thanks again 🙏
