### ISSUE TITLE
Ugly re-formatted code

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#444]
What I wrote:

![image](https://user-images.githubusercontent.com/1868933/69228844-9f095900-0b84-11ea-90f8-1eb51b33e4d5.png)

The same code after the auto formatter plugin kicks in:

![image](https://user-images.githubusercontent.com/1868933/69228676-48038400-0b84-11ea-969e-00cf0e265e59.png)

I know that I can add `CHECKSTYLE:OFF|ON` but it would be nice if we can check if there are any better code style combo that won't break the code so ugly

**Comment by ppalaga** [comment]
Adding a newline before the `post()` statement would perhaps improve the readability of the formatted result.

For the record: This is not a problem for me.

**Comment by lburgazzoli** [comment]
Another case is `given/then` notation with RestAssured

what I'd like:
![image](https://user-images.githubusercontent.com/1868933/71660263-ba9e7c80-2d4a-11ea-991c-2d629606bbce.png)

what the formatter does:
![image](https://user-images.githubusercontent.com/1868933/71660238-ace8f700-2d4a-11ea-8b7f-183aacb26515.png)

**Comment by ppalaga** [comment]
Do we still want to do something about this?

**Comment by lburgazzoli** [comment]
I think something has bee put in place in the format plugin so we can close this
