### ISSUE TITLE
Upgrade to OptaPlanner 9.x

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#4463]
Citing from https://issues.redhat.com/browse/PLANNER-2869:

> take a look at this epic: https://issues.redhat.com/browse/PLANNER-2872 to see how far we are with the migration.
>
> TLDR:
>
> * we will release OptaPlanner 9.x that will be compatible with Quarkus 3, while OptaPlanner 8.x stays on Quarkus 2.x
> * we are doing automated migration from 8 to 9, based on the Quarkus 3 OpenRewrite upgrade recipe (+ additional tweaking)
> * soon we will do an alpha release of OptaPlanner 9 based on Quarkus 3.0.0.Alpha3

https://repo1.maven.org/maven2/org/optaplanner/optaplanner-quarkus/

**Comment by ppalaga** [comment]
There are a couple of Optaplanner 9.x releases in the Central already: https://repo1.maven.org/maven2/org/optaplanner/optaplanner-quarkus/

**Comment by zbendhiba** [comment]
I can take a look at this.

**Comment by zbendhiba** [comment]
I opened an issue for Camel 4 : https://issues.apache.org/jira/browse/CAMEL-19230

**Comment by ppalaga** [comment]
This should work with Camel 4.0.0-M3, shouln't it?

**Comment by zbendhiba** [comment]
yes, I'm trying to upgrade locally
For now, I'm getting this exact error on native compilation : https://github.com/oracle/graal/issues/2177
Trying to figure out if we can solve this
