### ISSUE TITLE
smallrye-reactive-messaging-camel missing in smallrye-reactive-messaging 4.x

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#4464]
There is no `io.smallrye.reactive:smallrye-reactive-messaging-camel` in smallrye-reactive-messaging 4.x https://repo1.maven.org/maven2/io/smallrye/reactive/smallrye-reactive-messaging-camel/

This blocks the migration of camel-quarkus-smallrye-reactive-messaging to Camel 4/Quarkus 3.

**Comment by mswiderski** [comment]
I see that this marks smallrye-reactive-messaging-camel extension for 3.0.0-M1 but I cannot find it in maven central?
https://repo1.maven.org/maven2/org/apache/camel/quarkus/camel-quarkus-smallrye-reactive-messaging/

Was it added on 3.0.0-M1 or do I read it wrong?

**Comment by jamesnetherton** [comment]
Unfortunately, this issue got fixed, and was then broken again by a different problem https://github.com/apache/camel-quarkus/issues/4637.

Hopefully the extension will come back in the next Camel Quarkus 3.x release.

**Comment by mswiderski** [comment]
thanks for quick feedback @jamesnetherton. 

It looks like M2 of camel is already out so it can be used as a base for the fix in smallrye which will be included in M2 of camel quarkus, is this valid assumption?  and if so any time frame for M2 of camel quarkus?

**Comment by jamesnetherton** [comment]
The issue is already fixed in SmallRye Reactive Messaging. We need that fix to first filter down to Quarkus and then into this project. I don't have any timelines as to when that will happen yet.

**Comment by mswiderski** [comment]
thanks, I will wait for M2 and retest again
