### ISSUE TITLE
Permanently remove extensions depending on components removed from Camel 4

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#4477]
The list of components removed from Camel 4 is here: https://camel.apache.org/manual/camel-4-migration-guide.html#_removed_components

In our camel-4 branch, for now, I have already

1. Permanently Removed JMV-only extensions depending on those removed Camel modules. 
2. Commented the rest of extensions depending on those removed Camel modules. 

Step 2. was motivated by the fact that some of those components might get added back in the future and it would be a pity to lose their history in our source tree.

However, at some point, when it will be clear enough that the components are not coming back, we should remove the extensions permanently.

**Comment by zbendhiba** [comment]
I'd prefer to go and delete those, as it was painful to go through what is the reason of each non existing dependency in the automated generated integration in the Quarkus platform. 
The history of the component is still available on Camel Quarkus 2.x branches.
Can I delete those for next 3.0.0-M2 ?

**Comment by ppalaga** [comment]
> Can I delete those for next 3.0.0-M2 ?

Yeah, I think we can delete all but the ones having an issue requesting to re-add it - see the summary in https://github.com/apache/camel-quarkus/pull/4683#discussion_r1143944845 and the issues under [jakarta label](https://github.com/apache/camel-quarkus/labels/jakarta)

**Comment by jsight** [comment]
It looks like camel-activemq has been added back to camel 4? I no longer see it listed as removed in the source code for the upstream project, and it is no longer mentioned as removed here: https://camel.apache.org/manual/camel-4-migration-guide.html#_removed_components
