### ISSUE TITLE
`QuarkusVertxWebsocketHost` should return the actual port for the HTTP server

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#4557]
Currently [`QuarkusVertxWebsocketHost`](https://github.com/apache/camel-quarkus/blob/7dc82684910a20ea10159950390773ed6e3896c7/extensions/vertx-websocket/runtime/src/main/java/org/apache/camel/quarkus/component/vertx/websocket/VertxWebsocketRecorder.java#L50) does not return the actual port used by the underlying HTTP server.

This prohibits the `vertx-websocket` producer from being used against the local server like:

```java
.to("vertx-websocket:localhost:8080/foo");
``` 

There's an undocumented idiom that works instead like:

```java
.to("vertx-websocket:///foo");
``` 

But, it's a pain to maintain the logic to make it work properly. So I'd like to get rid of it and force usage of the standard `host:port/path` style.

**Comment by ebullient** [comment]
`.to("vertx-websocket:localhost:8080/foo")` .. that doesn't work so well given profile-specific ways to change the host and/or port, though, does it (w/ late binding config injection scoped by quarkus profile?)

I personally would never use the hard-coded host:port form.. ever. The implied/disovered is better.

**Comment by jamesnetherton** [comment]
> That form is documented here

Yes. For the WS consumer (`from(...)`) where specifying the `host:port` makes little sense on Quarkus.

For the WS producer (`to(..)`) you could either be connecting to the local Quarkus HTTP server or some externally hosted WebSocket. Hence `host:port/path` makes sense in that scenario.

I'm not advocating folks hard code the host / port either. Camel can resolve Quarkus config properties like:

```
.to("vertx-websocket:localhost:{{quarkus.http.port}}");
```

**Comment by ebullient** [comment]
y.. the trouble is (even in that case) it could be the http port or the test port, depending on where/when/how things are being invoked.

**Comment by jamesnetherton** [comment]
> it could be the http port or the test port

Which is a UX issue. Because that split ends up leading to wackiness like this:

https://github.com/apache/camel-quarkus/blob/23721fee0c62b6fe4503ed1250a2adaddf0b4ee1/integration-test-groups/foundation/timer/src/main/java/org/apache/camel/quarkus/component/timer/it/TimerProducers.java#L37-L41

**Comment by jamesnetherton** [comment]
Given the feedback, let me rethink this change and experiment a bit more.

**Comment by ebullient** [comment]
> > it could be the http port or the test port
> 
> Which is a UX issue. Because that split ends up leading to wackiness like this:
> 
> https://github.com/apache/camel-quarkus/blob/23721fee0c62b6fe4503ed1250a2adaddf0b4ee1/integration-test-groups/foundation/timer/src/main/java/org/apache/camel/quarkus/component/timer/it/TimerProducers.java#L37-L41

That could be a usability improvement to Quarkus itself (to give you / return the effective port). Also.. that logic isn't quite correct. A JVM-mode integration test will also use the httpPort instead of the httpTestPort...
