### ISSUE TITLE
Multiple test methods do not work when extending CamelQuarkusTestSupport

### ISSUE THREAD

**Issue by salagator** [apache/camel-quarkus#4560]
I am trying to write camel quarkus tests using the CamelQuarkusTestSupport facility.

From the documentation (here: https://camel.apache.org/camel-quarkus/2.16.x/user-guide/testing.html), I gather that the camel context is created once, for all the tests.

However, when I try writing tests the first one succeeds and any subsequent tests fail. If I apply the "TestInstance(TestInstance.Lifecycle.PER_CLASS)" annotation, the tests in one class succeed and the tests in any subsequently executed class fail.

Something in the test scaffolding seems to be stoping all routes, but not starting them back up (either at the test method boundary, or the class boundary respectively).

I must be doing something wrong, but I cannot understand what. I tried googling myself out of the problem, but to no avail. Please help.

I am attaching a "reproducer" project that shows what I am doing (wrong): [camel-testing.zip](https://github.com/apache/camel-quarkus/files/10715736/camel-testing.zip)

**Comment by ppalaga** [comment]
Thanks for the reproducer, @salagator! 
@JiriOndrusek could you please have a look?

**Comment by JiriOndrusek** [comment]
I'll check that, thanks for the information.

**Comment by JiriOndrusek** [comment]
@salagator Thanks for finding those issues. There are probably 2 isolated issues affecting this case

1.  Scenario  without `TestInstance(TestInstance.Lifecycle.PER_CLASS)` should succeed. I've almost finished fix for this sub-issue and I'll provide a PR soon.
2. Usage of `TestInstance(TestInstance.Lifecycle.PER_CLASS)` should work as a workaround for the first sub-issue. Unfortunately there is probably a small issue with propagating camel context. I'll investigate the second scenario after the first one and will create a separate ticket for it.
