### ISSUE TITLE
Expand micrometer test coverage

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#4582]
The following scenarios from the [documentation](https://camel.apache.org/components/3.20.x/micrometer-component.html) are not covered in Camel Quarkus:

- message headers (just increment/decrement for counter and start/stop for timer)
- event notification - cover dump to json
- if possible cover instrumenting thread pool
-  exposing to JMX (JVM only)

Because micrometer extension leverages quarkus extension (see the [documentaion](https://quarkus.io/guides/micrometer#does-micrometer-support-annotations)) it would be nice to cover major features - it is **optional**.

- try MeterFilter
- annotations
- customized meterRegistry
- microprofile metrics API
-  review gauge metrics coverage

**Comment by JiriOndrusek** [comment]
Thanks @llowinge for the information. I reported those problems in its own ticket https://github.com/apache/camel-quarkus/issues/4598 and will look at it.

**Comment by JiriOndrusek** [comment]
@llowinge I found a reason of different behavior in Quarkus and reported a ticket there - https://github.com/quarkusio/quarkus/issues/31433

**Comment by JiriOndrusek** [comment]
Test coverage revealed missing feature `instrumenting core thread pool`. Reported as https://github.com/apache/camel-quarkus/issues/4934.

**Comment by ppalaga** [comment]
Is there anyhing more to do here @JiriOndrusek. Can't we perhaps close this issue?

**Comment by JiriOndrusek** [comment]
There will be another PR covering the missing parts. Here is my WIP https://github.com/apache/camel-quarkus/compare/main...JiriOndrusek:CQ4582-expand-micrometer-coverage?expand=1
I hope to finish it this week or the next one.
