### ISSUE TITLE
Zendesk: update zendesk-java-client once it depends on asyncclient 3.x

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#4591]
Follows https://github.com/apache/camel-quarkus/issues/4514. Async-httpclient is upgraded to 3.x. This dependency should be brought by `com.cloudbees.thirdparty:zendesk-java-client`. If such java client exists, enable @sync task for `ahc.version` https://github.com/apache/camel-quarkus/blob/main/pom.xml#L68

**Comment by jamesnetherton** [comment]
No longer relevant since https://github.com/apache/camel-quarkus/pull/5202.
