### ISSUE TITLE
Expand JDBC test coverage

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#4596]
The following scenarios from the [documentation](https://camel.apache.org/components/3.20.x/jdbc-component.html) are not covered in Camel Quarkus:

1. [Generated keys](https://camel.apache.org/components/3.20.x/jdbc-component.html#_generated_keys)
2. [Using named parameters](https://camel.apache.org/components/3.20.x/jdbc-component.html#_using_named_parameters)
3. Polling databes every time interval - part of the [samples](https://camel.apache.org/components/3.20.x/jdbc-component.html#_sample_polling_the_database_every_minute).
4. Move data between datasources - part of the [samples](https://camel.apache.org/components/3.20.x/jdbc-component.html#_sample_move_data_between_data_sources).
 
Because JDBC extension leverages quarkus extension (see the [documentaion](https://quarkus.io/guides/datasource)) it would be nice to cover major features - it is optional.

1.  Cover different db types for jdbc (based on the [doc](https://quarkus.io/guides/datasource#jdbc-datasource-2)) - DB2, Derby, H2, MariaDB, Microsoft SQL Server, MySQL, Oracle and PostgreSQL.

**Comment by JiriOndrusek** [comment]
One item is missing in the summary

[Message headers ](https://camel.apache.org/components/3.20.x/jdbc-component.html#_message_headers)should be covered too. @ldrozdo thanks for noticing!

**Comment by ldrozdo** [comment]
Hi @JiriOndrusek, I will try to solve this, can you please assign me?

**Comment by ldrozdo** [comment]
Hi @aldettinger, can you please reopen this issue? It's only partially done, I've done:
1. Generated keys
2. Message headers ( except for CamelJdbcParameters header, which will be done in the next PR)

**Comment by aldettinger** [comment]
@ldrozdo Ok, done. It must have closed the ticket linked to rebase yesterday.
