### ISSUE TITLE
Dead guide link in tagsoup extension

### ISSUE THREAD

**Issue by holly-cummins** [apache/camel-quarkus#4620]
The `quarkus-extension.yaml` for `org.apache.camel.quarkus:camel-quarkus-tagsoup` points to a guide at https://camel.apache.org/camel-quarkus/latest/reference/extensions/tagsoup.html, but this page does not exist. 

I haven't created a PR since I'm not sure if it's better to create this page or remove the guides line in the extension metadata.

**Comment by jamesnetherton** [comment]
Tagsoup was removed back in June 2022 for Camel Quarkus 2.10.0.

**Comment by holly-cummins** [comment]
Could we mark the extension as deprecated? The annoying thing is that would need a new release to publish the new data, but otherwise the quarkus registry doesn't have any way of knowing that it's not a valid extension anymore.

**Comment by holly-cummins** [comment]
Alternatively, we *may* be able to patch the registry without doing a new release. I know we've talked about this, but I forget how hard it is. @gastaldi, what do you think?

**Comment by gastaldi** [comment]
@holly-cummins that makes sense. However the registry would need to support patching the extension release's metadata. See   https://github.com/quarkusio/registry.quarkus.io/pull/176

**Comment by holly-cummins** [comment]
Resolved by https://github.com/quarkusio/quarkus-extension-catalog/pull/52
