### ISSUE TITLE
Dead link in IPFS extension

### ISSUE THREAD

**Issue by holly-cummins** [apache/camel-quarkus#4621]
The quarkus-extension.yaml for org.apache.camel.quarkus:camel-quarkus-ipfs points to a guide at https://camel.apache.org/camel-quarkus/latest/reference/extensions/ipfs.html, but this page does not exist. 

I haven't created a PR since I'm not sure if it's better to create this page or remove the guides line in the extension metadata.

**Comment by ppalaga** [comment]
Thanks for reporting, @holly-cummins! 

We have removed IPFS around a year ago. I wonder which version of `org.apache.camel.quarkus:camel-quarkus-ipfs` you look into? I guess it is something pre 2.10-ish?

I agree, using `latest` extension docs URL in `quarkus-extension.yaml` is not ideal. It is hitting back in this and other situations. We did not have any better choice in the past, because Camel was frequently removing the old versions of the docs. Currently the available docs versions are 2.16.x, 2.15.x, 2.14.x and 2.13.x. 

@zregvart do you happen to know what is the current docs version removal policy?

**Comment by ppalaga** [comment]
> We have removed IPFS around a year ago. I wonder which version of `org.apache.camel.quarkus:camel-quarkus-ipfs` you look into? I guess it is something pre 2.10-ish?

Having read the discussion in https://github.com/apache/camel-quarkus/issues/4620, it is clear it is the metadata of some old version available in Quarkus registry.

**Comment by holly-cummins** [comment]
Yes, I think what happened is that the extension was removed without an intermediate release with a 'deprecated' status marker. Doing another release to update the status field and mark it as deprecated would be (a) kind of weird and confusing and (b) a lot of work to resurrect the codebase from github and run the release. So we should patch the registry, once https://github.com/quarkusio/registry.quarkus.io/pull/176 is merged.

See also the discussion in https://github.com/quarkusio/quarkus/issues/31148, which is for an extension at the opposite end of its lifecycle, but has similar issues with `latest` and versioned guides links.

**Comment by holly-cummins** [comment]
The context is that we now expose the contents of the registry to the world, so the data integrity becomes more important. https://quarkus.io/extensions/org.apache.camel.quarkus/camel-quarkus-ipfs is the page for IPFS. We'll want to patch the registry to indicate this is a deprecated extension (which will probably hide/mostly-hide it) to avoid people (a) following the dead docs link, or, more seriously, (b) wanting to use the extension.

**Comment by ppalaga** [comment]
Thanks for explaining the context, @holly-cummins! It is much clearer now how got to these long forgotten fossils :D

**Comment by holly-cummins** [comment]
I'd prefer not to interpolate extension metadata based just on release frequency, in case we get it wrong. Some extensions haven't been updated for a while (since Quarkus 1) but are still 'alive'. However, patching the registry seems reasonable. Fixed by https://github.com/quarkusio/quarkus-extension-catalog/pull/52.

**Comment by zbendhiba** [comment]
Great news! Thanks @holly-cummins
