### ISSUE TITLE
Dead link in weka extension

### ISSUE THREAD

**Issue by holly-cummins** [apache/camel-quarkus#4622]
The quarkus-extension.yaml for org.apache.camel.quarkus:camel-quarkus-weka points to a guide at  "https://camel.apache.org/camel-quarkus/latest/reference/extensions/weka.html, but this page does not exist. 

I haven't created a PR since I'm not sure if it's better to create this page or remove the guides line in the extension metadata.

**Comment by ppalaga** [comment]
This is exactly the same situation as IPFS https://github.com/apache/camel-quarkus/issues/4621. It was removed about a year ago, so `latest` version of the docs page does not exist anymore.

**Comment by holly-cummins** [comment]
Ok, sounds like the discussion in https://github.com/apache/camel-quarkus/issues/4620 is super-relevant here, and it's another one for https://github.com/quarkusio/registry.quarkus.io/pull/176. The extension was removed, but doing another release to update the status field and mark it as deprecated would be (a) kind of weird and confusing and (b) a lot of work to resurrect the codebase from github and run the release. So we should patch the registry.

**Comment by holly-cummins** [comment]
(I'll leave this open to track the work someone has to do to actually apply the patch, if that's ok?)
