### ISSUE TITLE
Remove org.freemarker:freemarker dependency override

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#4634]
`quarkus-freemarker` is out of sync with Camel 4.0.0-M2 in the freemarker version used (I have asked for a new release so we get back in sync). Since a version constant is now passed to the `Configuration`, it can cause issues if `quarkus-freemarker` lags behind.

https://github.com/apache/camel/blob/main/components/camel-freemarker/src/main/java/org/apache/camel/component/freemarker/FreemarkerComponent.java#L90

We should either make the override permanent or think of a way of maintaining this in a easy way, since we're likely to hit this issue again in the future.

**Comment by oscerd** [comment]
The reason for that was: https://freemarker.apache.org/docs/pgui_config_incompatible_improvements.html

If this is a problem we could also revert or find a different way, but it's not a best practice.

**Comment by jamesnetherton** [comment]
https://github.com/apache/camel-quarkus/pull/4650 will fix this.

> We should either make the override permanent or think of a way of maintaining this in a easy way, since we're likely to hit this issue again in the future.

Given that Freemarker does not seem to release very often, I think it's ok to temporarily live with some potential misalignment between Camel & CQ, while we request a new release from the Quarkiverse Freemarker project. We should be able to catch this early on the `camel-main` branch.
