### ISSUE TITLE
ReflectiveClassBuildItem has been deprecated and marked for removal

### ISSUE THREAD

**Issue by zhfeng** [apache/camel-quarkus#4635]
new ReflectiveClassBuildItem(boolean,boolean,java.lang.String...) should be replaced with some `builder()` metheds

**Comment by ppalaga** [comment]
> new ReflectiveClassBuildItem(boolean,boolean,java.lang.String...)

They dare to remove the cornerstone of our extension development 😱?!?!

**Comment by zhfeng** [comment]
I think they just removed the use of `new ReflectiveClassBuildItem` and use `ReflectiveClassBuildItem.builder()` instead.

**Comment by zhfeng** [comment]
Well, thanks the powerful IDEA and it saves my time by using [Structural Replace](https://www.jetbrains.com/help/idea/structural-search-and-replace.html).
