### ISSUE TITLE
Improve extension summary so they have more details in the code.quarkus.io

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#465]
for example if you want mqtt, you cannot find camel-paho which supports mqtt using the eclipse paho library.

**Comment by ppalaga** [comment]
We recently started using the descriptions from Camel catalog for new extensions. We should probably update the existing extensions too. The rest is a matter of quality of the metadata available in the Camel Catalog.

**Comment by ppalaga** [comment]
Searching for `mqtt` now returns also Camel Paho. All done, closing.
