### ISSUE TITLE
[camel-main] Http test "basicAuthCache" fails because of CAMEL-19184

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#4686]
Test 'HttpsAuthenticationTest.basicAuthCache' is disabled because of the https://issues.apache.org/jira/browse/CAMEL-19184. Has to be enabled once the camel issue is fixed.

**Comment by essobedo** [comment]
Unless I miss something, there is no bug in Camel please check this PR https://github.com/apache/camel/pull/9607 to see how to adapt your code

**Comment by JiriOndrusek** [comment]
Thank you for the help. Once I confirmed, that the problem is not in camel itself I was able to find problem in the camel-quarkus. Issue is fixed in 'camel-main' branch. (one of the problems was caused by serialization of 'org.apache.hc.client5.http.impl.auth.BasicScheme')
