### ISSUE TITLE
Add Build-Date in MANIFEST.MF in Camel Quarkus release JARs

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#4711]
Camel v4 adds build-date in the JARs so we know when the JARs was build and therefore also when it was released
https://issues.apache.org/jira/browse/CAMEL-19139

It would be good if CEQ could add this in their the JARs as well.

Here is how it was done for Camel Spring Boot
https://github.com/apache/camel-spring-boot/commit/ebdaab584cecd9b7ccf9de079ac928480a97e695

**Comment by ppalaga** [comment]
> including the hash of the last git commit (and its date perhaps) would not serve the purpose too?

[buildnumber-maven-plugin](https://www.mojohaus.org/buildnumber-maven-plugin/create-mojo.html) can be used for that IIRC.

**Comment by davsclaus** [comment]
Okay we found another way
