### ISSUE TITLE
java-joor-dsl - Add RegisterForReflection annotation support

### ISSUE THREAD

**Issue by essobedo** [apache/camel-quarkus#4716]
All the annotations added to a class managed by the extension `java-joor-dsl` are not considered by Quarkus since it is not part of the Jandex index. 

This task aims to support the annotation `RegisterForReflection` to easily configure the reflection in Camel-K.

**Comment by essobedo** [comment]
Related to https://github.com/apache/camel-k/issues/4124

**Comment by squakez** [comment]
Nice catch!

**Comment by essobedo** [comment]
Unfortunately, the Quarkus Team [rejected the idea to support annotations on generated classes ](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/.E2.9C.94.20Annotations.20on.20generated.20classes), so I will limit the support of the annotation `RegisterForReflection` which can be handy in Camel-K

**Comment by essobedo** [comment]
Should be fixed by https://github.com/apache/camel-quarkus/pull/4726
