### ISSUE TITLE
[camel-main] Xml tests: Better handling of http client (registration of org.apache.hc.client5.http.impl.auth.NTLMEngineImp)

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#4722]
Related to the issues https://github.com/apache/camel-quarkus/issues/4710 and https://github.com/apache/camel-quarkus/issues/4043

`camel-quarkus-xslt`  brings transitively `xalan`fails on `java.lang.ClassNotFoundException: org.apache.hc.client5.http.impl.auth.NTLMEngineImpl`.
This class is registered on 3 places in camel-quarkus:

1. `httpclient` -> here the registration happens only in case that the class is on classpath  (seems like a riight approach to me)
2. in `XslProcessor` - without a condition
3. in 'SaxonProcessor` - without a condition

As stated in https://github.com/apache/camel-quarkus/issues/4710, this registration could be "triggered"  without the class on the classpath, which causes failure.

From my PoV:

1. There should be a test covering such use case (which causes failure with the current codebase)
2.  Registration should be triggered only with a condition similarly as in `httpclient` module
3. I'm not sure about his one, but it might make sense to add `camel-quarkus-support-httpclient` as a dependency to i.g. wiremock-support (maybe others), as some modules (like `integration-tests/xml`) depend on this module in runtime

**Comment by zhfeng** [comment]
I think we need `httpclient` only if we use `http` schema in `camel-quarkus-xslt`. Then it makes sense to add `camel-quarkus-support-httpclient` as a dependency to `wiremock-support`  for testing. And when using `http` schema with `camel-quarkus-xslt` in an application, it needs to add `camel-quarkus-support-httpclient` in `pom.xml` to make sure it working in native mode.

**Comment by zhfeng** [comment]
`httpclient5` is an transitive dependency of `camel-xslt-saxon`
```
[INFO] |  \- org.apache.camel:camel-xslt-saxon:jar:4.0.0-M2:compile
[INFO] |     \- net.sf.saxon:Saxon-HE:jar:11.4:compile
[INFO] |        +- org.xmlresolver:xmlresolver:jar:4.4.3:compile
[INFO] |        |  +- org.apache.httpcomponents.client5:httpclient5:jar:5.2.1:runtime
[INFO] |        |  |  \- org.apache.httpcomponents.core5:httpcore5-h2:jar:5.2:runtime
[INFO] |        |  \- org.apache.httpcomponents.core5:httpcore5:jar:5.2.1:runtime
[INFO] |        \- org.xmlresolver:xmlresolver:jar:data:4.4.3:compile
```

since it is not supported in native, so I seperate it into a jvm test group. see https://github.com/apache/camel-quarkus/pull/4753

**Comment by zhfeng** [comment]
@JiriOndrusek  I already remove `org.apache.hc.client5.http.impl.auth.NTLMEngineImpl` in `XslProcessor`.

**Comment by zhfeng** [comment]
I've added in `XstlSaxonProcessor` now. Then it should be closed.
