### ISSUE TITLE
Foundation: RouteConfigurationsTest.sendContentToXmlRouteShouldTriggerOnExceptionInYamlRouteConfiguration fails

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#4736]
Tast [RouteConfigurationsTest#sendContentToXmlRouteShouldTriggerOnExceptionInYamlRouteConfiguration](https://github.com/apache/camel-quarkus/blob/main/integration-test-groups/foundation/route-configurations/src/test/java/org/apache/camel/quarkus/core/it/routeconfigurations/RouteConfigurationsTest.java#L93) fails.

The issue is caused by the fact, that the `onException` condition defined in [xml](https://github.com/apache/camel-quarkus/blob/main/integration-test-groups/foundation/route-configurations/src/main/resources/xml/routeConfigurations.xml#L21), is not triggered. Interesting fact is that if the xml condition is used from different route, or if the route uses different routeCondition (define by java or yaml), the test is succesful.

**Comment by jamesnetherton** [comment]
I think this is the change that causes the problem:

https://github.com/apache/camel/commit/15a2ef2948c6bcb38c7310083a565db351c481d1

I don't know if this test scenario is valid or not. Where you define a route configuration in one DSL language and reference it in another (E.g XML -> YAML). Maybe @aldettinger has an opinion.

**Comment by aldettinger** [comment]
They share the same context, so likely the route configurations are shared also.
Maybe this is a behavior that is changing with camel 4 ?

@davsclaus @oscerd  What do you think ?

**Comment by davsclaus** [comment]
yes route configurations are global in the same single context. What is triggered is dependent on route configuration ids, and what has been configured on the route.

**Comment by aldettinger** [comment]
Many thanks, so we'll need to fix this when we have bandwidth. And maybe even have the test in camel itself.
