### ISSUE TITLE
Support dependency injection of FluentProducerTemplate/FluentConsumerTemplate 

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#474]
If you have a quarks rest service then you may want to inject Camel as a producer or consumer template (also the fluent builder kind)

```
@Path("/hello")
public class ExampleResource {

    @Inject
    private CamelContext camel;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "hello";
    }

    @GET
    @Path("/bye")
    @Produces(MediaType.TEXT_PLAIN)
    public String bye() throws Exception {
        return camel.createFluentProducerTemplate().to("direct:bye").request(String.class);
    }
}
```

But so far its only inject of `CamelContext` that works.

It would be nice to inject

    @Inject
    private ProducerTemplate camel;

And if you add the camel annotations for `@Produce` and `@Consume` and also the older `@EndpointInject` name which works on both producer and consumer templates

    @Inject
    @Produce("kafka:blah")
    private FluentProducerTemplate camel;

**Comment by lburgazzoli** [comment]
The produce template should already work, we have some tests that are using it like https://github.com/apache/camel-quarkus/blob/396e008a9549b07cbea0835d655e2324aecf5d1a/integration-tests/controlbus/src/main/java/org/apache/camel/quarkus/component/controlbus/it/ControlbusResource.java#L35-L36

**Comment by ppalaga** [comment]
ConsumerTemplate is also used in several itests:

https://github.com/apache/camel-quarkus/blob/212887909b4509b99abe77860d833670935e85d9/integration-tests/paho/src/main/java/org/apache/camel/quarkus/component/paho/it/PahoResource.java#L42-L43

**Comment by davsclaus** [comment]
Maybe they only work on ApplicationScoped classes. This is a REST service class, eg what you get when you create a new project from the code website

**Comment by lburgazzoli** [comment]
Yeah this is a CDI thing, not sure how quarkus handles JX-RS things maybe we should open a cross issue on quarkus

**Comment by davsclaus** [comment]
Ah okay I got it working with 

    @Inject
    private ProducerTemplate camel;

But we dont support `FluentProducerTemplate` so can we get them added (also for consumer)

**Comment by davsclaus** [comment]
You can add this to `CamelProducers` and then change some of the existing unit test or add a new one that uses the fluent template instead.
