### ISSUE TITLE
[camel-main] Csimple:  Cannot find compiled csimple language for expression: Hello ${body}

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#4745]
Recent camel changes broke the test `CSimpleTest` from the module `integration-tests/csimple` on `camel-main` branch.

The error message is: `org.apache.camel.language.csimple.CSimpleException: Cannot find compiled csimple language for expression: Hello ${body}`

I tried the same scenario in Camel and it works (in component `camel-csimple-joot`)

I think that problem is related to the older CQ commit (from Jan) https://github.com/apache/camel-quarkus/commit/b4ac438e8e5041e232d5ed4556c85d4b5fc9e4da
and some recent Camel changes (I saw the failure for the first time about 2 days ago. I verified that Camel built from revision `84cb7636ae6906acf47a67aedf25bf7ed2a25b1c` makes CQ fsail. (I didn't try earlier commits because of compilation problems in recent days).

**Comment by JiriOndrusek** [comment]
@essobedo May I ask you for help?

**Comment by JiriOndrusek** [comment]
I'm not sure if scenario is valid (without `camel-csimple-joor`), but if I tried the same scenario in `camel-core` and  it was failing.

**Comment by JiriOndrusek** [comment]
Thank you for the fix! I checked both tests locally and they work. Once the CI confirms it, I'll close this ticket.

**Comment by essobedo** [comment]
Good news
