### ISSUE TITLE
camel-quarkus-jdbc: using named parameters fails for postgresql db kind

### ISSUE THREAD

**Issue by ldrozdo** [apache/camel-quarkus#4750]
Using [named parameters](https://camel.apache.org/components/3.20.x/jdbc-component.html#_using_named_parameters) in jdbc integration tests fails for **postgresql** database kind. Other database kinds are ok.

There are two tests which are failing:
1. [Named parameters test](https://github.com/apache/camel-quarkus/blob/main/integration-tests/jdbc/src/test/java/org/apache/camel/quarkus/component/jdbc/CamelJdbcTest.java#L119)
2. [Named parameters map test](https://github.com/apache/camel-quarkus/blob/main/integration-tests/jdbc/src/test/java/org/apache/camel/quarkus/component/jdbc/CamelJdbcTest.java#L129)

[This query](https://github.com/apache/camel-quarkus/blob/main/integration-tests/jdbc/src/main/java/org/apache/camel/quarkus/component/jdbc/CamelResource.java#L153) is used in the tests.

The error message: 
`Caused by: [CIRCULAR REFERENCE: org.postgresql.util.PSQLException: ERROR: operator does not exist: integer < character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.`

**Comment by jamesnetherton** [comment]
Just a guess, does it work if you pass `3` as an `int` instead of `String`?

Otherwise I guess you have to do type [casting](https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-cast/).

**Comment by ldrozdo** [comment]
@jamesnetherton that actually works, thanks! I'm closing this and I will rewrite the tests.
