### ISSUE TITLE
Introduce group testing for different jdbc db types

### ISSUE THREAD

**Issue by ldrozdo** [apache/camel-quarkus#4772]
As discussed in #4751, we could implement [group testing ](https://camel.apache.org/camel-quarkus/3.0.x/contributor-guide/extension-testing.html#_grouping) for db types in jdbc integration tests.

Supported DBs:
- Postgresql
- MySQL 
- MariaDB 
- H2 
- DB2
- MSSQL 
- Oracle

**Comment by ppalaga** [comment]
Would you like to work on this @ldrozdo?

**Comment by ldrozdo** [comment]
@ppalaga yes I can :)  but I can't start right now because of other priorities.

**Comment by zhfeng** [comment]
Thanks @ldrozdo - I just assign it to you but no worries,  keep your priorities please.
