### ISSUE TITLE
[camel-main] Add `quarkus-jackson-jq-extra` to jq extension runtime module dependencies

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#4799]
For this upcoming change in Camel 4.0.0-M3:

https://issues.apache.org/jira/browse/CAMEL-19276

```xml
<dependency>
  <groupId>io.quarkiverse.jackson-jq</groupId>
  <artifactId>quarkus-jackson-jq-extra</artifactId>
</dependency>
```

**Comment by JiriOndrusek** [comment]
Thanks @jamesnetherton ! Fixed in https://github.com/apache/camel-quarkus/commit/9ea406887180965bd3246dfc0dc8e5d70b5f1ff7
