### ISSUE TITLE
Cannot find eclipse-formatter-config.xml when an example is copied out of examples source tree.

### ISSUE THREAD

**Issue by shankar-sundar** [apache/camel-quarkus#4832]
I am encountering _cannot find config file_ error when running Maven commands as per the instructions. 

- [First Steps > Example Projects > Development Mode](https://camel.apache.org/camel-quarkus/3.0.x/user-guide/first-steps.html#_development_mode)
- [First Steps > Example Projects > Testing](https://camel.apache.org/camel-quarkus/3.0.x/user-guide/first-steps.html#_testing)
- [First Steps > Example Projects > JVM Mode](https://camel.apache.org/camel-quarkus/3.0.x/user-guide/first-steps.html#_jvm_mode)
- [First Steps > Example Projects > Native Mode](https://camel.apache.org/camel-quarkus/3.0.x/user-guide/first-steps.html#_native_mode)

`[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.17.1:format (format) on project camel-quarkus-examples-rest-json: Cannot find config file [/<path>/quarkus-samples/rest-json/eclipse-formatter-config.xml] -> [Help 1]`

However, the error can be resolved by adding the property -Dmaven.multiModuleProjectDirectory=../camel-quarkus-examples to the commands.

**Comment by ppalaga** [comment]
Indeed, thanks for the report, @shankar-sundar!

**Comment by ppalaga** [comment]
I guess the easiest solution would be to copy the `eclipse-formatter-config.xml` over to all example subdirs. So that they stay in sync in the future, we can put a `cp` line to `mvnw-for-each.sh`. What do others think?

**Comment by jamesnetherton** [comment]
Fixed here https://github.com/apache/camel-quarkus-examples/pull/140.
