### ISSUE TITLE
Automatic upgrade to Camel Quarkus 3

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#4846]
Quarkus has just published a doc page about the topic:

https://quarkus.io/guides/update-quarkus

We should check how well it works for CQ projects now and whether something needs to be fixed.

**Comment by zbendhiba** [comment]
I started testing in some of our apps. 
this is one issue to follow https://github.com/quarkusio/quarkus/issues/33805

**Comment by jamesnetherton** [comment]
We've had this since 3.2.x as part of the `quarkus update` tooling.
