### ISSUE TITLE
Paho MQTT 5 Component Quarkus: using ssl inside native image

### ISSUE THREAD

**Issue by francescobianca** [apache/camel-quarkus#4895]
**[Quarkus Framework]** Hi, I have compiled my image implementing an MQTT Paho5 client developed with Camel connector in JVM mode and it works correctly. The same image compiled with Docker native file gives error:

`org.apache.camel.PropertyBindingException: Error binding property (camel.component.paho-mqtt5.socketFactory=#class:mypackage.MqttSocketFactory) with name: socketFactory on bean: org.apache.camel.component.paho.mqtt5.PahoMqtt5Component@328cbaba with value: #class:mypackage.MqttSocketFactory`

Do you have to set any special configuration to use SSL on native image? The exact same configuration in JVM mode works without any problems.

**Comment by jamesnetherton** [comment]
If you use `#class`, then Camel will use reflection to instantiate the target class. Therefore, you need to provide a hint to the native compiler by annotating `mypackage.MqttSocketFactory` with `@RegisterForReflection`. See the native mode guide for more information:

https://camel.apache.org/camel-quarkus/3.0.x/user-guide/native-mode.html#reflection

You can probably avoid reflection entirely and create a CDI bean producer for the socket factory like:

```java
@ApplicationScoped
public class SocketFactoryProducer {
    @Produces
    @Named("mySocketFactory")
    public SocketFactory createSocketFactory() {
        return new MqttSocketFactory();
    }
}
```

Then the configuration can reference the named bean:

```
camel.component.paho-mqtt5.socketFactory=#mySocketFactory
```

**Comment by francescobianca** [comment]
Thank you very much, annotating the class with `@RegisterForReflection` works native compilation!

```
@RegisterForReflection
@Singleton
@Log4j2
public class MqttSocketFactory extends SSLSocketFactory {
```
