### ISSUE TITLE
Add support for tidymarkup and tagsoup

### ISSUE THREAD

**Issue by jsight** [apache/camel-quarkus#490]
https://camel.apache.org/components/latest/tidyMarkup-dataformat.html

**Comment by ppalaga** [comment]
@jsight are you by any chance planning to work on this?

**Comment by jsight** [comment]
@ppalaga - I wasn't, but maybe this would maybe be a good starting point for me? I will give it a shot.

**Comment by ppalaga** [comment]
You may want to check https://camel.apache.org/camel-quarkus/latest/contributor-guide.html
Feel free to ask here if you have specific questions.

**Comment by jsight** [comment]
PR sent -- I didn't know about the contributor guide when I started, so this was done a bit manually. Hopefully the steps were taken correctly... happy to adjust based on feedback, though.

**Comment by lburgazzoli** [comment]
Done with https://github.com/apache/camel-quarkus/pull/493
