### ISSUE TITLE
[camel-main] Remove excludes for tika/runtime

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#4907]
Camel upgraded tika-core to 2.8.0, quarkiverse/quarkus-tika is still on 2.7.0 
Quarkiverse/quarkus-tika already contains upgrade to 2.8.0 in https://github.com/quarkiverse/quarkus-tika/commit/1df2751671f67d356a6d7f8f04278c240c407099.
As soon as this update is propagated to camel-quarkus, exclusions in tika/runtime can be removed.

**Comment by jamesnetherton** [comment]
`quarkus-tika` 2.0.1 is available now. I also think we should restore exclusions for `camel-tika` in the BOM:

```
<exclusion>
    <groupId>org.apache.tika</groupId>
    <artifactId>*</artifactId>
</exclusion>
```

Otherwise it makes life harder to do seamless upgrades.

**Comment by JiriOndrusek** [comment]
I'll do it, thanks for notifying me!

**Comment by JiriOndrusek** [comment]
Fixed in `camel-main`
