### ISSUE TITLE
Improve netty-http test coverage

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#4956]
Improve `netty-http` consumer test coverage:

* Accessing `HttpRequest` / `HttpReponse` via `NettyHttpMessage`
* Basic authentication
* REST DSL
* Reverse proxy (E.g `from("netty-http:proxy")`)
* Specifying ACL on web resources with `SecurityConstraint` & `SecurityConstraintMapping`
* Wildcard routes (E.g `matchOnUriPrefix`)

**Comment by svkcemk** [comment]
@jamesnetherton I would like to work on this, I can't assign this to myself, feel free to assign it me, thanks!

**Comment by jamesnetherton** [comment]
I think @avano was going to look into this one.

@avano is that still the case?

**Comment by avano** [comment]
@jamesnetherton correct, you can assign to me
