### ISSUE TITLE
[Quarkus 3.2.0]  Enable native profile in master-openshift test

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#4957]
Camel [upgraded](https://github.com/apache/camel/commit/acd87a8a2191ba153c1c2aff18cc666d40bf648c) kubernetes-client to 6.7.0 which fails the native execution of master-openshift.

Bump on Quarkus side is already proposed - see the [PR](https://github.com/quarkusio/quarkus/pull/33767).

Native profiles are disabled in kubernetes and master-opemshift tests. Enable them once Quarkus is upgraded.

**Comment by jamesnetherton** [comment]
I disabled the native profile on `cluster-leader-election` example project. So that will also need reverting eventually.
