### ISSUE TITLE
Delegate complexity to quarkus-groovy

### ISSUE THREAD

**Issue by essobedo** [apache/camel-quarkus#4959]
[A new extension has been added to the Quarkiverse](https://github.com/quarkiverse/quarkus-groovy) that provides the support of Groovy in native mode, the code base could be simplified by delegating the complexity related to the native mode to the extension.

**Comment by essobedo** [comment]
Depends on https://github.com/apache/camel-quarkus/issues/4960

**Comment by zbendhiba** [comment]
Nice @essobedo !
