### ISSUE TITLE
Dead guides links for extensions

### ISSUE THREAD

**Issue by holly-cummins** [apache/camel-quarkus#4964]
It looks like the guides links in the released extensions have gone out of sync with the published docs again. 

I've started doing transformations to map from dead links (trying the previous release, etc). In these case, however, it seems like the issue isn't a timing one for when the docs are released and what extension is in what platform, but rather that we've changed the names or paths of docs pages. (Quarkus has this sometimes in the docs and handles it by putting redirects where the old pages were.)

For most of these, it seems like the name should have `-component.html` added on to the end, but there are exceptions. For example, https://camel.apache.org/camel-quarkus/latest/reference/extensions/cli-connector.html should be https://camel.apache.org/components/latest/others/cli-connector.html.

```
    +   "https://camel.apache.org/camel-quarkus/latest/reference/extensions/cli-connector.html => 404 (Not Found) on http://localhost:9000/org.apache.camel.quarkus/camel-quarkus-cli-connector",
    +   "https://camel.apache.org/camel-quarkus/latest/reference/extensions/datasonnet.html => 404 (Not Found) on http://localhost:9000/org.apache.camel.quarkus/camel-quarkus-datasonnet",
    +   "https://camel.apache.org/camel-quarkus/latest/reference/extensions/elasticsearch.html => 404 (Not Found) on http://localhost:9000/org.apache.camel.quarkus/camel-quarkus-elasticsearch",
    +   "https://camel.apache.org/camel-quarkus/latest/reference/extensions/mapstruct.html => 404 (Not Found) on http://localhost:9000/org.apache.camel.quarkus/camel-quarkus-mapstruct",
    +   "https://camel.apache.org/camel-quarkus/latest/reference/extensions/optaplanner.html => 404 (Not Found) on http://localhost:9000/org.apache.camel.quarkus/camel-quarkus-optaplanner",
    +   "https://camel.apache.org/camel-quarkus/latest/reference/extensions/smallrye-reactive-messaging.html => 404 (Not Found) on http://localhost:9000/org.apache.camel.quarkus/camel-quarkus-smallrye-reactive-messaging",
    +   "https://camel.apache.org/camel-quarkus/latest/reference/extensions/xmlsecurity.html => 404 (Not Found) on http://localhost:9000/org.apache.camel.quarkus/camel-quarkus-xmlsecurity",
    +   "https://camel.apache.org/camel-quarkus/latest/reference/extensions/tika.html => 404 (Not Found) on http://localhost:9000/org.apache.camel.quarkus/camel-quarkus-tika",
    ```

**Comment by jamesnetherton** [comment]
This is because the Camel website is set up to point at the `3.0.x` branch where these extensions do not exist:

https://github.com/apache/camel-website/blob/main/antora-playbook-snippets/antora-playbook.yml#LL66C1-L66C16

It should probably be updated to `3.0.0-M2.x`.

@ppalaga do we actually need to maintain separate branches for these 3.x milestone releases? Or should we just rebase / reset  `3.0.x` to the content from `3.0.0-M2.x`?

**Comment by holly-cummins** [comment]
Thanks for looking @jamesnetherton! I've hit the exact problem you describe in the past, and so I do a bit of logic where if the link doesn't exist, it will try a version before or after. There's some hardcoding in there in what I check, so I probably need to continue tuning it as new releases happen. 

However, in this case, it seems like the actual file names have changed/are incorrect. 

For example, 
https://camel.apache.org/components/latest/mapstruct.html does not exist
https://camel.apache.org/components/3.0.0.x/mapstruct.html does not exist
https://camel.apache.org/components/3.20.x/mapstruct.html does not exist
https://camel.apache.org/components/3.20.x/mapstruct-component.html *does* exist (note it's got `-component` tacked on to the end)

.... or are the -component pages actually a different page?

**Comment by jamesnetherton** [comment]
> or are the -component pages actually a different set of content?

Yes, it's a different set of content....

The setup of the Camel documentation is quite complex. Each project in the Camel ecosystem maintains its own set docs and it's all tied together on the Camel website with Antora playbooks.

This project maintains docs specific to Camel Quarkus extensions and they contain links to the corresponding Camel component docs.

Things are in a state of flux (or mess :slightly_smiling_face:) at the moment because docs for Camel 4.x have not yet been published. So we are having to link to the older 3.x Camel releases.

I think if we fixed up the `3.0.x` branch as I suggested, it would probably fix the 404s you mentioned.

**Comment by holly-cummins** [comment]
Ah, ok, that makes sense. Is there any published page on the camel docs site for mapstruct.html, or is it only in the unpublished 3.0.0-M2 branch? I can get some ways with mapping from one release to another, but if there's nothing to map to, I think it would need the camel docs site changes you suggest.

**Comment by holly-cummins** [comment]
I thought 2.16.x is what I normally attempted to map to, but I've checked, and optaplanner does have a https://camel.apache.org/camel-quarkus/2.16.x/reference/extensions/optaplanner.html. Then I checked the code and there's something about 2.13, but nothing about 2.16.x, so I'll try that and see how many of the dead links I can resolve with that back-mapping. I just tried another one at random, and https://camel.apache.org/camel-quarkus/2.16.x/reference/extensions/elasticsearch.html doesn't exist, so it definitely won't be all of them.

For Quarkus, they have a `snapshot` docs section, and if I can't find anything else, I link to that. For example, https://quarkus.io/version/main/guides/ is the top level. Something similar for Camel might make sense. I think that's what you're suggesting, @ppalaga. Quarkus call it `main` but I think `next` works well.

**Comment by jamesnetherton** [comment]
> we should remove 3.0.x and have only next, WDYT?

Yes, sounds ok to me :+1:

**Comment by jamesnetherton** [comment]
We already have 'next' available so linking to that would work:

https://camel.apache.org/camel-quarkus/next/reference/extensions/mapstruct.html

**Comment by jamesnetherton** [comment]
> maybe we should leave it open to track the M2 switch

Yes, that's fine 👍

**Comment by jamesnetherton** [comment]
Sorry it took so long, but we finally have docs for 3.x published:

https://camel.apache.org/camel-quarkus/3.2.x/

**Comment by holly-cummins** [comment]
Ahh, that would explain why I saw some new failures this morning (doh!). I haven't investigated properly to see if I need a different mapping logic now that we have the new release. I assume that's what's caused me problems. It's these guys: 

```
      "https://camel.apache.org/camel-quarkus/latest/reference/extensions/atlasmap.html",
      "https://camel.apache.org/camel-quarkus/latest/reference/extensions/corda.html",
      "https://camel.apache.org/camel-quarkus/latest/reference/extensions/solr.html",
      "https://camel.apache.org/camel-quarkus/latest/reference/extensions/vm.html",
```

I had a quick look and I could see 3.2.1 links for atlasmap component, but I don't know if that's the same as atlasmap, and ... I'm continuing to look at it, but if something jumps out at you from that list about what they have in common, do shout. 

Oh, and thanks for the update, and sorry to be the bearer of miserable news!

**Comment by jamesnetherton** [comment]
It's expected unfortunately, as all of those extensions got removed in Camel 4.0.0 / Camel Quarkus 3.2.0 / Quarkus Platform 3.2.6.Final.

**Comment by holly-cummins** [comment]
Ah, thanks for the insider knowledge! So what's supposed to happen in that case is that we go back through the docs to find the version of the docs where the extension did exist, and just point to that. Do you happen to know if there would be a version of the docs that they would still exist in? If so, I can figure out why I'm not finding it. 

Or, if the extension is marked as deprecated, we don't bother and just don't show its docs. But I guess there was no release of those extensions where they were marked as deprecated between being there and not-there ... is that right?

**Comment by jamesnetherton** [comment]
> But I guess there was no release of those extensions where they were marked as deprecated between being there and not-there ... is that right?

Yeah, I think that is the problem (I've not checked to verify yet). Some of those bits got removed late on as we approached the Camel 4.0.0 GA.

Probably the only stable version of the docs where those extensions are still present is in the `2.13.x` stream, which is LTS:

https://camel.apache.org/camel-quarkus/2.13.x/index.html
