### ISSUE TITLE
Intermittent failure of integration test `HazelcastListTest`

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#4989]
### Bug description

When upgrading the `quarkus-hazelcast-client` to 4.0.0 `HazelcastListTest` seems to be a bit flaky (it passed locally on average around 1 - 2 times out of 10 tries). There aren't really any clues from the console output as to what the problem could be.

**Comment by ppalaga** [comment]
Perhaps related to https://github.com/apache/camel-quarkus/issues/5081 ?

**Comment by aldettinger** [comment]
One more occurence here:
https://github.com/apache/camel-quarkus/actions/runs/6221815994/job/16885318727#step:8:1061
