### ISSUE TITLE
Filter out beans from CDI from build time discovery

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#499]
If i.e. a component is defined using CDI, like:

```java
@Singleton
public class CamelComponents {
    @Singleton
    @Named("direct")
    @Produces
    DirectComponent directComponent() {
        DirectComponent component = new DirectComponent();
        component.setTimeout(1234);

        return component;
    }
}
```

we should exclude it from build time auto discovery

**Comment by ppalaga** [comment]
> we should exclude it from build time auto discovery

Why?

**Comment by lburgazzoli** [comment]
because the auto discovered one has lower priority than the the runtime one so there's no point to have an unused instance of a component/language/data-format in the registry
