### ISSUE TITLE
Add native support for camel-quarkus-management

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5029]
### Describe the feature here

Since there is now experimental support for JMX in GraalVM, we could investigate adding some initial support for it in the `camel-quarkus-management` extension.

I did some very brief hacking and got to view the Camel MBeans:

![jmx-native](https://github.com/apache/camel-quarkus/assets/4721408/96e239e3-92f5-4e44-afd2-7b80a4e1d342)

![jmx-native2](https://github.com/apache/camel-quarkus/assets/4721408/5bce28bc-09be-4dfb-91dd-9bc90da32974)

**Comment by tadayosi** [comment]
@jamesnetherton Wow, so could we run JMX with native build?

**Comment by jamesnetherton** [comment]
> @jamesnetherton Wow, so could we run JMX with native build?

Yes, this provides native JMX support for Camel. Jolokia in native mode for HawtIO will probably bring its own set of problems that would need investigating. But we now have a basic starting point at least.

**Comment by zbendhiba** [comment]
@jamesnetherton Awesome !
