### ISSUE TITLE
camel-sql extension

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#505]
its using spring-jdbc but that may work with the spring data compatibility in quarkus?

**Comment by jamesnetherton** [comment]
Isn't Quarkus Spring Data more JPA focussed? So maybe better suited to camel-jpa?

We already have a camel-jdbc extension, so implementing camel-sql should be simple enough. I'm happy to work on it (and camel-jpa if we want to add an extension for it).

**Comment by lburgazzoli** [comment]
As far as I can remember the spring compatibility does not use any spring bits but translates spring concerns into the related quarkus/hibernate bits

**Comment by davsclaus** [comment]
Ah yeah a camel-jpa extension would be great

**Comment by davsclaus** [comment]
the sql component is just much more powerful than jdbc so it would have been nice
