### ISSUE TITLE
Velocity $foreach.index, $foreach.count and $foreach.hasNext do not work in native mode

### ISSUE THREAD

**Issue by jorgecastro05** [apache/camel-quarkus#5080]
### Bug description

Sentences like $foreach.index,  $foreach.count, y $foreach.hasNext used on velocity templates are not avaliable on native executables.

**How to reproduce?**

This is example repo using apache velocity - camel and quarkus latest version
https://github.com/jorgecastro05/velocity-test-latest

Once packaged native with quarkus build --native and running the native executable the foreach.hasNext is not rendered on the route.

**Fix workaround**

adding class org.apache.velocity.runtime.directive.ForeachScope  for register to reflection, the template is rendered successfully.

**Comment by ppalaga** [comment]
Thanks a lot for the reproducer, @jorgecastro05!
