### ISSUE TITLE
Re-add activemq extension after it was added back in Camel 4.0.0-RC1

### ISSUE THREAD

**Issue by jsight** [apache/camel-quarkus#5087]
### Bug description

It is no longer listed as removed here: https://camel.apache.org/manual/camel-4-migration-guide.html#_removed_components

**Comment by ppalaga** [comment]
Indeed, camel-activemq was added back in Camel 4.0.0-RC1

Let me revert 946e37aa3f2b6242a6555fb073fce2ce2e55d9a3 and see whether our old tests still pass.
