### ISSUE TITLE
[camel-main] Enable ssh tests + native after consuming quarkus-main (which brings sshd 2.10.0)

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#5092]
### Description

Tests and native profile in ssh integration-tests module are disabled, because camel requires sshd 2.10.0 and quarkus 3.2.0 brings 2.9.2.
Newest Quarkus already contains this upgrade (see https://github.com/quarkusio/quarkus/commit/c7eab6e6b7550c580e5fa85f02c4e3aabb7434f3)

**Comment by jamesnetherton** [comment]
I asked for the upgrade to be backported for Quarkus 3.2.1:

https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Backport.20sshd.202.2E10.2E0.20upgrade.20for.203.2E2.2E1.2EFinal

**Comment by jamesnetherton** [comment]
@JiriOndrusek you should be able to enable the tests again on `camel-main` after rebasing from `main`.

**Comment by JiriOndrusek** [comment]
Thanks, I'll try that.

**Comment by jamesnetherton** [comment]
Fixed by https://github.com/apache/camel-quarkus/pull/5119.
