### ISSUE TITLE
Upgrade localstack to 2.x

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5153]
### Description

We are using an ancient version of localstack. We should try to move to the latest release if possible.

**Comment by ppalaga** [comment]
I wonder if dependabot can be configured to upgrade also the new container image properties? 

@helpermethod has recenly shown something similar for Renovate. It is for upgrading JBang in-java deps using RegEx: https://twitter.com/helpermethod/status/1684873546059616257 The same approach would work for our new `.*\.container\..image` properties. But we do not use Renovate. Dependabot can perhaps do the same.
