### ISSUE TITLE
Expand Splunk test coverage

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#5154]
Several missing features should be covered by the tests:

- Scenario with a splunk producer using `raw == true` (see the [documentation](https://camel.apache.org/components/3.21.x/splunk-component.html#_endpoint_query_option_raw)), is not covered.
- ~Scheduler (leveraging camel-quartz) see the [doc](https://camel.apache.org/components/3.21.x/splunk-component.html#_endpoint_query_option_scheduler)~ not needed
-  ~Option to run tests on external Splunk instance (configurable via env, similar to aws2)~ not needed

**Comment by JiriOndrusek** [comment]
Current test coverage contains an error, which uses "submit" producer instead of stream or tcp ones.
Tests have to be fixed.

**Comment by jamesnetherton** [comment]
Fixed in https://github.com/apache/camel-quarkus/pull/5192.
