### ISSUE TITLE
[question] introduce testcontainers 

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#516]
I'm experimenting with testcontainers to replace the embedded kafka server we have now for running camel-quarkus-kafka integration tests and it simplifies a lot the set-up. 

The downside is that some tests depends on docker.

Any objection to introduce testcontainers ?

**Comment by ppalaga** [comment]
I'd prefer a solution that would work OOTB in Fedora 31 (no dockerd).

**Comment by lburgazzoli** [comment]
you can install moby :)

**Comment by lburgazzoli** [comment]
The point is that even the guys from debezium (providers of the kafka embedded facilities) recommend to use testcontainers

**Comment by davsclaus** [comment]
No we use testcontainers in camel 3 too, so we should do it here too. And you are welcome to make camel-kafka use testcontainers too, it uses some embedded kafka shit

**Comment by davsclaus** [comment]
And us mac osx guys are often the guys with docker issues, over those with native linux.

**Comment by oscerd** [comment]
+1

**Comment by bsideup** [comment]
> And us mac osx guys are often the guys with docker issues, over those with native linux.

Most of Testcontainers' development is done on Mac OS X (and the majority of devs that use TC are also on Mac OS X), you can be pretty confident that Testcontainers will work just fine on it ;)
