### ISSUE TITLE
Add `org.mapstruct:mapstruct-processor` to the BOM

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5163]
### Describe the feature here

Although `mapstruct-processor` is just a build time annotation processor dependency, it could be useful for users it if were in the BOM. Future versions of the `maven-compiler-plugin` will be able to [leverage](https://issues.apache.org/jira/browse/MCOMPILER-391) `dependencyManagement` for such dependencies.

**Comment by ppalaga** [comment]
> `maven-compiler-plugin` will be able to [leverage](https://issues.apache.org/jira/browse/MCOMPILER-391) `dependencyManagement`

Interesting!
