### ISSUE TITLE
`jms-ibmmq-client` integration test native build runs on CI despite being commented out

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5180]
### Bug description

Not sure what's going on here. The native profile is commented out:

https://github.com/apache/camel-quarkus/blob/main/integration-tests/jms-ibmmq-client/pom.xml#L108-L136

But in the CI logs we see:

```
2023-08-14T11:11:27.1623572Z GraalVM Native Image: Generating 'camel-quarkus-integration-test-jms-ibmmq-client-3.0.0-SNAPSHOT-runner' (executable)...
```

Started happening with the Quarkus 3.2.4 upgrade. The only vaguely related thing in the release notes is:

https://github.com/quarkusio/quarkus/pull/35203

**Comment by zhfeng** [comment]
Hmm, it's weird and I will take a look today.

**Comment by zhfeng** [comment]
It seems that the only way is to add `<quarkus.build.skip>true</quarkus.build.skip>` to skip quarkus build.

**Comment by zhfeng** [comment]
There is a related commit https://github.com/quarkusio/quarkus/commit/3747c0d85b68ca33b58871d9cf3b2d4b3bb304a4#diff-784b0a28679cfd7486e574f42e90ece03e187bae1e132d5c408f72eaa7ecfdf0

I wonder the `if` statement should check `setPackageTypeSystemPropertyIfNativeProfileEnabled` is true?

**Comment by zhfeng** [comment]
OK, the following change looks fixing our issue.
```
diff --git a/devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java b/devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java
index 0c7146ddb16..fefb7457970 100644
--- a/devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java
+++ b/devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java
@@ -118,7 +118,7 @@ protected void doExecute() throws MojoExecutionException {
             // Essentially what this does is to enable the native package type even if a different package type is set
             // in application properties. This is done to preserve what users expect to happen when
             // they execute "mvn package -Dnative" even if quarkus.package.type has been set in application.properties
-            if (!setPackageTypeSystemPropertyIfNativeProfileEnabled()) {
+            if (setPackageTypeSystemPropertyIfNativeProfileEnabled()) {
                 propertiesToClear.add(PACKAGE_TYPE_PROP);
             }

```

**Comment by zhfeng** [comment]
Anyway, I open the above quarkus issue to see if it can be fixed in upstream.
