### ISSUE TITLE
XSLT documentation is misleading

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#520]
XSLT configuration [docs](https://camel.apache.org/camel-quarkus/latest/extensions/xslt.html#_configuration) seem to suggest that the `file:` URI scheme is supported for the `quarkus.camel.xslt.sources` property.

But the extension seems to only be able to handle the `classpath` resources.

```
Build step org.apache.camel.quarkus.component.xslt.deployment.XsltProcessor#xsltResources threw an exception: java.lang.RuntimeException: URI scheme 'file:' not supported for build time compilation of XSL templates. Only 'classpath:' URIs are supported
	at org.apache.camel.quarkus.component.xslt.deployment.BuildTimeUriResolver.resolve(BuildTimeUriResolver.java:41)
	at org.apache.camel.quarkus.component.xslt.deployment.XsltProcessor.xsltResources(XsltProcessor.java:95)
```

**Comment by ppalaga** [comment]
Yes, the docs is out of date. My fault, I can fix it unless you started already.

**Comment by jamesnetherton** [comment]
Thanks. Please go ahead and fix whenever you get time :+1:
