### ISSUE TITLE
ZenDesk native integration test failure

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5201]
### Bug description

Quarkus is now managing `async-http-client` (for Pulsar) which effectively downgrades it to a non JakartaEE 10 friendly impl.

https://github.com/quarkusio/quarkus/issues/35128

**Comment by llowinge** [comment]
I'm just adding note here about https://github.com/apache/camel-quarkus/blob/main/extensions-support/ahc/deployment/src/main/java/org/apache/camel/quarkus/component/support/ahc/deployment/JakartaEnablement.java#L40 - CQ still uses async-client which is not Jakarta 10 compatible, so we cannot remove the workaround.
