### ISSUE TITLE
RuntimeCustomizerFallbackTest and RuntimeCustomizerTest are failing

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#5235]
### Bug description

Follows up https://github.com/apache/camel-quarkus/pull/5219 where we did not have time to investigate why they fail, so we just disabled them

**Comment by jamesnetherton** [comment]
These tests were removed in https://github.com/apache/camel-quarkus/commit/8555b89d1d153fbc529b833226fec239b31defa7.
