### ISSUE TITLE
[camel 3.18.9] Make sure that Johnzon is upgraded to 1.20.21

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#5269]
### Description

If Camel 3.18.9 is picked, make sure that Johnzon 1.20.21 is part of that release (PR is currently opened - https://github.com/apache/camel/pull/11314)
If change is not part of the camel release, upgrade Johnzon in the CQ BOM instead.

**Comment by jamesnetherton** [comment]
Lets close since there wont be a 3.18.9.
