### ISSUE TITLE
Add Generated SBOM to release as artifacts 

### ISSUE THREAD

**Issue by oscerd** [apache/camel-quarkus#5279]
### Describe the feature here

The idea is having something like:

https://repo1.maven.org/maven2/org/apache/commons/commons-dbcp2/2.10.0/

So people can watch/run/check any kind of analysis directly from an immutable SBOM. We just need to add a specific maven  plugin configuration in the release profile, like we did in https://github.com/apache/camel-kamelets/pull/1631

Thoughts on this?

**Comment by jamesnetherton** [comment]
Sounds ok to me.

I think in the quarkus-platform it's planned to generate SBOMs for each participant. So we'd be covered there also.
