### ISSUE TITLE
unable to map platform-http attachment to related form-data

### ISSUE THREAD

**Issue by dhimasya** [apache/camel-quarkus#5306]
### Bug description

hi, I'm really new to Camel-quarkus, just using it for around 6 months.
It mainly uses camel-quarkus-javascript-dsl for route definition.

could anyone help me figure out how to do it, 
I see the sample in the docs that we can fetch the file and input stream, 
but how to map it to the correct form parameter?

here is what i do in js dsl:
```
const Processor = Java.extend(Java.type("org.apache.camel.Processor"))

from("platform-http:/api/v1/upload?httpMethodRestrict=post&consumes=multipart/form-data")
.process(new Processor(function(e) {
   var msg = e.getIn(Java.type("org.apache.camel.attachment.AttachmentMessage"))
   if (msg.hasAttachments()) {
      msg.getAttachments().forEach(row => {
         console.log(row)
         console.log(msg.getAttachmentObject(row))
         console.log(msg.getAttachmentObject(row).getDataHandler().getContent())
      })
   }
   e.getIn().setBody("ok")
}))
```
I managed to do it using another camel component camel-netty, but i want to achieve it using platform-http as its not spawn separated HTTP services and its integration with Quarkus runtime:
```
const Processor = Java.extend(Java.type("org.apache.camel.Processor"))

from("netty-http:0.0.0.0:8082/api/v1/upload")
.process(new Processor(function(e) {   
   const HttpPostRequestDecoder = Java.type("io.netty.handler.codec.http.multipart.HttpPostRequestDecoder")
   const NettyHttpMessage = Java.type("org.apache.camel.component.netty.http.NettyHttpMessage")

   var msg = e.getIn(NettyHttpMessage)
   var data = new HttpPostRequestDecoder(msg.getHttpRequest())

   console.log(data.getBodyHttpDatas())
   
   e.getIn().setBody("ok")
}))
```
when I try to cast the exchange message to nettyHttpMessage inside the platform-http processor it returns me null.

thank you for the really good framework, I really enjoy writing many integration flows using it

**Comment by jamesnetherton** [comment]
> Thank you for the really good framework, I really enjoy writing many integration flows using it

Thanks! Great to hear such feedback :heart: 

> How to map it to the correct form parameter

Unfortunately, I do not think it is possible with `platform-http` at present. The name of the associated form field is logged and then effectively discarded:

https://github.com/apache/camel/blob/0f68caf93cd05b76abde3c8a58882c039bb7e824/components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpConsumer.java#L292 

This hack could maybe work using a `RouteFilter` from `quarkus-reactive-routes`. 

```java
@RouteFilter
void multipartHeaderFilter(RoutingContext rc) {
    rc.request().body().onComplete(new Handler<AsyncResult<Buffer>>() {
        @Override
        public void handle(AsyncResult<Buffer> bufferAsyncResult) {
            rc.fileUploads().forEach(fileUpload -> {
                rc.request().headers().add(fileUpload.fileName(), fileUpload.name());
            });
        }
    });
    rc.next();
}
```

Not sure if it is 100% reliable. But it will give you a Camel message exchange header, where the name is the uploaded file name and the value is the associated form field. So in your `msg.getAttachments` loop you could look it up like:

```
var formFieldName = e.getMessage().getHeader(row);
```

**Comment by dhimasya** [comment]
hi @jamesnetherton thank you for the workaround,
i think this will cause another issue if the API consumer tries to send the file with the same file name on a single request with 2 form input
> This hack could maybe work using a RouteFilter from quarkus-reactive-routes.

and the reference here, why its just drop the form input identifier? it's better to push it to the attachment header when we process the request. 
> Unfortunately, I do not think it is possible with platform-http at present. The name of the associated form field is logged and then effectively discarded:
> https://github.com/apache/camel/blob/0f68caf93cd05b76abde3c8a58882c039bb7e824/components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpConsumer.java#L292

i read servlet implementation and its there when i check the header.
https://github.com/apache/camel/blob/0f68caf93cd05b76abde3c8a58882c039bb7e824/components/camel-servlet/src/main/java/org/apache/camel/component/servlet/AttachmentHttpBinding.java#L75C75-L75C75

i then try to verify it via
```
quarkus.camel.servlet.url-patterns=/*

const Processor = Java.extend(Java.type("org.apache.camel.Processor"))

from("servlet:/api/v1/upload")
.process(new Processor(function(e) {   
    var req = e.getIn().getBody(Java.type("jakarta.servlet.http.HttpServletRequest"))
   console.log(req)
   console.log(req.getParts())
    
   e.getIn().setBody("ok")
}))
```
but again, it feel closer, but i got another blocker.
```
org.graalvm.polyglot.PolyglotException: UT010057: multipart config was not present on Servlet
        at io.undertow.servlet.spec.HttpServletRequestImpl.verifyMultipartServlet(HttpServletRequestImpl.java:520)
        at io.undertow.servlet.spec.HttpServletRequestImpl.getParts(HttpServletRequestImpl.java:509)
```
i try to find the way to set / configure this, but not able to find properties for the servlet component other than url-pattern.

I hope can submit a PR but I'm really clueless about the tooling and general contrib rule here.

**Comment by jamesnetherton** [comment]
If you'd like to contribute to Apache Camel, the first step is to create a Bug report here:

https://issues.apache.org/jira/projects/CAMEL

Then take a browse through the contributors guide:

https://camel.apache.org/camel-core/contributing/

**Comment by jamesnetherton** [comment]
> unable to find a way to set/configure this, so far the quarkus config that i found for servlet is only url-patterns.

Yeah, we are lacking a way to configure the MultiPart bits for the Servlet. I opened https://github.com/apache/camel-quarkus/issues/5326.

**Comment by jamesnetherton** [comment]
Fixed by a combination of https://github.com/apache/camel-quarkus/issues/5326 & https://github.com/apache/camel-quarkus/issues/5981.
