### ISSUE TITLE
Feature: Add camel-mock

### ISSUE THREAD

**Issue by jsight** [apache/camel-quarkus#531]
This is useful for asserting on routes that are not Rest based or that are InOnly.

**Comment by ppalaga** [comment]
Please note that the usefulness of the current camel-mock endpoint is a bit limited in the native mode: the test and the application under test are running in two separate processes, so you cannot share the a single camel-mock instance between them. To test the native executable, you have to wrap the camel endpoints in REST (or similar) interface.

**Comment by jsight** [comment]
I don't really anticipate ever wanting to use native.

**Comment by ppalaga** [comment]
We added a couple of JVM-only extenstions recently, so having mock as a JVM only extension wouldn't be anything special. 

Running

```
mvn -N cq:create -Dcq.nativeSupported=false -Dcq.artifactIdBase=mock
```

from the root directory will scaffold the necessary boilerplate. A contribution with a proper test is welcome!

**Comment by JiriOndrusek** [comment]
Please, assign to me.
