### ISSUE TITLE
[Quarkus 3.5.0] Kubernetes client integration tests fail in native mode

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5318]
### Bug description

Quarkus finally upgraded to Kubernetes Client 6.8.x, so I'll do the same on the Camel side. Until that's released in 4.1.0, we'll need to disable the problem tests on `quarkus-main` & `camel-main`.

**Comment by JiriOndrusek** [comment]
Affected modules (with disabled tests + native profiles) on `camel-main` are:

- kubernetes
- master-openshift
- camel-k-runtime

**Comment by jamesnetherton** [comment]
Fixed in https://github.com/apache/camel-quarkus/pull/5420.
