### ISSUE TITLE
Camel-k-runtime tests is failing in Quarkus platform

### ISSUE THREAD

**Issue by zbendhiba** [apache/camel-quarkus#5319]
### Bug description

When running the integration test in quarkus-platform, we get this error

`Caused by: org.apache.camel.RuntimeCamelException: java.lang.RuntimeException: java.io.FileNotFoundException: /Users/zbendhib/dev/quarkus-platform/generated-platform-project/quarkus-camel/integration-tests/camel-quarkus-integration-test-camel-k-runtime/src/test/resources/routes.xml does not exists`

**Comment by jamesnetherton** [comment]
I enabled camel-k-runtime tests on the platform 3.5.0 upgrade PR and they passed.
