### ISSUE TITLE
Manjaro: Dependency Problem with Platform-HTTP

### ISSUE THREAD

**Issue by bframke** [apache/camel-quarkus#532]
Another Day, another Problem.

I'm using Manjaro Arch Linux to develop software. Some days ago we expanded our camel project with the Dependencies:

1. camel-quarkus-platform-http
2. camel-quarkus-platform-http-component

If I just wanted to use the camel-quarkus-platform-http it wants camel-quarkus-platform-http-component as a dependency, but this also needs org.apache.camel:apt repo. I've added that also to it, but then this happens:

```
Could not resolve all dependencies for configuration ':detachedConfiguration1'.
   > Could not find org.apache.camel.quarkus:camel-quarkus-platform-http:.
     Required by:
         project : > org.apache.camel.quarkus:camel-quarkus-platform-http-deployment:0.4.0
   > Could not find org.apache.camel.quarkus:camel-quarkus-core-xml:.
     Required by:
         project : > org.apache.camel.quarkus:camel-quarkus-core-xml-deployment:0.4.0
   > Could not find org.apache.camel.quarkus:camel-quarkus-support-xml:.
     Required by:
         project : > org.apache.camel.quarkus:camel-quarkus-support-xml-deployment:0.4.0

```
Normally Arch Linux has no apt installed and can't fulfill this dependency. Is there a workaround or am I forced to have a system which has apt?

**Comment by lburgazzoli** [comment]
here apt does not mean the package manager but the annotation processor support that camel provides.

**Comment by oscerd** [comment]
it's really a different thing.

**Comment by bframke** [comment]
Aahh...but why does it still not work, but for my colleagues with the same project setup? Okay, I need to investigate that further, thanks anyway.

**Comment by ppalaga** [comment]
BTW you do not need to depend on `camel-quarkus-platform-http-component` directly. `camel-quarkus-platform-http` is enough. 

`camel-quarkus-platform-http-component` even does not exist since Camel Quarkus 1.0.0-M1 because it was moved to Camel main project.

**Comment by bframke** [comment]
Ah okay, good to know, idea said that component and apt were marked as missing dependencies, so I've added them. Had to move a bit around with the versions to let be build on my end. Now it works, but I will also test that.
