### ISSUE TITLE
Check if disablement of the tests in camel-k-runtine is still needed?

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#5323]
### Description

I noticed some disabled tests on `master-openshift` (related to https://github.com/apache/camel-quarkus/issues/5235)
The reason referenced in https://github.com/apache/camel-quarkus/issues/5235 is already solved, so it might be possible that the tests are working again. 

When the kubernetes client is aligned correctly - https://github.com/apache/camel-quarkus/issues/5318, try to enable the tests.

**Comment by jamesnetherton** [comment]
Fixed in https://github.com/apache/camel-quarkus/pull/5420.
