### ISSUE TITLE
Add documentation about configuration options

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#536]
We should have more docs for camel-quarkus. One page should be about general configuration where you can set many options on `camel.main.xxx` and for example also for components via `camel.component.xxx=123` etc

We should add the page to the TOC
https://camel.apache.org/camel-quarkus/latest/user-guide.html

And also have another page for build time configurations, where you can use
`quarkus.camel.xx` to configure things.

**Comment by davsclaus** [comment]
The build time has the following options
https://github.com/apache/camel-quarkus/blob/master/extensions/core/runtime/src/main/java/org/apache/camel/quarkus/core/CamelConfig.java

**Comment by jamesnetherton** [comment]
IIRC the Quarkus project auto generate their [configuration docs](https://quarkus.io/guides/all-config) from the JavaDoc applied to `ConfigItem` annotated fields.

Maybe we should try to do something similar?

**Comment by ppalaga** [comment]
We now have Camel Quarkus specific options on extension pages. Camel options are listed on the respective component pages to which we link from extension pages. I think we can close this as done. If you feel there is still something to do, please file a new issue that reflects the current state.
