### ISSUE TITLE
Automatically register beans with methods annotated with `@Handler` for reflection

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5378]
### Describe the feature here

Seems our examples where beans have methods annotated with `@Handler` all have the bean class tagged with `@RegisterForReflection`. We should be able to detect such beans at build time and automatically register them for method reflection.

**Comment by jamesnetherton** [comment]
@spatnity you may find this one of interest whenever you get time.

**Comment by spatnity** [comment]
@jamesnetherton Yeah, I'd want to work on this. Thanks for mentioning!
