### ISSUE TITLE
Add support/spring artifact for common substrate support

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#538]
Extract Spring substitutions etc, from the SQL extension into its own 'common' support artifact, since they will likely be needed for other Camel components that we add in the future.

**Comment by ppalaga** [comment]
Sounds good. Would `extensions/support/spring-support` match the current naming scheme, @lburgazzoli ? (Asking because I am about to add a similar ancillary extension)

**Comment by lburgazzoli** [comment]
don't have any strong opinion, would go for a simpler "extensions/support/spring" or if it is specific to the kotlin side of spring something like "extensions/support/spring-kotlin"

but don't mind much

**Comment by ppalaga** [comment]
`extensions/support/spring` sounds good for the directory. The artifactId would be `camel-quarkus-spring-support`, right?

**Comment by lburgazzoli** [comment]
Everything else is like `camel-quarkus-support-${context}`
