### ISSUE TITLE
[Quarkus 3.5.0] Kafka container fails to start when configured for SSL

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5381]
### Bug description

Quarkus upgraded Testcontainers to 1.19.0. One of the new features for Kafka is enabling additional listeners to be configured:

https://java.testcontainers.org/modules/kafka/

Something has changed where the current container config for SSL is no longer working. Hopefully someone smarter than me can figure out what needs modifying for these tests:

* kafka-ssl
* kafka-sasl
* kafka-sasl-ssl

I am disabling them for now.

**Comment by zhfeng** [comment]
It should be fixed by moving all of `withEnv(...);` to the `configuration()` method. I will prepare a PR.
