### ISSUE TITLE
Dozer extension should use JaxbFileRootBuildItem

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#539]
We should leverage the JAXB extension and `JaxbFileRootBuildItem` so that the Dozer `jaxb.index`  can be automatically read and the classes defined in it registered for reflection.

https://github.com/quarkusio/quarkus/issues/6070 currently blocks this.

**Comment by lburgazzoli** [comment]
Should be part of 1.1.0.Final
