### ISSUE TITLE
Consider changing description of this project which is presented in google result

### ISSUE THREAD

**Issue by llowinge** [apache/camel-quarkus#5398]
### Description

Currently when i search for `camel quarkus github` it prints `Apache Camel Quarkus support`. Personally the `support` suffix leads me to impression, it is link to some documentation and not github repo with code.

We should consider following:
* `apache/camel-quarkus - Apache Camel Quarkus - GitHub` - which would corresponds to Quarkus result the most
* `Apache Camel Quarkus - GitHub` - to shorten it a bit, but still show it is really GitHub link
* `Apache Camel Quarkus` - the most simplest solution

We should also consider 
* https://github.com/apache/camel-spring-boot, which prints `Apache Camel Spring Boot support` so ideally changing it there as well if possible
* https://github.com/apache/camel, which prints extremely long sentence for google search result

**Comment by oscerd** [comment]
This needs to be reviewed even for other subprojects.

**Comment by oscerd** [comment]
I think the simplest solution is the best one. But let's gather more feedback.

**Comment by aldettinger** [comment]
:+1: for anything aligned across runtimes.

When it comes to personal preferences:
 1. Apache Camel Quarkus - GitHub
 2. Apache Camel Quarkus
 3. apache/camel-quarkus - Apache Camel Quarkus - GitHub

**Comment by jamesnetherton** [comment]
I prefer the simplest naming.

Isn't adding any `GitHub` suffix unnecessary? That part is already implied by the URL etc.

**Comment by llowinge** [comment]
@jamesnetherton I don't know why, but i don't check the links under the result. If i see it on first sight, it is easier represent it in my brain. But i'm OK with anything which i've mentioned. Not sure how we should handle the voting here. 

@oscerd Should i create similar issues in https://github.com/apache/camel-spring-boot and https://github.com/apache/camel ?

**Comment by oscerd** [comment]
@llowinge you'll need to create them on JIRA for Camel Spring Boot and Camel, but yeah, it would be helpful. Thanks.
