### ISSUE TITLE
[MongoDB extension] Refactor with camel 3.1.x new connection bean

### ISSUE THREAD

**Issue by squakez** [apache/camel-quarkus#544]
As originally described in [jira issue](https://issues.apache.org/jira/browse/CAMEL-14258), the next camel 3.1.x version will add a change to the camel-mongodb component, using a new connection bean interface replacing the older deprecated one.

**Comment by ppalaga** [comment]
@squakez are you by any chance planning to work on this?

**Comment by squakez** [comment]
> @squakez are you by any chance planning to work on this?

Not in the short term. I may have a look after Jan 15, but no guarantees.

**Comment by jamesnetherton** [comment]
I'll take this one. Probably best we test it ASAP against a Camel 3.1 SNAPSHOT to verify that the changes work ok.
