### ISSUE TITLE
Enable tests and the native profiles after kubernetes client upgrade in quarkus 3.6.0

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#5447]
### Description

Camel upgraded kubernetes client to 6.9.0 (in https://github.com/apache/camel/pull/11737)
Until relevant [change](https://github.com/quarkusio/quarkus/pull/36312 ) on Quarkus side is consumed, native profiles and tests of  test modules `master-openshift`, `kubernetes` and `camel-k-runtime` are disabled.

Enable profiles and tests after the upgrade on quarkus side.

**Comment by jamesnetherton** [comment]
Closing this as versions are in alignment between Quarkus 3.6.x and Camel 4.2.x. I'll open a new issue that captures the other issues.
