### ISSUE TITLE
[Camel 4.2.0] Quarkus CDI add support for Primary beans

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#5464]
### Describe the feature here

If Quarkus has a similar concept like Spring with @Primary beans then it would be good to add support for this too.

Here is how we did this for camel-spring
https://github.com/apache/camel/blob/main/components/camel-spring/src/main/java/org/apache/camel/spring/spi/ApplicationContextBeanRepository.java#L88

The method `findSingleByType` needs to favour the @Primary bean if there are 2+ beans of the same type.

**Comment by zhfeng** [comment]
I think there is no such Primary beans in Quarkus. @mkouba is there any plan to add this support or similar way in Quarkus CDI?

**Comment by mkouba** [comment]
I don't know how exactly the "primary beans" work but in Quarkus you can [inject multiple beans of the same type](https://quarkus.io/guides/cdi-reference#injecting-multiple-bean-instances-intuitively) with `@Inject @All List<Foo> foos`/`Arc.container().listAll()` and the list is sorted by priority as defined by `io.quarkus.arc.InjectableBean#getPriority()`; higher priority goes first.

The `@jakarta.annotation.Priority` annotation can be used to assign the priority to a class bean, producer method or producer field. The priority is also honored if using the programmatic lookup via `jakarta.enterprise.inject.Instance`.

**Comment by zhfeng** [comment]
@davsclaus It seem there are some changes in https://github.com/apache/camel/blame/main/core/camel-support/src/main/java/org/apache/camel/support/DefaultRegistry.java to override `public <T> T findSingleByType(Class<T> type)` method. So this funtionality should be only in camel `4.2.0-SNAPSHOT`?

**Comment by davsclaus** [comment]
Yes its only a change for 4.2 onwards
