### ISSUE TITLE
LocalDateTime not work in Apache Camel quarkus

### ISSUE THREAD

**Issue by brianmolinaspring** [apache/camel-quarkus#5474]
### Bug description

Hello guys, please help, I have my pod made in Quarkus with Apache Camel and native mode, I have an issue with my pod, since it is not updating the record of my logs with the current date, for example I have this in my route :

.log("\n["+getCurrentDateTime()+"]")
but I see that the date that the log gives me is the exact date on which the pod was created, and it does not change for each request, additionally I leave you this function

private Timestamp getCurrentDateTime() {

        LocalDateTime now = LocalDateTime.now();
        return Timestamp.valueOf(now);
    }

I don't know if there are incompatibility issues with camel, I read that I can use this ${date:now:yyyyMMdd}, but my code is already in a testing environment and I want to know if there is any reason to see this strange behavior and if it can be solved.

**Comment by ppalaga** [comment]
Thanks for the report @brianmolinaspring!
I think the behavior would be the same in JVM mode. Your getCurrentDateTime() method is simply called only once on route creation. 
To reach what you want, you might use something like the following:

```
.log("${bean:myBean.getCurrentDateTime()}")

@Named("myBean")
@RegisterForReflection
class MyBean {
  private Timestamp getCurrentDateTime() {
     LocalDateTime now = LocalDateTime.now();
      return Timestamp.valueOf(now);
  }
}

**Comment by brianmolinaspring** [comment]
ok friend, thanks for answering, with this every time I call the log does the log update? What makes it different is the annotation?

**Comment by ppalaga** [comment]
> What makes it different is the annotation?

The main difference is that with `.log("${bean:myBean.getCurrentDateTime()}")` you pass an expression that will be evaluated on each call rather than a value obtained at route creation.

**Comment by brianmolinaspring** [comment]
thanks, @ppalaga , your support helped me

**Comment by ppalaga** [comment]
Happy to hear that!
