### ISSUE TITLE
Debug `JmxConnectorService` is not registered when `camel.debug.enabled` is `true`

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5506]
### Bug description

Something I noticed on the Camel 4.2.0 upgrade PR https://github.com/apache/camel-quarkus/pull/5501, is the removal of `DebugEnabledFromCamelMainPropertyTest`. Which is maybe due Camel 4.2.0 switching the debug property naming from `camel.main.debugging` to `camel.debug.enabled`.

However, when trying to reinstate the test, there is some strangeness. Everything works ok when `quarkus.camel.debug.enabled = true` but not when `camel.debug.enabled = true`. The `CamelDebuggerFactory` is never loaded and thus the `JmxConnectorService` is not registered.

**Comment by davsclaus** [comment]
The JMX connector is only in use if you have camel-debug JAR on classpath.

camel.debug.enabled=true

Can use the debugger without camel-debug and JMX connector - that is what camel-jbang debug do.

**Comment by JiriOndrusek** [comment]
I removed the test `DebugEnabledFromCamelMainPropertyTest` as my understanding of the relevant camel changes is, that debug is enabled when a `camel-debug` is among dependencies. 
I realize now that the new test verifying the debug is disabled with no `camel-debug` dependency behaves as expected.
