### ISSUE TITLE
Ftp: certificate used by the test is generated with a very short validity

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#5522]
### Bug description

My previous [fix](https://github.com/apache/camel-quarkus/commit/b3691d5a82af65b67244487f7adb62b9d0ab0948) did not extend validity of the certificate. Therefore validity is 30 days. It should be regenerated and the commands for the certificate generation should be updated to use for example 10000 days,

**Comment by zhfeng** [comment]
@JiriOndrusek this could be fixed by
- https://github.com/apache/camel-quarkus/pull/5523 ?

**Comment by JiriOndrusek** [comment]
@zhfeng yes, I'm sorry I forgot to put this ticket into the summary, to autoclose

**Comment by jamesnetherton** [comment]
> @zhfeng yes, I'm sorry I forgot to put this ticket into the summary, to autoclose

FYI it's better to put the `Fixes #` part into the commit comment as we have a GitHub workflow that can auto add the issue to the current milestone after merge.

**Comment by JiriOndrusek** [comment]
> > @zhfeng yes, I'm sorry I forgot to put this ticket into the summary, to autoclose
> 
> FYI it's better to put the `Fixes #` part into the commit comment as we have a GitHub workflow that can auto add the issue to the current milestone after merge.

That's what I meant, sorry for confusion.
