### ISSUE TITLE
Some openapi-java array types cannot be configured

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5559]
### Bug description

https://issues.apache.org/jira/browse/CAMEL-20156

**Comment by zhfeng** [comment]
@jamesnetherton is there any reproducer?

It looks like that we can use `Schema::cast` method

https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/Schema.java#L854-L856

**Comment by zhfeng** [comment]
OK, I will check them when I find a fix in camel.

**Comment by zhfeng** [comment]
Hi @jamesnetherton ,

I open https://github.com/apache/camel/pull/12269 and can you take a look?

**Comment by zhfeng** [comment]
There is still https://issues.apache.org/jira/browse/CAMEL-20181 for making sure support for 3.0 and 3.1
