### ISSUE TITLE
Review extensions' dependencies chains

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#56]
i.e. 
- deployments should depend on camel-quarkus-code-deployment
- deployments should not depends on arc-deployment and quarkus-deployment as is should be transitively provided by camel-quarkus-code-deployment

**Comment by ppalaga** [comment]
I vote for enforcing things like this via a groovy script, enforcer plugin or similar automatic solution. Our ultimate goal is to have extensions for most Camel components and the bigger the number of extensions gets the harder it will be to keep things like this under control.

**Comment by lburgazzoli** [comment]
I'll open a new issue for that
