### ISSUE TITLE
Camel 4.4 - Auto configuration of route controller changed

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#5611]
### Describe the feature here

https://issues.apache.org/jira/browse/CAMEL-20243

You likely need to do something like Spring Boot where we have a config class that maps to the options in the new group, and create the SupervisingRouteController bean if enabled.

See this commit
https://github.com/apache/camel-spring-boot/commit/e08242c0a9920c6fbb7ec1adf7f96161a082d729

**Comment by zhfeng** [comment]
I just take a quick look at the codebase and it seems that there is nothing needed to change. But it looks like we lack of a test for `SupervisingRouteController`.

**Comment by jamesnetherton** [comment]
> But it looks like we lack of a test for `SupervisingRouteController`.

I added some to the MicroProfile Health tests.
