### ISSUE TITLE
Error in creating quorum type queues using camel-quarkus-rabbitmq

### ISSUE THREAD

**Issue by francescobianca** [apache/camel-quarkus#5651]
### Bug description

Hello,

I am migrating classical queues to quorum-type queues. Communication with RabbitMQ is established through the following [camel component](https://camel.apache.org/camel-quarkus/2.16.x/reference/extensions/rabbitmq.html) (version 2.16.0).

  ```
<dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-rabbitmq</artifactId>
  </dependency>
```

I defined the route as follows: 
_rabbitmq:iot-exchange?queue=telemetry_general_queue&routingKey=telemetry_general_rk&autoDelete=false&arg.queue.x-queue-type=quorum_

Compared with the previous (working) version, I added the following argument: **arg.queue.x-queue-type=quorum**.

I have other spring boot framework based microservices that use the dependency below and with the same parameter they work correctly.
  ```
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-spring-rabbitmq</artifactId>
</dependency>
```

When I start the microservice with the route defined as described the rabbit server notifies me with the following error:

> [4:36 PM] 2024-01-16 15:34:55.418094+00:00 [error] <0.5583.0> Channel error on connection <0.5574.0> (127.0.0.1:39566 -> 127.0.0.1:5672, vhost: '/', user: 'default_user_lfHfpaMt6kTqiZDaAk8'), channel 1:
> 2024-01-16 15:34:55.418094+00:00 [error] <0.5583.0> operation queue.declare caused a channel exception precondition_failed: invalid arg 'x-queue-type' for queue 'telemetry_general_queue' in vhost '/': {unacceptable_type,void} (edited)

Is there an alternative mechanism to solve this problem?

Thanks in advance

**Comment by jamesnetherton** [comment]
Can you try with the latest Camel Quarkus 3.x release?

**Comment by francescobianca** [comment]
Searching around the web, I found the version of the <artifactId>camel-spring-rabbitmq</artifactId> component for quarkus: https://camel.apache.org/camel-quarkus/3.6.x/reference/extensions/spring-rabbitmq.html. With this library and setting the ConnectionFactory it seems to be compatible with quorum type queues. It was not immediate to reperform this version in the Camel documentation. Thanks equally for the support

**Comment by Lucasark** [comment]
@francescobianca Can you provide example using ConnectionFactory for create Quorum Queues?
