### ISSUE TITLE
Broken icon URL in quarkus-extension.yaml

### ISSUE THREAD

**Issue by christophd** [apache/camel-quarkus#5663]
### Bug description

The icon URL referenced in the quarkus-extension.yaml seems to be invalid. See https://github.com/apache/camel-quarkus/blob/main/extensions-core/core/runtime/src/main/resources/META-INF/quarkus-extension.yaml#L27

This icon is displayed on the quarkus.io website extension catalog. We should fix the URL as the Quarkus website will fallback to the Apache feather as an icon as soon as the website gets rebuilt

**Comment by jamesnetherton** [comment]
I guess the URL to logo has the potential to change across website rebuilds. Maybe we should just point to its location on GitHub instead. E.g.

https://raw.githubusercontent.com/apache/camel-website/main/antora-ui-camel/src/img/logo-d.svg

**Comment by ppalaga** [comment]
> Maybe we should just point to its location on GitHub instead. E.g.
>
> https://raw.githubusercontent.com/apache/camel-website/main/antora-ui-camel/src/img/logo-d.svg

Yeah, it even seems to be served with the right content-type. Let's try it.

**Comment by ppalaga** [comment]
Thanks for the report @christophd!
