### ISSUE TITLE
Consider porting the Twitter Camel support

### ISSUE THREAD

**Issue by emmanuelbernard** [apache/camel-quarkus#57]
I know it might be closer to demoware but it would be really clear in people's mind if we could use the Camel Twitter integration in Quarkus as part of a flow. It's also easier to set up that the current connectors you are offering here.

CC @jpechane @gunnarmorling

**Comment by ppalaga** [comment]
@jonathanvila you wanted to try?

**Comment by jamesnetherton** [comment]
If nobody else is working on this, then I'd like to try and implement it.
