### ISSUE TITLE
extensions-support httpclient: The BasicAuthCache alias may not be needed anymore when adopting http client >= 5.4

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#5704]
### Describe the feature here

Since https://issues.apache.org/jira/browse/HTTPCLIENT-2070, the BasicAuthCache is not using reflection anymore.
So we should probably be able to remove this native alias: https://github.com/apache/camel-quarkus/blob/main/extensions-support/httpclient/runtime/src/main/java/org/apache/camel/quarkus/support/httpclient/graalvm/BasicAuthCacheAlias.java

Some context could be found in #3079

**Comment by jamesnetherton** [comment]
The problem is that `extensions-support-httpclient` is still supporting components where httpclient 4.x is on the classpath.

Maybe we need a separate support extension for 4.x & 5.x as was hinted at in https://github.com/apache/camel-quarkus/issues/4703.
