### ISSUE TITLE
Google-bigquery: Tests are failing because of google regression

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#5734]
### Bug description

There is an issue (which was not present in 2.35.0) which causes all the test fail. See https://github.com/googleapis/java-bigquery/issues/3125

As soon as the issue on in google library is fixed, please enable the tests and the native profile.

Perhaps some kind of the workaround for the test could be used here, because the issue should affect only the testing

**Comment by JiriOndrusek** [comment]
Fix should be present in https://github.com/googleapis/java-bigquery/releases/tag/v2.37.2

**Comment by jamesnetherton** [comment]
I proposed a temporary workaround in https://github.com/apache/camel-quarkus/pull/5773.
