### ISSUE TITLE
Contribute A New Example Project.

### ISSUE THREAD

**Issue by Namphibian** [apache/camel-quarkus#574]
Hi Team.

I have worked through the examples in the repo. Got things running and I am very happy with Quarkus so far. So I took it a step further I  and made a simple file reader which uses the split EIP to read rows and columns. It XML DSL based no Java and shockingly fast. I would like to contribute this to the examples, if it good enough obliviously.

The contribution guide does not give any guidelines around how to contribute example projects specifically.  What is the current standards etc that I need to be aware of? I assume it would be similar to the ones outlined in the contribution guide. 

Keen on using this in production so would love to contribute in anyway I can.

Thanks
Neil

**Comment by davsclaus** [comment]
Hi Neil

Yay sounds great, we love contributions.

We dont have a specific strict standard for examples. So take a look as you have of some of the existing examples, and have same similar structure with a pom.xml file and readme with instructions.

**Comment by Namphibian** [comment]
Hi Claus.

Thanks will add my project to my local repo and get it working and submit a pull request. 

Regards
Neil

**Comment by ppalaga** [comment]
Yes, your PR is welcome. A `README.adoc` file explaining the example is a minimal requirement. An integration test passing in both JVM an native modes would be nice to have.

**Comment by Namphibian** [comment]
Cool.

Heading out to the beach today when I get back tonight I will work on getting a basic unit test/integration test into the package.

**Comment by Namphibian** [comment]
Hey Team.

Just a quick question. I am ready to push the project into a pull request. Just wanted to make sure how you guys deal with it.

I created a local branch called file-reader-example which I want to push upstream to the source but not sure if that would be the right approach in my mind.

1. Push my branch into the project. 
2. Create PR from my branch to master.

How do you want me to approach this.

Regards
Neil

**Comment by ppalaga** [comment]
You should first fork https://github.com/apache/camel-quarkus/ using the button in the top right corner. Then you should push your branch to your fork (presumably https://github.com/Namphibian/camel-quarkus ). After that you can create a pull request from the file-reader-example branch in your fork against the master branch in apache/camel-quarkus. Does that help?

**Comment by Namphibian** [comment]
Hi There.

Makes perfect sense. I completely forgot about forking I will blame it on the eggnog for now. PR is coming up. Will see if I can contribute in other ways going forward.

Regards
Neil

**Comment by Namphibian** [comment]
Hi Team.

SO the PR is failing due to the following:
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:3.0:check (license-format) on project camel-quarkus-examples: Unable to find a comment style definition for some files. You may want to add a custom mapping for the relevant file extensions. -> [Help 1]

I suspect it is due to my CSV file not having an apache license header. Could you have a look and let me know.

Regards
Neil

PS. This is not urgent so dont work on a weekend like me if you dont need to.

**Comment by Namphibian** [comment]
Thanks Team.

Will see what other examples/wiki/docs/blogs I can create to support this effort. It is a real game changer for me. Time permitted I would like to help migrate some of the endpoints across as well.
