### ISSUE TITLE
No alternative for camel-quarkus-rabbitmq in migration docs

### ISSUE THREAD

**Issue by varoliver** [apache/camel-quarkus#5766]
Hi,

we are using camel quarkus 2.13 and are relying on the camel-quarkus-rabbitmq component. 
https://camel.apache.org/manual/camel-4-migration-guide.html
mentions spring-rabbitmq-component as replacement.
It is also referenced as quarkus extension here:
https://camel.apache.org/camel-quarkus/3.7.x/reference/extensions/spring-rabbitmq.html

But the migration guide mentions "none" as the replacement for camel-quarkus-rabbitmq here
https://camel.apache.org/camel-quarkus/3.7.x/migration-guide/3.2.0.html

I guess that is an error in the docs isn't it?
Is the camel-quarkus-spring-rabbitmq extension for 2.13 and 3.2 production ready ?

Thanks, regards
Oliver

**Comment by jamesnetherton** [comment]
> I guess that is an error in the docs isn't it?

Yes, thanks for spotting it. `camel-quarkus-spring-rabbitmq` is the replacement for `camel-quarkus-rabbitmq`.

**Comment by varoliver** [comment]
great, thanks!
