### ISSUE TITLE
google-bigquery: tests are failing on quarkus-platform since camel-quarkus 3.8.0 release

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#5798]
### Bug description

While releasing Camel Quarkus 3.8.0, the google-big-query tests below were failing in the [pr](https://github.com/quarkusio/quarkus-platform/pull/1129):
 * org.apache.camel.quarkus.component.google.bigquery.it.GoogleBigqueryTest.insertIdTest line 240
 * org.apache.camel.quarkus.component.google.bigquery.it.GoogleBigqueryTest.insertListTest line 135
 * org.apache.camel.quarkus.component.google.bigquery.it.GoogleBigqueryTest.insertMapTest line 104
 * org.apache.camel.quarkus.component.google.bigquery.it.GoogleBigqueryTest.partitioningTest line 211
 * org.apache.camel.quarkus.component.google.bigquery.it.GoogleBigqueryTest.sqlCrudOperations line 296
 * org.apache.camel.quarkus.component.google.bigquery.it.GoogleBigqueryTest.templateTableTest line 162

**Comment by zhfeng** [comment]
@aldettinger Is there any more detail about the test failures?

**Comment by aldettinger** [comment]
It's possible to reproduce locally at this [commit](https://github.com/quarkusio/quarkus-platform/pull/1129/commits/1b017664919f18c600a35dd62a37a07fef6be7c7) level from the [pr](https://github.com/quarkusio/quarkus-platform/pull/1129) [branch](https://github.com/aldettinger/quarkus-platform/tree/main) 

The captured output [gbq-qplatform-issue-reproduced.txt](https://github.com/apache/camel-quarkus/files/14404354/gbq-qplatform-issue-reproduced.txt) mention a missing method `boolean com.google.cloud.bigquery.BigQueryOptions.hasValidUniverseDomain()`

**Comment by jamesnetherton** [comment]
This happens because Quarkus Google Cloud Services is forcing an older version of bigquery-java to what we expect for CQ.  It should get resolved once that projects integrates a new release into the platform.
