### ISSUE TITLE
Various guide pages have been taken down for non-deprecated extensions

### ISSUE THREAD

**Issue by holly-cummins** [apache/camel-quarkus#5814]
### Bug description

I'm not sure what the best way to handle this is. It looks like some old versions have been removed from the https://camel.apache.org/camel-quarkus/ docs site, which means their pages have dead links. 

When what's written in the metadata file doesn't point to a live file, I currently do the following to try and help users find the documentation, and avoid dead links: 
- Rewrite Camel URLs. I try mapping `latest` to `2.16.x` and `2.13.x` (this is a hand-coded list of mappings, so I need to maintain it)
- If an extension is marked deprecated, I silently drop the guides link

I don't silently drop dead guides link as a general rule, because putting in an incorrect guides link is a common error for extension authors, and I want to catch those cases. The general assumption is that if you put it in the file, it's because you expect it to work. :) 

For Camel, the current model doesn't seem to be working, so there's a few things I can do. 
- Add an exception and silently drop dead links for Camel extensions only. This has the drawback that if a guides link on a new extension gets messed up (easily done), no one gets alerted
- Silently drop dead links, if an extension is more than (say) a year old. I'd be treating "this hasn't been updated for ages" as an implicit deprecation process. This wouldn't help with, for example, the facebook extension below. It was last updated in October last year, but its documentation seems to have vanished. Atmos was updated in 
- Continue raising issues, so that the team can review and choose to add the deprecated status. This has the advantage that the deprecated status is useful for users.
- Update the camel docs to include an 'archive' section, and I can look in there when mapping guides links
- Something else? 

Here's the links
- https://camel.apache.org/camel-quarkus/latest/reference/extensions/johnzon.html
- https://camel.apache.org/camel-quarkus/latest/reference/extensions/jclouds.html
- https://camel.apache.org/camel-quarkus/latest/reference/extensions/avro-rpc.html
- https://camel.apache.org/camel-quarkus/latest/reference/extensions/xstream.html
- https://camel.apache.org/camel-quarkus/latest/reference/extensions/jbpm.html
- https://camel.apache.org/camel-quarkus/latest/reference/extensions/rabbitmq.html
- https://camel.apache.org/camel-quarkus/latest/reference/extensions/milo.html
- https://camel.apache.org/camel-quarkus/latest/reference/extensions/vm.html
- https://camel.apache.org/camel-quarkus/latest/reference/extensions/atmos.html
- https://camel.apache.org/camel-quarkus/latest/reference/extensions/solr.html
- https://camel.apache.org/camel-quarkus/latest/reference/extensions/corda.html
- https://camel.apache.org/camel-quarkus/latest/reference/extensions/atlasmap.html
- https://camel.apache.org/camel-quarkus/latest/reference/extensions/facebook.html

**Comment by jamesnetherton** [comment]
> Add an exception and silently drop dead links for Camel extensions only. This has the drawback that if a guides link on a new extension gets messed up (easily done), no one gets alerted

I'd be ok with that. Not sure what others think.

The messed up guides link issue should (hopefully) never be a problem for us. They are all auto generated and the doc file name follows a convention.

> Something else?

Maybe fall back to the raw AsciiDoc content on the release maintenance branch? E.g for Facebook:

https://github.com/apache/camel-quarkus/blob/3.6.x/docs/modules/ROOT/pages/reference/extensions/facebook.adoc

Some of the links wont get rendered outside of the Camel website, but at least the core content should be there.

**Comment by holly-cummins** [comment]
Ok, I've made updates to drop dead guides, if the extension has the Camel group id.
