### ISSUE TITLE
Camel 4.5 - Trace config

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#5824]
### Describe the feature here

The backlog tracer has its configuration moved into its own group like the debug already have
https://issues.apache.org/jira/browse/CAMEL-20472

Its probably easier to see what we did for CSB to learn what may need to be done in CEQ
https://github.com/apache/camel-spring-boot/commit/3e8de47443debcf6c1372f53312961fbd6e0be37

There is a `DebugConfig.java` in CEQ today, so maybe a `TraceConfig.java` needs to be created. As trace is very similar to how debug config is.

**Comment by zhfeng** [comment]
@davsclaus please take a look at the PR and I wonder if there is any way to test with these trace configuration?

**Comment by davsclaus** [comment]
use null instead of empty string. For testing them I am afraid you can only test like its tested in the core project. But generally its not really needed as core tests the tracing functionality, and CEQ is just a facade on setting the options.
