### ISSUE TITLE
Create Qdrant JVM only extension

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#5860]
### Describe the feature here

This extension would make it possible to use a Qdrant vector database.
https://github.com/apache/camel/tree/main/components/camel-qdrant

**Comment by lburgazzoli** [comment]
See https://github.com/apache/camel-quarkus/issues/5815

**Comment by aldettinger** [comment]
@lburgazzoli Are you already on it ? If not, I would probably let this ticket for JVM and reuse #5815 for native mode.

**Comment by lburgazzoli** [comment]
no, I'm not. Was just to reference it so you can close both eventually
