### ISSUE TITLE
Optimize the Maven release

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5887]
### Description

We deploy a lot of redundant stuff.

* integration-test-groups/*
* integration-tests-jvm/*
* perf-regression

The only test JARs that need to be deployed are in the integration-tests module.

**Comment by jamesnetherton** [comment]
This appears to be trickier than it first seems. I was hoping to just add a property for `<maven.deploy.skip>true</maven.deploy.skip>` to the parent of the modules mentioned above.

But due to the parent that the sub-modules use, it has no effect. You have to explicitly add the property in each sub-module pom.xml. Which is a pain to maintain.

So I thought of adding something extra to the `cq-maven-plugin` format mojo that could configure the property automatically like:

```xml
<mavenDeploySkip>
    <basedir>${project.basedir}</basedir>
    <includes>
        <include>integration-test-groups/**/pom.xml</include>
        <include>integration-tests-jvm/**/pom.xml</include>
        <include>tooling/perf-regression/pom.xml</include>
    </includes>
</mavenDeploySkip>
```

It [works](https://github.com/jamesnetherton/cq-maven-plugin/commit/b0a60ca3663ce94e828773e43875bef5aa108294). Just not sure if that's the right way to go. WDYT @ppalaga?

**Comment by ppalaga** [comment]
We could perhaps play with the `apache-release` profile. In the top pom.xml we could add a `non-release` profile activated by `!apache-release` property under which we  would move 

```
        <module>integration-test-groups</module>
        <module>integration-tests-jvm</module>
```

Then, we'd have to change the activation of the release profile in release plugin's config:

```
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-release-plugin</artifactId>
                    <version>${maven-release-plugin.version}</version>
                    <configuration>
                        <!-- release:prepare config -->
                        <preparationGoals>clean validate -Pcommit-release-changes "-Dcq.commit.message.prefix=[maven-release-plugin] Prepare release" -N</preparationGoals>
                        <completionGoals>clean validate -Pcommit-release-changes "-Dcq.commit.message.prefix=[maven-release-plugin] Set next development version" -N</completionGoals>
                        <!-- release:perform config -->
                        <goals>deploy</goals>
                        <!-- Both release:prepare and release:perform config -->
                        <arguments>-Dapache-release -DskipTests -Denforcer.skip -Dquarkus.build.skip -Dformatter.skip -Dimpsort.skip -Dskip.installyarn -Dskip.yarn</arguments>
                    </configuration>
                </plugin>
```

In that way, the deploy executed in the forked JVM would run without those modules and thus the whole build incl signing, javadoc and deploy would be skipped for all those tests. 

I hope this solution would still keep changing the version of the current project in all those tests during release.
