### ISSUE TITLE
OpenAPI model not considering mixins in natibe build

### ISSUE THREAD

**Issue by ivivanov-bg** [apache/camel-quarkus#5891]
### Bug description

When using `camel-quarkus-openapi-java` generation of the OpenAPI specification in native mode doesn't take into account the mixins specified in the `swagger-core` library:

https://github.com/swagger-api/swagger-core/blob/3fcc473c33c56f306902853a451020926ad691ea/modules/swagger-core/src/main/java/io/swagger/v3/core/util/ObjectMapperFactory.java#L244

In JVM mode - everything works as expected.

The root cause of the issue is that the mixins are abstract classes without any children, so they get stripped during native build.
As a result - the OpenAPI document might become very big (in case of complex data model) and make swagger UI completely unresponsive.

The  extension should register the mixins for reflection to prevent flooding openapi json with unnecessary data.

Attached is sample reproduces: `[sample-app.zip](https://github.com/apache/camel-quarkus/files/14634597/sample-app.zip)`

In **JVM**    mode openapi size (accessible on `/v1/openapi`) is **1502 bytes**
In **Native** mode  openapi size (accessible on `/v1/openapi`) is **3653 bytes**
(The difference comes mostly from `Components -> Schemas -> <DataType> -> jsonSchema` section)

**Comment by zhfeng** [comment]
Thanks @ivivanov-bg - I will take a look.

**Comment by zhfeng** [comment]
@ivivanov-bg what the mixin classes should be registered for reflection? I tried all class from `io.swagger.v3.core.jackson.mixin` but the native runner is producing an empty response now.

**Comment by ivivanov-bg** [comment]
That's exacrly what I observed too and the reason to not privide a PR directly.

My cussrent issue (with the jsonSchema) gets resolved if the Schema31 mixin and the inner type serializer are registered, but to me this looked more like a workaround for particular situation

**Comment by zhfeng** [comment]
`io.swagger.v3.core.jackson.mixin.Schema31Mixin` and `Schema31Mixin.TypeSerializer` ?

**Comment by ivivanov-bg** [comment]
Yes 
Attached is updated sample-app
[sample-app.zip](https://github.com/apache/camel-quarkus/files/14646312/sample-app.zip)

**Comment by zhfeng** [comment]
Thanks @ivivanov-bg - yeah, it works by adding all the mixin classes and relavant JsonSerializer. I will prepare a PR with an integration test.

**Comment by zhfeng** [comment]
@ivivanov-bg can you check the fix with your reproducer? If it works, I will merge the PR.

**Comment by ivivanov-bg** [comment]
I just tested it - it's working as expected now
Thanks
