### ISSUE TITLE
Catalog throws IllegalArgumentException: Unexpected kind model

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5893]
### Bug description

Since https://github.com/apache/camel/pull/13481, there's a few places that interrogate the catalog which fail with:

```
Caused by: java.lang.IllegalArgumentException: Unexpected kind model
    at org.apache.camel.catalog.CamelCatalog.model (CamelCatalog.java:620)
```

`CamelCatalog` is lacking some case clauses for `model`  here:

https://github.com/apache/camel/blob/main/catalog/camel-catalog/src/main/java/org/apache/camel/catalog/CamelCatalog.java#L229-L248

And here:

https://github.com/apache/camel/blob/main/catalog/camel-catalog/src/main/java/org/apache/camel/catalog/CamelCatalog.java#L601-L620

@lburgazzoli can you help with this?

**Comment by lburgazzoli** [comment]
@jamesnetherton sure, do you have a link to a failure ?

**Comment by jamesnetherton** [comment]
Example here:

https://github.com/apache/camel-quarkus/actions/runs/8340782266/job/22825442309

**Comment by lburgazzoli** [comment]
I would probably add an additional filter here: https://github.com/apache/camel-quarkus/blob/camel-main/tooling/maven-plugin/src/main/java/org/apache/camel/quarkus/maven/CqCatalog.java#L225-L228 to also exclude `model`, so I can try to figure out on the camel catalog side how to better handle it as model in fact were not included before anyhow

**Comment by lburgazzoli** [comment]
I can send a PR later on, but I'll be AFK for some time now

**Comment by JiriOndrusek** [comment]
> I would probably add an additional filter here: https://github.com/apache/camel-quarkus/blob/camel-main/tooling/maven-plugin/src/main/java/org/apache/camel/quarkus/maven/CqCatalog.java#L225-L228 to also exclude `model` as model in fact were not included before anyhow, so I can try to figure out on the camel catalog side how to better handle it

Thanks for the suggestion. I added change you described into `camel-main`. Do I understand correctly, that it is only temporary solution and should be removed once it is fixed on Camel side?

**Comment by lburgazzoli** [comment]
@JiriOndrusek I need to investigate it a little bit more, it looks like the kind model was somehow mentioned but never used in practice.

**Comment by JiriOndrusek** [comment]
@lburgazzoli I had to add the same kind of exclusion for `Kind.bean`, Otherwise I was getting:
```
Execution update-extension-doc-page of goal org.apache.camel.quarkus:camel-quarkus-maven-plugin:3.9.0-SNAPSHOT:update-extension-doc-page failed: Unexpected kind bean 
```
 (from https://github.com/apache/camel/blob/main/catalog/camel-catalog/src/main/java/org/apache/camel/catalog/CamelCatalog.java#L632)

**Comment by lburgazzoli** [comment]
Yeah some new types have been added
