### ISSUE TITLE
[camel-main] Mongodb upgrade from Camel is not aligned to Quarkus

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#5895]
### Bug description

In the Camel core dependabot bumped Mongo from 4.x to 5.x (https://github.com/apache/camel/pull/13476)
Update is not compatible with 4.11.1.  (forced by Quarkus)
Until the version is aligned, several tests have to be disabled.
See also https://github.com/quarkusio/quarkus/pull/39097 and https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Mongo.205.2Ex/near/427688385

Disabled items:
- tests in MongoDB + MongoDB gridfs
- native profile in MongoDB grupped
- disabled Debezium mongdb test + native profile
- slack - disabled mongodb dependency in slack (see ttps://github.com/apache/camel-quarkus/issues/2489 )

**Comment by JiriOndrusek** [comment]
tests in MongoDB + MongoDB gridfs 
native profile in MongoDB grupped

**Comment by JiriOndrusek** [comment]
Debezium - disable Debezium mongdb test + native profile

**Comment by JiriOndrusek** [comment]
Camel reverted the upgrade, disabled tests and profiles are reverted in `camel-main`, as upgrade to camel4.5 from `camel-main` is merged to `main`, ticket can be closed

**Comment by jamesnetherton** [comment]
Lets close this for now.
