### ISSUE TITLE
Camel 4.5 : create the langchain-chat extension

### ISSUE THREAD

**Issue by zbendhiba** [apache/camel-quarkus#5923]
### Describe the feature here

check the components https://github.com/apache/camel/tree/main/components/camel-ai

**Comment by spatnity** [comment]
Hi @zbendhiba, I'd like to work on this.Could you please assign it to me?

**Comment by zbendhiba** [comment]
yes thanks @spatnity

**Comment by zbendhiba** [comment]
Narrowing this one to Langchain-chat as the camel-ai folder is containing many components
Created another issue for embeddings https://github.com/apache/camel-quarkus/issues/5970

**Comment by jamesnetherton** [comment]
Any progress on this?

If possible, I'd like to get it into the 3.10 release, even if it's just with JVM mode support with the dummy component test.

I can try to add it if nobody else has time.

**Comment by zbendhiba** [comment]
Hello @jamesnetherton 
Is Monday fine or do you need to push it now?
@spatnity has already created the extension and implemented tests for JVM mode, and pinged me for an issue, I couldn't fine the time this week

**Comment by jamesnetherton** [comment]
> Hello @jamesnetherton
> Is Monday fine or do you need to push it now?
> @spatnity has already created the extension and implemented tests for JVM mode, and pinged me for an issue, I couldn't fine the time this week

Yes, no rush 👍
