### ISSUE TITLE
Camel 4.6 - Add openapi-contract-first example

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#5964]
### Describe the feature here

Add a CEQ based example like we have for CSB
https://github.com/apache/camel-spring-boot-examples/tree/main/openapi-contract-first

This can help ensure that this new functionality works in CEQ and that end users have an example to look at as well.

**Comment by jamesnetherton** [comment]
The `bindingPackageScan` thing probably wont work OOTB in native mode, so that'll need figuring out.

If there's a `camel.rest` property for it, then you could get the value at build time to produce `CamelPackageScanClassBuildItem`.

**Comment by davsclaus** [comment]
yes there is a `camel.rest` option.

**Comment by Mikkelmedetk** [comment]
Would also really like to see an example :)

**Comment by zhfeng** [comment]
@jamesnetherton are you working on this example? if not, I can take a look.

**Comment by jamesnetherton** [comment]
@zhfeng if you want to assign this to yourself, feel free.

It'd be good to have test coverage for these features in the main project before we work on any example.

**Comment by zhfeng** [comment]
Thanks! yeah, I agree that we should have some tests at first.
