### ISSUE TITLE
Improve keystore generation

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#5967]
### Describe the feature here

Http-grouped: It should be possible to generate keystore and truststore during build. (if not disabled)

**Comment by JiriOndrusek** [comment]
The feature for generating the certificates could be created in a general way, so other modules can re-use it

**Comment by JiriOndrusek** [comment]
One way of general solution might be adopting the Quarkus way by using https://github.com/cescoffier/certificate-generator

**Comment by jamesnetherton** [comment]
> One way of general solution might be adopting the Quarkus way by using https://github.com/cescoffier/certificate-generator

Yeah, I saw that project mentioned on Quarkus Zulip some time ago and wondered whether we could start using it.

If possible, I think it'd be good to try and use a single tool for cert generation in the project. Currently we've got a mix of shell scripts, maven plugins etc which becomes a bit of a maintenance pain.

**Comment by JiriOndrusek** [comment]
> Indeed https://github.com/cescoffier/certificate-generator would be great to replace them all. I did not know it exist, thanks for the pointer. IIRC, we were forced to use openssl for writing PKCS12 stores, because Java's `java.security.KeyStore` did not support some sort of store encoding required by FIPS. Looking at https://github.com/cescoffier/certificate-generator/blob/main/certificate-generator/src/main/java/me/escoffier/certs/CertificateUtils.java#L200-L270 it seems that it is using `java.security.KeyStore` for writing the stores. But you mentioned recently @JiriOndrusek that JKS works on FIPS too? I wonder whether we need to try to fix certificate-generator's PKCS12 impl to comply with FIPS?

With one of the recent java updates (I'm not sure which concrete build it was), certificates generated by the java keystore  work in FIPS environment. (I noticed it several weeks ago) Therefore the certificate-generator project should cover all our needs.

I'm currently trying to solve FIPS for kafka tests and I'm using the certificate-generator, which seems to be easily usable. Once I'm sure that all works, I'll ping you on the PR to discuss whether we want to use such approach on the whole project.

**Comment by JiriOndrusek** [comment]
I tried generator-projext in kafka and all looks good.
My second attempt would be cxf-soap to see whether the complex generation can be achieved by the project.
