### ISSUE TITLE
Camel 4.6 - Rename anything Langchain to Langchain4j 

### ISSUE THREAD

**Issue by zbendhiba** [apache/camel-quarkus#5971]
### Describe the feature here

check https://issues.apache.org/jira/browse/CAMEL-20611

**Comment by zbendhiba** [comment]
Make sure to update also migration guides

**Comment by jamesnetherton** [comment]
I had to add a hack for the docs which will need to be removed:

https://github.com/apache/camel-quarkus/blob/main/tooling/maven-plugin/src/main/java/org/apache/camel/quarkus/maven/UpdateExtensionDocPageMojo.java#L209-L212

**Comment by jamesnetherton** [comment]
I hacked up a script to try to & make this less painful:

https://gist.github.com/jamesnetherton/5511f774b8eb4ad7b0cf2454eb5c9770

**Comment by jamesnetherton** [comment]
Done in https://github.com/apache/camel-quarkus/commit/af662f7dd28b828fab4ce94b48ac942e78408675.
