### ISSUE TITLE
platform-http form name not sent during multipart upload

### ISSUE THREAD

**Issue by Serkan80** [apache/camel-quarkus#5981]
### Bug description

I'm using platformHttp as a consumer and I'm sending a multipart request with file upload. The form name attribute of form-data is not set in Camel, see also attachments below and the reproducer url.

The multipart request:
![camel-multipart-02](https://github.com/apache/camel-quarkus/assets/19950946/5440ef2f-eeb7-43de-82b5-9893c408b6e3)

The content of AttachmentObject:
![camel-multipart-01](https://github.com/apache/camel-quarkus/assets/19950946/b7c54d7e-21f0-4757-a8b2-e0287cc87c92)

The content of exchange.getMessage():
![camel-multipart-03](https://github.com/apache/camel-quarkus/assets/19950946/bfe7fc93-7c82-4bef-9019-4d9d89d597d5)

Reproducer url:
https://github.com/Serkan80/quarkus-issue-reproducers/tree/master/http-path-permission-issue

Current behaviour:
the filename is set as the form name. 

Expected behaviour:
form name should be the name what comes in from the http request form-name attribute. In this case form-name should be "file".

**Comment by jamesnetherton** [comment]
I created a Camel ticket: https://issues.apache.org/jira/browse/CAMEL-20670.

**Comment by jamesnetherton** [comment]
Fixed by https://github.com/apache/camel-quarkus/commit/af662f7dd28b828fab4ce94b48ac942e78408675.
