### ISSUE TITLE
Initial source code - Package names

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#6]
The root java package name should be renamed to

- org.apache.camel.quarkus

**Comment by ppalaga** [comment]
I wonder whether the java package renaming should be a part of the code migration from the Quarkus repo?

I could try to modify my import script that I used to produce the current state of #3 .  Not sure how well that can be done using `git filter-branch --filter-tree` and `sed s/import io.quarkus/import org.apache.camel.quarkus/` , but it would result in a cleaner history for sure.

I am also not sure modifying the commits in this way would be acceptable from the legal point of view.

WDYT?

**Comment by oscerd** [comment]
I think we cannot leave the package with the old name. We can import with that package name, merge and then change the package name completely with a new commit done in the ASF Camel repo.
