### ISSUE TITLE
xpath : from message.in.header if there is a header with the given key is broken ? i cant use but before yes, and never see depecrated

### ISSUE THREAD

**Issue by marteloudini** [apache/camel-quarkus#6000]
### Bug description

this is my exemple : 
.setHeader("nameHeaderDestination").xpath("//abc/y/text()",String.class,"nameHeaderFrom")

why i cant now ? 
i need really this function setHeader().xpath()
thanks

**Comment by jamesnetherton** [comment]
Which Camel Quarkus version are you using? If it's >= 3.8.x then this section in the upgrade guide is probably relevant:

https://camel.apache.org/manual/camel-4x-upgrade-guide-4_4.html#_camel_core

**Comment by marteloudini** [comment]
ok, it is works...thanks...
too bad because this meant we didn't have to go through a temporary variable, for the value we wanted to extract from another header in a single line
