### ISSUE TITLE
Camel 4.7 - Running Camel Quarkus in dev mode should pre-configure Camel in dev mode as well

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#6083]
### Describe the feature here

camel-core / camel-main has a profile concept that makes it convenient to turn on a bunch of stuff in dev mode that assist during development, and for camel-jbang CLI as well.

So can we make `mvn quarkus:dev` able to call camel-main to set it in dev mode, via

org.apache.camel.main.ProfileConfigurer#configureCommon

**Comment by jamesnetherton** [comment]
There's a small issue that blocks this:

https://issues.apache.org/jira/browse/CAMEL-21003
