### ISSUE TITLE
Fix the defineClass exception in camel-quarkus-jsonpath while running in native mode

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#610]
How to reproduce:
Set <reportErrorsAtRuntime>**false**</reportErrorsAtRuntime> in integration-tests/jsonpath/pom.xml
Run mvn clean verify -P native
An issue where the @Deleted defineClass method would be accessed is reported.

**Comment by aldettinger** [comment]
Thanks @lburgazzoli for discussing the case.
I will try adding the jsonb extension, or then find what to substitute in order to cut the possibly false unreachable code path detection.

**Comment by lburgazzoli** [comment]
looking a little bit into this issue you probably need to substitute:
- `net.minidev.json.JSONValue`
- `net.minidev.json.JSONWriter`

Something like:

```java
@TargetClass(JSONValue.class)
class JSONValueSubstitution {
    
    @Substitute
	public static void writeJSONString(Object value, Appendable out, JSONStyle compression) throws IOException {
		if (value == null) {
			out.append("null");
			return;
		}
		Class<?> clz = value.getClass();
		@SuppressWarnings("rawtypes")
		JsonWriterI w = defaultWriter.getWrite(clz);
		if (w == null) {
			if (clz.isArray())
				w = JsonWriter.arrayWriter;
			else {
				w = defaultWriter.getWriterByInterface(value.getClass());
				if (w == null)
					throw new UnsupportedOperationException("...")
			}
			defaultWriter.registerWriter(w, clz);
		}
		w.writeJSONString(value, out, compression);
	}
}
```

```java
@TargetClass(JSONWriter.class)
class JSONWriterSubstitution {
    @Delete
    static public JsonWriterI<Object> beansWriterASM;
}
```

Not sure it it is enough but the issue is that the library tries to generate classes in case it does not find a suitable writer. 

An potential future evolution would be to generate such classes at build time.

**Comment by aldettinger** [comment]
@lburgazzoli, you were few brackets from having it fully done :) Thanks for analysis and proposal by the way :+1:

**Comment by aldettinger** [comment]
I've pushed a fix, let's ensure next build is fine with that.

**Comment by aldettinger** [comment]
The build is fine regarding this ticket, closing.
