### ISSUE TITLE
Camel 4.7 - Supervising route controller change default values

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#6106]
### Describe the feature here

https://issues.apache.org/jira/browse/CAMEL-20244

It may be that CEQ needs to change some code to adjust to this.

Here is the code change done for spring boot
https://github.com/apache/camel-spring-boot/commit/5605c0c7afbca3185488bbc3da5a2b4683b2e414

**Comment by jamesnetherton** [comment]
There's nothing to do for this. But I added some basic test coverage for supervised routes.
