### ISSUE TITLE
Improve the camel-jsonpath extension by not using an alias for DefaultAnnotationExpressionFactory

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#611]

**Comment by aldettinger** [comment]
I will try to fix this upstream in [CAMEL-14384](https://issues.apache.org/jira/browse/CAMEL-14384)

**Comment by aldettinger** [comment]
It should be fixed in upcoming camel releases (3.0.1 and 3.1.0).

**Comment by davsclaus** [comment]
If we need to remove some code in camel-quarkus after the upgrade, then it would be good to add a TODO in the source code so we wont forget

**Comment by aldettinger** [comment]
Yeah, we'll just need to remove the Target_DefaultAnnotationExpressionFactory class from camel-quarkus-jsonpath runtime. I'll remember as it is written in this comment.
