### ISSUE TITLE
Extension for endpoint DSL

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#612]
I wonder if we should have a quarkus extension for camel-endpointdsl. So its visible in the extension system in Quarkus.

Otherwise end users need to know how to add it as a camel dependency.

**Comment by lburgazzoli** [comment]
https://github.com/apache/camel-quarkus/tree/master/extensions/endpointdsl :)

**Comment by lburgazzoli** [comment]
@davsclaus can we close this one as we have the extension already ? or is there anything missing ?
