### ISSUE TITLE
Create a camel-websocket-jsr356 extension

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#613]

**Comment by jamesnetherton** [comment]
I can take this one. I actually had a tentative look into it this morning.

**Comment by jamesnetherton** [comment]
As the producer part of this component is currently [broken](https://issues.apache.org/jira/browse/CAMEL-14390), is it worth me implementing an extension for `camel-ahc-ws` until the fix is available?

**Comment by lburgazzoli** [comment]
@jamesnetherton no hack possible ?

**Comment by jamesnetherton** [comment]
It is possible. Would need to override and extend some bits of the component internals.

**Comment by lburgazzoli** [comment]
if the workaround is not too complex I'd go for the workaround and oyu are free to implement also camel-ahc-ws :)

**Comment by jamesnetherton** [comment]
I think this component in its current form is going to need too many hacks to get it working properly.

I opened #619 to implement ahc-ws. I'll revisit this when I'm done fixing up the websocket-jsr356 component on the Camel side.
