### ISSUE TITLE
Camel application with rest-component does not open more than 200 threads, even though it has memory for this

### ISSUE THREAD

**Issue by jacome-source** [apache/camel-quarkus#6145]
### Bug description

**Context**:

I created a simple camel-k integration, whose only functionality is to receive a request through a rest-component, wait 10 seconds and log the thread.

```
from('rest:get:/test')
          .process(ex -> {
               System.out.println(Thread.currentThread().getName());
               try {
               Thread.sleep(10000);
               } catch(Exception e) {}
          })
          .setBody(simple(Thread.currentThread().toString()));
```

I have set the memory request and memory limit to 1000M.
I configured Visual VM to monitor the threads and Locust to make requests to the endpoint in the integration-related pod.

Scenario:

Scenario 1: I configured locust to make 100 requests per second. The pod opened 100 threads and performed as expected.

Scenario 2: I configured locust to make 200 requests per second. The pod opened 200 threads and performed as expected.

Scenario 3: I configured locust to make more than 200 requests per second (until 1000 rps). The pod opened only 200 threads, even though it had enough memory. In this way, the response time becomes increasingly greater the higher the number of requests.

**Bug**:
I don't know if it's really a bug, but I think camel should open more than 200 threads.

**Question**:
Is there any restriction to open only 200 threads or some configuration that allows camel to open more than 200 threads?

**Comment by jamesnetherton** [comment]
> Is there any restriction to open only 200 threads or some configuration that allows camel to open more than 200 threads?

See [`quarkus.thread-pool.max-threads`](https://quarkus.io/guides/all-config#quarkus-core_quarkus-thread-pool-max-threads).

**Comment by jacome-source** [comment]
Thanks, solved my problem
