### ISSUE TITLE
Camel Quarkus Catalog - Add beans

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#6199]
### Describe the feature here

We recently have added `beans` as a kind to the catalog, that CEQ does not include

Here is what we include in CSB
https://github.com/apache/camel-spring-boot/tree/main/catalog/camel-catalog-provider-springboot/src/main/resources/org/apache/camel/springboot/catalog/beans

**Comment by zhfeng** [comment]
In camel-quarkus, we use `prepare-catalog-quarkus` to generate the catalog. I just tried to add `bean` kind but it seems that the `generatePojoBeanModel` in `tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/JsonMapper.java` is missing the `parseArtifact` which causes the PojoBeanModel does not include the `artifactId` and the genreated `beans.properties` is empty because we filter the models with `artifactsId`

I create https://issues.apache.org/jira/browse/CAMEL-20887

**Comment by zhfeng** [comment]
Hi @jamesnetherton , I tried the following changes
```java
diff --git a/tooling/maven-plugin/src/main/java/org/apache/camel/quarkus/maven/CqCatalog.java b/tooling/maven-plugin/src/main/java/org/apache/camel/quarkus/maven/CqCatalog.java
index 912b1463d7..348082d2ca 100644
--- a/tooling/maven-plugin/src/main/java/org/apache/camel/quarkus/maven/CqCatalog.java
+++ b/tooling/maven-plugin/src/main/java/org/apache/camel/quarkus/maven/CqCatalog.java
@@ -47,6 +47,7 @@ import org.apache.camel.tooling.model.JsonMapper;
 import org.apache.camel.tooling.model.Kind;
 import org.apache.camel.tooling.model.LanguageModel;
 import org.apache.camel.tooling.model.OtherModel;
+import org.apache.camel.tooling.model.PojoBeanModel;
 import org.apache.camel.tooling.model.TransformerModel;
 
 public class CqCatalog {
@@ -193,6 +194,9 @@ public class CqCatalog {
         }
         String rawJson;
         switch (model.getKind()) {
+        case bean:
+            rawJson = JsonMapper.createParameterJsonSchema((PojoBeanModel) model);
+            break;
         case component:
             rawJson = JsonMapper.createParameterJsonSchema((ComponentModel) model);
             break;
@@ -224,7 +228,7 @@ public class CqCatalog {
 
     public static Stream<Kind> kinds() {
         return Stream.of(Kind.values())
-                .filter(kind -> (kind != Kind.eip && kind != Kind.model && kind != Kind.bean));
+                .filter(kind -> (kind != Kind.eip && kind != Kind.model));
     }

```

**Comment by jamesnetherton** [comment]
@zhfeng Thanks for the fix!

Yes, that's the change I have locally. I have a couple of other tidy-ups to make things more consistent compared to the Camel & SB catalogs.
