### ISSUE TITLE
Bean autowiring is non-deterministic when multiple beans exist with no @Priority

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#6301]
### Bug description

Relates to #5464. The code changes for that feature assume that if there are multiple beans for a given type, that they will have an `@Priority` assigned, so that the desired bean is returned from registry lookups.

IMO this is only reliable for beans declared from user code. The majority of beans created by Quarkus extensions do not have any `@Priority` (AFAIK). E.g like `DataSource` beans.

Thus, when Camel attempts to do autowiring, it will potentially inject a 'random' bean into components, since there is no `@Priority` enforced.

**Comment by zhfeng** [comment]
I don't see a simple way to change this behavior except to intrdouct a `priority` in `quarkus-agroal` like

```
quarkus.datasource."test".priority = 100
```

Default beans can optionally declare @jakarta.annotation.Priority. If there is no priority defined, @Priority(0) is assumed. see https://quarkus.io/guides/cdi-reference#default_beans

**Comment by jamesnetherton** [comment]
In theory the same problem could exist for other extensions where you can have multiple named configurations. Like Infinispan, MongoDB etc.

Maybe another option would be to check if all of the returned beans have the same priority. If they do, try to resolve the default bean for the type. E.g something like:

```
container.select(type, Default.Literal.INSTANCE);
```

And if that fails, just return `null` and leave it for the user to determine which bean is used in their route.

**Comment by zhfeng** [comment]
Thanks @jamesnetherton and let me try this at first.
