### ISSUE TITLE
Adapt update-extension-doc-page mojo to Quarkus 3.14.0

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#6334]
There's been a lot of rework to the annotation processing and docs generation in Quarkus.

`UpdateExtensionDocPageMojo` no longer compiles as a lot of the classes we reference have been removed. We probably need to rework things a bit so that we can have the configuration section in our extension docs auto-generated.

See:

https://github.com/quarkusio/quarkus/commit/11c3181eb69ebaf6887e731d1d5096b98b16e348

And (not sure if this is relevant for us):

https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.14#publishing-the-config-documentation

**Comment by jamesnetherton** [comment]
For now I've disabled `UpdateExtensionDocPageMojo ` so that the build can complete.

https://github.com/apache/camel-quarkus/commit/0cf262d0f10e45246817fda82c7895bc47a45ad4

**Comment by ppalaga** [comment]
Yeah, thanks for filing the issue, I am aware of the problem and I also need to solve it in Quarkus CXF
