### ISSUE TITLE
smpp: no type converter available for byte properties

### ISSUE THREAD

**Issue by phibo22** [apache/camel-quarkus#6350]
### Bug description

Property binding for byte properties does throw 
`org.apache.camel.NoTypeConversionAvailableException: No type converter available to convert from type: java.lang.String to the required type: byte`

How to reproduce:

1. Create a new project with camel-quarkus-smpp extension:

`quarkus create app org.acme:getting-started \
    --extension='rest,camel-quarkus-smpp'`

2. Add property `camel.component.smpp.data-coding=0` to application.properties

3. Try to start the application using `quarkus dev`

**Comment by zhfeng** [comment]
It's more likely an issue in camel?

**Comment by jamesnetherton** [comment]
> It's more likely an issue in camel?

Yes, it's because `CamelBaseBulkConverterLoader` cannot deal with the primitive `byte`. I have it fixed locally.

**Comment by jamesnetherton** [comment]
https://issues.apache.org/jira/browse/CAMEL-21089

**Comment by davsclaus** [comment]
Can you backport to 4.4.x branch

**Comment by jamesnetherton** [comment]
Fixed in https://github.com/apache/camel-quarkus/pull/6439.
