### ISSUE TITLE
[quarkus-main] Components are not being discovered at build time

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#6354]
### Bug description

Almost every test in the project is failing with a similar startup failure like:

```
Caused by: org.apache.camel.NoSuchLanguageException: No language could be found for: simple
```

I've not had time to look into it. But it probably means that the code we have in CQ core is not able to discover the Camel `META-INF/services` files. Possibly due to these changes:

https://github.com/quarkusio/quarkus/commit/9872f92af04c6f5dde1fbf6189e7898bbd4d066e

https://github.com/quarkusio/quarkus/commit/6780c2c17788d59e30ff50238224416cd62786bb

**Comment by gsmet** [comment]
We merged a fix that could be the source of the problem so please have another look and report back. Thanks!

**Comment by jamesnetherton** [comment]
> We merged a fix that could be the source of the problem so please have another look and report back. Thanks!

Thanks @gsmet. Looks like it's fixed (just one random test failure). 

https://github.com/apache/camel-quarkus/actions/runs/10434798215

**Comment by jamesnetherton** [comment]
I'll close this as the nightly builds look good.
