### ISSUE TITLE
camel-quarkus-javascript extension

### ISSUE THREAD

**Issue by mweissdigchg** [apache/camel-quarkus#6360]
### Describe the feature here

Create a camel-quarkus-javascript extension to use javascript as expression language in camel quarkus, like you can do with the camel-javascript component in Camel.

**Comment by mweissdigchg** [comment]
Hi! Anyone working on this? If not I will start working on this extension.

**Comment by zhfeng** [comment]
Thanks @mweissdigchg - please go ahead!
