### ISSUE TITLE
Use an Artemis container instead of `quarkus-test-artemis` in `camel-quarkus-integration-test-jms-artemis-client`

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#6364]
### Description

... to improve the robustness and lower the maintenance overhead.

**Comment by ppalaga** [comment]
cc @jamesnetherton

**Comment by jamesnetherton** [comment]
Would be good to also apply this to the `jms-jpa` example if possible:

https://github.com/apache/camel-quarkus-examples/blob/8e3f6067ca6639fda54092366356b1a4d67c96a9/jms-jpa/pom.xml#L139-L143

**Comment by jamesnetherton** [comment]
https://github.com/apache/camel-quarkus-examples/pull/258 completes this task.
