### ISSUE TITLE
Unmarshalling with Jackson in multiple routes with different classes

### ISSUE THREAD

**Issue by philschaller** [apache/camel-quarkus#637]
**Describe the bug**
Camel unmarshalling uses only one class for all routes instead of the programmatically configured ones as used in the following line:

`unmarshal().json(JsonLibrary.Jackson, POJO_1.class)`

Calling unmarhal() in a different route (same RouteBuilder or not does not matter) with POJO_2 leads to Jackson exceptions because it expects POJO_1.

**Expected behavior**
Isolated unmarshalling for all routes and invocations. Works with Camel 2.x (without Quarkus).

**Workaround**
Manually unmarshalling with Jackson ObjectMapper.

`process((exchange) -> {
        POJO body = new ObjectMapper().readValue(exchange.getIn().getBody(String.class), POJO.class);
});`

**Environment**
Camel Quarkus 1.0.0-M2
JDK 11

**Comment by lburgazzoli** [comment]
That’s a know issue that should be fixed in the next milestone

**Comment by philschaller** [comment]
Sorry

Missed it in the open/closed issues.

**Comment by lburgazzoli** [comment]
no worries it did not appear as an issue but pop up while discussing another topic :)

**Comment by philschaller** [comment]
Ahhh, then I'm relieved :-)

**Comment by lburgazzoli** [comment]
@philschaller do you mind sending a pr that enhance the jackson tests to include this scenario ?

**Comment by philschaller** [comment]
You mean as part of camel-quarkus/integration-tests/jackson/ ?
No promises, but I can give it a try.

**Comment by lburgazzoli** [comment]
Yes that one, if you need we can help you, just reach us here on on the camel-quarkus gitter room

**Comment by philschaller** [comment]
Solved by 1.0.0-M3
