### ISSUE TITLE
java.lang.NoClassDefFoundError with JDK 11+

### ISSUE THREAD

**Issue by NFI-Chase** [apache/camel-quarkus#642]
When starting up the quarkus server in dev mode it gives java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlElement.  I'm running open jdk 12.  The fix for this is attached, but if you have  a better fix please assist: 
[fixXMLBindIssue.txt](https://github.com/apache/camel-quarkus/files/4089664/fixXMLBindIssue.txt)

**Comment by oscerd** [comment]
You need to add that dependency explicitly. This is something changed with JDK 11.

**Comment by oscerd** [comment]
We can document this for sure. Thanks for spotting this.

**Comment by NFI-Chase** [comment]
cool, no problem.  should I close the issue?

**Comment by oscerd** [comment]
Leave this one open, so we can remember about document this :-)

Thanks

**Comment by ppalaga** [comment]
For jaxb to work flawlessly with camel-quarkus, your project needs to depend on `org.apache.camel.quarkus:camel-quarkus-core-xml` (which should transitively pull whichever artifact that contains `javax/xml/bind/annotation/XmlElement`). If this does not help, please share a minimal project demonstrating the issue.

**Comment by NFI-Chase** [comment]
as per https://camel.apache.org/camel-quarkus/latest/first-steps.html , it tells you to replace org.apache.camel.quarkus:camel-quarkus-core-xml with org.apache.camel.quarkus:camel-quarkus-bom.

**Comment by ppalaga** [comment]
> as per https://camel.apache.org/camel-quarkus/latest/first-steps.html , it tells you to replace org.apache.camel.quarkus:camel-quarkus-core-xml with org.apache.camel.quarkus:camel-quarkus-bom.

That page recommends to use `camel-quarkus-bom` as the parent of your maven project so that you get the dependency versions of camel quarkus extensions (and their transitive dependencies) managed. There is no mention of `camel-quarkus-core-xml`. What I mean is that you need to add something like the following to your project:

```
<project>

...

    <dependencies>
...
        <dependency>
            <groupId>org.apache.camel.quarkus</groupId>
            <artifactId>camel-quarkus-core-xml</artifactId>
        </dependency>
...
    </dependencies>
...
</project>
```

**Comment by NFI-Chase** [comment]
ok, I agree with that. Thank you

**Comment by lburgazzoli** [comment]
@NFI-Chase can we close this issue ?

**Comment by NFI-Chase** [comment]
yes, i will close it now.
