### ISSUE TITLE
Deprecate kotlin extension

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#6444]
Rethinking my comments in #6438. I think we should deprecate (for 3.15.0) and remove `camel-quarkus-kotlin` (in 3.16.0) along with the `kotlin-dsl` extension.

I don't see any major benefits to keeping `camel-quarkus-kotlin`. All it does is provide a Kotlin function wrapper around `RouteBuilder.configure`.

If folks want to build with Kotlin then it's simple enough to add `quarkus-kotlin` and write a `RouteBuilder` impl.

```kotlin
class Routes : RouteBuilder() {
    override fun configure() {
        from("timer:tick?period=5s")
            .log("Hello World")
    }
}
```

**Comment by apupier** [comment]
Camel Quarkus 3.15 will be based on Camel 4.7?
Camel Quarkus 3.16 will be based on Camel 4.9?

Double-checking that we can remove the Kotlin DSl part with Camel 4.9.

**Comment by jamesnetherton** [comment]
CQ 3.15.x will be LTS and will stay aligned to Camel 4.8.x
CQ 3.16.0 will probably be based on whatever the latest Camel 4.8.x release is. It depends if Camel 4.9.0 is available (unlikely TBH). So I guess we delay the extension removal until we integrate Camel 4.9.0.
