### ISSUE TITLE
Junit5-extension-test DoubleRoutesPerClassTest is disabled (possibly would be removed)

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#6492]
### Bug description

Refactors in Camel (based around AbstractTestSupport) made the scenario covered by `DoubleRoutesPerClassTest` invalid.
The test are using `Lifecycle.PER_CLASS`, therefore the routeBuilder from the second test class is not applied and test is failing. Because some of the functionality is marked as deprecated, the whole scenario might not be valid anymore.

**Comment by JiriOndrusek** [comment]
This is not an issue, I probably used wrong version of Camel or something similar.

**Comment by JiriOndrusek** [comment]
The nightly CI confirmed the error, reopening

**Comment by JiriOndrusek** [comment]
FYI @orpiske

**Comment by orpiske** [comment]
@JiriOndrusek thanks for the heads up. Yeah, this test scenario seems like it's invalid from now on
