### ISSUE TITLE
[quarkus-main] openapi-java deployment module fails to compile due to missing DefinitionReader class

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#6498]
`io.smallrye.openapi.runtime.io.definition.DefinitionReader` is removed in SmallRye OpenAPI 3.12, which breaks the build time logic in the `openapi-java` extension here:

https://github.com/apache/camel-quarkus/blob/main/extensions/openapi-java/deployment/src/main/java/org/apache/camel/quarkus/component/openapi/java/deployment/OpenApiJavaProcessor.java#L242-L244

The only fix I found is to use `OpenApiParser`. 

https://github.com/apache/camel-quarkus/blob/quarkus-main/extensions/openapi-java/deployment/src/main/java/org/apache/camel/quarkus/component/openapi/java/deployment/OpenApiJavaProcessor.java#L232-L237

But, that class is marked as deprecated and has a comment stating that it may be removed or have reduced visibility in the future. So we probably need to find an alternate solution.

**Comment by zhfeng** [comment]
Well, I can take a look. IIRC these codes were borrowed from quarkus somewhere before.

**Comment by zhfeng** [comment]
It could be alter to use [OpenAPIDefinitionIO](https://github.com/smallrye/smallrye-open-api/blob/main/core/src/main/java/io/smallrye/openapi/runtime/io/OpenAPIDefinitionIO.java#L55)

**Comment by jamesnetherton** [comment]
Done in https://github.com/apache/camel-quarkus/pull/6523.
