### ISSUE TITLE
Automate tests against camel and quarkus master

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#652]
As long term we need to make the process of testing against camel and quarkus master done on regular basis so would be nice if we could create some branches like:

- camel-master
- quarkus-master

ad set up some action that do the backport from camel-quarkus master to those branches

**Comment by lburgazzoli** [comment]
Relates to https://github.com/apache/camel-quarkus/pull/651

**Comment by jamesnetherton** [comment]
Fixed in https://github.com/apache/camel-quarkus/commit/d032f1cfa24bd6987ba64dd24644d66a95412e71 & https://github.com/apache/camel-quarkus/commit/3ab385a437a74c3bd150a2f5f4443b4a57a2dbef.
