### ISSUE TITLE
[camel-main] Enable csv test once quarkus upgrades commons-io to 2.17.0

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#6560]
### Bug description

Newly upgraded `commons-csv` requires `commons-io` 2.17.0, which is forced by Quarkus, Once following [PR](https://github.com/quarkusio/quarkus/pull/43504) is merged into Quarkus, csv test can be enabled.

**Comment by JiriOndrusek** [comment]
The native profile in the test module had to be disabled. Please enable when `commons-io` is upgraded.

**Comment by gsmet** [comment]
FYI I merged the upgrade PR in Quarkus main.
