### ISSUE TITLE
[camel-main] SmallRye Fault Tolerance  not compatible with camel-microprofile-fault-tolerance #6584

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#6602]
### Description

See https://github.com/apache/camel-quarkus/issues/6584 for more details.

The issue on `camel-main` branch happens only in native, therefore the native profile is disabled. 
As soon as the quarkus 3.16 is adopted by  the main branch, the issue should be fixed and the native profile enabled back

**Comment by jamesnetherton** [comment]
3.16 is now on the `main` branch so this could be unblocked on `camel-main`.

**Comment by MikaelAnderssonWigander** [comment]
Hi, is this issue related to FaultTolerance not compatibe in native mode?

https://github.com/quarkusio/quarkus/discussions/43072

**Comment by jamesnetherton** [comment]
> Hi, is this issue related to FaultTolerance not compatibe in native mode?
> 
> [quarkusio/quarkus#43072](https://github.com/quarkusio/quarkus/discussions/43072)

Yes, SmallRye Fault Tolerance introduced breaking changes and Camel has to adapt to them.

It should get fixed when Camel Quarkus 3.17.0 is eventually released.

**Comment by MikaelAnderssonWigander** [comment]
In 3.17.2 it is still not working, I'm afraid

**Comment by jamesnetherton** [comment]
> In 3.17.2 it is still not working, I'm afraid

Expected because Camel Quarkus 3.17.x is not released yet. Quarkus 3.17.x is still aligned to CQ 3.16.0.

**Comment by jamesnetherton** [comment]
Fixed by the Camel 4.9.0 upgrade.
