### ISSUE TITLE
Remove quarkus-artemis-bom from bom-test

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#6623]
### Describe the feature here

Quarlus-artemis-bom is part of the quarkus-bom, therefore:

1. Imported quarkus-artemis-bom (https://github.com/apache/camel-quarkus/blob/main/poms/bom-test/pom.xml#L58-L64) should be removed from the ``bom-test. 
2. Should be replaced with `quarkus-artemis-core` where version is synced to artemis-bom (becaose of https://github.com/jboss-fuse/camel-quarkus/commit/d6df1c8ea396906935fdcc16d3fae3fd80bd6bc5#diff-e90395d00913473ae3d46edf4bed7169b7f74eef6057d8658e3b59c1278058f3R51)

**Comment by zhfeng** [comment]
Well, I think we need to keep it in the upstream since `quarkus-artemis` is only used in the integration-tests.

**Comment by JiriOndrusek** [comment]
I agree closing the issue
