### ISSUE TITLE
Google-secret-manager: use Quarkiverse Google Cloud Services

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#6691]
### Describe the feature here

It should be possible to leverage `secret-manager` quarkiverse [extension](https://github.com/quarkiverse/quarkus-google-cloud-services).

**Comment by jamesnetherton** [comment]
We [removed](https://github.com/apache/camel-quarkus/pull/3188) Quarkus Google Cloud Services from the project long ago and we're not going to adopt it again without a good reason.

**Comment by jamesnetherton** [comment]
Wont do.
