### ISSUE TITLE
RabbitMQ support

### ISSUE THREAD

**Issue by hanzo2001** [apache/camel-quarkus#675]
As suggested in [https://camel.apache.org/camel-quarkus/latest/list-of-camel-quarkus-extensions.html](https://camel.apache.org/camel-quarkus/latest/list-of-camel-quarkus-extensions.html)

> In case you are missing some Camel feature in the list:
> * Upvote an existing issue or create a new one so that we can better prioritize our work

For the time being, I'll try my luck
> * You may try your luck using the given camel component on Quarkus directly (without an extension). Most probably it will work in the JVM mode and fail in the native mode. Do not hesitate to report any issues you encounter.

I would like to be able to compile my project down to native eventually. If I can help in any way (other than writing the extension and reporting errors), please let me know.

**Comment by ppalaga** [comment]
Yeah, try to scaffold the extension as documented in https://camel.apache.org/camel-quarkus/latest/contributor-guide.html#_create_a_new_extension and implement some tests. That's the safest way to figure out what is missing for the native mode. Feel free to ask here if you have specific questions.

**Comment by mmelko** [comment]
I can look at this

**Comment by hanzo2001** [comment]
Sorry, I've been too busy this entire month. I might have some time next next week but I'm not sure with my current issues.

**Comment by Jeansen** [comment]
Any roadmap when it will be available for native and considered stable (instead of JVM + Preview)?

**Comment by ppalaga** [comment]
Created a separate issue https://github.com/apache/camel-quarkus/issues/1531
