### ISSUE TITLE
[quarkus-main] Quarkus Artemis dev services fail to start

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#6791]
### Bug description

Quarkus has reorganised some of the dev services config:

https://github.com/quarkusio/quarkus/commit/bbb10098d8fc0b584990f37595bf02a84f5349d5

It makes Quarkus Artemis dev services fail due to:

```
Caused by: java.lang.NoSuchFieldError: timeout
   at io.quarkus.artemis.core.deployment.DevServicesArtemisProcessor.start(DevServicesArtemisProcessor.java:128)
```

**Comment by jamesnetherton** [comment]
FYI @turing85. A breaking change for Quarkus Artemis coming in Quarkus 3.18.

**Comment by zhfeng** [comment]
Hi @turing85 , I got this same isseu when running `quarkus-pooled-jms` tests with `quarkus-artemis` against Quarkus snapshot , see https://github.com/quarkiverse/quarkus-pooled-jms/actions/runs/1

**Comment by jamesnetherton** [comment]
This has been fixed in https://github.com/quarkusio/quarkus/commit/a5e8b1cf568c10309b735245af995ca5a387d0ca.
