### ISSUE TITLE
Pinecone: re-capture wiremocked data after upgrade from 1.2.2 to 3.0.0

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#6808]
### Bug description

After the major upfdate of  `pinecone-client` (camel [PR](https://github.com/apache/camel/pull/16146)) - the wiremock data has to be updated as well.

Please enable tests afterwards.

**Comment by jamesnetherton** [comment]
I fixed the WireMock recordings and native support.
