### ISSUE TITLE
Message-bridge example: does not work if there is less then 10% of free disk space

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#6821]
### Bug description

If the free disk space is less then 10%, the artemis queue become blocking and the example fails.

**Comment by jamesnetherton** [comment]
Fixed in https://github.com/apache/camel-quarkus-examples/pull/306.

I applied a similar change for the `artemis-elasticsearch` project in https://github.com/apache/camel-quarkus-examples/pull/307.

Both commits were backported to 3.15.x.
