### ISSUE TITLE
Do not expose mutable collections from FHIR BuildItems

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#690]
BuildItems should not expose mutable collections because they are consumed from concurrent threads. Mutability does not seem to be required here. Making the properties immutable would simplify the reasoning about the code. 

This applies at least to 

* Dstu2PropertiesBuildItem
* R5PropertiesBuildItem
* R4PropertiesBuildItem
* Dstu3PropertiesBuildItem

**Comment by johnpoth** [comment]
@ppalaga 

The idea here is to allow the user to add FHIR resources to the FHIR context before recording. Otherwise you'll get a ClassNotFoundException. See https://wiki.hl7.org/FHIR_Custom_Resources

**Comment by ppalaga** [comment]
Fixed via 623e0456c074b26d1ca53cd2baf28b17c23257b3
