### ISSUE TITLE
quarkus-maven-plugin generate application.properties file for IT tests

### ISSUE THREAD

**Issue by johnpoth** [apache/camel-quarkus#694]
When creating new extensions, it'd be cool to have the quarkus-maven-plugin generate the application.properties file for IT tests

**Comment by ppalaga** [comment]
Plz assign to me

**Comment by ppalaga** [comment]
PR sent to Quarkus https://github.com/quarkusio/quarkus/pull/7182

**Comment by ppalaga** [comment]
If the Quarkus PR gets merged as is, the mojo will create an empty application.properties file. 

We can override the template and the question what content do we want there?

A valid license header is a minimal requirement for sure, but maybe we want more?
