### ISSUE TITLE
Unable to GET an https URL with netty-http client

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#695]
Steps to reproduce: enable "netty-http" in `integration-tests/http/src/test/java/org/apache/camel/quarkus/component/http/it/HttpTest.java` https://github.com/apache/camel-quarkus/pull/697/files#diff-829f912f061c8d9bd2c05e5b8e30da82R55 and run the test. 

It fails already in the JVM mode, the server responds with 400, so I guess there is something wrong with the request. 

Any ideas @jamesnetherton @lburgazzoli ?

**Comment by jamesnetherton** [comment]
I think you may need to provide a trust store with the cert chain for `rescountries.eu`. E.g something like:

```
netty-https:https://restcountries.eu/rest/v2/alpha/cz?ssl=true&keyStoreResource=classpath:keystore.jks&trustStoreResource=classpath:keystore.jks&passphrase=password
```

**Comment by lburgazzoli** [comment]
is this still a thing ?

**Comment by ppalaga** [comment]
Yes, certainly, as I had no time to try James's advice.

**Comment by jamesnetherton** [comment]
Fixed in https://github.com/apache/camel-quarkus/commit/6fa5685de2baa8a071475018ff0c44c7f90564e0.
