### ISSUE TITLE
Restore the testing of the font option when switching to camel 3.1.0

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#708]

**Comment by aldettinger** [comment]
We should be able to restore the font option in `PdfResource.createFromText` `"pdf:create?fontSize=6&pageSize=PAGE_SIZE_A5&font=Courier"` when upgrading to camel >= 3.1.0 as [CAMEL-14452](https://issues.apache.org/jira/browse/CAMEL-14452) should fix the NPE.

**Comment by ppalaga** [comment]
If you'd like to test against Camel master, this is the most up to date branch ATM: https://github.com/apache/camel-quarkus/pull/698

**Comment by jamesnetherton** [comment]
I've applied the change & verified that this works fine on the `camel-master` branch.
