### ISSUE TITLE
Include quarkus info in camel-catalog

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#75]
We should add information about what components are quarkus ready to the camel catalog

/cc @davsclaus @oscerd

**Comment by ppalaga** [comment]
Actually, what purpose should the Catalog serve? If the main use case is to answer the question 

> For given component *c* and Camel version *x.y.z*, which platforms (SB, Quarkus, WidlFly, ...) are supported?

then I think all the necessary info is already available on Maven Central. The answer can be obtained by a script that joins camel BOM with the compatible platform BOMs. So we perhaps do not need feed that information into a git repository? Well at least not manually. There could be a service or a regular job that would aggregate that info and make it available in some suitable format. WDYT?

**Comment by lburgazzoli** [comment]
It is broader that that as the catalog contains information about endpoint, the properties that each endpoint supports, its schema and so on so for quarkus it can also include info about the properties each extension supports and so on.

**Comment by ppalaga** [comment]
We'll create a Quarkus catalog
