### ISSUE TITLE
Test the Jira extension using Testcontainer and the Jira image

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#752]
The README [1] in the itest states that the test can be run against a manually started container using the Jira Image [2]. I wonder whether this can be automated via Test containers as we do with Consul and other extensions.

[1] https://github.com/apache/camel-quarkus/pull/728/files#diff-946d5ce322e8e8d37da82de18d75551cR5
[2] https://hub.docker.com/r/atlassian/jira-software

**Comment by jamesnetherton** [comment]
I thought about doing this, but the problem is that it needs a development license key to run and they expire every 90 days.

**Comment by ppalaga** [comment]
Good to know, thanks for the info.

**Comment by jamesnetherton** [comment]
Since 2d2eeefecbdc0fa34b936c207d5f3ec59edc69be the Jira endpoints under test return stubbed responses. Which IMO is an acceptable alternative to having a full Jira server up and running.
