### ISSUE TITLE
Cannot build examples/timer-log in native mode

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#756]
❯ mvn clean package -Pnative
[INFO] Scanning for projects...
[INFO]
[INFO] -----< org.apache.camel.quarkus:camel-quarkus-examples-timer-log >------
[INFO] Building Camel Quarkus :: Examples :: Timer Log 1.1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ camel-quarkus-examples-timer-log ---
[INFO] Deleting /Users/davsclaus/workspace/camel-quarkus/examples/timer-log/target
[INFO]
[INFO] --- directory-maven-plugin:0.3.1:highest-basedir (directories) @ camel-quarkus-examples-timer-log ---
[INFO] Highest basedir set to: /Users/davsclaus/workspace/camel-quarkus
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (camel-quarkus-enforcer-rules) @ camel-quarkus-examples-timer-log ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven-version) @ camel-quarkus-examples-timer-log ---
[INFO]
[INFO] --- groovy-maven-plugin:2.1.1:execute (sanity-checks) @ camel-quarkus-examples-timer-log ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/Users/davsclaus/.m2/repository/org/codehaus/groovy/groovy/2.5.8/groovy-2.5.8.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO]
[INFO] --- formatter-maven-plugin:2.11.0:format (format) @ camel-quarkus-examples-timer-log ---
[INFO] Using 'UTF-8' encoding to format source files.
[INFO] Number of files to be formatted: 1
[INFO] Successfully formatted:          0 file(s)
[INFO] Fail to format:                  0 file(s)
[INFO] Skipped:                         1 file(s)
[INFO] Read only skipped:               0 file(s)
[INFO] Approximate time taken:          0s
[INFO]
[INFO] --- impsort-maven-plugin:1.3.2:sort (sort-imports) @ camel-quarkus-examples-timer-log ---
[INFO]  Total Files Processed: 1 in 00:00.203
[INFO]         Already Sorted: 1
[INFO]         Needed Sorting: 0
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ camel-quarkus-examples-timer-log ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ camel-quarkus-examples-timer-log ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/davsclaus/workspace/camel-quarkus/examples/timer-log/target/classes
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:resources (copy-generated-resources) @ camel-quarkus-examples-timer-log ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ camel-quarkus-examples-timer-log ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/davsclaus/workspace/camel-quarkus/examples/timer-log/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ camel-quarkus-examples-timer-log ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M4:test (default-test) @ camel-quarkus-examples-timer-log ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ camel-quarkus-examples-timer-log ---
[INFO] Building jar: /Users/davsclaus/workspace/camel-quarkus/examples/timer-log/target/camel-quarkus-examples-timer-log-1.1.0-SNAPSHOT.jar
[INFO]
[INFO] --- maven-site-plugin:3.7.1:attach-descriptor (attach-descriptor) @ camel-quarkus-examples-timer-log ---
[INFO] Skipping because packaging 'jar' is not pom.
[INFO]
[INFO] --- quarkus-maven-plugin:1.3.0.Alpha2:build (build) @ camel-quarkus-examples-timer-log ---
[INFO] [org.jboss.threads] JBoss Threads version 3.0.1.Final
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /Users/davsclaus/workspace/camel-quarkus/examples/timer-log/target/camel-quarkus-examples-timer-log-1.1.0-SNAPSHOT-native-image-source-jar/camel-quarkus-examples-timer-log-1.1.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /Users/davsclaus/workspace/camel-quarkus/examples/timer-log/target/camel-quarkus-examples-timer-log-1.1.0-SNAPSHOT-native-image-source-jar/camel-quarkus-examples-timer-log-1.1.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 19.3.1 CE
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] /opt/graalvm-ce-java11-19.3.1/Contents/Home/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -H:+JNI -jar camel-quarkus-examples-timer-log-1.1.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services --no-server -H:-UseServiceLoaderFeature -H:+StackTrace camel-quarkus-examples-timer-log-1.1.0-SNAPSHOT-runner
[camel-quarkus-examples-timer-log-1.1.0-SNAPSHOT-runner:95074]    classlist:   3,317.43 ms
19:09:51,100 INFO  [org.apa.cam.sup.LRUCacheFactory] Detected and using LURCacheFactory: camel-caffeine-lrucache
[camel-quarkus-examples-timer-log-1.1.0-SNAPSHOT-runner:95074]        (cap):   2,086.01 ms
[camel-quarkus-examples-timer-log-1.1.0-SNAPSHOT-runner:95074]        setup:   3,588.00 ms
19:09:56,275 INFO  [org.jbo.threads] JBoss Threads version 3.0.1.Final
[camel-quarkus-examples-timer-log-1.1.0-SNAPSHOT-runner:95074]   (typeflow):  23,748.55 ms
[camel-quarkus-examples-timer-log-1.1.0-SNAPSHOT-runner:95074]    (objects):  19,071.35 ms
[camel-quarkus-examples-timer-log-1.1.0-SNAPSHOT-runner:95074]   (features):   1,223.97 ms
[camel-quarkus-examples-timer-log-1.1.0-SNAPSHOT-runner:95074]     analysis:  46,394.54 ms
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: javax.xml.bind.JAXBContext. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing org.apache.camel.reifier.rest.RestBindingReifier.setupJaxb(RestBindingReifier.java:166)
Call path from entry point to org.apache.camel.reifier.rest.RestBindingReifier.setupJaxb(RestConfiguration, String, String, DataFormat, DataFormat):
	at org.apache.camel.reifier.rest.RestBindingReifier.setupJaxb(RestBindingReifier.java:160)
	at org.apache.camel.reifier.rest.RestBindingReifier.createRestBindingAdvice(RestBindingReifier.java:124)
	at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:396)
	at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:112)
	at org.apache.camel.quarkus.core.FastModel.start(FastModel.java:57)
	at org.apache.camel.quarkus.core.BaseModel.startRoute(BaseModel.java:327)
	at org.apache.camel.quarkus.core.BaseModel.startRouteDefinitions(BaseModel.java:320)
	at org.apache.camel.quarkus.core.BaseModel.startRouteDefinitions(BaseModel.java:299)
	at org.apache.camel.quarkus.core.FastCamelContext.startRouteDefinitions(FastCamelContext.java:141)
	at com.oracle.svm.reflect.AbstractCamelContext_startRouteDefinitions_d9d0e38b2319b6d7686c4d0b97300500cfc8b56c_1381.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at java.util.ServiceLoader$ProviderImpl.invokeFactoryMethod(ServiceLoader.java:736)
	at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:719)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:188)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:141)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:342)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

**Comment by davsclaus** [comment]
Looks like some REST stuff is pulling in xml bits

**Comment by davsclaus** [comment]
Adding `camel-quarkus-core-xml` makes it work, but would be good to get it to run without as we are not in need of xml

**Comment by aldettinger** [comment]
Closing as I could run it in native mode locally and it looks [fixed](https://github.com/apache/camel-quarkus/commit/6c2595c4fdda5c8ae6e1a3d78fdbcba770585ee0#diff-aaa7eadc3e7fdd1e8d11cbf88dc52b4c).
