### ISSUE TITLE
gRPC native support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#762]
Waiting for gRPC support by Quarkus itself. Related:

* https://github.com/quarkusio/quarkus/issues/5627
* https://github.com/quarkusio/quarkus/issues/820
* https://groups.google.com/forum/#!msg/quarkus-dev/FpPN5Bei6-0/2YtEXSxoDgAJ

**Comment by ppalaga** [comment]
Let's do the easy JVM part first: https://github.com/apache/camel-quarkus/issues/965

**Comment by ppalaga** [comment]
Also related: https://github.com/quarkusio/quarkus-grpc

**Comment by jamesnetherton** [comment]
gRPC extension has landed in the main project now:

https://github.com/quarkusio/quarkus/tree/master/extensions/grpc
