### ISSUE TITLE
CXF JAX-WS support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#764]
A.k.a. SOAP client and SOAP server.

Related: 

* https://github.com/quarkusio/quarkus/issues/4005
* https://github.com/quarkusio/quarkus/issues/3479
* https://github.com/quarkusio/quarkus/pull/5538

**Comment by dufoli** [comment]
Soap server is on good way with cxf. I need to check what is the possibilities to add client side too.

**Comment by famod** [comment]
FWIW: `org.apache.cxf.ws.security.trust.STSClient` seems to work out of the box in JVM mode.
Next we are going to try `JaxWsProxyFactoryBean` in our Quarkus project. I hope we'll manage to get it working somehow until an official extension is available.
So a definite +1!

**Comment by janstey** [comment]
Seems there is a CXF extension in progress in the quarkiverse https://github.com/quarkiverse/quarkiverse-cxf

**Comment by grigoni** [comment]
it would really help me to implement SOAP services, I hope the extension comes soon
thanks to all who contributes to it

**Comment by famod** [comment]
@grigoni If you don't need something that is tightly integrated into camel(-quarkus) then you can just use https://github.com/quarkiverse/quarkiverse-cxf

**Comment by grigoni** [comment]
thx @famod but I'm really looking for camel integrations

**Comment by aymenfurter** [comment]
Thanks to everyone contributing to this cause. I would love to use camel-cxf on quarkus aswell.

**Comment by dufoli** [comment]
hello,

I can work on camel-cxf... I see that a soap folder already exist on camel. Someone can point me any documentation to help on that ?

**Comment by ppalaga** [comment]
> I can work on camel-cxf... I see that a soap folder already exist on camel. Someone can point me any documentation to help on that ?

That would be highly welcome, here is is the guide: https://camel.apache.org/camel-quarkus/latest/contributor-guide/create-new-extension.html . You'd start with 

```
$ cd camel-quarkus
$ mvn cq:create -N -Dcq.artifactIdBase=cxf
```

And then go on to adding tests to `integration-tests/cxf` and fixing the issues until the tests pass in both JVM and native mode.

**Comment by dufoli** [comment]
not working on windows.... and it will take too much time to make the build working on windows...

**Comment by ppalaga** [comment]
Ups, sorry about that. Could you please report the issues your have? We'd be definitely interested in making the Windows builds work.

**Comment by dufoli** [comment]
@ppalaga  
https://github.com/apache/camel-quarkus/issues/2999 for creation of extension on windows
on windows build another ticket already exists : https://github.com/apache/camel-quarkus/issues/1429

**Comment by javaduke** [comment]
Pardon my annoyance, is there any update on this? I'd really like to see the camel-cxf extension, at least with client functionality.

**Comment by jochenr** [comment]
I'd like to join the previous post.
the camel-cxf extension ist very important for us and it becomes urgent to get it, since we don't want to migrate to migrate our Camel based applications (currently running on Red Hat Fuse on EAP) to spring.
SOAP-webservices are still a very relevant technology in financial industries, if you like it or not;-)

Is there any way I can support this issue/feature?

**Comment by javaduke** [comment]
Good news, I have the CXF extension working and I successfully tested CXF client with WS-Security and WS-Addressing.
Haven't tried creating a SOAP service yet, wondering if it's really needed.

**Comment by grigoni** [comment]
@javaduke this is great news! I would need both ways to move them to quakes: some apps are camel cxd client and some others are cxd services

**Comment by javaduke** [comment]
Sure, CXF service testing is my next step, shouldn't be any different. So far it only works in JVM mode, I'll see what I can do about native.

**Comment by javaduke** [comment]
https://github.com/apache/camel-quarkus/pull/3727 - so far JVM mode only.

**Comment by jamesnetherton** [comment]
Done in https://github.com/apache/camel-quarkus/commit/2449a3928e7f2c8130ade6ca57cf6802ec456281.
