### ISSUE TITLE
XML Tokenize language native support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#780]
This might work already, maybe just a test needs to be added.

**Comment by ppalaga** [comment]
We have `camel-quarkus-xml-jaxp` extension depending on `camel-xml-jaxp` that provides the necessary bits. We need a test.

**Comment by jamesnetherton** [comment]
I verified this works fine in JVM mode when an appropriate StAX Reader implementation is added (E.g woodstox). For it to work in native mode, I think we'd need an extension for the StAX impl so it can register services, reflective classes etc.
