### ISSUE TITLE
Saga native support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#819]

**Comment by aldettinger** [comment]
May relate to this [PR](https://github.com/quarkusio/quarkus/pull/6763).

**Comment by ppalaga** [comment]
Not sure about the details, but we have a separate issue for LRA https://github.com/apache/camel-quarkus/issues/793

**Comment by zhfeng** [comment]
The camel-saga component  provides a way to make a manual decision of complete or compensate a Saga transaction. For normal use of the Saga, you can refer to [SAGA EIP](https://camel.apache.org/components/latest/eips/saga-eip.html).
In term of the LRA (Long Running Action), it is more like a transaction model based on Saga pattern. You can refer to the [MicroProfile LRA](https://github.com/eclipse/microprofile-lra) to know more details about the APIs.
The camel-lra provides a LRASagaService to talk to the [Narayana LRA coordinator](https://github.com/jbosstm/narayana/tree/master/rts/lra) and I think we could leverage the narayana lra coordinator extension in quarkus if it get merged in the future.

Feel free to assign this issue to me and I will take a close look.

**Comment by zhfeng** [comment]
@ppalaga is there any way to add a service in camel context at the build or runtime phase just like we do with the [LraServiceAutoConfiguration.java ](https://github.com/apache/camel-spring-boot/blob/master/components-starter/camel-lra-starter/src/main/java/org/apache/camel/service/lra/springboot/LraServiceAutoConfiguration.java#L74) in spring boot ?

**Comment by lburgazzoli** [comment]
There's no direct support so far.

One solution would be to use `CamelContextBuildItem` however to use it, we need to introduce a synchronization point i.e. by using [empty build items](https://quarkus.io/guides/writing-extensions#empty-build-items) as the Camel Context should be fully configured before [Camel Main](https://github.com/apache/camel-quarkus/blob/b8135432cb67a4739395671ea98f366d2e252b36/extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/BuildProcessor.java#L521) set up kicks in.

Another option would be to introduce a sort of `CamelContextCustomizerBuildItem` which can then be used by the core's [BuildProcessor](https://github.com/apache/camel-quarkus/blob/b8135432cb67a4739395671ea98f366d2e252b36/extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/BuildProcessor.java#L360) to do further customization of the camel context.

**Comment by ppalaga** [comment]
> Another option would be to introduce a sort of `CamelContextCustomizerBuildItem` which can then be used by the core's [BuildProcessor](https://github.com/apache/camel-quarkus/blob/b8135432cb67a4739395671ea98f366d2e252b36/extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/BuildProcessor.java#L360) to do further customization of the camel context.

Isn't CamelMainListenerBuildItem doing just that?

**Comment by zhfeng** [comment]
Thanks @lburgazzoli and @ppalaga !

Is there any difference about the [contextConfigurerListener](https://github.com/apache/camel-quarkus/blob/master/extensions/microprofile-metrics/deployment/src/main/java/org/apache/camel/quarkus/component/microprofile/metrics/deployment/MicroProfileMetricsProcessor.java#L51) and [configureCamelContext](https://github.com/apache/camel-quarkus/blob/master/extensions/microprofile-metrics/deployment/src/main/java/org/apache/camel/quarkus/component/microprofile/metrics/deployment/MicroProfileMetricsProcessor.java#L60) in MicroProfileMetricsProcessor.java? It looks like both of them can do the configure with the camel context.

**Comment by lburgazzoli** [comment]
> > Another option would be to introduce a sort of `CamelContextCustomizerBuildItem` which can then be used by the core's [BuildProcessor](https://github.com/apache/camel-quarkus/blob/b8135432cb67a4739395671ea98f366d2e252b36/extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/BuildProcessor.java#L360) to do further customization of the camel context.
> 
> Isn't CamelMainListenerBuildItem doing just that? There is an example in MicroProfileMetricsProcessor.

yep when that's when main is enabled but those are generic services that do not depend on main

**Comment by zhfeng** [comment]
So these services can be added in the camel context before the main whenever it is enabled or not ?

**Comment by lburgazzoli** [comment]
> Thanks @lburgazzoli and @ppalaga !
> 
> Is there any difference about the [contextConfigurerListener](https://github.com/apache/camel-quarkus/blob/master/extensions/microprofile-metrics/deployment/src/main/java/org/apache/camel/quarkus/component/microprofile/metrics/deployment/MicroProfileMetricsProcessor.java#L51) and [configureCamelContext](https://github.com/apache/camel-quarkus/blob/master/extensions/microprofile-metrics/deployment/src/main/java/org/apache/camel/quarkus/component/microprofile/metrics/deployment/MicroProfileMetricsProcessor.java#L60) in MicroProfileMetricsProcessor.java? It looks like both of them can do the configure with the camel context.

`configureCamelContext` seems to be a good candidate to be refactored to a `CamelContextCustomizerBuildItem` 

`contextConfigurerListener` turn on message history as you can turn in off on camel-main with a property thus we need to force it if mp metrics is enabled

**Comment by lburgazzoli** [comment]
> So these services can be added in the camel context before the main whenever it is enabled or not ?

I think so

**Comment by zhfeng** [comment]
OK, I think it could be worth to raise a new issue to introduce the ```CamelContextCustomizerBuildItem``` for help to do such things, any thoughts ?

**Comment by ppalaga** [comment]
> could be worth to raise a new issue to introduce the `CamelContextCustomizerBuildItem`

I am not against that, but please write a proper class level JavaDoc on the new BuildItem, explaining 

* What happens before and after
* Sum up roughly which uses is it intended for and 
* Explain the relationship to Core and Main.

**Comment by zhfeng** [comment]
yeah, I totally agree that the doc would be very helpful !

**Comment by lburgazzoli** [comment]
>     * Explain the relationship to Core and Main.

Like it has not relation to main :)

**Comment by ppalaga** [comment]
A JVM-only extension (without test) is underway

**Comment by zhfeng** [comment]
Thanks @ppalaga and I will take a look at the native support.

**Comment by mayeqc** [comment]
When using LRA on Camel Quarkus, when the saga is about to end, an error occurs when communicating with the participant. An embedded coordinator is used. Does anyone know why this can happen?

This is the error
022-02-02 16:24:35,702 INFO  [io.nar.lra] (Periodic Recovery) LRARecord.doEnd put http://localhost:8080/lra-participant/complete?Camel-Saga-Compensate=direct://refundCredit failed
2022-02-02 16:24:35,708 INFO  [io.nar.lra] (Periodic Recovery) LRARecord.doEnd put http://localhost:8080/lra-participant/complete?Camel-Saga-Compensate=direct://cancelOrder&Camel-Saga-Complete=direct://complete failed
2022-02-02 16:24:35,712 INFO  [io.nar.lra] (Periodic Recovery) LRARecord.doEnd put http://localhost:8080/lra-participant/complete failed
2022-02-02 16:24:35,738 INFO  [io.nar.lra] (Periodic Recovery) RecoveringLRA.replayPhase2 for http://localhost:8080/lra-coordinator/0_ffffac1a8001_e0af_61faf689_2 ended with status: Closing
