### ISSUE TITLE
Milo native support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#821]
A.k.a. OPC UA Client and OPC UA Server

**Comment by danielwagn3r** [comment]
Especially in industry applications OPC UA is often used by actuators, sensors or gateways. This would add to the already existing support for Eclipse Paho

**Comment by ppalaga** [comment]
A JVM-only extension (without a proper test) is underway.

**Comment by jnsw** [comment]
Is this a thing now?

**Comment by oscerd** [comment]
No.

**Comment by oscerd** [comment]
Only JVM https://github.com/apache/camel-quarkus/tree/main/extensions-jvm/milo

**Comment by jamesnetherton** [comment]
Milo was removed in Camel 4.x.
