### ISSUE TITLE
Qute support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#825]

**Comment by zhfeng** [comment]
There is an issue [camel-qute - Quarkus template engine](https://issues.apache.org/jira/browse/CAMEL-14326) which I'm working on. It could be WIP with the [my branch](https://github.com/apache/camel/compare/master...zhfeng:CAMEL-14326)

**Comment by zhfeng** [comment]
So feel free to assign this issue to me and I will try to port this component to camel-quarkus if it get in the camel 3.x

**Comment by ppalaga** [comment]
Thanks for the info, @zhfeng !

**Comment by zhfeng** [comment]
@ppalaga as we discussed in the upstream camel PR, I think it could be better to move the camel-qute component to the camel-quarkus to avoid the a circular quarkus dependency problem.

**Comment by ppalaga** [comment]
> move the camel-qute component to the camel-quarkus

No problem with that

**Comment by ppalaga** [comment]
Fixed via https://github.com/apache/camel-quarkus/pull/878
