### ISSUE TITLE
Move Groovy executions under the enforce profile

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#831]
I profiled maven builds that I execute quite often and i found that enforcer and Groovy make ~18% of the build time. enforcer is easy to skip via `-Denforce=false` but we do not have anything like that for Groovy. Given that our Groovy scripts serve a purpose quite similar to the enforcer, I propose to move the Groovy executions under the `enforce` profile, so that they all can be skipped together. WDYT?

**Comment by ppalaga** [comment]
Actually we do that in `poms/build-parent/pom.xml` for `validate-dependencies.groovy` already. So we should do that for the other two validation groovy scripts too.

**Comment by lburgazzoli** [comment]
I did propose to make at least some of them proper enforce extensions so they would obey to the enforcer semantics, a profile would be good enough but it may be something to think about.
