### ISSUE TITLE
Re-org the source tree

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#865]
## Goals

* Reduce the number of extensions under `extensions`
* Increase the visibility of the extensions now under `extensions/support`. They are hard to find for newcomers and they are hard to scroll to for maintainers

## Non-goals (possible future goals)

* Split the extensions under `extensions` into even smaller groups, like we have in the GH workflow
* Do anything with the itests

## Current state:

```
├── catalog
├── docs
├── examples
├── extensions
│   ├── ...
│   ├── support
├── integration-tests
├── poms
└── tooling
```

## Proposed state

```
├── catalog
├── docs
├── examples
├── extensions
├── extensions-core       # The extensions whose camel artifacts are under core in the Camel source tree
├── extensions-support   # Moved from extensions/support
├── integration-tests
├── poms
└── tooling

```

WDYT?

**Comment by lburgazzoli** [comment]
Fine with me, wonder if it could make sense to use `core` instead if `extensions-core` (same for `support`)

**Comment by ppalaga** [comment]
> Fine with me, wonder if it could make sense to use `core` instead if `extensions-core` (same for `support`)

No problem, if you like it that way.

Now pondering whether it is worth to have a common parent folder for the three extension folders. We currently have some sanity checks defined in `extensions` - I'd either have to move the def to the top pom or have them three times.

**Comment by ppalaga** [comment]
I think I slightly prefer the option without the common parent folder for the three extension folders. It's less clicking around in the IDE.

**Comment by ppalaga** [comment]
> > Fine with me, wonder if it could make sense to use `core` instead if `extensions-core` (same for `support`)
> 
> No problem, if you like it that way.

Actually, we already have a module called `camel-quarkus-core` and I'd like to keep the naming scheme `artifactId = "camel-quarkus-" + dirName`. So `extensions-core` or `core-extensions` seems to be a better choice.
