### ISSUE TITLE
@BindToRegistry fields need to be explicitly registered for reflection in order to work in native mode

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#867]

**Comment by aldettinger** [comment]
The issue could be reproduced in mustache itests, just comment this [line](https://github.com/apache/camel-quarkus/blob/master/integration-tests/mustache/src/main/java/org/apache/camel/quarkus/component/mustache/it/MustacheRoute.java#L23).
Then run `mvn clean verify -P native`.

**Comment by lburgazzoli** [comment]
There should not be the need to register the class for reflection as it is already done by the native image processor, https://github.com/apache/camel-quarkus/blob/master/extensions/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/NativeImageProcessor.java#L227-L229
