### ISSUE TITLE
Add extension support for camel-jpa

### ISSUE THREAD

**Issue by rafaeltuelho** [apache/camel-quarkus#889]
In addition to sql and jdbc, would be great to have an extension for camel-jpa as it offers an ORM approach that makes it easy to map the resultset into Object Domain as entities.

**Comment by ppalaga** [comment]
A contribution is welcome! @rafaeltuelho or anybody else please follow the contributor guide https://camel.apache.org/camel-quarkus/latest/contributor-guide.html . It is not hard at all, we already had a couple of contributions from newcomers. Feel free to ask here if you have specific questions.

**Comment by rafaeltuelho** [comment]
@ppalaga I asked for help on https://gitter.im/apache/camel-quarkus
Can you take a look, please?

**Comment by ppalaga** [comment]
Sorry, replied there.
