### ISSUE TITLE
[camel-master branch] support ComponentNameResolver

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#892]
See: https://github.com/apache/camel/commit/2e57fd7f4eadc7f0d6269417ddba8f1bcbdb6a99

**Comment by lburgazzoli** [comment]
@gnodet @jamesnetherton is someone of you already working on this ?

**Comment by jamesnetherton** [comment]
@lburgazzoli is there anything specific that needs to be done for this?

I tested it on the master branch and it seems to be working fine.

**Comment by lburgazzoli** [comment]
@jamesnetherton not I'm aware of, was thinking to have this process done at build time so basically have a component name resolver that returns a static list of component names.

**Comment by lburgazzoli** [comment]
@jamesnetherton I think this has been already fixed right ?

**Comment by jamesnetherton** [comment]
I need to revisit this, I started work on it but stopped for some reason that I now forget.

**Comment by jamesnetherton** [comment]
I finally got around to taking another look at this. Is the intention that `CamelContext.getComponentNames` would leverage this?

If so the signature for that method and `ComponentNameResolver.resolveNames` has an incompatible return type. `Set` Vs `List`, so Camel would need modifying.

**Comment by lburgazzoli** [comment]
@davsclaus may know

**Comment by davsclaus** [comment]
Yeah Set would be better api as component names are unique

**Comment by davsclaus** [comment]
Created a JIRA
https://issues.apache.org/jira/browse/CAMEL-16822

**Comment by davsclaus** [comment]
Okay changed the API in Camel 3.12

**Comment by oscerd** [comment]
What do you mean with dependencies updates are what they are?

**Comment by omnipitous** [comment]
> What do you mean with dependencies updates are what they are?

Meaning for a load of real world reasons we're not updating all of our dependencies relentlessly.  *Especially when they are largely transitive dependencies of other dependencies that have interweaving version locks. (Such as Camel and Dropwizard) AND when we frequently run into breaking changes such as this one. I would love to just have Dependabot keep all of our deps current all the time BUT that's not the world of stability we live in.
