### ISSUE TITLE
List the JVM-only extensions in the docs

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#897]
A followup of https://github.com/apache/camel-quarkus/pull/895

**Comment by lburgazzoli** [comment]
I think we should not use the term _JVM only_ but we should probably document what is the support level for the different targets i.e. a table like

Compilation Target | Support Level
------------ | -------------
JVM | supported
Native| experimental

**Comment by ppalaga** [comment]
I find the data model useful, let's discuss how we could present it.

I have not planned to generate a per-extension doc page, so the only place where we could present this is the list of extensions: https://camel.apache.org/camel-quarkus/latest/list-of-camel-quarkus-extensions.html

Adding two columns sounds a bit too much. How about one column?

Current


Component | Since | Description
-- | -- | --
ActiveMQ (camel-quarkus-activemq)activemq:destinationType:destinationName | 1.0.0-M5 | The activemq component allows messages to be sent to (or consumed from) Apache ActiveMQ. This component extends the Camel JMS component.


Proposed:


Component | Target Level | Since | Description
-- |-- | -- | --
ActiveMQ (camel-quarkus-activemq)activemq:destinationType:destinationName | Native stable | 1.0.0-M5 | The activemq component allows messages to be sent to (or consumed from) Apache ActiveMQ. This component extends the Camel JMS component.


Where the "Target Level" values could wrap under each other so that they take less horizontal space.

Btw. I find stable/preview better than supported/experimental because they are shorter.
