### ISSUE TITLE
quarkus-camel - Use MainSupport as base for running Camel

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#9]
We should look at using MainSupport (parts of Camel Main) some more for bootstrapping camel-quarkus.

Then its similar across standalone Camel, Camel K, and Camel Quarkus. And also Camel Main has parts that are similar to Camel Spring Boot.

**Comment by ppalaga** [comment]
This should be easier to do now that we are on Camel 3.0.0.M4. Any hints or examples @davsclaus how to do that?

**Comment by lburgazzoli** [comment]
As today `core` is responsible to act like a `main` but for better flexibility (i.e. for other to build on top of `core`) I think we need to split responsibilities like:

1. `core` to set-up low level things such as:
    - camel context
    - registry
    - integration with quarkus event loop #131
2. `main` to set up application related things, like:
    - initialize, start/stop the camel context created by `core`
    - discover routes
    - discover and register life-cycle interceptors (to allow i.e. camel-k to hook into the static init build processors)
    - integration with quarkus health checks #141 
    - integration with quarkus metrics #128
    - fire CDI events

/cc @gnodet @davsclaus

**Comment by lburgazzoli** [comment]
Fixed by https://github.com/apache/camel-quarkus/pull/226
