### ISSUE TITLE
mongo-gridfs should reuse the Quarkus Mongo extension

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#932]

**Comment by ppalaga** [comment]
@jamesnetherton actually, I have checked whether there is some overlap in deps with the Quarkus extensions, but there were none. I may recheck.

**Comment by jamesnetherton** [comment]
Although I suggested this, it might not actually be possible (or easy) at the moment, as IIRC, mogo-gridfs still uses the old deprecated Mongo client API. So we'd possibly need to do some hackery like [this](https://github.com/apache/camel-quarkus/blob/1.0.0-M1/extensions/mongodb/runtime/src/main/java/org/apache/camel/quarkus/component/mongodb/CamelMongoClient.java) to make it work.
