### ISSUE TITLE
Warn if JVM only extensions are used in native mode

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#936]

**Comment by ppalaga** [comment]
Should that be a (a) build time warning (b) runtime warning or (c) both?

**Comment by jamesnetherton** [comment]
If it's not too difficult to implement, then it can't hurt to do both.

**Comment by ppalaga** [comment]
Is this text ok?

```
Extension %s may fail because it was not tested in the native mode. You may want to report about the success or failure on https://github.com/apache/camel-quarkus/issues
```

**Comment by ppalaga** [comment]
A slightly modified text referring to the list of issues filtered by the extension name

```
The %s extension was not tested in the native mode.
You may want to report about the success or failure running it in the native mode on https://github.com/apache/camel-quarkus/issues?q=is%%3Aissue+%s
```

WDYT?

**Comment by jamesnetherton** [comment]
Seems ok to me.

I spotted one minor thing to correct. It reads better when you say 'in native mode' instead of 'in the native mode'.
