### ISSUE TITLE
Introduce the CamelContextCustomizerBuildItem to do further customization of the camel context

### ISSUE THREAD

**Issue by zhfeng** [apache/camel-quarkus#984]
This idea comes up during the discussion of https://github.com/apache/camel-quarkus/issues/819

CamelContextCustomizerBuildItem  could be used to add the service in the camel context when we have the LRASagaService just like the auto configuration in the spring boot.

It needs a proper class level JavaDoc to explain:

- What happens before and after
- Sum up roughly which uses is it intended for and
- Explain the relationship to Core and Main.

**Comment by lburgazzoli** [comment]
@zhfeng do you plan to work on this ? if not I can take it as it could  ease also for other things I'm working on

**Comment by zhfeng** [comment]
Thanks @lburgazzoli  for taking this issue.

**Comment by zhfeng** [comment]
Hi @lburgazzoli , I just committed my changes to this issue and can you take a look ?
