### ISSUE TITLE
Replace quarkus.camel.native.resources.* with quarkus.native.resources.*

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#988]
Native resources and reflection inclusion and exclusion is a very generic functionality that all Quarkus users could benefit from.

**Comment by ppalaga** [comment]
Proposed the idea on quarkus-dev https://groups.google.com/forum/#!topic/quarkus-dev/SLuS7DiDMVA

**Comment by lburgazzoli** [comment]
@ppalaga the pr https://github.com/quarkusio/quarkus/pull/8484 has been merged so we can probably close this one ?

**Comment by ppalaga** [comment]
The original idea was to deprecate and later remove `quarkus.camel.native.resources.include-patterns` and `quarkus.camel.native.resources.exclude-patterns` from Camel Quarkus once the same functionality is available in Quarkus. However, https://github.com/quarkusio/quarkus/pull/8484 adds only support for includes. Excludes are blocked by https://github.com/oracle/graal/issues/2347
So I'd keep this open as long as there is any hope to get excludes from Quarkus.

**Comment by ppalaga** [comment]
Blocked by https://github.com/quarkusio/quarkus/pull/13476

**Comment by aldettinger** [comment]
Discussed with @jamesnetherton and we should update all of the tests and deprecate quarkus.camel.native.resources.*

**Comment by ppalaga** [comment]
I am narrowing the scope from `quarkus.camel.native.*` to `quarkus.camel.native.resources.*`.

We still have `quarkus.camel.native.reflection.*` which does not have a drop in replacement in Quarkus and I do not think it is a big issue to keep it as is for now.
