### ISSUE TITLE
Couchdb native support for Producer Mode

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#989]
I'm gonna try this one.

**Comment by ppalaga** [comment]
Thanks @aldettinger! You are probably the first one porting a JVM extension to native. It would be nice if you could start listing the necessary steps on a new doc page.

**Comment by aldettinger** [comment]
good idea, I will take some notes.

**Comment by aldettinger** [comment]
Follow up issue to list necessary steps to promote a JVM only extension to native in #1021

**Comment by aldettinger** [comment]
Follow up issue for consumer support in native mode in #1022
